### ISSUE TITLE
pripara execution error

### ISSUE THREAD

**Issue by qpal54682** [Ryujinx/Ryujinx#1035]
It will turn off after 00:00:39.600 | when running
[Ryujinx_2020-03-25_20-18-13.log](https://github.com/Ryujinx/Ryujinx/files/4380566/Ryujinx_2020-03-25_20-18-13.log)

00:00:00.596 | Application LoadApplication: Loading as XCI.
00:00:01.568 | Loader LoadExeFs: Loading rtld...
00:00:01.569 | Loader LoadExeFs: Loading main...
00:00:01.799 | Loader LoadExeFs: Loading subsdk0...
00:00:01.828 | Loader LoadExeFs: Loading sdk...
00:00:02.674 | Loader LoadStaticObjects: Loading image 0 at 0x0000000008000000...
00:00:02.675 | Loader LoadStaticObjects: Loading image 1 at 0x0000000008004000...
00:00:02.734 | Loader LoadStaticObjects: Loading image 2 at 0x000000000bb02000...
00:00:02.740 | Loader LoadStaticObjects: Loading image 3 at 0x000000000c1bd000...
00:00:02.760 | Application EnsureSaveData: Ensuring required savedata exists.
00:00:03.629 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.679 | GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation GeForce GTX 760/PCIe/SSE2 (4.6.0 NVIDIA 445.75)
00:00:03.875 | ServiceAm GetAppletResourceUserId: Stubbed. 
00:00:04.033 | ServiceAm AcquireForegroundRights: Stubbed. 
00:00:04.051 | ServiceAm SetFocusHandlingMode: Stubbed. 
00:00:04.086 | ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. 
00:00:06.614 | ServiceNv FinishInitialize: Stubbed. 
00:00:06.739 | ServiceAm SetRestartMessageEnabled: Stubbed. 
00:00:06.746 | ServiceAm SetPerformanceModeChangedNotification: Stubbed. 
00:00:06.755 | ServiceAm SetOperationModeChangedNotification: Stubbed. 
00:00:07.865 | ServiceBsd RegisterClient: Stubbed. 
00:00:07.866 | ServiceBsd StartMonitoring: Stubbed. unknown0: 0
00:00:15.826 | ServiceHid ActivateNpad: Stubbed. appletResourceUserId: 0
00:00:15.846 | ServiceHid SetSupportedNpadStyleSet: Stubbed. appletResourceUserId: 0 - _npadStyleSet: FullKey, Handheld
00:00:15.902 | ServiceHid SetSupportedNpadIdType: Stubbed. appletResourceUserId: 0 - npadIdType: ControllerPlayer1
00:00:15.909 | ServiceHid ActivateDebugPad: Stubbed. appletResourceUserId: 0
00:00:19.503 | ServiceNv InitializeEx: Stubbed. 
00:00:19.509 | ServiceNv GetVaRegions: Stubbed. 
00:00:19.513 | ServiceNv GetVaRegions: Stubbed. 
00:00:19.606 | ServiceNv Create: Created map 1 with size 0x00001000!
00:00:19.645 | ServiceNv Create: Created map 2 with size 0x00010000!
00:00:19.672 | ServiceNv GetActiveSlotMask: Stubbed. 
00:00:19.708 | ServiceNv Create: Created map 3 with size 0x00001000!
00:00:19.728 | ServiceNv BindChannel: Stubbed. 
00:00:19.731 | ServiceNv SetNvMapFd: Stubbed. 
00:00:19.732 | ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:19.733 | ServiceNv AllocObjCtx: Stubbed. 
00:00:19.743 | ServiceNv SetErrorNotifier: Stubbed. 
00:00:19.743 | ServiceNv SetUserData: Stubbed. 
00:00:19.746 | ServiceNv SetPriority: Stubbed. 
00:00:19.750 | ServiceNv Create: Created map 4 with size 0x00010000!
00:00:19.786 | ServiceNv Create: Created map 5 with size 0x00049000!
00:00:19.794 | ServiceNv ZcullBind: Stubbed. 
00:00:19.972 | ServiceNv Create: Created map 6 with size 0x01000000!
00:00:19.999 | ServiceNv Create: Created map 7 with size 0x00054000!
00:00:20.031 | ServiceNv Create: Created map 8 with size 0x06000000!
00:00:20.216 | ServiceNv Create: Created map 9 with size 0x021d0000!
00:00:20.790 | ServiceNv Create: Created map 10 with size 0x0c000000!
00:00:22.624 | ServiceNv Create: Created map 11 with size 0x0c000000!
00:00:32.779 | ServiceNv Create: Created map 12 with size 0x04000000!
00:00:38.443 | ServiceAcc InitializeApplicationInfo: Stubbed. unknown: 0
00:00:38.667 | ServiceHid SetSupportedNpadIdType: Stubbed. appletResourceUserId: 0 - npadIdType: ControllerPlayer1
00:00:38.667 | ServiceHid SetSupportedNpadStyleSet: Stubbed. appletResourceUserId: 0 - _npadStyleSet: FullKey, Handheld, Dual
00:00:39.600 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> SoundIOSharp.SoundIOException: incompatible device
   at SoundIOSharp.SoundIOOutStream.Open() in C:\projects\ryujinx\Ryujinx.Audio\Native\libsoundio\SoundIOOutStream.cs:line 190
   at Ryujinx.Audio.SoundIo.SoundIoAudioTrack.Open(Int32 sampleRate, Int32 channelCount, ReleaseCallback callback, SoundIOFormat format) in C:\projects\ryujinx\Ryujinx.Audio\Renderers\SoundIo\SoundIoAudioTrack.cs:line 115
   at Ryujinx.Audio.SoundIoAudioOut.OpenTrack(Int32 sampleRate, Int32 channels, ReleaseCallback callback) in C:\projects\ryujinx\Ryujinx.Audio\Renderers\SoundIo\SoundIoAudioOut.cs:line 85
   at Ryujinx.HLE.HOS.Services.Audio.IAudioOutManager.OpenAudioOutImpl(ServiceCtx context, Int64 sendPosition, Int64 sendSize, Int64 receivePosition, Int64 receiveSize) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\IAudioOutManager.cs:line 150
   at Ryujinx.HLE.HOS.Services.Audio.IAudioOutManager.OpenAudioOut(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\IAudioOutManager.cs:line 34
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by B3astTech** [comment]
You may want to try installing openal. In the mean time this should not be issued on this tracker.

**Comment by AcK77** [comment]
Please go to our Discord server if you need support on the emulator. This place is for development. In that case I close the issue. Thanks.
