### ISSUE TITLE
Error while loading the ndk file

### ISSUE THREAD

**Issue by ray851107** [Ryujinx/Ryujinx#1045]
I'm using the preview build from patreon.
OS: Linux (Debian 10)

Log:
```
00:00:01.701 | Application LoadApplication: Loading as NSP.
00:00:01.711 | Loader LoadExeFs: Loading rtld...
00:00:01.711 | Loader LoadExeFs: Loading main...
00:00:01.842 | Loader LoadExeFs: Loading subsdk0...
00:00:01.858 | Loader LoadExeFs: Loading sdk...
00:00:02.647 | Loader LoadStaticObjects: Loading image 0 at 0x0000000008000000...
00:00:02.647 | Loader LoadStaticObjects: Loading image 1 at 0x0000000008004000...
00:00:02.677 | Loader LoadStaticObjects: Loading image 2 at 0x000000000babb000...
00:00:02.681 | Loader LoadStaticObjects: Loading image 3 at 0x000000000c1c8000...
00:00:02.697 | Application EnsureSaveData: Ensuring required savedata exists.
00:00:02.826 | Application Glib_UnhandledException: Unhandled exception caught: System.InvalidCastException: Unable to cast object of type 'OpenTK.Platform.X11.X11WindowInfo' to type 'OpenTK.Platform.Linux.LinuxWindowInfo'.
   at OpenTK.Platform.Linux.LinuxFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GLWidget.Initialize()
   at OpenTK.GLWidget.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by AcK77** [comment]
Please go to our Discord server for support.
This repository isn’t for users support.
Thanks.
