### ISSUE TITLE
Ryujinx not even opening on macOS

### ISSUE THREAD

**Issue by Animenosekai** [Ryujinx/Ryujinx#1049]
When I try to launch Ryujinx on macOS, I get this error from Terminal:
```
00:00:01.084 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 82
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 82
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```
macOS v10.14.6 (Mojave)
CPU: 3 GHz Intel Core i5
RAM: 16 Go 2400 MHz DDR4
GPU: Radeon Pro 555 2 Go

```
$ dotnet --version
>>> 3.1.201
```

**Comment by B3astTech** [comment]
We don't support mac os. Even if we give the application out to the platform

**Comment by Xpl0itR** [comment]
You need to install gtk3 `brew install gtk3`.
This is an issue tracker not tech support, next time you need help, ask in the support channel in the discord.

**Comment by Animenosekai** [comment]
> You need to install gtk3 `brew install gtk3`.
> This is an issue tracker not tech support, next time you need help, ask in the support channel in the discord.

Ok my bad!
Thank you for your reply!
