### ISSUE TITLE
ACNH Error

### ISSUE THREAD

**Issue by StrawberriAcaii** [Ryujinx/Ryujinx#1060]
00:00:00.345 | Application LoadApplication: Loading as XCI.
00:00:01.666 | Loader LoadExeFs: Loading rtld...
00:00:01.668 | Loader LoadExeFs: Loading main...
00:00:02.169 | Loader LoadExeFs: Loading subsdk0...
00:00:02.237 | Loader LoadExeFs: Loading sdk...
00:00:03.643 | Loader LoadStaticObjects: Loading image 0 at 0x0000000008000000...
00:00:03.644 | Loader LoadStaticObjects: Loading image 1 at 0x0000000008004000...
00:00:03.704 | Loader LoadStaticObjects: Loading image 2 at 0x000000000bc39000...
00:00:03.711 | Loader LoadStaticObjects: Loading image 3 at 0x000000000c346000...
00:00:03.743 | Application EnsureSaveData: Ensuring required savedata exists.
00:00:04.460 | GUI.RenderLoop Gpu PrintGpuInformation: ATI Technologies Inc. AMD Radeon HD 6900 Series  (4.1.11251 Compatibility Profile Context)
00:00:05.644 | ServiceAm GetAppletResourceUserId: Stubbed. 
00:00:06.193 | ServiceAm AcquireForegroundRights: Stubbed. 
00:00:06.273 | ServiceAm SetFocusHandlingMode: Stubbed. 
00:00:06.346 | ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. 
00:00:06.533 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:06.538 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:06.539 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:06.540 | ServicePctl Initialize: Service is already initialized!
00:00:49.478 | HLE.HostThread.0 KernelSvc PrintResult: MapSharedMemory64 returned error InvalidMemRange.
00:00:50.663 | ServiceNv FinishInitialize: Stubbed. 
00:00:50.960 | ServiceVi CreateStrayLayer: Stubbed. 
00:00:52.352 | ServiceNv InitializeEx: Stubbed. 
00:00:52.362 | ServiceNv GetVaRegions: Stubbed. 
00:00:52.371 | ServiceNv GetVaRegions: Stubbed. 
00:00:52.547 | ServiceNv Create: Created map 1 with size 0x00001000!
00:00:52.624 | ServiceNv Create: Created map 2 with size 0x00010000!
00:00:52.680 | ServiceNv GetActiveSlotMask: Stubbed. 
00:00:52.708 | ServiceNv Create: Created map 3 with size 0x00063000!
00:00:52.782 | ServiceNv Create: Created map 4 with size 0x00001000!
00:00:52.811 | ServiceNv BindChannel: Stubbed. 
00:00:52.814 | ServiceNv SetNvMapFd: Stubbed. 
00:00:52.824 | ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:52.825 | ServiceNv AllocObjCtx: Stubbed. 
00:00:52.829 | ServiceNv SetTimeout: Stubbed. 
00:00:52.838 | ServiceNv SetErrorNotifier: Stubbed. 
00:00:52.840 | ServiceNv SetUserData: Stubbed. 
00:00:52.847 | ServiceNv SetTimeslice: Stubbed. 
00:00:52.850 | ServiceNv Create: Created map 5 with size 0x00010000!
00:00:52.919 | ServiceNv Create: Created map 6 with size 0x00049000!
00:00:52.931 | ServiceNv ZcullBind: Stubbed. 
00:00:53.342 | ServiceNv Create: Created map 7 with size 0x01950000!
00:00:53.745 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: android.gui.IGraphicBufferProducer 2
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.NvFlinger.ProcessParcelRequest(ServiceCtx context, Byte[] parcelData, Int32 code) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\NvFlinger.cs:line 88
   at Ryujinx.HLE.HOS.Services.Vi.RootService.ApplicationDisplayService.IHOSBinderDriver.TransactParcelAuto(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Vi\RootService\ApplicationDisplayService\IHOSBinderDriver.cs:line 83
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by AcK77** [comment]
Closed because of https://github.com/Ryujinx/Ryujinx-Games-List/issues/250
If you needs support, please come to our discord server.
Thanks.

**Comment by StrawberriAcaii** [comment]
What is the Discord?

**Comment by AcK77** [comment]
https://discord.gg/N2FmfVc
