### ISSUE TITLE
Ruyjinx crashes for unknown reason on game start 

### ISSUE THREAD

**Issue by graceunique** [Ryujinx/Ryujinx#1069]
00:00:00.598 | Application LoadApplication: Loading as XCI.
00:00:01.563 | Loader LoadExeFs: Loading rtld...
00:00:01.565 | Loader LoadExeFs: Loading main...
00:00:01.808 | Loader LoadExeFs: Loading subsdk0...
00:00:01.838 | Loader LoadExeFs: Loading sdk...
00:00:02.735 | Loader LoadStaticObjects: Loading image 0 at 0x0000000008000000...
00:00:02.736 | Loader LoadStaticObjects: Loading image 1 at 0x0000000008004000...
00:00:02.784 | Loader LoadStaticObjects: Loading image 2 at 0x000000000babb000...
00:00:02.790 | Loader LoadStaticObjects: Loading image 3 at 0x000000000c1c8000...
00:00:02.814 | Application EnsureSaveData: Ensuring required savedata exists.
00:00:03.523 | GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation GeForce GTX 950/PCIe/SSE2 (4.6.0 NVIDIA 432.00)
00:00:03.962 | ServiceAm GetAppletResourceUserId: Stubbed. 
00:00:04.290 | ServiceAm AcquireForegroundRights: Stubbed. 
00:00:04.336 | ServiceAm SetFocusHandlingMode: Stubbed. 
00:00:04.376 | ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. 
00:00:04.482 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:04.486 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:04.486 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:04.487 | ServicePctl Initialize: Service is already initialized!
00:00:30.299 | HLE.HostThread.0 KernelSvc PrintResult: MapSharedMemory64 returned error InvalidMemRange.
00:00:30.999 | ServiceNv FinishInitialize: Stubbed. 
00:00:31.174 | ServiceVi CreateStrayLayer: Stubbed. 
00:00:32.022 | ServiceNv InitializeEx: Stubbed. 
00:00:32.029 | ServiceNv GetVaRegions: Stubbed. 
00:00:32.033 | ServiceNv GetVaRegions: Stubbed. 
00:00:32.138 | ServiceNv Create: Created map 1 with size 0x00001000!
00:00:32.184 | ServiceNv Create: Created map 2 with size 0x00010000!
00:00:32.219 | ServiceNv GetActiveSlotMask: Stubbed. 
00:00:32.234 | ServiceNv Create: Created map 3 with size 0x00063000!
00:00:32.277 | ServiceNv Create: Created map 4 with size 0x00001000!
00:00:32.299 | ServiceNv BindChannel: Stubbed. 
00:00:32.302 | ServiceNv SetNvMapFd: Stubbed. 
00:00:32.307 | ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:32.308 | ServiceNv AllocObjCtx: Stubbed. 
00:00:32.310 | ServiceNv SetTimeout: Stubbed. 
00:00:32.317 | ServiceNv SetErrorNotifier: Stubbed. 
00:00:32.319 | ServiceNv SetUserData: Stubbed. 
00:00:32.326 | ServiceNv SetTimeslice: Stubbed. 
00:00:32.327 | ServiceNv Create: Created map 5 with size 0x00010000!
00:00:32.365 | ServiceNv Create: Created map 6 with size 0x00049000!
00:00:32.372 | ServiceNv ZcullBind: Stubbed. 
00:00:32.630 | ServiceNv Create: Created map 7 with size 0x01950000!
00:00:32.887 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: android.gui.IGraphicBufferProducer 2
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.NvFlinger.ProcessParcelRequest(ServiceCtx context, Byte[] parcelData, Int32 code) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\NvFlinger.cs:line 88
   at Ryujinx.HLE.HOS.Services.Vi.RootService.ApplicationDisplayService.IHOSBinderDriver.TransactParcelAuto(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Vi\RootService\ApplicationDisplayService\IHOSBinderDriver.cs:line 83
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by AcK77** [comment]
This is for development issues. 
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
