### ISSUE TITLE
ACNH Patreon v3 Crash

### ISSUE THREAD

**Issue by optimumbox** [Ryujinx/Ryujinx#1091]
The game is crashing upon load with the provided save file on the patreon.

Here is the error:
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.TranslatedFunction.Execute(ARMeilleure.State.ExecutionContext)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Copy of my log can be found here: https://pastebin.com/QmUUNfEx

Also here's a memtest showing no errors or corrupt DIMMs on my end: https://imgur.com/a/RhYOWlw

I have a second machine that is running the same copy of the game with the exact same save perfectly.

**Comment by HorrorTroll** [comment]
This is for development issues.
If you needs support please come to our discord server (https://discord.gg/N2FmfVc).
Thanks.
