### ISSUE TITLE
'Gtk.Application' threw an exception while running

### ISSUE THREAD

**Issue by CurryEx** [Ryujinx/Ryujinx#1103]
Very sorry to bother. When I'm running Ryujinx lastest pre-built version 1.0.4168, firstly it shows an alert window _cann not found entry point in libpng16-16.dll **(I have no idea if it is correct expression in English)**_ and throw exception _'Gtk.Application' threw an exception while running_ and crash, then I try to use another libpng16 that found in another game to cover, the alert window no longer pops, but still can not run Ryujinx and still that problem. Here is the whole exception, and I make sure I have dotnet runtime 3.1.

```
00:00:00.105 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 82
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 82
```

**Comment by AcK77** [comment]
As a temporary fix you can move the `bin` folder content in the same directory as `Ryujinx.exe`.

For reference, it’s probably a ˋ`

**Comment by CurryEx** [comment]
@AcK77 Thanks! After asking another user, I found an easier resolution like yours. Just copy `./bin/zlib1.dll` to the same folder where `Ryujinx.exe` is, can resolve this problem.

**Comment by highjeans** [comment]
The temporary solutions do not work for any build for Mac when built from source.

**Comment by Thog** [comment]
> The temporary solutions do not work for any build for Mac when built from source.

macOS isn't supported and will not be for a long time

**Comment by luojunyuan** [comment]
I solved this by `brew install gtk+3` on Mac m1

**Comment by mikeyo** [comment]
I am still plagued by this issue. When I move the bin folder to the same folder as the exe, then update ryujinx, the bin files are removed and and I have to move them again from bin folder. I have to do this every time I update ryujinx.
