### ISSUE TITLE
Get This Error Launching Pokemon Sword (Solved)

### ISSUE THREAD

**Issue by zChybo** [Ryujinx/Ryujinx#1111]
New error for me. The game has worked in the past. 

```
00:01:12.810 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> SoundIOSharp.SoundIOException: incompatible device
   at SoundIOSharp.SoundIOOutStream.Open() in C:\projects\ryujinx-testing-69\Ryujinx.Audio\Native\libsoundio\SoundIOOutStream.cs:line 190
   at Ryujinx.Audio.SoundIo.SoundIoAudioTrack.Open(Int32 sampleRate, Int32 channelCount, ReleaseCallback callback, SoundIOFormat format) in C:\projects\ryujinx-testing-69\Ryujinx.Audio\Renderers\SoundIo\SoundIoAudioTrack.cs:line 115
   at Ryujinx.Audio.SoundIoAudioOut.OpenTrack(Int32 sampleRate, Int32 channels, ReleaseCallback callback) in C:\projects\ryujinx-testing-69\Ryujinx.Audio\Renderers\SoundIo\SoundIoAudioOut.cs:line 85
   at Ryujinx.HLE.HOS.Services.Audio.IAudioOutManager.OpenAudioOutImpl(ServiceCtx context, Int64 sendPosition, Int64 sendSize, Int64 receivePosition, Int64 receiveSize) in C:\projects\ryujinx-testing-69\Ryujinx.HLE\HOS\Services\Audio\IAudioOutManager.cs:line 150
   at Ryujinx.HLE.HOS.Services.Audio.IAudioOutManager.OpenAudioOut(ServiceCtx context) in C:\projects\ryujinx-testing-69\Ryujinx.HLE\HOS\Services\Audio\IAudioOutManager.cs:line 34
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx-testing-69\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx-testing-69\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx-testing-69\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by Th3d0nGsT3R** [comment]
iirc you just need openal

**Comment by zChybo** [comment]
Yup that fixed it! Thanks.
