### ISSUE TITLE
Error running Animal Crossing without a save

### ISSUE THREAD

**Issue by 1073600834** [Ryujinx/Ryujinx#1190]
i don‘t know why it was Flashback when the game screen has appeared，is it because my machine configuration is too low???

```
00:00:01.114 | Application LoadApplication: Loading as NSP.
00:00:01.133 | Loader LoadExeFs: Loading rtld...
00:00:01.136 | Loader LoadExeFs: Loading main...
00:00:01.408 | Loader LoadExeFs: Loading subsdk0...
00:00:01.443 | Loader LoadExeFs: Loading sdk...
00:00:01.701 | Loader LoadStaticObjects: Loading image 0 at 0x0000000008000000...
00:00:01.702 | Loader LoadStaticObjects: Loading image 1 at 0x0000000008004000...
00:00:01.748 | Loader LoadStaticObjects: Loading image 2 at 0x000000000babb000...
00:00:01.755 | Loader LoadStaticObjects: Loading image 3 at 0x000000000c1c8000...
00:00:01.783 | Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.825 | Loader LoadNca: Application Loaded: 集合啦！动物森友会 v1.0.0 [01006f8002326000] [64-bit]
00:00:01.830 | GUI.WindowThread Hid InitController: Connected ControllerType ProController to PlayerIndex Player1
00:00:02.298 | GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation GeForce GTX 960M/PCIe/SSE2 (4.6.0 NVIDIA 430.64)
00:00:03.082 | ServiceAm GetAppletResourceUserId: Stubbed. 
00:00:03.510 | ServiceAm AcquireForegroundRights: Stubbed. 
00:00:03.573 | ServiceAm SetFocusHandlingMode: Stubbed. 
00:00:03.619 | ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. 
00:00:03.754 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.759 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.760 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.761 | ServicePctl Initialize: Service is already initialized!
00:00:31.656 | HLE.HostThread.0 KernelSvc PrintResult: MapSharedMemory64 returned error InvalidMemRange.
00:00:32.424 | ServiceNv FinishInitialize: Stubbed. 
00:00:32.613 | SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:33.542 | ServiceNv InitializeEx: Stubbed. 
00:00:33.552 | ServiceNv GetVaRegions: Stubbed. 
00:00:33.555 | ServiceNv GetVaRegions: Stubbed. 
00:00:33.675 | ServiceNv Create: Created map 1 with size 0x00001000!
00:00:33.729 | ServiceNv Create: Created map 2 with size 0x00010000!
00:00:33.772 | ServiceNv GetActiveSlotMask: Stubbed. 
00:00:33.791 | ServiceNv Create: Created map 3 with size 0x00063000!
00:00:33.845 | ServiceNv Create: Created map 4 with size 0x00001000!
00:00:33.869 | ServiceNv BindChannel: Stubbed. 
00:00:33.874 | ServiceNv SetNvMapFd: Stubbed. 
00:00:33.880 | ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:33.882 | ServiceNv AllocObjCtx: Stubbed. 
00:00:33.885 | ServiceNv SetTimeout: Stubbed. 
00:00:33.892 | ServiceNv SetErrorNotifier: Stubbed. 
00:00:33.894 | ServiceNv SetUserData: Stubbed. 
00:00:33.901 | ServiceNv SetTimeslice: Stubbed. 
00:00:33.905 | ServiceNv Create: Created map 5 with size 0x00010000!
00:00:33.951 | ServiceNv Create: Created map 6 with size 0x00049000!
00:00:33.959 | ServiceNv ZcullBind: Stubbed. 
00:00:34.258 | ServiceNv Create: Created map 7 with size 0x01950000!
00:00:34.618 | ServiceNv Create: Created map 8 with size 0x00101000!
00:00:34.622 | ServiceNv Create: Created map 9 with size 0x00100000!
00:00:34.913 | ServiceHid ActivateDebugPad: Stubbed. appletResourceUserId: 0
00:00:34.972 | ServiceHid ActivateNpadWithRevision: Stubbed. appletResourceUserId: 0 - revision: 3
00:00:35.031 | ServiceHid SetSupportedNpadIdType: Stubbed. 9 Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:35.048 | ServiceHid SetSupportedNpadStyleSet: Stubbed. appletResourceUserId: 0 - type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight
00:00:35.063 | ServiceHid ActivateMouse: Stubbed. appletResourceUserId: 0
00:00:35.078 | ServiceHid ActivateKeyboard: Stubbed. appletResourceUserId: 0
00:00:35.134 | ServiceHid SetNpadJoyHoldType: Stubbed. appletResourceUserId: 0 - JoyHold: Horizontal
00:00:35.162 | ServiceHid ActivateTouchScreen: Stubbed. appletResourceUserId: 0
00:00:35.262 | ServiceAm SetOperationModeChangedNotification: Stubbed. 
00:00:35.265 | ServiceAm SetPerformanceModeChangedNotification: Stubbed. 
00:00:35.270 | ServiceAm SetRestartMessageEnabled: Stubbed. 
00:00:35.278 | ServiceAm LockExit: Stubbed. 
00:00:35.568 | HLE.HostThread.4 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:36.159 | ServiceAcc InitializeApplicationInfo: Stubbed. unknown: 0
00:00:36.229 | ServiceAcc IsUserAccountSwitchLocked: Stubbed.
00:04:23.570 | GUI.RenderLoop Gpu WaitOnSyncpoint: Wait on syncpoint 3 for threshold 2 took more than 1000ms, resuming execution...
00:04:23.646 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Gpu.Engine.Methods.FinishTransfer() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 73
   at Ryujinx.Graphics.Gpu.Engine.Methods.LoadInlineData(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 66
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 337
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by PyrDeus** [comment]
Right click on your Animal Crossing entry on Ryujinx.
Select "Open Device Save Directory".
Place in opened folder you save.

(I do not know if links are agreed, I post in a second comment a dropbox link of saved Animal Crossing files zipped)
(Sorry for bad english ^^)
<img width="1348" alt="Capture d’écran 2020-05-20 à 14 13 19" src="https://user-images.githubusercontent.com/49350315/82445411-0c029a80-9aa5-11ea-80f3-ad901bf3193e.png">

**Comment by PyrDeus** [comment]
Link for Animal Crossing save files :
https://www.dropbox.com/s/rs98px3avprkfgk/animal_crossing_save.zip?dl=0

**Comment by ganyao114** [comment]
> Link for Animal Crossing save files :
> https://www.dropbox.com/s/rs98px3avprkfgk/animal_crossing_save.zip?dl=0

404

**Comment by 1073600834** [comment]
i may give it up, may be get a switch is easyer
