### ISSUE TITLE
VoiceContext.GetBufferData(MemoryManager memory, Int32 maxSamples, Int32& samplesCount) 

### ISSUE THREAD

**Issue by EmulationChannel** [Ryujinx/Ryujinx#1212]
---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.VoiceContext.GetBufferData(MemoryManager memory, Int32 maxSamples, Int32& samplesCount) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\VoiceContext.cs:line 70
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.AppendMixedBuffer(Int64 tag) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 372
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.UpdateAudio() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 346
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.RequestUpdateAudioRenderer(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 228
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Used Super Mario Odyssey ryujinx master f84fb209 full logs dropbox 
https://www.dropbox.com/s/j3l0eqr4saha5mf/Ryujinx_2020-05-04_12-17-56.log?dl=0

**Comment by Thog** [comment]
Already known issue, a rewrite is in the work closing.
