### ISSUE TITLE
Invalid variable type "F64".

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx#1255]
## Full error:

```
00:03:19.825 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentException: Invalid variable type "F64".
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.NumberFormatter.TryFormat(Int32 value, VariableType dstType, String& formatted) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/CodeGen/Glsl/NumberFormatter.cs:line 34
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.TypeConversion.ReinterpretCast(CodeGenContext context, IAstNode node, VariableType srcType, VariableType dstType) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/CodeGen/Glsl/TypeConversion.cs:line 18
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGen.GetExpression(CodeGenContext context, AstOperation operation) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs:line 30
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGen.GetExpression(CodeGenContext context, IAstNode node) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs:line 25
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.TypeConversion.ReinterpretCast(CodeGenContext context, IAstNode node, VariableType srcType, VariableType dstType) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/CodeGen/Glsl/TypeConversion.cs:line 24
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintBlock(CodeGenContext context, AstBlock block) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs:line 130
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintMainBlock(CodeGenContext context, StructuredProgramInfo info) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs:line 65
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.Generate(StructuredProgramInfo info, ShaderConfig config) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs:line 21
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(Operation[] ops, ShaderConfig config, Int32 size, Int32 sizeA) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/Translation/Translator.cs:line 51
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Shader/Translation/Translator.cs:line 19
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs:line 333
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs:line 140
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/Engine/Methods.cs:line 830
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/Engine/Methods.cs:line 128
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/Engine/MethodDraw.cs:line 59
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/State/GpuState.cs:line 105
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/MacroInterpreter.cs:line 217
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CachedMacro.Execute(Int32[] mme, ShadowRamControl shadowCtrl, GpuState state) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/NvGpuFifo.cs:line 73
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/NvGpuFifo.cs:line 218
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in /home/space/Documents/Games/Switch/aoc/Ryujinx.Graphics.Gpu/DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in /home/space/Documents/Games/Switch/aoc/Ryujinx/Ui/GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
## Happens in:
Ryujinx/Ryujinx-Games-List#448 when you bypass the original crash with using #1221

**Comment by gdkchan** [comment]
This was fixed in #1670 and #1673.
