### ISSUE TITLE
Ryujinx.HLE.Exceptions.ServiceNotImplementedException: The service call is not implemented. [Animal Crossing New Horizons](Harv's Island)

### ISSUE THREAD

**Issue by MirayXS** [Ryujinx/Ryujinx#1269]
## When trying to use Harv's island photo studio in Animal Crossing (tried to edit room) Ryujinx crashes. 

# Error:
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.Exceptions.ServiceNotImplementedException: The service call is not implemented.

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00133e9c nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l> >, 8ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<8ul, 4ul, void>, unsigned int)
   sdk:0x00282804 Sub000000000c613804
   sdk:0x00284c64 nn::nfp::StartDetection(nn::nfp::DeviceHandle const&)
   main:0x00ca0dc8 Sub0000000008ca4dc8
   main:0x00ca07a8 Sub0000000008ca47a8
   main:0x00ca112c Sub0000000008ca512c
   main:0x01db6018 Sub0000000009dba018
   main:0x01ab10b4 Sub0000000009ab50b4
   main:0x01ab03e8 Sub0000000009ab43e8
   sdk:0x000cfb48 Sub000000000c460b48
   sdk:0x000d4314 Sub000000000c465314
   ??? Sub0000000000000000

Raw Request Data:
00000000   01 00 18 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  03 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  00 00 00 00 30 82 23 C6   ············0?#Æ
00000030   10 00 48 00 00 00 00 00                            ··H·····

   at Ryujinx.HLE.HOS.Services.Nfc.Nfp.IUser.StartDetection(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nfc\Nfp\UserManager\IUser.cs:line 106
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

## Harv's island uses amiibo so that's the problem, but i wasn't using any amiibo, just tried to edit the room via the down arrow button; it's trying to scan for possible amiibo.

**Comment by GamerzHell9137** [comment]
![image](https://user-images.githubusercontent.com/2002038/82677540-7869cf00-9c48-11ea-97ea-81b3a3a3f001.png)
![image](https://user-images.githubusercontent.com/2002038/82677804-e4e4ce00-9c48-11ea-828c-9a926520bf18.png)
![image](https://user-images.githubusercontent.com/2002038/82677858-fa59f800-9c48-11ea-924b-56675f4a0207.png)

**Comment by Doctorwho1909** [comment]
> ![image](https://user-images.githubusercontent.com/2002038/82677540-7869cf00-9c48-11ea-97ea-81b3a3a3f001.png)
> ![image](https://user-images.githubusercontent.com/2002038/82677804-e4e4ce00-9c48-11ea-828c-9a926520bf18.png)
> ![image](https://user-images.githubusercontent.com/2002038/82677858-fa59f800-9c48-11ea-924b-56675f4a0207.png)
> 
> Wrong place to post in.

No its not this about a missing Service check the issues tab next time you will see a ton of these and for good reason

**Comment by MirayXS** [comment]
oh sorry! i'll post it there.
Also i have missing services on.

**Comment by Doctorwho1909** [comment]
> oh sorry! i'll post it there.
> Also i have missing services on.

no, you did the right thing they were wrong

**Comment by MirayXS** [comment]
ohh am being confused

**Comment by Doctorwho1909** [comment]
bad info does that don't worry

**Comment by MirayXS** [comment]
Sorry again! found out the error posted wasn't complete. 

uploading the same error in this comment but with additional  infos + updating the error above.

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.Exceptions.ServiceNotImplementedException: The service call is not implemented.

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00133e9c nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l> >, 8ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<8ul, 4ul, void>, unsigned int)
   sdk:0x00282804 Sub000000000c613804
   sdk:0x00284c64 nn::nfp::StartDetection(nn::nfp::DeviceHandle const&)
   main:0x00ca0dc8 Sub0000000008ca4dc8
   main:0x00ca07a8 Sub0000000008ca47a8
   main:0x00ca112c Sub0000000008ca512c
   main:0x01db6018 Sub0000000009dba018
   main:0x01ab10b4 Sub0000000009ab50b4
   main:0x01ab03e8 Sub0000000009ab43e8
   sdk:0x000cfb48 Sub000000000c460b48
   sdk:0x000d4314 Sub000000000c465314
   ??? Sub0000000000000000

Raw Request Data:
00000000   01 00 18 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  03 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  00 00 00 00 30 82 23 C6   ············0?#Æ
00000030   10 00 48 00 00 00 00 00                            ··H·····

   at Ryujinx.HLE.HOS.Services.Nfc.Nfp.IUser.StartDetection(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nfc\Nfp\UserManager\IUser.cs:line 106
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by youer-mam** [comment]
If you're really desperate to stop the crashing you can "fix" this by changing one line in \Ryujinx.HLE\HOS\Services\Nfc\Nfp\UserManager\IUser.cs:

```
        [Command(3)]
        // StartDetection(bytes<8, 4>)
        public ResultCode StartDetection(ServiceCtx context)
        {
            //throw new ServiceNotImplementedException(context);  // replace this line...
            return ResultCode.Success;                            // with this
        }
```
Can't guarantee this won't nuke your game saves or format your OS drive but I've been playing with this "fix" for a while and haven't noticed any ill effects.

**Comment by MirayXS** [comment]
I prefer waiting than nuking or doing something thanks :)

**Comment by AcK77** [comment]
Supersedes #1472
