### ISSUE TITLE
UE4 Games Fail to Boot on Pascal Hardware (NVIDIA GeForce GTX 10-series)

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1282]
Games that utilize the Unreal 4 Engine are crashing on launch (after a string of GUI renderloop invalid instruction errors; roughly 90 seconds after launch) on Pascal GPUs. 

This particular issue with Pascal GPUs and UE4 games began with [PR 1152](https://github.com/Ryujinx/Ryujinx/pull/1152) ; master builds prior to 1.0.4319 boot successfully.

#### Examples of UE4 games:
Octopath Traveler
Hellblade: Senua's Sacrifice
Rime
Dragon Quest XI
Yoshi's Crafted World
Minecraft Dungeons

#### NVIDIA Driver Version: 446.14 (latest as of 5/27/2020)
Other driver revisions also tested:
- 425.31
- 436.30

The following NVIDIA Control Panel settings were tested in both an off and on state in an attempt to resolve the issue at a driver level, with no success. All other driver settings were left at NVIDIA defaults:
- Threaded Optimization
- Shader Cache
- Triple Buffering

Below is an example console error from an NVIDIA GTX 1080 at the time of the crash.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenTK.Graphics.OpenGL.GL.CopyImageSubData(Int32, OpenTK.Graphics.OpenGL.ImageTarget, Int32, Int32, Int32, Int32, Int32, OpenTK.Graphics.OpenGL.ImageTarget, Int32, Int32, Int32, Int32, Int32, Int32, Int32)
   at Ryujinx.Graphics.OpenGL.Image.TextureCopyUnscaled.Copy(Ryujinx.Graphics.GAL.TextureCreateInfo, Ryujinx.Graphics.GAL.TextureCreateInfo, Int32, Int32, Int32, Int32, Int32, Int32)
   at Ryujinx.Graphics.OpenGL.Image.TextureView.CopyTo(Ryujinx.Graphics.GAL.ITexture, Int32, Int32)
   at Ryujinx.Graphics.Gpu.Image.Texture.RecreateStorageOrView(Int32, Int32, Int32)
   at Ryujinx.Graphics.Gpu.Image.Texture.ChangeSize(Int32, Int32, Int32)
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(Ryujinx.Graphics.Gpu.Image.TextureInfo, Ryujinx.Graphics.Gpu.Image.TextureSearchFlags)
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(Ryujinx.Graphics.Gpu.Image.TexturePool, Ryujinx.Graphics.Shader.ShaderStage, Int32)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings()
   at Ryujinx.Graphics.Gpu.Image.TextureManager.CommitGraphicsBindings()
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(Ryujinx.Graphics.MethodParams, Ryujinx.Graphics.Gpu.ShadowRamControl)
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[], Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[], Int32, Int32, Ryujinx.Graphics.Gpu.ShadowRamControl, Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.NvGpuFifo+CachedMacro.Execute(Int32[], Ryujinx.Graphics.Gpu.ShadowRamControl, Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(Ryujinx.Graphics.MethodParams)
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32)
   at Ryujinx.Graphics.Gpu.DmaPusher.Step()
   at Ryujinx.Ui.GlRenderer.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by EmulationFanatic** [comment]
https://github.com/Ryujinx/Ryujinx/pull/1627 will fix this when merged.

**Comment by EmulationFanatic** [comment]
Fixed by https://github.com/Ryujinx/Ryujinx/pull/1627
