### ISSUE TITLE
Ryujinx crashes when opening any game on Fedora Silverblue

### ISSUE THREAD

**Issue by Proton64** [Ryujinx/Ryujinx#1333]
Output of the terminal:
```
00:00:00.636 | Application Glib_UnhandledException: Unhandled exception caught: System.InvalidCastException: Unable to cast object of type 'OpenTK.Platform.X11.X11WindowInfo' to type 'OpenTK.Platform.Linux.LinuxWindowInfo'.
   at OpenTK.Platform.Linux.LinuxFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GLWidget.Initialize()
   at OpenTK.GLWidget.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

**Comment by Theo-Dlr** [comment]
I managed to fix this error (thanks @samantas5855) by installing these dependencies
`sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev`
