### ISSUE TITLE
Ryujinx Failed to Start Emulate

### ISSUE THREAD

**Issue by AthenaCN** [Ryujinx/Ryujinx#1371]
[athena@MiWiFi-R1D-srv ~]$ ./ryujinx-1.0.4864-linux_x64/publish/Ryujinx
00:00:00.028 | Application Main: Ryujinx Version: 1.0.4864
00:00:00.045 | Application Main: Operating System: Linux 5.7.7-200.fc32.x86_64 #1 SMP Wed Jul 1 19:53:01 UTC 2020 (X64)
00:00:00.045 | Application Main: CPU: Intel(R) Core(TM) i7-3970X CPU @ 3.50GHz
00:00:00.045 | Application Main: Total RAM: 15948 MB
00:00:00.161 | Application LoadApplication: Using Firmware Version: 10.0.4
00:00:00.161 | Application LoadApplication: Loading as NSP.
00:00:00.188 | Application AddAocItem: Found AddOnContent with TitleId 01006F800232712D
00:00:00.189 | Application AddAocItem: Found AddOnContent with TitleId 01006F800232712C
00:00:00.217 | Loader LoadExeFs: Loading rtld...
00:00:00.222 | Loader LoadExeFs: Loading main...
00:00:00.690 | Loader LoadExeFs: Loading subsdk0...
00:00:00.735 | Loader LoadExeFs: Loading sdk...
00:00:00.865 | Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: False).
00:00:01.013 | Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.014 | Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.092 | Loader LoadNsos: Loading image 2 at 0x000000000be98000...
00:00:01.101 | Loader LoadNsos: Loading image 3 at 0x000000000c549000...
00:00:01.127 | Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.176 | Loader LoadNca: Application Loaded: 集合啦！动物森友会 v1.3.0 [01006f8002326000] [64-bit]
00:00:01.181 | GUI.WindowThread Hid InitController: Connected ControllerType JoyconPair to PlayerIndex Player1
00:00:01.341 | Application Glib_UnhandledException: Unhandled exception caught: System.InvalidCastException: Unable to cast object of type 'OpenTK.Platform.X11.X11WindowInfo' to type 'OpenTK.Platform.Linux.LinuxWindowInfo'.
   at OpenTK.Platform.Linux.LinuxFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GLWidget.Initialize()
   at OpenTK.GLWidget.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)

Please Help !

**Comment by AthenaCN** [comment]
Problem Solved. Following Dependencies should be Installed.
#dnf install systemd-devel
#dnf install libinput-devel
#dnf install mesa-libgbm-devel
#dnf install mesa-libEGL-devel
