### ISSUE TITLE
Error when trying to save game folders settings

### ISSUE THREAD

**Issue by MarcosDGF** [Ryujinx/Ryujinx#1372]
Hey, so I'm trying to install Ryujinx on my Windows 10 and when I try to set my game folders location this is happening: 

`00:00:13.873 | Application Glib_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: 
Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Enum.TryParse[TEnum](String value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at Ryujinx.Ui.SettingsWindow.SaveToggle_Activated(Object sender, EventArgs args) in C:\projects\ryujinx\Ryujinx\Ui\SettingsWindow.cs:line 421
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
`

**O.S.: Windows 10 x64
CPU: AMD Ryzen 5 1600x
GPU: R9 290x (AMD Radeon Software version 20.5.1)
Ryujinx v1.0.4864**

**Comment by AcK77** [comment]
Should be fixed in #1360 (It’s not related to the games folder)
