### ISSUE TITLE
nfp:user IUser: 3 (StartDetection) is not implemented

### ISSUE THREAD

**Issue by albfan** [Ryujinx/Ryujinx#1472]
## Bug Report

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.Exceptions.ServiceNotImplementedException: The service call is not implemented.

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x000c43b0 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l> >, 8ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> > >::ProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<8ul, 4ul, void>, unsigned int)
   sdk:0x00133728 Sub000000000ad9a728
   sdk:0x0012f534 nn::nfp::StartDetection(nn::nfp::DeviceHandle const&)
   main:0x0095f6c0 al::NfpControllerThread::executeCommandStartDetection()
   main:0x0095f120 al::NfpControllerThread::executeCommand(sead::Thread*, long)
   main:0x0075b040 sead::Thread::run_()
   main:0x0075a908 sead::Thread::ninThreadFunc_(void*)
   sdk:0x0008a8a8 Sub000000000acf18a8
   sdk:0x0008e958 Sub000000000acf5958
   ??? Sub0000000000000000

Raw Request Data:
00000000   01 00 18 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 00 00 00 00  03 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000030   00 00 00 00 00 00 00 00                            ········        

   at Ryujinx.HLE.HOS.Services.Nfc.Nfp.IUser.StartDetection(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nfc\Nfp\UserManager\IUser.cs:line 106
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### What's the issue you encountered?

Pressing some key combinations this error appears and game game execution and ryujinx ends

### How can the issue be reproduced?

Pressing random keys (quickly it fails faster)

### Environment?

- Ryujinx version: 1.0.5155
- Game version: 1.0.0
- System Specs:
  - OS: Fedora 32
  - CPU: i7-8650
  - GPU: Intel
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Using a PS3 controller mapped with:

```
{
  deadzone_left: 0,
  deadzone_right: 0,
  trigger_threshold: 0,
  left_joycon: {
    stick_x: Axis0,
    invert_stick_x: false,
    stick_y: Axis1,
    invert_stick_y: false,
    stick_button: Button10,
    button_minus: Button4,
    button_l: Button4,
    button_zl: Button6,
    button_sl: Unbound,
    button_sr: Unbound,
    dpad_up: Hat0Left,
    dpad_down: Hat0Left,
    dpad_left: Hat0Left,
    dpad_right: Hat0Right
  },  
  right_joycon: {
    stick_x: Axis2,
    invert_stick_x: false,
    stick_y: Axis3,
    invert_stick_y: false,
    stick_button: Button11,
    button_a: Button1,
    button_b: Button2,
    button_x: Button0,
    button_y: Button3,
    button_plus: Button5,
    button_r: Button5,
    button_zr: Button7,
    button_sl: Unbound,
    button_sr: Unbound
  },  
  index: 0,
  controller_type: JoyconPair,
  player_index: Player1
}
```

**Comment by mageven** [comment]
Pretty sure the random button presses are triggering an nfc scan which isn't implemented yet.
What game is it?

**Comment by AcK77** [comment]
@mageven is right! It’s an unimplemented call about NFP(NFC) service (StartDetection). Nothing related to the controller you used! You just reached it by pressing buttons.

**Comment by albfan** [comment]
@AcK77 I can provide a PR (at least to avoid fatal) Any example I can follow?

**Comment by albfan** [comment]
Ouch, I see:

```
  102         [Command(3)]
  103         // StartDetection(bytes<8, 4>)
  104         public ResultCode StartDetection(ServiceCtx context)
  105         {
  106             throw new ServiceNotImplementedException(context);
  107         }
```

Can we just wrap that errors on execution? I mean. throw only on debug mode or similar

**Comment by albfan** [comment]
Just as feedback #1476 PR shows no crash for several hours. Not sure what those services represents and how they should be implemented.

Let me know if there's any open analysis so I can contribute

**Comment by Thog** [comment]
@albfan see https://switchbrew.org/wiki/Services_API for more informations (and switchbrew in general) for more detail about the Switch OS

this need to be figured out by reverse engineering the NFC system module.
