### ISSUE TITLE
It crashes when running on my computer

### ISSUE THREAD

**Issue by EinsteinZheng** [Ryujinx/Ryujinx#1486]
### What's the issue you encountered?

When I want to play Animal Crossing for the first time,I double clicked, and see the exception in the Terminal.

### Log file

00:00:00.151 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.HorizonResultException: ResultFsAesXtsFileHeaderInvalidKeys (2002-4743): NAX0 key derivation failed.
   at LibHac.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.AesXtsFile..ctor(OpenMode mode, IFile baseFile, U8String path, ReadOnlySpan`1 kekSeed, ReadOnlySpan`1 verificationKey, Int32 blockSize)
   at LibHac.FsSystem.AesXtsFileSystem.OpenFileImpl(IFile& file, U8Span path, OpenMode mode)
   at LibHac.Fs.FileSystemBase.OpenFile(IFile& file, U8Span path, OpenMode mode)
   at LibHac.FsSystem.SubdirectoryFileSystem.OpenFileImpl(IFile& file, U8Span path, OpenMode mode)
   at LibHac.Fs.FileSystemBase.OpenFile(IFile& file, U8Span path, OpenMode mode)
   at LibHac.FsSystem.Utility.CopyFile(IFileSystem destFileSystem, IFileSystem sourceFileSystem, U8Span destParentPath, U8Span sourcePath, DirectoryEntry& entry, Span`1 workBuffer)
   at LibHac.FsSystem.Utility.<>c__DisplayClass10_1.<CopyDirectoryRecursively>g__OnFile|2(U8Span path, DirectoryEntry& entry)
   at LibHac.FsSystem.Utility.IterateDirectoryRecursivelyImpl(IFileSystem fs, Span`1 workPath, DirectoryEntry& dirEntry, FsIterationTask onEnterDir, FsIterationTask onExitDir, FsIterationTask onFile)
   at LibHac.FsSystem.Utility.IterateDirectoryRecursively(IFileSystem fs, U8Span rootPath, Span`1 workPath, DirectoryEntry& dirEntry, FsIterationTask onEnterDir, FsIterationTask onExitDir, FsIterationTask onFile)
   at LibHac.FsSystem.Utility.IterateDirectoryRecursively(IFileSystem fs, U8Span rootPath, FsIterationTask onEnterDir, FsIterationTask onExitDir, FsIterationTask onFile)
   at LibHac.FsSystem.Utility.CopyDirectoryRecursively(IFileSystem destFileSystem, IFileSystem sourceFileSystem, U8Span destPath, U8Span sourcePath, Span`1 workBuffer)
   at LibHac.FsSystem.Utility.CopyDirectoryRecursively(IFileSystem fileSystem, U8Span destPath, U8Span sourcePath, Span`1 workBuffer)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.SynchronizeDirectory(U8Span destPath, U8Span sourcePath)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.Initialize(Boolean isPersistentSaveData, Boolean canCommitProvisionally)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.CreateNew(DirectorySaveDataFileSystem& created, IFileSystem baseFileSystem, Boolean isPersistentSaveData, Boolean canCommitProvisionally)
   at LibHac.FsService.Creators.SaveDataFileSystemCreator.Create(IFileSystem& fileSystem, ISaveDataExtraDataAccessor& extraDataAccessor, IFileSystem sourceFileSystem, UInt64 saveDataId, Boolean allowDirectorySaveData, Boolean useDeviceUniqueMac, SaveDataType type, ITimeStampGenerator timeStampGenerator)
   at LibHac.FsService.FileSystemProxyCore.OpenSaveDataFileSystem(IFileSystem& fileSystem, SaveDataSpaceId spaceId, UInt64 saveDataId, String saveDataRootPath, Boolean openReadOnly, SaveDataType type, Boolean cacheExtraData)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystemImpl(IFileSystem& fileSystem, UInt64& saveDataId, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly, Boolean cacheExtraData)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystemBySystemSaveDataId(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute)
   at LibHac.Fs.Shim.SystemSaveData.MountSystemSaveData(FileSystemClient fs, U8Span mountName, SaveDataSpaceId spaceId, UInt64 saveDataId, UserId userId)
   at LibHac.Fs.Shim.SystemSaveData.MountSystemSaveData(FileSystemClient fs, U8Span mountName, SaveDataSpaceId spaceId, UInt64 saveDataId)
   at LibHac.FsService.SaveDataIndexer.Mounter.Initialize(FileSystemClient fsClient, U8String mountName, SaveDataSpaceId spaceId, UInt64 saveDataId)
   at LibHac.FsService.SaveDataIndexer.Initialize()
   at LibHac.FsService.SaveDataIndexer.OpenSaveDataInfoReader(ISaveDataInfoReader& infoReader)
   at LibHac.FsService.FileSystemProxy.FindSaveDataWithFilterImpl(Int64& count, SaveDataInfo& info, SaveDataSpaceId spaceId, SaveDataFilterInternal& filter)
   at LibHac.FsService.FileSystemProxy.FindSaveDataWithFilter(Int64& count, Span`1 saveDataInfoBuffer, SaveDataSpaceId spaceId, SaveDataFilter& filter)
   at LibHac.Fs.Shim.SaveDataManagement.<>c__DisplayClass16_0.<FindSaveDataWithFilter>b__0()
   at LibHac.Fs.FileSystemClient.RunOperationWithAccessLog(AccessLogTarget logTarget, Func`1 operation, Func`1 textGenerator, String caller)
   at LibHac.Fs.Shim.SaveDataManagement.FindSaveDataWithFilter(FileSystemClient fs, SaveDataInfo& info, SaveDataSpaceId spaceId, SaveDataFilter& filter)
   at LibHac.Fs.ApplicationSaveDataManagement.GetCacheStorageTargetMediaImpl(FileSystemClient fs, CacheStorageTargetMedia& target, TitleId applicationId)
   at LibHac.Fs.ApplicationSaveDataManagement.EnsureApplicationCacheStorageImpl(FileSystemClient fs, Int64& requiredSize, CacheStorageTargetMedia& target, TitleId applicationId, TitleId saveDataOwnerId, Int16 index, Int64 dataSize, Int64 journalSize, Boolean allowExisting)
   at LibHac.Fs.ApplicationSaveDataManagement.EnsureApplicationCacheStorage(FileSystemClient fs, Int64& requiredSize, TitleId applicationId, ApplicationControlProperty& nacp)
   at Ryujinx.HLE.HOS.ApplicationLoader.EnsureSaveData(TitleId titleId) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 576
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNca(Nca mainNca, Nca patchNca, Nca controlNca) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 336
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNsp(String nspFile) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 203
   at Ryujinx.HLE.Switch.LoadNsp(String nspFile) in C:\projects\ryujinx\Ryujinx.HLE\Switch.cs:line 144
   at Ryujinx.Ui.MainWindow.LoadApplication(String path) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 447
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 831
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### Environment?

- Ryujinx version: 1.0.5182
- Game version: 1.0.0
- System Specs:
  - OS: macOS Catalina
  - CPU: i5(MacBook Air 2017)
  - GPU: Intel HD Graphics 6000
  - RAM: 8GB

**Comment by EmulationFanatic** [comment]
The macOS client can only run 2D games. If you want to be able to run Animal Crossing you will need to use Boot Camp to dual boot with Windows and then use the windows Ryujinx client.
