### ISSUE TITLE
This happens whenever I try to start Animal Crossing

### ISSUE THREAD

**Issue by FiREGoKHaN** [Ryujinx/Ryujinx#1500]
Marshaling row-activated signal
```
00:00:04.447 |N| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: No valid channel configuration found!
   at Ryujinx.Audio.IAalOutput.SelectHardwareChannelCount(Int32 targetChannelCount) in C:\projects\ryujinx\Ryujinx.Audio\IAalOutput.cs:line 25
   at Ryujinx.Audio.IAalOutput.SelectHardwareChannelCount(Int32 targetChannelCount) in C:\projects\ryujinx\Ryujinx.Audio\IAalOutput.cs:line 25
   at Ryujinx.Audio.IAalOutput.OpenTrack(Int32 sampleRate, Int32 channels, ReleaseCallback callback) in C:\projects\ryujinx\Ryujinx.Audio\IAalOutput.cs:line 31
   at Ryujinx.HLE.HOS.Services.Audio.AudioRenderer.AalHardwareDevice..ctor(Int32 bufferTag, IAalOutput output, UInt32 channelCount, UInt32 sampleRate) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRenderer\AalHardwareDevice.cs:line 32
   at Ryujinx.HLE.HOS.Horizon.InitializeAudioRenderer() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Horizon.cs:line 216
   at Ryujinx.HLE.HOS.Horizon..ctor(Switch device, ContentManager contentManager) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Horizon.cs:line 193
   at Ryujinx.HLE.Switch..ctor(VirtualFileSystem fileSystem, ContentManager contentManager, IRenderer renderer, IAalOutput audioOut) in C:\projects\ryujinx\Ryujinx.HLE\Switch.cs:line 85
   at Ryujinx.Ui.MainWindow.InitializeSwitchInstance() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 327
   at Ryujinx.Ui.MainWindow.LoadApplication(String path) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 406
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 823
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

**Comment by bukyapavankumar** [comment]
Which audio backend are you using

**Comment by FiREGoKHaN** [comment]
> Which audio backend are you using

If you mean Audio Software... I am using Realtek Audio Console.

**Comment by EmulationFanatic** [comment]
This is for development related issues, not configuration support. Please come to Discord for personalized help (and it is your audio backend that needs to be set to OpenAL in options > settings > system tab.)
