### ISSUE TITLE
Can't save Controller-Layout / Can't switch to OpenAL

### ISSUE THREAD

**Issue by Sp4wnf3rk3l** [Ryujinx/Ryujinx#1599]
### What's the issue you encountered?

I **can't save** some changes... like **the controller-layout** for example.
Changing the keyboard-layout and saving it works like a charm.

I also **can't switch to OpenAL**, because it is greyed out in the systems
tab. OpenAL is installed and works in other apps.

### Log file

00:00:11.604 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at Ryujinx.Ui.ControllerWindow.GetValues() in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 528
   at Ryujinx.Ui.ControllerWindow.SaveToggle_Activated(Object sender, EventArgs args) in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 993
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### Environment?

- Ryujinx version: 1.0.5485

  - OS: *Win10*
  - CPU: *i7-9700K*
  - GPU: *NVIDIA RTX 2070*
  - RAM: *32GB*
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please come to Discord for support on this.

**Comment by EmulationFanatic** [comment]
Was able to resolve on Discord.
