### ISSUE TITLE
a error when i click settign

### ISSUE THREAD

**Issue by Pulviscolo** [Ryujinx/Ryujinx#1835]
00:00:00.022 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0-ldn2
00:00:01.250 |N| Application PrintSystemInfo: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:01.250 |N| Application PrintSystemInfo: CPU: AMD Ryzen 5 3600 6-Core Processor
00:00:01.250 |N| Application PrintSystemInfo: Total RAM: 16332 MB
00:00:01.252 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
Marshaling activate signal
00:00:12.417 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.SettingsWindow..ctor(Builder builder, VirtualFileSystem virtualFileSystem, ContentManager contentManager) in C:\project\ryujinx\Ryujinx\Ui\SettingsWindow.cs:line 271
   at Ryujinx.Ui.MainWindow.Settings_Pressed(Object sender, EventArgs args) in C:\project\ryujinx\Ryujinx\Ui\MainWindow.cs:line 1238
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by AcK77** [comment]
Download and open the latest ryujinx master build and then open up LDN2 build and the settings tab should work just fine. It’s a known issue, will be fixed soon.

**Comment by Pulviscolo** [comment]
i don't understand, sorry i don't know really much of these things

**Comment by ShahilSharma** [comment]
Download and Open the latest ryujinx master build and then open up LDN 2 and the settings tab should work just fine

**Comment by Pulviscolo** [comment]
i don't understand, sorry i don't know really much of these things

**Comment by AcK77** [comment]
Then you can go to our discord for much support! Thanks!
