### ISSUE TITLE
apm:p is not implemented

### ISSUE THREAD

**Issue by macabeus** [Ryujinx/Ryujinx#1846]
### What service call is missing?

A lot of [homebrew games](https://switchbrew.org/wiki/Homebrew_Applications) are asking for `apm:p` for some reason (probably because a library uses it).

I can help to add this service on Ryujinx. I just would like some initial instructions about what should I do on the codebase.

```
Exception has occurred: CLR/System.NotImplementedException
An exception of type 'System.NotImplementedException' occurred in Ryujinx.HLE.dll but was not handled in user code: 'apm:p'
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetService(ServiceCtx context) in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 98
```

### Service description

https://switchbrew.org/wiki/PPC_services#apm:p

### Required by: 
- [2048](https://github.com/FlagBrew/2048)
- [InvadersNX](https://github.com/MaesterRowen/InvadersNX)
- [tetriswitch](https://github.com/Ryuzaki-MrL/tetriswitch)
(and probably many others)

**Comment by jduncanator** [comment]
For those interested, this should be relatively straight forward to implement, as nearly all functionality of APM can likely be stubbed.

**Comment by AcK77** [comment]
> For those interested, this should be relatively straight forward to implement, as nearly all functionality of APM can likely be stubbed.

Even if they can be stubbed, it’s not a reason to do a bad stub. With the refactoring I’ve made for the service the logic is easy to add.
I’ll do it soon... Even if I don’t recommend that because it’s not the emulator fault if homebrews aren’t updated to the last Libnx version.
Service was removed in 8.0.0 firmware, current switch firmware is 11.0.1.

**Comment by macabeus** [comment]
@AcK77 I tried to add this service with the following approach (if you prefer, I could open a PR).
I created the file `Ryujinx/Ryujinx.HLE/HOS/Services/Apm/IManagerPrivileged.cs` with:
```cs
namespace Ryujinx.HLE.HOS.Services.Apm
{
    [Service("apm:p")] // 8.0.0-
    class IManagerPrivileged : IManager
    {
        private readonly ServiceCtx _context;

        public IManagerPrivileged(ServiceCtx context) : base(context)
        {
            _context = context;
        }

        [Command(0)]
        protected override ResultCode OpenSession(out SessionServer sessionServer)
        {
            sessionServer = new SessionServer(_context);

            return ResultCode.Success;
        }

        protected override PerformanceMode GetPerformanceMode()
        {
            // not implemented
            return _context.Device.System.PerformanceState.PerformanceMode;
        }

        protected override bool IsCpuOverclockEnabled()
        {
            // not implemented
            return _context.Device.System.PerformanceState.CpuOverclockEnabled;
        }
    }
}
```

I didn't know what should I do with `GetPerformanceMode` and `IsCpuOverclockEnabled`. I kept it because I'm using as base `IManager` and these methods are mandatory - but I think that it doesn't exist on `apm:p`.

With this, I don't have anymore the `apm:p` error, but now opening these homebrew games I have any the following error:

```
Exception has occurred: CLR/System.ArgumentOutOfRangeException
An exception of type 'System.ArgumentOutOfRangeException' occurred in Ryujinx.Graphics.Gpu.dll but was not handled in user code: 'Specified argument was out of the range of valid values.'
   at Ryujinx.Graphics.Gpu.Synchronization.SynchronizationManager.RegisterCallbackOnSyncpoint(UInt32 id, UInt32 threshold, Action callback) in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.Graphics.Gpu\Synchronization\SynchronizationManager.cs:line 80
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.AndroidFence.RegisterCallback(GpuContext gpuContext, Action callback) in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\Types\AndroidFence.cs:line 73
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.PostFrameBuffer(Layer layer, BufferItem item) in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 351
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.Compose() in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 290
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.HandleComposition() in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 227
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

@gdkchan said that this error was fixed at https://github.com/Ryujinx/Ryujinx/pull/1839, but even when I tried using this branch I still have the same error.

What should I do?
