### ISSUE TITLE
Regalia: Of Men and Monarchs - Royal Edition now suffers from frequent crashes

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1935]
### What's the issue you encountered?

When last tested, [Regalia: Of Men and Monarchs - Royal Edition](https://github.com/Ryujinx/Ryujinx-Games-List/issues/910) had no issues other than being a bit slow. Re-tested on current master 1.0.6355, the game suffers from crashes during boot, in menus, and in gameplay. All crashes only show output in the console; no log output is generated.

### How can the issue be reproduced?

Boot up the game and attempt to play.

### Log file

Here is the crash from the console:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ryujinx.Graphics.Texture.LayoutConverter.<ConvertLinearToBlockLinear>g__Convert|5_0[[System.UInt32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Span`1<Byte>, System.ReadOnlySpan`1<Byte>, <>c__DisplayClass5_0 ByRef, <>c__DisplayClass5_1 ByRef, <>c__DisplayClass5_2 ByRef)
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Ryujinx.Graphics.Texture.SizeInfo, System.ReadOnlySpan`1<Byte>)
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu(Boolean, Ryujinx.Graphics.GAL.ITexture)
   at Ryujinx.Graphics.Gpu.Image.Texture.<ExternalFlush>b__80_0()
   at Ryujinx.Memory.Tracking.RegionHandle.Signal(UInt64, UInt64, Boolean)
   at Ryujinx.Memory.Tracking.VirtualRegion.Signal(UInt64, UInt64, Boolean)
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64, UInt64, Boolean)
   at Ryujinx.Cpu.MemoryManager.SignalMemoryTracking(UInt64, UInt64, Boolean)
   at Ryujinx.Cpu.MemoryManager.Write(UInt64, System.ReadOnlySpan`1<Byte>)
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(Ryujinx.Graphics.MethodParams)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(System.ReadOnlySpan`1<Int32>)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.GlRenderer.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Environment?

- Ryujinx version: 1.0.6355
- Game version: 1.0.0
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10 20H2
  - CPU: Ryzen 7 5800X
  - GPU: NVIDIA GTX 1080
  - RAM: 32GB
- Applied Mods : No

**Comment by benderscruffy** [comment]
is this still a problem ??
