### ISSUE TITLE
LibHac fails to decrypt some games on launch with AES-XTS keys error

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1947]
### What's the issue you encountered?

A few games, such as Alien: Isolation, or the Pokken Tournament DX Demo crash shortly after launch with this error:

```
HLE.OsThread.5 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.HorizonResultException: ResultFsAesXtsFileHeaderInvalidKeysInRenameFile (2002-4747): Could not decrypt AES-XTS keys
   at LibHac.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.AesXtsFileSystem.ReadXtsHeader(String filePath, String keyPath)
   at LibHac.FsSystem.AesXtsFileSystem.RenameDirectoryImpl(String srcDir, String dstDir, Boolean doRollback)
   at LibHac.FsSystem.AesXtsFileSystem.DoRenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.Fs.Fsa.IFileSystem.RenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.FsSystem.SubdirectoryFileSystem.DoRenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.Fs.Fsa.IFileSystem.RenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.<DoCommit>g__RenameSynchronizingDir|45_2()
   at LibHac.FsSystem.Utility.RetryFinitelyForTargetLocked(Func`1 function)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.DoCommit()
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IFileSystem.Commit(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IFileSystem.cs:line 150
   --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 114
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
However these same games are able to be launched in yuzu with the same keys, so the game files are known to be valid.

### How can the issue be reproduced?

Dump Alien: Isolation or Pokken Tournament DX Demo and try to launch them in Ryujinx. If you get the NAX0 keys derivation error, delete everything in appdata\roaming\ryujinx\sdcard\Nintendo\save

### Log file

[Ryujinx_1.0.6373_2021-01-22_11-55-01.log](https://github.com/Ryujinx/Ryujinx/files/5857966/Ryujinx_1.0.6373_2021-01-22_11-55-01.log)

### Environment?

- Ryujinx version: 1.0.6373
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10 20H2
  - CPU: Ryzen 7 5800X
  - GPU: NVIDIA GTX 1080
  - RAM: 32GB
- Applied Mods : No

**Comment by ReaperOfSouls1909** [comment]
Same issue on alien isolations

**Comment by benderscruffy** [comment]
AO Tennis 2 - 010047000E9AA000 https://github.com/Ryujinx/Ryujinx-Games-List/issues/3118

**Comment by benderscruffy** [comment]
Pinball Fx3 when you update from 1.0.0 to 1.0.7 or later Ryujinx/Ryujinx-Games-List/issues/298
