### ISSUE TITLE
Ryujinx Version: 1.0.6551 Exception on setting input

### ISSUE THREAD

**Issue by agry** [Ryujinx/Ryujinx#2020]
00:00:00.031 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6551
00:00:01.162 |N| Application PrintSystemInfo: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:01.163 |N| Application PrintSystemInfo: CPU: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
00:00:01.163 |N| Application PrintSystemInfo: Total RAM: 32707 MB
00:00:01.165 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, AccessLog, Stub
00:00:14.720 |E| Application : Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'button')
   at OpenTK.Input.JoystickState.SetButton(Int32 button, Boolean value)
   at OpenTK.Platform.Windows.WinRawJoystick.QueryDeviceCaps(Device stick)
   at OpenTK.Platform.Windows.WinRawJoystick.RefreshDevices()
   at OpenTK.Platform.Windows.WinRawJoystick..ctor(IntPtr window)
   at OpenTK.Platform.Windows.WinRawInput.CreateDrivers()
   at OpenTK.Platform.Windows.WinInputBase.ProcessEvents()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

i have 6 "joystick" input devices connectet

**Comment by AcK77** [comment]
Could you test this again using the master build and let’s us know if it’s still available?

**Comment by agry** [comment]
getting same error on master build.
maybe a problem with input's with more as 128 buttons  ?

00:00:00.102 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6659
00:00:01.294 |N| Application PrintSystemInfo: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:01.294 |N| Application PrintSystemInfo: CPU: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
00:00:01.294 |N| Application PrintSystemInfo: Total RAM: 32707 MB
00:00:01.297 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, AccessLog, Stub
00:00:21.548 |E| Application : Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'button')
   at OpenTK.Input.JoystickState.SetButton(Int32 button, Boolean value)
   at OpenTK.Platform.Windows.WinRawJoystick.QueryDeviceCaps(Device stick)
   at OpenTK.Platform.Windows.WinRawJoystick.RefreshDevices()
   at OpenTK.Platform.Windows.WinRawJoystick..ctor(IntPtr window)
   at OpenTK.Platform.Windows.WinRawInput.CreateDrivers()
   at OpenTK.Platform.Windows.WinInputBase.ProcessEvents()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by jduncanator** [comment]
Can I ask what device you're using?

**Comment by agry** [comment]
i have 1 gunfighter MKII, Gladiator MKII, CH-Pedals, 2x F16 MDF, Razer tatarus, and a Xbox controller on my rig :). sorry i play most time Starcitzien ;)

**Comment by AcK77** [comment]
@agry Could you test master build and tell us if there is still an issue ? (should be fixed in #2194)

**Comment by agry** [comment]
now it works :) thanks
