### ISSUE TITLE
Bravely Default 2 : Crash after first successfull run.

### ISSUE THREAD

**Issue by toniohc** [Ryujinx/Ryujinx#2096]
### What's the issue you encountered?

Just start a second time Bravely Default 2 after first successfull play and emulator crash.
</br>I dont make any change to the emulator settings other than 4X display size & 16X anisotropic settings.
Problem appears even with standard settings.

### How can the issue be reproduced?

Start the game. Play 2 or 3 minute then stop emulation. Exit Ryujinx & start the game again without delecte cache shader.
I play 15 minutes without problem ( run smoothly @ 30 fps almost all the time ) and when i exit, cannot launch it. Emulator freeze.

### Log file

```
00:00:00.029 |I| Hid Configure: Configured Controller JoyconPair to Player1
00:00:00.083 |N| Application LoadApplication: Using Firmware Version: 11.0.0
00:00:00.083 |I| Application LoadApplication: Loading as XCI.
00:00:00.115 |I| ModLoader QueryContentsDir: Searching mods for Title 010056F00C7B4000
00:00:00.115 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.128 |I| Loader LoadExeFs: Loading rtld...
00:00:00.129 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.129 |I| Loader LoadExeFs: Loading main...
00:00:01.435 |I| Loader PrintRoSectionInfo: main:
    Module: C:\Sunrise\Project\Sunrise\Binaries\Switch\Sunrise-Switch-Shipping.nss
    SDK Libraries: SDK MW+EpicGames+UnrealEngine-4_23_0
                   SDK MW+Nintendo+NintendoSDK_libcurl-10_4_0-Release
                   SDK MW+Nintendo+NEX-4_6_4-
                   SDK MW+Nintendo+NEX_R2-4_6_4
                   SDK MW+Nintendo+NEX_MM-4_6_4
                   SDK MW+Nintendo+NEX_VS-4_6_4
                   SDK MW+NVIDIA+PhysX-3_4_0-release
00:00:01.435 |I| Loader LoadExeFs: Loading subsdk0...
00:00:01.530 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-10_4_0-Release
00:00:01.530 |I| Loader LoadExeFs: Loading sdk...
00:00:01.842 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 10.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-10_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-10_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-10_4_0-Release
00:00:01.870 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:04.659 |I| Ptc Load: Loaded Translation Cache (size: 253117667 bytes, translated functions: 150255).
00:00:04.675 |I| Ptc Load: Loaded Profiling Info (size: 414316 bytes, profiled functions: 150553).
00:00:04.675 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:04.675 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:04.709 |I| Loader LoadNsos: Loading image 2 at 0x0000000010fa5000...
00:00:04.711 |I| Loader LoadNsos: Loading image 3 at 0x0000000011656000...
00:00:04.714 |I| Loader LoadNca: Application Loaded: BRAVELY DEFAULT Ⅱ v1.0.0 [010056f00c7b4000] [64-bit]
00:00:04.780 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:04.906 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation GeForce RTX 3090/PCIe/SSE2 (4.6.0 NVIDIA 461.72)
00:00:04.928 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\Antonio DiFargas\AppData\Roaming\Ryujinx\games\010056f00c7b4000\cache\shader\guest\program\cache.zip...
00:00:04.954 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\Antonio DiFargas\AppData\Roaming\Ryujinx\games\010056f00c7b4000\cache\shader\guest\program\cache.zip.
00:00:04.970 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\Antonio DiFargas\AppData\Roaming\Ryujinx\games\010056f00c7b4000\cache\shader\opengl\glsl\host\cache.zip...
00:00:04.994 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\Antonio DiFargas\AppData\Roaming\Ryujinx\games\010056f00c7b4000\cache\shader\opengl\glsl\host\cache.zip.
00:00:05.172 |W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x0006F0 (0xEB50050200070005).
00:00:05.172 |W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x000708 (0xEB50050200070106).
00:00:05.172 |W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x000710 (0xEB50050200070807).
00:00:05.173 |I| GUI.RenderLoop Gpu Initialize: Host shader 34c3d155c1244dba0a707db15be27e2e got invalidated, rebuilding from guest...
00:00:05.270 |E| GUI.RenderLoop Application : Unhandled exception caught: System.ArgumentException: Value does not fall within the expected range.
   at Ryujinx.Graphics.Gpu.Shader.CachedGpuAccessor.GetTextureDescriptor(Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\CachedGpuAccessor.cs:line 148
   at Ryujinx.Graphics.Gpu.Shader.TextureDescriptorCapableGpuAccessor.QueryIsTextureRectangle(Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\TextureDescriptorCapableGpuAccessor.cs:line 94
   at Ryujinx.Graphics.Shader.Translation.Rewriter.RewriteTextureSample(LinkedListNode`1 node, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 143
   at Ryujinx.Graphics.Shader.Translation.Rewriter.RunPass(BasicBlock[] blocks, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 35
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(FunctionCode[] functions, ShaderConfig config, ShaderProgramInfo& shaderProgramInfo) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 75
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.Initialize() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 69
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 431
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Environment?

- Ryujinx version: 1.0.6781</br>
- Game version: 1.0.0</br>

- System Specs:
  - OS: Windows 10 Version 20H2 ( 19042.867 )
  - CPU: I9 9900K
  - GPU: Geforce RTX 3090
  - RAM: 32 GB
- Applied Mods :  No

### Additional context?

Additional info about your environment:</br>

Problem only appear with Bravely Default. No problem with Octopath Traveler
Full log : [Ryujinx_1.0.6781_2021-03-10_23-15-02.log](https://github.com/Ryujinx/Ryujinx/files/6119270/Ryujinx_1.0.6781_2021-03-10_23-15-02.log)

**Comment by EmulationFanatic** [comment]
This issue has already been submitted here: https://github.com/Ryujinx/Ryujinx/issues/2045

**Comment by gdkchan** [comment]
For now the only solution is disabling the shader cache on the settings (or purging it before each run).

**Comment by toniohc** [comment]
Didn't know it was related. Thanks for your answer.
