### ISSUE TITLE
Crash on Taiko no Tatsujin Drum N' Fun

### ISSUE THREAD

**Issue by ThatOneCalculator** [Ryujinx/Ryujinx#2111]
### What's the issue you encountered?

Launching Taiko No Tatsujin Drum N' Fun crashes, with both no update and the 1.4.3 update.

### How can the issue be reproduced?

Launch the game.

### Log file

```
00:00:12.682 |W| HLE.GuestThread.16 KernelSvc PrintResult: SendSyncRequest64 returned error InvalidMemState.
00:00:12.682 |I| HLE.OsThread.10 ServiceNv Create: Created map 114 with size 0x00024000!
00:00:12.683 |I| HLE.OsThread.10 ServiceNv Create: Created map 115 with size 0x00024000!
00:00:12.683 |I| HLE.OsThread.10 ServiceNv Create: Created map 116 with size 0x00024000!
00:00:12.683 |I| HLE.OsThread.10 ServiceNv Create: Created map 117 with size 0x00024000!
00:00:12.698 |I| HLE.OsThread.10 ServiceNv Create: Created map 118 with size 0x00090000!
00:00:12.698 |I| HLE.OsThread.10 ServiceNv Create: Created map 119 with size 0x00090000!
00:00:12.706 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0x0000080900010000, size=0x0000000000000008
   at Ryujinx.Cpu.MemoryManager.AssertValidAddressAndSize(UInt64 va, UInt64 size) in /home/kainoa/.cache/yay/ryujinx-git/src/Ryujinx/Ryujinx.Cpu/MemoryManager.cs:line 567
   at Ryujinx.Cpu.MemoryManager.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write) in /home/kainoa/.cache/yay/ryujinx-git/src/Ryujinx/Ryujinx.Cpu/MemoryManager.cs:line 678
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in /home/kainoa/.cache/yay/ryujinx-git/src/Ryujinx/Ryujinx.Cpu/MemoryManager.cs:line 150
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: va=0x0000080900010000, size=0x0000000000000008
   at Ryujinx.Cpu.MemoryManager.AssertValidAddressAndSize(UInt64 va, UInt64 size) in /home/kainoa/.cache/yay/ryujinx-git/src/Ryujinx/Ryujinx.Cpu/MemoryManager.cs:line 567
   at Ryujinx.Cpu.MemoryManager.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write) in /home/kainoa/.cache/yay/ryujinx-git/src/Ryujinx/Ryujinx.Cpu/MemoryManager.cs:line 678
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in /home/kainoa/.cache/yay/ryujinx-git/src/Ryujinx/Ryujinx.Cpu/MemoryManager.cs:line 150
[1]    137982 abort (core dumped)  Ryujinx
```

### Environment?

- Ryujinx version: 1.0.0 Dirty (Installed via `yay -S ryujinx-git`). Issue happens on the non-dirty, latest binary as well.
- Game version: 1.0.0, 1.4.3
- System Specs:
  - OS: Arch GNU/Linux
  - CPU: Ryzen 3800X
  - GPU: NVIDIA RTX 2070 Super
  - RAM: 32 GB @ 3200 MHz
  - Applied Mods/DLC: None

**Comment by GamerzHell9137** [comment]
Works fine on Linux now, can be closed.
![image](https://user-images.githubusercontent.com/2002038/153525200-69b5a473-2656-4d9f-82f9-a6e8da585db7.png)

**Comment by ThatOneCalculator** [comment]
![](http://images6.fanpop.com/image/photos/36700000/Japan-image-japan-36709375-150-150.gif)
