### ISSUE TITLE
One Piece Pirate Warriors 3 Create map delete map loop 

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [Ryujinx/Ryujinx#213]
`00:00:46.375 | 0009 ServiceNv Create: Created map 13 with size 0x00040000!
00:00:46.442 | 0009 ServiceNv Free: Deleted map 13!`

`Unhandled Exception: ChocolArm64.Exceptions.VmmPageFaultException: Tried to access unmapped address 0xffffffffffffffff!
   at ChocolArm64.Memory.AMemory.EnsureAccessIsValid(Int64 Position, AMemoryPerm Perm) in C:\projects\ryujinx\ChocolArm64\Memory\AMemory.cs:line 700
   at ChocolArm64.Memory.AMemory.ReadUInt32(Int64 Position) in C:\projects\ryujinx\ChocolArm64\Memory\AMemory.cs:line 235
   at Ryujinx.Graphics.Gal.Shader.ShaderDecoder.FillBlock(IGalMemory Memory, ShaderIrBlock Block) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\Shader\ShaderDecoder.cs:line 139
   at Ryujinx.Graphics.Gal.Shader.ShaderDecoder.Decode(IGalMemory Memory, Int64 Start) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\Shader\ShaderDecoder.cs:line 41
   at Ryujinx.Graphics.Gal.Shader.GlslDecompiler.Decompile(IGalMemory Memory, Int64 Position, GalShaderType ShaderType) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\Shader\GlslDecompiler.cs:line 126
   at Ryujinx.Graphics.Gal.OpenGL.OGLShader.ShaderStageFactory(IGalMemory Memory, Int64 Position, Int64 PositionB, Boolean IsDualVp, GalShaderType Type) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLShader.cs:line 119
   at Ryujinx.Graphics.Gal.OpenGL.OGLShader.<>c__DisplayClass12_0.<Create>b__0(Int64 Stage) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLShader.cs:line 100
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Ryujinx.Graphics.Gal.OpenGL.OGLShader.Create(IGalMemory Memory, Int64 Key, GalShaderType Type) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLShader.cs:line 101
   at Ryujinx.HLE.Gpu.Engines.NvGpuEngine3d.UploadShaders(NvGpuVmm Vmm) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuEngine3d.cs:line 173
   at Ryujinx.HLE.Gpu.Engines.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuEngine3d.cs:line 78
   at Ryujinx.HLE.Gpu.Engines.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuEngine3d.cs:line 72
   at Ryujinx.HLE.Gpu.Engines.MacroInterpreter.Send(NvGpuVmm Vmm, Int32 Value) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\MacroInterpreter.cs:line 431
   at Ryujinx.HLE.Gpu.Engines.MacroInterpreter.Step(NvGpuVmm Vmm, Int32[] Mme) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\MacroInterpreter.cs:line 199
   at Ryujinx.HLE.Gpu.Engines.MacroInterpreter.Execute(NvGpuVmm Vmm, Int32[] Mme, Int32 Position, Int32 Param) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\MacroInterpreter.cs:line 92
   at Ryujinx.HLE.Gpu.Engines.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuFifo.cs:line 176
   at Ryujinx.HLE.Gpu.Engines.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuFifo.cs:line 143
   at Ryujinx.HLE.Gpu.Engines.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuFifo.cs:line 84
   at Ryujinx.HLE.Switch.ProcessFrame() in C:\projects\ryujinx\Ryujinx.HLE\Switch.cs:line 76
   at Ryujinx.GLScreen.OnUpdateFrame(FrameEventArgs e) in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 185
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Ui\Program.cs:line 70`

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/57
