### ISSUE TITLE
Settings Bug

### ISSUE THREAD

**Issue by WassaYT** [Ryujinx/Ryujinx#2196]
## Bug Report

When I want to go to the settings in my Master LDN, there is this error:

Marshaling activate signal
00:00:03.790 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.Windows.SettingsWindow..ctor(MainWindow parent, Builder builder, VirtualFileSystem virtualFileSystem, ContentManager contentManager) in C:\project\ryujinx\Ryujinx\Ui\Windows\SettingsWindow.cs:line 293
   at Ryujinx.Ui.MainWindow.Settings_Pressed(Object sender, EventArgs args) in C:\project\ryujinx\Ryujinx\Ui\MainWindow.cs:line 1207
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### Log file
[Ryujinx_1.0.0-ldn2.2_2021-04-11_12-56-09.log](https://github.com/Ryujinx/Ryujinx/files/6291604/Ryujinx_1.0.0-ldn2.2_2021-04-11_12-56-09.log)

### Environment?

- Ryujinx version: 1.0.0</br>
- Game version: Its not a game, its just when i want to open settings

- System Specs:
  - OS: *Windows 10*
  - CPU: *Ryzen 5 2600*
  - GPU: *Rx 580*
  - RAM: *8gb DDR4*

**Comment by AcK77** [comment]
`File` > `Open Ryujinx Folder` then delete the LDNconfig.json in the opened folder and try again.
Issues aren't for user support. If you needs more help, please come to our discord. Thanks.
