### ISSUE TITLE
Ryujinx.Memory.MemoryProtectionException

### ISSUE THREAD

**Issue by MrAdamo** [Ryujinx/Ryujinx#2201]
### What's the issue you encountered?

I launched Monster Hunter Rise after updating Ryujinx to the latest version, it started to rebuild PPTC cache and then loading PTC cache but it crashed past halfway.
I was also browsing in google chrome and my screen flashed a few times before the crash, when Ryujinx crashed my current tab displayed a "Aw, Snap!" error message.
Second launch attempt was successful.

### How can the issue be reproduced?

N/A

### Log file

> 00:03:45.895 |I| GUI.RenderLoop Gpu Initialize: Shader cache loaded 385 entries.
00:03:45.905 |I| HLE.GuestThread.15 Ptc MakeAndSaveTranslations: 0 of 80266 functions translated | Thread count: 32
00:07:38.109 |E| Application : Unhandled exception caught: Ryujinx.Memory.MemoryProtectionException: Failed to set memory protection to "ReadWriteExecute".
   at Ryujinx.Memory.MemoryManagement.Reprotect(IntPtr address, UInt64 size, MemoryPermission permission) in C:\projects\ryujinx\Ryujinx.Memory\MemoryManagement.cs:line 87
   at Ryujinx.Cpu.JitMemoryBlock.MapAsRwx(UInt64 offset, UInt64 size) in C:\projects\ryujinx\Ryujinx.Cpu\JitMemoryBlock.cs:line 20
   at ARMeilleure.Translation.Cache.JitCache.Map(CompiledFunction func) in C:\projects\ryujinx\ARMeilleure\Translation\Cache\JitCache.cs:line 61
   at ARMeilleure.Translation.Translator.Translate(IMemoryManager memory, JumpTable jumpTable, UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 254
   at ARMeilleure.Translation.PTC.Ptc.<>c__DisplayClass77_0.<MakeAndSaveTranslations>g__TranslateFuncs|0() in C:\projects\ryujinx\ARMeilleure\Translation\PTC\Ptc.cs:line 816
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment?

- Ryujinx version: 1.0.6829</br>
- Game version: 1.1.1</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-8700K
  - GPU: RTX 2080 Ti
  - RAM: 32GB
- Applied Mods : 6GB memory hack

### Additional context?

N/A

**Comment by AcK77** [comment]
I don't understand your issue here, and I don't see how to reproduce that. In that way I close it.
