### ISSUE TITLE
Input configuration window does not work

### ISSUE THREAD

**Issue by BishopWolf** [Ryujinx/Ryujinx#2234]
### What's the issue you encountered?

Input configuration window doesn't show from settings, it is not possible to configure any controller.

### How can the issue be reproduced?

in the last update it stopped working

### Log file

```
00:00:00.161 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.169 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.169 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.169 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.169 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.169 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.170 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.170 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.170 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.173 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0-dirty
00:00:00.178 |N| Application Print: Operating System: Linux 5.11.14-1-MANJARO #1 SMP PREEMPT Wed Apr 14 08:25:29 UTC 2021 (X64)
00:00:00.178 |N| Application Print: CPU: AMD Ryzen 7 2700X Eight-Core Processor ; 16 logical
00:00:00.178 |N| Application Print: RAM: Total 32119 MB ; Available 24641 MB
00:00:00.180 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.181 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.668 |W| GUI.ApplicationLibraryThread Application LoadApplications: The header key is incorrect or missing and therefore the NCA header content type check has failed. Errored File: /home/alex/Descargas/Nintendo Switch/Super Smash Bros Ultimate V11.0.0 Incl. all Dlcs Eur SuperXCi - kaze-nico.xci
00:00:06.464 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Ryujinx.Ui.Windows.ControllerWindow.GetShrinkedGamepadName(String str) in /build/ryujinx-git/src/Ryujinx/Ryujinx/Ui/Windows/ControllerWindow.cs:line 237
   at Ryujinx.Ui.Windows.ControllerWindow.UpdateInputDeviceList() in /build/ryujinx-git/src/Ryujinx/Ryujinx/Ui/Windows/ControllerWindow.cs:line 269
   at Ryujinx.Ui.Windows.ControllerWindow..ctor(MainWindow mainWindow, Builder builder, PlayerIndex controllerId) in /build/ryujinx-git/src/Ryujinx/Ryujinx/Ui/Windows/ControllerWindow.cs:line 178
   at Ryujinx.Ui.Windows.SettingsWindow.ConfigureController_Pressed(Object sender, PlayerIndex playerIndex) in /build/ryujinx-git/src/Ryujinx/Ryujinx/Ui/Windows/SettingsWindow.cs:line 581
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

### Environment?

- Ryujinx version: 1.0.0-dirty r1619.c1cbdd45d-1 </br>
- Game version: N/A</br>
- System Specs:
  - OS: Manjaro 21.0.2 Ornara
  - CPU: Ryzen 2700X
  - GPU: AMD RX570
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
N/A

**Comment by AcK77** [comment]
Sadly your logs contains a file path to a pirated content, since Ryujinx don’t support piracy we can’t help you.
