### ISSUE TITLE
Monster hunter rise LAN ERROR after load game or start new game.

### ISSUE THREAD

**Issue by ZeyRick** [Ryujinx/Ryujinx#2235]
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient: 31

Guest Stack Trace:
Process: Service, PID: 83

Raw Request Data:
00000000   01 00 20 00 01 00 00 00  00 00 00 00 00 00 00 00   ｷｷ ｷｷｷｷｷｷｷｷｷｷｷｷｷ
00000010   53 46 43 49 01 00 00 00  1F 00 00 00 00 00 00 00   SFCIｷｷｷｷｷｷｷｷｷｷｷｷ
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ｷｷｷｷｷｷｷｷｷｷｷｷｷｷｷｷ
00000030   48 80 B6 BA 01 00 00 00                            H? ｺｷｷｷｷ

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 148
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 216
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\project\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ZeyRick** [comment]
NOTE it doesnt crash if I turn off LAN

**Comment by EmulationFanatic** [comment]
You've solved the puzzle; leave LAN off for this game.
