### ISSUE TITLE
Unhandled exception thrown and emulator exit on starting Animal Crossing New Horizons

### ISSUE THREAD

**Issue by fasterliu** [Ryujinx/Ryujinx#2239]
### What's the issue you encountered?

Just had a new install of release version 1.0.6845 and then auto upgrade to version 1.0.6846. When starting the game Animal Crossing New Horizons, there is an exception thrown, and the emulator quit. Here are the exception (details in the log file):
<pre>
00:00:46.706 |E| GUI.RenderLoop Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.LoadMmeStartAddressRam(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 183
   at Ryujinx.Graphics.Device.DeviceState`1.Write(Int32 offset, Int32 data) in C:\projects\ryujinx\Ryujinx.Graphics.Device\DeviceState.cs:line 97
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 150
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 450
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
</pre>
or
<pre>
00:00:43.297 |E| GUI.RenderLoop Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.LoadMmeInstructionRam(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 174
   at Ryujinx.Graphics.Device.DeviceState`1.Write(Int32 offset, Int32 data) in C:\projects\ryujinx\Ryujinx.Graphics.Device\DeviceState.cs:line 97
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 150
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 450
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
</pre>

### How can the issue be reproduced?

- Open Ryujinx (current version 1.0.6846)
- Select firmware 12.0.0
- Run Animal Crossing New Horizons v1.0.9 ('Animal Crossing New Horizons  (01006F8002326000) (World) (En,Ja,Fr,De,Es,It,Nl,Pt,Ru).nsp' with patch 'Animal Crossing New Horizons [01006F8002326800] [USA] [v1179648] Patched.nsp')
-  After a while, begin to play the startup video, the exception will occur

### Log file

[Ryujinx_1.0.6846_2021-04-22_18-19-07.log](https://github.com/Ryujinx/Ryujinx/files/6361913/Ryujinx_1.0.6846_2021-04-22_18-19-07.log)
[Ryujinx_1.0.6846_2021-04-22_20-35-19.log](https://github.com/Ryujinx/Ryujinx/files/6361940/Ryujinx_1.0.6846_2021-04-22_20-35-19.log)

### Environment?

- Ryujinx version: 1.0.6846</br>
- Game version: Animal Crossing New Horizons 1.0.9</br>
- System Specs:
  - OS: *Windows 10 Pro version 20H2*
  - CPU: *Intel(R) Core(TM) i9-9900T*
  - GPU: *NVIDIA Quadro P620*
  - RAM: *32GB*
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
N/A

**Comment by EmulationFanatic** [comment]
I think you mean version 1.9.0, but in all versions there is a high chance to crash on first boot without a save file. See our post here for a save file you can download:  
https://www.patreon.com/posts/animal-crossing-35196813

**Comment by fasterliu** [comment]
Thank you for the information. With the downloaded save file, it leads to other invalid memory potiner exception:
<pre>
00:03:04.514 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000004
   at Ryujinx.Cpu.MemoryManager.AssertValidAddressAndSize(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 567
   at Ryujinx.Cpu.MemoryManager.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 678
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 192
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.WriteImpl(UInt64 va, ReadOnlySpan`1 data, WriteCallback writeCallback) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 195
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 148
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 450
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
</pre>
I will do some more test before open a new issue.
