### ISSUE TITLE
Bayonetta 2 doesn't start anymore

### ISSUE THREAD

**Issue by redvulps** [Ryujinx/Ryujinx#2244]
### What's the issue you encountered?

Game make the emulator crash while booting the game itself.

### How can the issue be reproduced?

Just try to start the game. Caches gets generated and all the stuff, but emulator crashes before showing anything.

### Log file

```
00:00:04.838 |I| HLE.OsThread.8 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:04.841 |W| HLE.GuestThread.29 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:04.852 |S| HLE.OsThread.9 ServiceHid ActivateNpad: Stubbed. {appletResourceUserId: 1}
00:00:04.853 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:04.853 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 4294967296 ; type: ProController, Handheld}
00:00:04.865 |E| HLE.OsThread.9 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'npadIdType')
   at Ryujinx.HLE.HOS.Services.Hid.HidServer.HidUtils.GetIndexFromNpadIdType(NpadIdType npadIdType) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Hid\HidServer\HidUtils.cs:line 20
   at Ryujinx.HLE.HOS.Services.Hid.IHidServer.SetSupportedNpadIdType(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Hid\IHidServer.cs:line 601
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Environment?

- Ryujinx version: 1.0.6848</br>
- Game version: 1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 3600
  - GPU: NVIDIA RTX 2070 Super
  - RAM: 32GB
- Applied Mods : No

### Additional context?

N/A

**Comment by EmulationFanatic** [comment]
Thanks for the report! A fix is on the way.

**Comment by EmulationFanatic** [comment]
@redvulps this should now be fixed in the latest master.
