### ISSUE TITLE
Bravely Default 2 GuestBrokeExecutionException

### ISSUE THREAD

**Issue by Ryan2603** [Ryujinx/Ryujinx#2251]
## Bug Report

Ryujinx random crash

### What's the issue you encountered?

freeze, Ryujinx terminated.

### How can the issue be reproduced?

about an hours game play, more or less, its happened while loading map stage, battle or non-battle

### Log file

00:00:00.176 |N| Application LoadApplication: Using Firmware Version: 12.0.1
00:00:09.003 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 (4.6.0 NVIDIA 470.14)
00:41:10.797 |N| HLE.GuestThread.17 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 160
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment

- Ryujinx version: 1.0.6852</br>
- Game version: Bravely Default 2 NSP (this game no update)</br>
- System Specs:
  - OS: Windows 10 20H2
  - CPU: amd 3600X
  - GPU: NVIDIA 1060
  - RAM: 64GB
- Applied Mods :  No

### Additional context

Shader Cache disabled in Ryujin and Nvidia application profile 
PPTC also disabled after bootup game completely 
Whole NSP is stored and Running in Ramdrive

**Comment by AcK77** [comment]
It’s seems you have disabled some logs (for a strange reason). If you can provide a full log file it could be more useful, in the current state, your issue can’t help to fix anything. Thanks.

**Comment by Ryan2603** [comment]
[Ryujinx_1.0.6852_2021-04-28_20-05-49.log](https://github.com/Ryujinx/Ryujinx/files/6392098/Ryujinx_1.0.6852_2021-04-28_20-05-49.log)

my bad sorry, this is my first time here open an issue, thank you for reply, i recreated the error with full log here, many thanks for all!

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
