### ISSUE TITLE
Ryujinx crashes if SoundIO cannot get a valid channel configuration

### ISSUE THREAD

**Issue by sidewinder94** [Ryujinx/Ryujinx#2270]
### What's the issue you encountered?

Ryujinx crashes if SoundIO cannot get a valid channel configuration (Tested with Xenoblade Chronicles 2)

This is not happening when selecting either OpenAL or SDL2

### How can the issue be reproduced?

Run Ryujinx with Voicemeeter defined as the default sound peripheral and with SoundIO selected as the audio backend.

Games tested were Xenoblade Chronicles 2 and Gnosia

### Log file

Actual user name replaced with <username> in the below log

> 00:00:00.009 |I| Configuration LogValueChange: ResScale set to: 2
> 00:00:00.009 |I| Configuration LogValueChange: ResScaleCustom set to: 1
> 00:00:00.009 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
> 00:00:00.010 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
> 00:00:00.012 |I| Configuration LogValueChange: EnableDockedMode set to: True
> 00:00:00.020 |I| Configuration LogValueChange: EnableVsync set to: False
> 00:00:00.020 |I| Configuration LogValueChange: EnableShaderCache set to: True
> 00:00:00.020 |I| Configuration LogValueChange: EnablePtc set to: True
> 00:00:00.020 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
> 00:00:00.020 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
> 00:00:00.021 |I| Configuration LogValueChange: AudioBackend set to: SoundIo
> 00:00:00.021 |I| Configuration LogValueChange: ExpandRam set to: True
> 00:00:00.021 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
> 00:00:00.023 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6864
> 00:00:00.027 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
> 00:00:00.027 |N| Application Print: CPU: AMD Ryzen 7 3800X 8-Core Processor ; 16 logical
> 00:00:00.027 |N| Application Print: RAM: Total 32683 MB ; Available 16216 MB
> 00:00:00.028 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest
> 00:00:00.028 |N| Application PrintSystemInfo: Launch Mode: UserProfile
> 00:00:00.717 |I| Hid Configure: Configured Controller JoyconPair to Player1
> 00:00:00.795 |N| Application LoadApplication: Using Firmware Version: 11.0.1
> 00:00:00.795 |I| Application LoadApplication: Loading as XCI.
> 00:00:00.846 |I| Application AddAocData: Found AddOnContent with TitleId 0100E95004039005
> 00:00:00.846 |I| Application AddAocData: Found AddOnContent with TitleId 0100E95004039063
> 00:00:00.846 |I| Application AddAocData: Found AddOnContent with TitleId 0100E95004039006
> 00:00:00.846 |I| Application AddAocData: Found AddOnContent with TitleId 0100E95004039001
> 00:00:00.846 |I| Application AddAocData: Found AddOnContent with TitleId 0100E95004039003
> 00:00:00.846 |I| Application AddAocData: Found AddOnContent with TitleId 0100E95004039004
> 00:00:00.846 |I| Application AddAocData: Found AddOnContent with TitleId 0100E95004039002
> 00:00:00.871 |I| ModLoader QueryContentsDir: Searching mods for Title 0100E95004038000
> 00:00:00.871 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100E95004039001
> 00:00:00.871 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100E95004039002
> 00:00:00.871 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100E95004039003
> 00:00:00.871 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100E95004039004
> 00:00:00.871 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100E95004039005
> 00:00:00.871 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100E95004039006
> 00:00:00.871 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100E95004039063
> 00:00:00.878 |I| Application EnsureSaveData: Ensuring required savedata exists.
> 00:00:00.959 |I| Loader LoadExeFs: Loading rtld...
> 00:00:00.975 |I| Loader PrintRoSectionInfo: rtld:
>     Module: nnrtld
> 00:00:00.975 |I| Loader LoadExeFs: Loading main...
> 00:00:01.022 |I| Loader PrintRoSectionInfo: main:
>     Module: C:\Monolithsoft\BF2\prog\application\BF2\NX64\Rom_Final\BF2.nss
>     SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-3_5_0-Release
> 00:00:01.022 |I| Loader LoadExeFs: Loading subsdk0...
> 00:00:01.046 |I| Loader PrintRoSectionInfo: subsdk0:
>     Module: multimedia
>     SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-3_5_0-Release
> 00:00:01.046 |I| Loader LoadExeFs: Loading sdk...
> 00:00:01.081 |I| Loader PrintRoSectionInfo: sdk:
>     Module: nnSdk
>     FS SDK Version: 3.5.0
>     SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-3_5_0-Release
>                    SDK MW+Nintendo+NintendoSdk_nnSdk-3_5_0-Release
>                    SDK MW+Nintendo+NintendoSDK_NVN-3_5_0-Release
> 00:00:01.132 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
> 00:00:02.149 |I| Ptc Load: Loaded Translation Cache (size: 97669369 bytes, translated functions: 41490).
> 00:00:02.159 |I| Ptc Load: Loaded Profiling Info (size: 139433 bytes, profiled functions: 41490).
> 00:00:02.249 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
> 00:00:02.251 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
> 00:00:02.254 |I| Loader LoadNsos: Loading image 2 at 0x00000000095f1000...
> 00:00:02.255 |I| Loader LoadNsos: Loading image 3 at 0x0000000009cac000...
> 00:00:02.261 |I| ModLoader LoadCheats: Build ids found for title 0100E95004038000:
>     A75512BE30BB2A8C880177505D7A0B3E24E9D642000000000000000000000000
>     F77F1559371C0EC6D50E78774AC59D9500000000000000000000000000000000
>     2201BB705408EF610E9AAC23195011D1DD9606F5000000000000000000000000
>     867B345248124EF3D70E3202E221E978964C592F000000000000000000000000
> 00:00:02.261 |I| Loader LoadNca: Application Loaded: Xenoblade Chronicles 2 v2.1.0 [0100e95004038000] [64-bit]
> 00:00:02.479 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
> 00:00:02.848 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce RTX 3090/PCIe/SSE2 (4.6.0 NVIDIA 466.11)
> 00:00:02.934 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\<username>\AppData\Roaming\Ryujinx\games\0100e95004038000\cache\shader\guest\program\cache.zip...
> 00:00:03.043 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\<username>\AppData\Roaming\Ryujinx\games\0100e95004038000\cache\shader\guest\program\cache.zip.
> 00:00:03.116 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\<username>\AppData\Roaming\Ryujinx\games\0100e95004038000\cache\shader\opengl\glsl\host\cache.zip...
> 00:00:03.245 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\<username>\AppData\Roaming\Ryujinx\games\0100e95004038000\cache\shader\opengl\glsl\host\cache.zip.
> 00:00:05.644 |I| GUI.RenderLoop Gpu Initialize: Host shader 990e37a5437ccef38c1bd34e01cbd699 got invalidated, rebuilding from guest...
> 00:00:05.969 |I| CacheCollection.Worker.program Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\<username>\AppData\Roaming\Ryujinx\games\0100e95004038000\cache\shader\guest\program\cache.zip...
> 00:00:05.973 |I| CacheCollection.Worker.host Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\<username>\AppData\Roaming\Ryujinx\games\0100e95004038000\cache\shader\opengl\glsl\host\cache.zip...
> 00:00:06.092 |I| CacheCollection.Worker.program Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\<username>\AppData\Roaming\Ryujinx\games\0100e95004038000\cache\shader\guest\program\cache.zip.
> 00:00:06.116 |I| CacheCollection.Worker.host Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\<username>\AppData\Roaming\Ryujinx\games\0100e95004038000\cache\shader\opengl\glsl\host\cache.zip.
> 00:00:06.123 |I| GUI.RenderLoop Gpu Initialize: Shader cache loaded 2686 entries.
> 00:00:06.607 |I| HLE.GuestThread.15 Ptc LoadTranslations: 41490 translated functions loaded
> 00:00:06.748 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
> 00:00:06.801 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039001
> 00:00:06.802 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039001
> 00:00:06.804 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039002
> 00:00:06.805 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039002
> 00:00:06.806 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039003
> 00:00:06.807 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039003
> 00:00:06.813 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039004
> 00:00:06.814 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039004
> 00:00:06.815 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039005
> 00:00:06.816 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039005
> 00:00:06.817 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039006
> 00:00:06.818 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039006
> 00:00:06.819 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039063
> 00:00:06.820 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039063
> 00:00:06.913 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 1
> 00:00:06.947 |I| HLE.OsThread.10 ServiceNv Create: Created map 1 with size 0x00001000!
> 00:00:06.956 |I| HLE.OsThread.10 ServiceNv Create: Created map 2 with size 0x00010000!
> 00:00:06.959 |I| HLE.OsThread.10 ServiceNv Create: Created map 3 with size 0x00001000!
> 00:00:06.965 |I| HLE.OsThread.10 ServiceNv Create: Created map 4 with size 0x00020000!
> 00:00:06.965 |I| HLE.OsThread.10 ServiceNv Create: Created map 5 with size 0x00049000!
> 00:00:06.969 |I| HLE.OsThread.10 ServiceNv Create: Created map 6 with size 0x00080000!
> 00:00:06.969 |I| HLE.OsThread.10 ServiceNv Create: Created map 7 with size 0x16a00000!
> 00:00:06.984 |I| HLE.OsThread.10 ServiceNv Create: Created map 8 with size 0x02a00000!
> 00:00:06.986 |I| HLE.OsThread.10 ServiceNv Create: Created map 9 with size 0x01c00000!
> 00:00:06.991 |I| HLE.OsThread.10 ServiceNv Create: Created map 10 with size 0x01f82000!
> 00:00:06.992 |I| HLE.OsThread.10 ServiceNv Create: Created map 11 with size 0x00004000!
> 00:00:06.992 |I| HLE.OsThread.10 ServiceNv Create: Created map 12 with size 0x00180000!
> 00:00:06.992 |I| HLE.OsThread.10 ServiceNv Create: Created map 13 with size 0x00180000!
> 00:00:06.992 |I| HLE.OsThread.10 ServiceNv Create: Created map 14 with size 0x00180000!
> 00:00:06.993 |I| HLE.OsThread.10 ServiceNv Create: Created map 15 with size 0x00300000!
> 00:00:06.994 |I| HLE.OsThread.10 ServiceNv Create: Created map 16 with size 0x00600000!
> 00:00:06.995 |I| HLE.OsThread.10 ServiceNv Create: Created map 17 with size 0x00300000!
> 00:00:07.022 |I| HLE.OsThread.10 ServiceNv Create: Created map 18 with size 0x00001000!
> 00:00:07.327 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
> 00:00:07.738 |I| HLE.OsThread.10 ServiceNv Create: Created map 19 with size 0x00100000!
> 00:00:07.818 |I| HLE.OsThread.10 ServiceNv Create: Created map 20 with size 0x001b6000!
> 00:00:07.854 |I| HLE.OsThread.10 ServiceNv Create: Created map 21 with size 0x00002000!
> 00:00:07.855 |I| HLE.OsThread.10 ServiceNv Create: Created map 22 with size 0x00002000!
> 00:00:07.855 |I| HLE.OsThread.10 ServiceNv Create: Created map 23 with size 0x00002000!
> 00:00:07.858 |I| HLE.OsThread.10 ServiceNv Create: Created map 24 with size 0x00020000!
> 00:00:07.861 |I| HLE.OsThread.10 ServiceNv Create: Created map 25 with size 0x00010000!
> 00:00:07.862 |I| HLE.OsThread.10 ServiceNv Create: Created map 26 with size 0x00010000!
> 00:00:07.872 |I| HLE.OsThread.10 ServiceNv Create: Created map 27 with size 0x000ac000!
> 00:00:07.882 |I| HLE.OsThread.10 ServiceNv Create: Created map 28 with size 0x000ac000!
> 00:00:07.884 |I| HLE.OsThread.10 ServiceNv Create: Created map 29 with size 0x00020000!
> 00:00:07.886 |I| HLE.OsThread.10 ServiceNv Create: Created map 30 with size 0x00010000!
> 00:00:07.887 |I| HLE.OsThread.10 ServiceNv Create: Created map 31 with size 0x00002000!
> 00:00:07.889 |I| HLE.OsThread.10 ServiceNv Create: Created map 32 with size 0x00010000!
> 00:00:07.890 |I| HLE.OsThread.10 ServiceNv Create: Created map 33 with size 0x00002000!
> 00:00:07.892 |I| HLE.OsThread.10 ServiceNv Create: Created map 34 with size 0x00010000!
> 00:00:07.892 |I| HLE.OsThread.10 ServiceNv Create: Created map 35 with size 0x00001000!
> 00:00:07.896 |I| HLE.OsThread.10 ServiceNv Create: Created map 36 with size 0x00001000!
> 00:00:07.898 |I| HLE.OsThread.10 ServiceNv Create: Created map 37 with size 0x00008000!
> 00:00:07.899 |I| HLE.OsThread.10 ServiceNv Create: Created map 38 with size 0x00008000!
> 00:00:07.926 |I| HLE.OsThread.10 ServiceNv Create: Created map 39 with size 0x00004000!
> 00:00:07.927 |I| HLE.OsThread.10 ServiceNv Create: Created map 40 with size 0x00004000!
> 00:00:07.927 |I| HLE.OsThread.10 ServiceNv Create: Created map 41 with size 0x00004000!
> 00:00:07.927 |I| HLE.OsThread.10 ServiceNv Create: Created map 42 with size 0x00004000!
> 00:00:07.927 |I| HLE.OsThread.10 ServiceNv Create: Created map 43 with size 0x00004000!
> 00:00:07.927 |I| HLE.OsThread.10 ServiceNv Create: Created map 44 with size 0x00004000!
> 00:00:07.927 |I| HLE.OsThread.10 ServiceNv Create: Created map 45 with size 0x00004000!
> 00:00:07.928 |I| HLE.OsThread.10 ServiceNv Create: Created map 46 with size 0x00004000!
> 00:00:07.928 |I| HLE.OsThread.10 ServiceNv Create: Created map 47 with size 0x00004000!
> 00:00:07.928 |I| HLE.OsThread.10 ServiceNv Create: Created map 48 with size 0x00004000!
> 00:00:07.928 |I| HLE.OsThread.10 ServiceNv Create: Created map 49 with size 0x00004000!
> 00:00:07.928 |I| HLE.OsThread.10 ServiceNv Create: Created map 50 with size 0x00004000!
> 00:00:07.928 |I| HLE.OsThread.10 ServiceNv Create: Created map 51 with size 0x00004000!
> 00:00:07.930 |I| HLE.OsThread.10 ServiceNv Create: Created map 52 with size 0x00004000!
> 00:00:07.931 |I| HLE.OsThread.10 ServiceNv Create: Created map 53 with size 0x00004000!
> 00:00:07.931 |I| HLE.OsThread.10 ServiceNv Create: Created map 54 with size 0x00004000!
> 00:00:07.931 |I| HLE.OsThread.10 ServiceNv Create: Created map 55 with size 0x00004000!
> 00:00:07.931 |I| HLE.OsThread.10 ServiceNv Create: Created map 56 with size 0x00004000!
> 00:00:07.931 |I| HLE.OsThread.10 ServiceNv Create: Created map 57 with size 0x00004000!
> 00:00:07.931 |I| HLE.OsThread.10 ServiceNv Create: Created map 58 with size 0x00004000!
> 00:00:07.932 |I| HLE.OsThread.10 ServiceNv Create: Created map 59 with size 0x00004000!
> 00:00:07.932 |I| HLE.OsThread.10 ServiceNv Create: Created map 60 with size 0x00004000!
> 00:00:07.932 |I| HLE.OsThread.10 ServiceNv Create: Created map 61 with size 0x00004000!
> 00:00:07.932 |I| HLE.OsThread.10 ServiceNv Create: Created map 62 with size 0x00004000!
> 00:00:07.932 |I| HLE.OsThread.10 ServiceNv Create: Created map 63 with size 0x00004000!
> 00:00:07.932 |I| HLE.OsThread.10 ServiceNv Create: Created map 64 with size 0x00004000!
> 00:00:07.933 |I| HLE.OsThread.10 ServiceNv Create: Created map 65 with size 0x00004000!
> 00:00:07.933 |I| HLE.OsThread.10 ServiceNv Create: Created map 66 with size 0x00004000!
> 00:00:07.933 |I| HLE.OsThread.10 ServiceNv Create: Created map 67 with size 0x00004000!
> 00:00:07.933 |I| HLE.OsThread.10 ServiceNv Create: Created map 68 with size 0x00004000!
> 00:00:07.933 |I| HLE.OsThread.10 ServiceNv Create: Created map 69 with size 0x00004000!
> 00:00:07.933 |I| HLE.OsThread.10 ServiceNv Create: Created map 70 with size 0x00004000!
> 00:00:07.933 |I| HLE.OsThread.10 ServiceNv Create: Created map 71 with size 0x00004000!
> 00:00:07.934 |I| HLE.OsThread.10 ServiceNv Create: Created map 72 with size 0x00004000!
> 00:00:07.934 |I| HLE.OsThread.10 ServiceNv Create: Created map 73 with size 0x00004000!
> 00:00:07.934 |I| HLE.OsThread.10 ServiceNv Create: Created map 74 with size 0x00004000!
> 00:00:07.934 |I| HLE.OsThread.10 ServiceNv Create: Created map 75 with size 0x00004000!
> 00:00:07.934 |I| HLE.OsThread.10 ServiceNv Create: Created map 76 with size 0x00004000!
> 00:00:07.934 |I| HLE.OsThread.10 ServiceNv Create: Created map 77 with size 0x00004000!
> 00:00:07.934 |I| HLE.OsThread.10 ServiceNv Create: Created map 78 with size 0x00004000!
> 00:00:07.935 |I| HLE.OsThread.10 ServiceNv Create: Created map 79 with size 0x00004000!
> 00:00:07.935 |I| HLE.OsThread.10 ServiceNv Create: Created map 80 with size 0x00004000!
> 00:00:07.935 |I| HLE.OsThread.10 ServiceNv Create: Created map 81 with size 0x00004000!
> 00:00:07.935 |I| HLE.OsThread.10 ServiceNv Create: Created map 82 with size 0x00004000!
> 00:00:07.935 |I| HLE.OsThread.10 ServiceNv Create: Created map 83 with size 0x00004000!
> 00:00:07.936 |I| HLE.OsThread.10 ServiceNv Create: Created map 84 with size 0x00004000!
> 00:00:07.936 |I| HLE.OsThread.10 ServiceNv Create: Created map 85 with size 0x00004000!
> 00:00:07.936 |I| HLE.OsThread.10 ServiceNv Create: Created map 86 with size 0x00004000!
> 00:00:07.936 |I| HLE.OsThread.10 ServiceNv Create: Created map 87 with size 0x00004000!
> 00:00:07.936 |I| HLE.OsThread.10 ServiceNv Create: Created map 88 with size 0x00004000!
> 00:00:07.936 |I| HLE.OsThread.10 ServiceNv Create: Created map 89 with size 0x00004000!
> 00:00:07.936 |I| HLE.OsThread.10 ServiceNv Create: Created map 90 with size 0x00004000!
> 00:00:07.937 |I| HLE.OsThread.10 ServiceNv Create: Created map 91 with size 0x00004000!
> 00:00:07.937 |I| HLE.OsThread.10 ServiceNv Create: Created map 92 with size 0x00004000!
> 00:00:07.937 |I| HLE.OsThread.10 ServiceNv Create: Created map 93 with size 0x00004000!
> 00:00:07.937 |I| HLE.OsThread.10 ServiceNv Create: Created map 94 with size 0x00004000!
> 00:00:07.937 |I| HLE.OsThread.10 ServiceNv Create: Created map 95 with size 0x00004000!
> 00:00:07.937 |I| HLE.OsThread.10 ServiceNv Create: Created map 96 with size 0x00004000!
> 00:00:07.937 |I| HLE.OsThread.10 ServiceNv Create: Created map 97 with size 0x00004000!
> 00:00:07.939 |I| HLE.OsThread.10 ServiceNv Create: Created map 98 with size 0x17c00000!
> 00:00:08.024 |I| HLE.OsThread.10 ServiceNv Create: Created map 99 with size 0x04000000!
> 00:00:08.032 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
> 00:00:08.034 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new renderer (0)
> 00:00:08.043 |I| HLE.OsThread.7 AudioRenderer Initialize: Initializing with REV3
> 00:00:08.074 |E| HLE.OsThread.7 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.ArgumentException: No valid channel configuration found!
>    at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.SelectHardwareChannelCount(UInt32 targetChannelCount) in C:\projects\ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 61
>    at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.SelectHardwareChannelCount(UInt32 targetChannelCount) in C:\projects\ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 57
>    at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.OpenDeviceSession(Direction direction, IVirtualMemoryManager memoryManager, SampleFormat sampleFormat, UInt32 sampleRate, UInt32 channelCount) in C:\projects\ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 116
>    at Ryujinx.Audio.Integration.HardwareDeviceImpl..ctor(IHardwareDeviceDriver deviceDriver, UInt32 channelCount, UInt32 sampleRate) in C:\projects\ryujinx\Ryujinx.Audio\Integration\HardwareDeviceImpl.cs:line 35
>    at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Start(IHardwareDeviceDriver deviceDriver) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 87
>    at Ryujinx.Audio.Renderer.Server.AudioRendererManager.StartLocked() in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Server\AudioRendererManager.cs:line 185
>    at Ryujinx.Audio.Renderer.Server.AudioRendererManager.Register(AudioRenderSystem renderer) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Server\AudioRendererManager.cs:line 249
>    at Ryujinx.Audio.Renderer.Server.AudioRendererManager.OpenAudioRenderer(AudioRenderSystem& renderer, IVirtualMemoryManager memoryManager, AudioRendererConfiguration& parameter, UInt64 appletResourceUserId, UInt64 workBufferAddress, UInt64 workBufferSize, UInt32 processHandle) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Server\AudioRendererManager.cs:line 295
>    at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.OpenAudioRenderer(ServiceCtx context, IAudioRenderer& obj, AudioRendererConfiguration& parameter, UInt64 workBufferSize, UInt64 appletResourceUserId, KTransferMemory workBufferTransferMemory, UInt32 processHandle) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager.cs:line 38
>    at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManagerServer.OpenAudioRenderer(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManagerServer.cs:line 37
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
>    at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 211
>    at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
>    at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 

### Environment?

- Ryujinx version: 1.0.6864</br>
- Game version: 2.1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 7 3800X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
- Applied Mods : None

### Additional context?

Additional info about your environment:</br>
None that I can think of

**Comment by sidewinder94** [comment]
From what little I could experiment running Ryujinx in debug, and playing with the wrapper code for soundIO.

I'd say there is an incompatibility of some sort between soundIO and Voicemeeter.

I'm not proficient enough to go further than this, but if nothing can be done to make it work, at least, having Ryujinx fall back to another audio backend (even if it's just the dummy one) to avoid a crash would be beneficial IMHO.

**Comment by conkerts** [comment]
I will hop in here, as I had a 
---> System.ArgumentException: No valid channel configuration found!
yesterday, too

So I am on Windoze 10, funnily also tried to run XB2.
I didn't change any audio settings in the emu, so just checked, that it is indeed SoundIO here, too.

I am connected to an AV receiver, and when it is set on Windoze to 5.1 channel configuration, the whole emu crashes when trying to run the game.

When I change it to stereo config, it works.
Sadly the logs got overwritten (I really need an option to keep more, or just archive them ...),
but I can set it back to 5.1 and then generate logs, if needed.

**Comment by sidewinder94** [comment]
@TSRBerry I can confirm that the issue is still present / relevant.

Just tested it right now with the latest available stable build.
