### ISSUE TITLE
Rune factory 4 - crash to desktop: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.  at Ryujinx.Audio.Renderer.Server.Mix.MixState.UpdateConnection

### ISSUE THREAD

**Issue by anonus1231** [Ryujinx/Ryujinx#2293]
## Bug Report

After playing for about 1 hour Rune factory 4 will crash to desktop, in the logs at the end there is always a message:
`00:55:08.366 |E| HLE.OsThread.7 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Audio.Renderer.Server.Mix.MixState.UpdateConnection(EdgeMatrix edgeMatrix, MixParameter& parameter, SplitterContext& splitterContext) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Server\Mix\MixState.cs:line 262
   at Ryujinx.Audio.Renderer.Server.Mix.MixState.Update(EdgeMatrix edgeMatrix, MixParameter& parameter, EffectContext effectContext, SplitterContext splitterContext, BehaviourContext behaviourContext) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Server\Mix\MixState.cs:line 294
   at Ryujinx.Audio.Renderer.Server.StateUpdater.UpdateMixes(MixContext mixContext, UInt32 mixBufferCount, EffectContext effectContext, SplitterContext splitterContext) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Server\StateUpdater.cs:line 413
   at Ryujinx.Audio.Renderer.Server.AudioRenderSystem.Update(Memory`1 output, Memory`1 performanceOutput, ReadOnlyMemory`1 input) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Server\AudioRenderSystem.cs:line 453
   at Ryujinx.HLE.HOS.Services.Audio.AudioRenderer.AudioRendererServer.RequestUpdate(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRenderer\AudioRendererServer.cs:line 77
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 212
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1028
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
00:55:08.368 |S| HLE.OsThread.9 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 4294967296 ; sixAxisSensorHandle: 131075 ; isAtRest: True}
`
### Environment

- Ryujinx version: 1.0.0+d7f4df7 - build from:  https://github.com/Ryujinx/Ryujinx/pull/2286 

- Game version: 1.0

- System Specs:
  - OS: Windows 10
  - CPU: i7-7700k
  - GPU: NVIDIA GTX 1070
  - RAM: 16GB
- Applied Mods : Some texture replacer

### Logs
[logs.zip](https://github.com/Ryujinx/Ryujinx/files/6511791/logs.zip)

**Comment by gdkchan** [comment]
Please only post bugs that only happens with PR builds on the PR itself. Also the build you are using is outdated, the issue might have been already fixed. If you still get the issue with the new PR build, please post it on #2286. Thanks.
