### ISSUE TITLE
Crash when launching a game with SoundIO

### ISSUE THREAD

**Issue by PandaJoueur** [Ryujinx/Ryujinx#2294]
### What's the issue you encountered?

When using SoundIO, any game that I launched crashed immediately (just after black loading screen) but when using OpenAL, games are fine, except Yoshi Crafted World who have a bad crispy audio quality (by the way, this why i'm trying to use SoundIO).

### How can the issue be reproduced?

Launch Ryujinx with SoundIO. The below crash occurs.

```
HLE.OsThread.8 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: No valid channel configuration found!
   at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.SelectHardwareChannelCount(UInt32 targetChannelCount) in C:\projects\ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 61
   at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.SelectHardwareChannelCount(UInt32 targetChannelCount) in C:\projects\ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 57
   at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.OpenDeviceSession(Direction direction, IVirtualMemoryManager memoryManager, SampleFormat sampleFormat, UInt32 sampleRate, UInt32 channelCount) in C:\projects\ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 116
   at Ryujinx.Audio.Output.AudioOutputManager.OpenAudioOut(String& outputDeviceName, AudioOutputConfiguration& outputConfiguration, AudioOutputSystem& obj, IVirtualMemoryManager memoryManager, String inputDeviceName, SampleFormat sampleFormat, AudioInputConfiguration& parameter, UInt64 appletResourceUserId, UInt32 processHandle) in C:\projects\ryujinx\Ryujinx.Audio\Output\AudioOutputManager.cs:line 210
   at Ryujinx.HLE.HOS.Services.Audio.AudioOutManager.OpenAudioOut(ServiceCtx context, String& outputDeviceName, AudioOutputConfiguration& outputConfiguration, IAudioOut& obj, String inputDeviceName, AudioInputConfiguration& parameter, UInt64 appletResourceUserId, UInt32 processHandle) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioOutManager.cs:line 27
   at Ryujinx.HLE.HOS.Services.Audio.AudioOutManagerServer.OpenAudioOut(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioOutManagerServer.cs:line 78
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 212
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Log file

[Ryujinx_1.0.6878_2021-05-20_14-11-14.log](https://github.com/Ryujinx/Ryujinx/files/6515814/Ryujinx_1.0.6878_2021-05-20_14-11-14.log)

### Environment?

- Ryujinx version: 1.0.6878</br>

- Game version: 1.0.1</br>

- System Specs:
  - OS: Windows 10 (Family)
  - CPU: i7-10750H CPU @ 2.60GHz
  - GPU: NVIDIA RTX 2070 SUPER
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Shader Cache: On
Audio Engine: SoundIO
Resolution Scale: x2

**Comment by AcK77** [comment]
It’s the same issue as https://github.com/Ryujinx/Ryujinx/issues/2270, in that way I close this one. Thanks.

**Comment by PandaJoueur** [comment]
So no solution ? ;(

**Comment by EmulationFanatic** [comment]
> So no solution ? ;(

You can use SDL2 which should work better than OpenAL and without the SoundIO issue. Or you can change your audio output configuration in the OS to stereo which should fix it on SoundIO.

**Comment by PandaJoueur** [comment]
okay will try ^^ thanks.
