### ISSUE TITLE
Zelda BOTW crashing

### ISSUE THREAD

**Issue by tvoracek** [Ryujinx/Ryujinx#2314]
## Bug Report
Zelda BOTW crashing in various areas. Was not happening that often before Power release.

### What's the issue you encountered?

Game seems to be crashing when some backgound processing and other stuff is happening, it will slowdown significantly, also audio will stop. Then it crashes the emulator. 

### How can the issue be reproduced?

Just walking around Kakariko village or trying to get to another location from there is enough to crash the emulator.

### Log file

00:00:00.021 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.022 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.022 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.023 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.024 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.025 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.025 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.025 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.025 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: False
00:00:00.025 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.025 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.025 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.025 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.027 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6875
00:00:00.030 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.030 |N| Application Print: CPU: AMD Ryzen 5 3600 6-Core Processor ; 12 logical
00:00:00.030 |N| Application Print: RAM: Total 16298 MB ; Available 8052 MB
00:00:00.032 |N| Application PrintSystemInfo: Logs Enabled: Info
00:00:00.032 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### Environment?

- Ryujinx version: 1.0.6895
- Game version: 1.6.0
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5 3600
  - GPU: NVIDIA GTX 1660Ti
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Stacktrace from Windows error log:
Application: Ryujinx.exe
CoreCLR Version: 5.0.621.22011
.NET Version: 5.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: Ryujinx.Memory.InvalidMemoryRegionException: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000004
   at Ryujinx.Cpu.MemoryManagerHostMapped.AssertValidAddressAndSize(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 121
   at Ryujinx.Cpu.MemoryManagerHostMapped.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 403
   at Ryujinx.Cpu.MemoryManagerHostMapped.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 241
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.WriteImpl(UInt64 va, ReadOnlySpan`1 data, WriteCallback writeCallback) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 195
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 148
   at Ryujinx.Graphics.Device.DeviceState`1.Write(Int32 offset, Int32 data) in C:\projects\ryujinx\Ryujinx.Graphics.Device\DeviceState.cs:line 97
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 150
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\projects\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 307

another error spotted:
Application: Ryujinx.exe
CoreCLR Version: 5.0.621.22011
.NET Version: 5.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'id')
   at Ryujinx.Graphics.Gpu.Synchronization.SynchronizationManager.IncrementSyncpoint(UInt32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Synchronization\SynchronizationManager.cs:line 42
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.Syncpointb(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 141
   at Ryujinx.Graphics.Device.DeviceState`1.Write(Int32 offset, Int32 data) in C:\projects\ryujinx\Ryujinx.Graphics.Device\DeviceState.cs:line 97
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 150
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\projects\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 307

**Comment by GamerzHell9137** [comment]
Still happens on master 1.1.23

**Comment by combo-pizza** [comment]
I'm using the experimental vulkan build so take this with a grain of salt, but disabling PPTC seems to have stopped it from crashing for me. After disabling it link would end up swimming on land sometimes. I figured it was similar to the old cemu texture cache bug so I ended up disable texture cache and it was fast enough with out it with multithreading enabled.

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!

**Comment by tvoracek** [comment]
@EmulationFanatic was this resolved though? What is the reason for closing this?

**Comment by ayurai** [comment]
He literally SAID the reason "REPORT GAME-SPECIFIC ISSUES ON COMPATIBILITY LIST 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/86 
/\ for zelda botw
