### ISSUE TITLE
Cannot set controller --- |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by Kenya-Watanabe** [Ryujinx/Ryujinx#2345]
When I set controller on Ryujinx ( Options -> Setttings -> Input -> Player 1 Configure Click )  this error happens.
Please help me.

 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Ryujinx.Ui.Windows.ControllerWindow.GetShrinkedGamepadName(String str) in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 237
   at Ryujinx.Ui.Windows.ControllerWindow.UpdateInputDeviceList() in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 269
   at Ryujinx.Ui.Windows.ControllerWindow..ctor(MainWindow mainWindow, Builder builder, PlayerIndex controllerId) in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 178
   at Ryujinx.Ui.Windows.SettingsWindow.ConfigureController_Pressed(Object sender, PlayerIndex playerIndex) in C:\projects\ryujinx\Ryujinx\Ui\Windows\SettingsWindow.cs:line 618
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by AcK77** [comment]
Please open a new issue following our template with much informations as possible. Thanks.
