### ISSUE TITLE
Rune Factory 5 Unhandled Exception Caught? System.InvalidOperationException? CTD

### ISSUE THREAD

**Issue by Algester** [Ryujinx/Ryujinx#2356]
## Bug Report
I'm not sure if this is a bug or a missing instruction issue but it is somewhere here that the game crashed
00:34:50.854 |E| HLE.GuestThread.59 Application : Unhandled exception caught: System.InvalidOperationException: Decoded a single empty exit block. Entry point = 0x0.
   at ARMeilleure.Decoders.Decoder.Decode(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq, Boolean singleBlock) in C:\projects\ryujinx\ARMeilleure\Decoders\Decoder.cs:line 143
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 254
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 223
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 240
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 171
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1038
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

### What's the issue you encountered?

The game just caused to CTD

### How can the issue be reproduced?
Playing the game and attempt to plant meteor seeds it will maybe cause the game to crash but I havent tried to do a repeatability test yet

### Log file

[Ryujinx_1.0.6909_2021-06-10_10-05-23.log](https://github.com/Ryujinx/Ryujinx/files/6628074/Ryujinx_1.0.6909_2021-06-10_10-05-23.log)

### Environment?

- Ryujinx version: 1.0.690</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.2</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10
  - CPU: i7-9700K
  - GPU: nVidia GTX 1050ti
  - RAM: 16GB
- Applied Mods : No? but there are farm plot cheats.... maybe they maybe the culprit so I'll remove them to check if it works

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
