### ISSUE TITLE
Can't get whether dynamic DNS is enabled on Linux

### ISSUE THREAD

**Issue by Benedani** [Ryujinx/Ryujinx#2415]
### What's the issue you encountered?
Minecraft: Bedrock Edition (v1.0.0 tested) - and I guess other games if they make the same request - cause the emulator to crash with the following exception.
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties.get_IsDynamicDnsEnabled()
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.Types.DnsSetting..ctor(IPInterfaceProperties interfaceProperties)
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService.GetCurrentNetworkProfile(ServiceCtx context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
This issue is not related to game compatibility; rather, it's the implementation of a service not working on Linux. The game boots fine on Windows and makes it ingame.

### How can the issue be reproduced?
1. Install Linux on your system, and get Ryujinx running on it.
2. Try to open Minecraft: Bedrock Edition without any updates applied.
3. As it's loading things at the black screen, you should get the crash.

### Log file
[Ryujinx_1.0.6939_2021-06-27_15-01-31.log](https://github.com/Ryujinx/Ryujinx/files/6721620/Ryujinx_1.0.6939_2021-06-27_15-01-31.log)

### Environment?
- Ryujinx version: 1.0.6939</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Arch Linux
  - CPU: i7-4770s
  - GPU: GTX 1050 Ti
  - RAM: 16 GiB physical, 8 GiB swap
- Applied Mods : None

**Comment by edisionnano** [comment]
Its a known bug, sera reported it on a game report too. I get this bug even with ryu versions that didn't before so it isn't a ryujinx regression. I believe it could be a dotnet one.
One way of "fixing" this is to go to https://github.com/Ryujinx/Ryujinx/blob/b662a26c7e2b66d916986b1ed9ffae3b918619d1/Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/DnsSetting.cs and replace all 3 occurances of IsDynamicDnsEnabled with IsDnsEnabled
