### ISSUE TITLE
Cannot use controller settings

### ISSUE THREAD

**Issue by Kenya-Watanabe** [Ryujinx/Ryujinx#2442]
## Bug Report
 
I cannot set controller and use it.

### What's the issue you encountered?
I want to use controller on Ryujinx.
Go Options -> Settings -> Input.
When I click "configure" button, Nothing happens.
Keyboard can be used.
Enable Docker mode checked and Direct Keyboard Access not checked. 

### Log file

0:00:00.012 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.013 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.013 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.013 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.015 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.027 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.027 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.027 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.027 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.027 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.028 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.029 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.029 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.029 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.030 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6906
00:00:00.035 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.035 |N| Application Print: CPU: AMD Ryzen 5 4600HS with Radeon Graphics ; 12 logical
00:00:00.036 |N| Application Print: RAM: Total 15790 MB ; Available 5306 MB
00:00:00.038 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.038 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:12.583 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Ryujinx.Ui.Windows.ControllerWindow.GetShrinkedGamepadName(String str) in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 237
   at Ryujinx.Ui.Windows.ControllerWindow.UpdateInputDeviceList() in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 269
   at Ryujinx.Ui.Windows.ControllerWindow..ctor(MainWindow mainWindow, Builder builder, PlayerIndex controllerId) in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 178
   at Ryujinx.Ui.Windows.SettingsWindow.ConfigureController_Pressed(Object sender, PlayerIndex playerIndex) in C:\projects\ryujinx\Ryujinx\Ui\Windows\SettingsWindow.cs:line 618
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### Environment?

- Ryujinx version: 1.0.6906</br>

- Game version: 12.0.3 </br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 5 4600HS with Radeon Graphics            3.00 GHz
  - GPU: nvidia geforce gtx 1650 gddr6 4gb
  - RAM: 16 GB
- Applied Mods : No

**Comment by Kenya-Watanabe** [comment]
Using this version, I became able to use my controller. Thank you !
