### ISSUE TITLE
Firmware 12.1.0

### ISSUE THREAD

**Issue by Xabyos** [Ryujinx/Ryujinx#2472]
## Bug Report

Firmware 12.1.0 can't install because of missing Prod.key's. But the keys are correctly installed.
Didn't had that problem with 12.0.3.

### What's the issue you encountered?

00:00:13.960 |E| Application HandleInstallerDialog: LibHac.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0b
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.<VerifyFirmwarePackage>g__VerifyAndGetVersionZip|44_1(ZipArchive archive, <>c__DisplayClass44_0& )
   at Ryujinx.HLE.FileSystem.Content.ContentManager.VerifyFirmwarePackage(String firmwarePackage)
   at Ryujinx.Ui.MainWindow.HandleInstallerDialog(FileChooserDialog fileChooser)
00:07:37.638 |E| Application HandleInstallerDialog: LibHac.MissingKeyException: Unable to decrypt NCA section.

### How can the issue be reproduced?

Just try to install Firmware 12.1.0 and this message shows in the Console and Popup window with no prod keys installed shows up.

### Log file

00:00:13.960 |E| Application HandleInstallerDialog: LibHac.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0b
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.<VerifyFirmwarePackage>g__VerifyAndGetVersionZip|44_1(ZipArchive archive, <>c__DisplayClass44_0& )
   at Ryujinx.HLE.FileSystem.Content.ContentManager.VerifyFirmwarePackage(String firmwarePackage)
   at Ryujinx.Ui.MainWindow.HandleInstallerDialog(FileChooserDialog fileChooser)
00:07:37.638 |E| Application HandleInstallerDialog: LibHac.MissingKeyException: Unable to decrypt NCA section.

### Environment?

- Ryujinx version: 1.0.6961</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 5950X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by RyzenDew** [comment]
The new firmware brought a new header key you have to update your keys once you're done 12.1.0 will work fine I am already running it￼
