### ISSUE TITLE
DLL not found when load .nsp file

### ISSUE THREAD

**Issue by Catiks** [Ryujinx/Ryujinx#2513]
## Bug Report

00:00:15.968 |E| Ryujinx.NvdecProcessor Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Ryujinx.Graphics.Nvdec.H264Decoder' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'avutil.56 under /home/***/Ryujinx/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_611(Int32 level)
   at Ryujinx.Graphics.Nvdec.H264.FFmpegContext..ctor()
   at Ryujinx.Graphics.Nvdec.H264.Decoder..ctor()
   at Ryujinx.Graphics.Nvdec.H264Decoder..cctor()
   --- End of inner exception stack trace ---
   at Ryujinx.Graphics.Nvdec.H264Decoder.Decode(NvdecDevice device, ResourceManager rm, NvdecRegisters& state)
   at Ryujinx.Graphics.Nvdec.NvdecDevice.Decode(CodecId codecId)
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment?

- Ryujinx version: 1.0.6976</br>

- Game version: 4.0.0</br>

- System Specs:
  - OS: ubuntu 20.04
  - CPU: i7-9700K
  - GPU: Intel Corporation UHD Graphics 630 (Desktop 9 Series)
  - RAM: 32G
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>

**Comment by AcK77** [comment]
You have to install ffmpeg dependencies. I suggest you to come to our discord server if you needs more help.

**Comment by KingKebab** [comment]
I'm on the same issue with many .xci dumps.

```
00:00:02.744 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD PITCAIRN (DRM 2.50.0, 5.15.11, LLVM 13.0.0) (4.5 (Compatibility Profile) Mesa 21.3.4)
00:00:21.805 |E| Ryujinx.NvdecProcessor FFmpeg : FFmpeg wasn't found. Make sure that you have it installed and up to date.
00:00:21.954 |E| Ryujinx.NvdecProcessor Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Ryujinx.Graphics.Nvdec.FFmpeg.FFmpegContext' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'avutil.56 under /tmp/.mount_RyujinVhDVxy/usr/bin/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_613(Int32 level)
   at Ryujinx.Graphics.Nvdec.FFmpeg.FFmpegContext..cctor()
   --- End of inner exception stack trace ---
   at Ryujinx.Graphics.Nvdec.FFmpeg.FFmpegContext..ctor(AVCodecID codecId)
   at Ryujinx.Graphics.Nvdec.FFmpeg.H264.Decoder..ctor()
   at Ryujinx.Graphics.Nvdec.NvdecDecoderContext.GetH264Decoder()
   at Ryujinx.Graphics.Nvdec.H264Decoder.Decode(NvdecDecoderContext context, ResourceManager rm, NvdecRegisters& state)
   at Ryujinx.Graphics.Nvdec.NvdecDevice.Decode(CodecId codecId)
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork()
```

FFMpeg is available throught the command line.

 
```
[root@CAPRI /usr/lib]# ffmpeg
ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.2.0 (Buildroot 2021.08-1645-gcccc06e59a)
  configuration: --enable-cross-compile --cross-prefix=/x86_64/host/bin/x86_64-buildroot-linux-gnu- --sysroot=/x86_64/host/x86_64-buildroot-linux-gnu/sysroot --host-cc='/x86_64/host/bin/ccache /usr/bin/gcc' --arch=x86_64 --target-os=linux --disable-stripping --pkg-config=/x86_64/host/bin/pkg-config --enable-static --enable-shared --prefix=/usr --enable-avfilter --disable-version3 --enable-logging --enable-optimizations --disable-extra-warnings --enable-avdevice --enable-avcodec --enable-avformat --enable-network --disable-gray --enable-swscale-alpha --disable-small --enable-dct --enable-fft --enable-mdct --enable-rdft --disable-crystalhd --disable-dxva2 --enable-runtime-cpudetect --disable-hardcoded-tables --disable-mipsdsp --disable-mipsdspr2 --disable-msa --enable-hwaccels --disable-cuda --disable-cuvid --disable-nvenc --disable-avisynth --disable-frei0r --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libdc1394 --disable-libgsm --disable-libilbc --disable-libvo-amrwbenc --disable-symver --disable-doc --enable-gpl --disable-nonfree --enable-ffmpeg --disable-ffplay --disable-libv4l2 --enable-avresample --enable-ffprobe --enable-libxcb --enable-libxcb-shape --enable-libxcb-shm --enable-libxcb-xfixes --enable-postproc --enable-swscale --enable-indevs --enable-alsa --enable-outdevs --enable-pthreads --enable-zlib --enable-bzlib --disable-libfdk-aac --enable-libcdio --enable-gnutls --disable-openssl --enable-libdrm --enable-libopenh264 --enable-libvorbis --enable-muxer=ogg --enable-encoder=libvorbis --enable-vaapi --enable-vdpau --disable-mmal --disable-omx --disable-omx-rpi --disable-libopencv --enable-libopus --enable-libvpx --enable-libass --enable-libbluray --disable-libmfx --enable-librtmp --enable-libmp3lame --enable-libmodplug --enable-libspeex --enable-libtheora --disable-iconv --enable-libfreetype --enable-fontconfig --disable-libopenjpeg --enable-libx264 --enable-libx265 --disable-libdav1d --enable-x86asm --enable-sse --enable-sse2 --enable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-avx --disable-avx2 --disable-armv6 --disable-armv6t2 --disable-vfp --disable-neon --disable-altivec --extra-libs=-latomic --enable-pic --cpu=nocona
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

The Linux operating system is a Batocera_x64 release 33.
And the required libavutil.56 is available in the _/usr/bin_ folder.

```
[root@CAPRI /usr/lib]# ls *libavutil* 
libavutil.so            libavutil.so.56         libavutil.so.56.70.100
```

**Comment by All-The-Foxes** [comment]
I'm having the same issue. The dependencies are all installed and up to date.
