### ISSUE TITLE
Issue Booting ANY Game With Ryujinx

### ISSUE THREAD

**Issue by Jack-Rickwood** [Ryujinx/Ryujinx#253]
I have a pc running windows 10, and would like to run ryujinx on it, however whenever i drag a rom onto the executable, it always says:
"Unhandled Exception: System.TypeInitializationException: The type initializer for 'OpenTK.Audio.AudioContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'OpenTK.Audio.AudioDeviceEnumerator' threw an exception. ---> System.TypeInitializationException: The type initializer for 'OpenTK.Audio.OpenAL.Alc' threw an exception. ---> System.TypeInitializationException: The type initializer for 'OpenTK.Audio.OpenAL.AL' threw an exception. ---> System.InvalidOperationException: Could not load openal32.dll
   at OpenTK.NativeLibrary..ctor(String libraryName)
   at OpenTK.NativeLibrary.Load(String libraryName)
   at OpenTK.Audio.OpenAL.AL..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Audio.OpenAL.Alc..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Audio.OpenAL.Alc.MakeContextCurrent(IntPtr context)
   at OpenTK.Audio.OpenAL.Alc.MakeContextCurrent(ContextHandle context)
   at OpenTK.Audio.AudioDeviceEnumerator..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Audio.AudioDeviceEnumerator.get_IsOpenALSupported()
   at OpenTK.Audio.AudioContext..cctor()
   --- End of inner exception stack trace ---
   at Ryujinx.Audio.OpenAL.OpenALAudioOut..ctor() in C:\projects\ryujinx\Ryujinx.Audio\OpenAL\OpenALAudioOut.cs:line 204
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Ui\Program.cs:line 21". And then it closes.

I have tried many different versions of ryujinx and none of them work. Im sure its not the roms im using, because they all work with yuzu. The roms i have tried booting are Super Mario Odyssey, 1... 2... Switch and Space Game (a port to switch).

**Comment by Jack-Rickwood** [comment]
Thanks, idk what i was thinking

**Comment by khang06** [comment]
you should probably close this then

**Comment by Jack-Rickwood** [comment]
Ok

**Comment by pasko17** [comment]
hi i have the same problem and i have installed openal 11sdk.  but still the same impossible to launch the game except dummy

**Comment by pasko17** [comment]
Only dummy no sound work,,why ? Please help

**Comment by EmulationFanatic** [comment]
@pasko17 this issue is closed. Please come to our Discord server support.
