### ISSUE TITLE
Crash when game load on Clear Linux

### ISSUE THREAD

**Issue by gartstell** [Ryujinx/Ryujinx#2555]
I start Ryujinx with the same command that I use in Fedora

`env AMD_DEBUG=w32ge,w32ps,w32cs,nohyperz,nofmask glsl_zero_init=true radeonsi_clamp_div_by_zero=true force_integer_tex_nearest=true mesa_glthread=true vblank_mode=0 ./Ryujinx`

I get this error message:

```
00:00:00.739 |E| Application : Unhandled exception caught: System.EntryPointNotFoundException: Unable to find an entry point named 'glXCreateContextAttribsARB' in shared library 'glx.dll'.
   at SPB.Platform.GLX.GLX.ARB.CreateContextAttribs(IntPtr display, IntPtr fbConfigs, IntPtr shareContext, Boolean direct, Int32[] attributes)
   at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL()
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

Ryujinx 1.0.6997
Clear 34930

**Comment by Thog** [comment]
Invalid format, please follow the template.
