### ISSUE TITLE
crash when verify de keys

### ISSUE THREAD

**Issue by Marcosmoreno123** [Ryujinx/Ryujinx#2558]
### What's the issue you encountered?

I just try to execute de program with the key and receive that error log

### How can the issue be reproduced?

NA

### Log file

```
00:00:00.018 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.019 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.019 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.019 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.023 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.033 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.033 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.033 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.033 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.033 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.035 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.036 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.036 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.036 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.043 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6997
00:00:00.050 |N| Application Print: Operating System: Microsoft Windows 10.0.19041 (X64)
00:00:00.050 |N| Application Print: CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz ; 8 logical
00:00:00.050 |N| Application Print: RAM: Total 16321 MB ; Available 11980 MB
00:00:00.056 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.056 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.922 |E| Application : Unhandled exception caught: LibHac.HorizonResultException: ResultFsAesXtsFileHeaderInvalidKeys (2002-4743): NAX0 key derivation failed.
   at LibHac.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.AesXtsFile..ctor(OpenMode mode, IFile baseFile, U8String path, ReadOnlySpan`1 kekSeed, ReadOnlySpan`1 verificationKey, Int32 blockSize)
   at LibHac.FsSystem.AesXtsFileSystem.DoOpenFile(IFile& file, U8Span path, OpenMode mode)
   at LibHac.Fs.Fsa.IFileSystem.OpenFile(IFile& file, U8Span path, OpenMode mode)
   at LibHac.FsSystem.SubdirectoryFileSystem.DoOpenFile(IFile& file, U8Span path, OpenMode mode)
   at LibHac.Fs.Fsa.IFileSystem.OpenFile(IFile& file, U8Span path, OpenMode mode)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.Initialize(ISaveDataCommitTimeStampGetter timeStampGetter, RandomDataGenerator randomGenerator, Boolean isJournalingSupported, Boolean isMultiCommitSupported, Boolean isJournalingEnabled)
   at LibHac.FsSrv.FsCreator.SaveDataFileSystemCreator.Create(ReferenceCountedDisposable`1& fileSystem, ReferenceCountedDisposable`1& extraDataAccessor, ISaveDataFileSystemCacheManager cacheManager, ReferenceCountedDisposable`1& baseFileSystem, SaveDataSpaceId spaceId, UInt64 saveDataId, Boolean allowDirectorySaveData, Boolean useDeviceUniqueMac, Boolean isJournalingSupported, Boolean isMultiCommitSupported, Boolean openReadOnly, Boolean openShared, ISaveDataCommitTimeStampGetter timeStampGetter)
   at LibHac.FsSrv.SaveDataFileSystemServiceImpl.OpenSaveDataFileSystem(ReferenceCountedDisposable`1& fileSystem, SaveDataSpaceId spaceId, UInt64 saveDataId, U8Span saveDataRootPath, Boolean openReadOnly, SaveDataType type, Boolean cacheExtraData)
   at LibHac.FsSrv.SaveDataFileSystemService.OpenSaveDataFileSystemCore(ReferenceCountedDisposable`1& fileSystem, UInt64& saveDataId, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly, Boolean cacheExtraData)
   at LibHac.FsSrv.SaveDataFileSystemService.OpenSaveDataFileSystemBySystemSaveDataId(ReferenceCountedDisposable`1& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute)
   at LibHac.FsSrv.FileSystemProxyImpl.OpenSaveDataFileSystemBySystemSaveDataId(ReferenceCountedDisposable`1& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute)
   at LibHac.Fs.Shim.SystemSaveData.<MountSystemSaveData>g__Mount|3_0(FileSystemClient fs, U8Span mountName, SaveDataSpaceId spaceId, UInt64 saveDataId, UserId userId)
   at LibHac.Fs.Shim.SystemSaveData.MountSystemSaveData(FileSystemClient fs, U8Span mountName, SaveDataSpaceId spaceId, UInt64 saveDataId, UserId userId)
   at LibHac.FsSrv.SaveDataIndexer.Mounter.Mount(FileSystemClient fsClient, U8String mountName, SaveDataSpaceId spaceId, UInt64 saveDataId)
   at LibHac.FsSrv.SaveDataIndexer.TryInitializeDatabase()
   at LibHac.FsSrv.SaveDataIndexer.OpenSaveDataInfoReader(ReferenceCountedDisposable`1& infoReader)
   at LibHac.FsSrv.SaveDataFileSystemService.OpenSaveDataInfoReaderBySaveDataSpaceId(ReferenceCountedDisposable`1& infoReader, SaveDataSpaceId spaceId)
   at LibHac.FsSrv.FileSystemProxyImpl.OpenSaveDataInfoReaderBySaveDataSpaceId(ReferenceCountedDisposable`1& infoReader, SaveDataSpaceId spaceId)
   at LibHac.Fs.Shim.SaveDataManagement.OpenSaveDataIterator(FileSystemClientImpl fs, SaveDataIterator& iterator, SaveDataSpaceId spaceId)
   at LibHac.Fs.Shim.SaveDataManagement.OpenSaveDataIterator(FileSystemClient fs, SaveDataIterator& iterator, SaveDataSpaceId spaceId)
   at Ryujinx.HLE.FileSystem.VirtualFileSystem.FixExtraDataInSpaceId(HorizonClient hos, SaveDataSpaceId spaceId)
   at Ryujinx.HLE.FileSystem.VirtualFileSystem.FixExtraData(HorizonClient hos)
   at Ryujinx.Ui.MainWindow..ctor(Builder builder)
   at Ryujinx.Program.Main(String[] args)
```

### Environment?

- Ryujinx version: 1.0.6997
- Game version: NA
- System Specs:
  - OS: Microsoft Windows 10.0.19041 (X64)
  - CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  - GPU: NVIDIA GTX 1660 SUPER
  - RAM: 16GB DDR 3
- Applied Mods : NO

### Additional context?

NA

**Comment by natanaelsimoes** [comment]
Same here

**Comment by AcK77** [comment]
Delete the `%appdata%\Ryujinx\sdcard\Nintendo` directory

**Comment by Marcosmoreno123** [comment]
i must to delete the \sdcard directory too. Finally is working
