### ISSUE TITLE
Cannot compile a cheat

### ISSUE THREAD

**Issue by Xenofex** [Ryujinx/Ryujinx#2559]
### What's the issue you encountered?

I was trying to find an 60 fps mod for Monster Hunter Rise 3.2. I found the cheat [here](https://gbatemp.net/threads/monster-hunter-rise-60-fps-mod.585713/page-8#post-9540699). It says only the cheat is required, no more the patch/mod.

Placed a cheat code file ([B09F83B9EF28C00D.txt](https://github.com/Ryujinx/Ryujinx/files/6991408/B09F83B9EF28C00D.txt)) in the mods directory (in its 'cheats' sub directory), which is opened by right clicking the game in the list and click 'Open Mods Directory', but nothing happened. 

In the log I saw

```
00:00:04.229 |I| ModLoader LoadCheats: Installing cheat '<Unlock 60 FPS Limit Cheat>'
00:00:04.229 |E| TamperMachine Compile: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Tamper.InstructionHelper.GetCodeType(Byte[] instruction) in C:\project\ryujinx\Ryujinx.HLE\HOS\Tamper\InstructionHelper.cs:line 80
   at Ryujinx.HLE.HOS.Tamper.CodeEmitters.EndConditionalBlock.Emit(Byte[] instruction, CompilationContext context) in C:\project\ryujinx\Ryujinx.HLE\HOS\Tamper\CodeEmitters\EndConditionalBlock.cs:line 18
   at Ryujinx.HLE.HOS.Tamper.AtmosphereCompiler.CompileImpl(IEnumerable`1 rawInstructions, UInt64 exeAddress, UInt64 heapAddress, ITamperedProcess process) in C:\project\ryujinx\Ryujinx.HLE\HOS\Tamper\AtmosphereCompiler.cs:line 59
   at Ryujinx.HLE.HOS.Tamper.AtmosphereCompiler.Compile(IEnumerable`1 rawInstructions, UInt64 exeAddress, UInt64 heapAddress, ITamperedProcess process) in C:\project\ryujinx\Ryujinx.HLE\HOS\Tamper\AtmosphereCompiler.cs:line 19
00:00:04.229 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
```

### How can the issue be reproduced?

- Install Ryujinx LDN 2.3. Obtained from https://www.patreon.com/posts/introducing-ldn2-45268370
- Install Monster Hunter Rise in xci format, and the 3.2 update.
- Open its mods directory, place the cheat file ([B09F83B9EF28C00D.txt](https://github.com/Ryujinx/Ryujinx/files/6991408/B09F83B9EF28C00D.txt)) in the 'cheats' sub directory
- Launch the game, still running in 30 fps

### Log file

[Ryujinx_1.0.0-ldn2.3_2021-08-16_17-40-48.log](https://github.com/Ryujinx/Ryujinx/files/6991402/Ryujinx_1.0.0-ldn2.3_2021-08-16_17-40-48.log)

### Environment?

- Ryujinx version: LDN 2.3
- Game version: 3.2
- System Specs:
  - OS: Windows 10 Professional
  - CPU: AMD Ryzen 7 5800X
  - GPU: NVIDIA GTX 1080
  - RAM: 16GB
- Applied Mods : No, except for the aformentioned cheat

### Additional context?

Nothing here.

**Comment by Mou-Ikkai** [comment]
I can't say with 100% confidence, but the mod uses a 0x4 address (42700000), and we only started supporting those addresses in master. Not LDN yet.

**Comment by Xenofex** [comment]
Thanks for the reply!

Though I tried it on the master build (1.0.6997), it showed similar output in logs:

```
00:00:01.461 |E| TamperMachine Compile: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Tamper.InstructionHelper.GetCodeType(Byte[] instruction)
   at Ryujinx.HLE.HOS.Tamper.CodeEmitters.EndConditionalBlock.Emit(Byte[] instruction, CompilationContext context, IEnumerable`1 operationsElse)
   at Ryujinx.HLE.HOS.Tamper.AtmosphereCompiler.CompileImpl(String name, IEnumerable`1 rawInstructions)
   at Ryujinx.HLE.HOS.Tamper.AtmosphereCompiler.Compile(String name, IEnumerable`1 rawInstructions)
00:00:01.461 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:01.462 |I| Loader LoadNca: Application Loaded: MONSTER HUNTER RISE v3.2.0 [0100b04011742000] [64-bit]
```

Any idea on that? BTW the reason I run LDN build is that I learned that this runs MH Rise much smoother than the master build somewhere on the web. When will these improvements be merged back to master? Maybe in the near future?

**Comment by JumpmanSr** [comment]
Hello, it is recommended to use 3.0.0/3.1.0 for now because it has a wider variety of mods available. 
[3.0.0 Mods](https://github.com/theboy181/switch-ptchtxt-mods/tree/main/MONSTER%20HUNTER%20RISE/%5B0100B04011742000%5D/3.0.0) / [3.1.0 Mods](https://github.com/theboy181/switch-ptchtxt-mods/tree/main/MONSTER%20HUNTER%20RISE/%5B0100B04011742000%5D/3.1.0)

That being said, if you _need_ 60 fps on version 3.2.0 then please try the attached cheat file, there seemed to be a slight issue with the way it was written and how the TamperMachine module was reading it. I have resolved it and it seems to work fine on my end. Hopefully that helped!

[B09F83B9EF28C00D.txt](https://github.com/Ryujinx/Ryujinx/files/7003031/B09F83B9EF28C00D.txt) Credits to Hazerou for the original code.

**Comment by Xenofex** [comment]
Much appreciated, for your information and cheat file! I tested on LDN 2.3 and it works!

**Comment by JumpmanSr** [comment]
> Much appreciated, for your information and cheat file! I tested on LDN 2.3 and it works!

Glad I could help, since it was an issue with the cheat and not the emulator you should mark this as closed/resolved :) Enjoy!
