### ISSUE TITLE
Ryujinx crashes when launching any game

### ISSUE THREAD

**Issue by petran79** [Ryujinx/Ryujinx#2810]
Suddenly application stopped working at any game and it freezes after this message. I have to quit and relaunch it. 

 00:00:00.002 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.064 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.066 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.068 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.069 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.071 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.080 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.105 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.105 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.106 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.106 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.107 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.109 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.112 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.112 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.112 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.123 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.7096
00:00:00.131 |N| Application Print: Operating System: Microsoft Windows 10.0.19043 (X64)
00:00:00.131 |N| Application Print: CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz ; 8 logical
00:00:00.131 |N| Application Print: RAM: Total 16345 MB ; Available 11511 MB
00:00:00.134 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.134 |N| Application PrintSystemInfo: Launch Mode: UserProfile

(Ryujinx:12380): Gtk-CRITICAL **: 22:28:06.875: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
00:00:00.119 |I| Gpu : Backend Threading (Auto): True
Marshaling row-activated signal
00:00:00.406 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen)
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by ExE-Boss** [comment]
For me, this only happens when launching from the game list.

---

Launching from **File** → **Load Application from File** works fine.

**Comment by MetrosexualGarbodor** [comment]
Protip: click the game once then press Enter.

**Comment by fraf** [comment]
> Protip: click the game once then press Enter.

With your tip, regression occurs, this PR doesn't not work anymore (hide cursor checkbox) : https://github.com/Ryujinx/Ryujinx/pull/1993

**Comment by IceLancerSR** [comment]
Bloody hell so thats why i couldnt start games with updated Ryu

**Comment by Kaylakaze** [comment]
How is this still a problem after almost a year?

**Comment by riperiperi** [comment]
> How is this still a problem after almost a year?

Because it has never happened to a developer, and nobody it has happened to has really followed up. Double clicking on the games list does work on most setups.

**Comment by Kaylakaze** [comment]
Well, I'll follow up since I have the issue and think I see where it's coming from. On the game list, if I click a game, it highlights and immediately un-highlights. My guess is the error is thrown on double click because, when the event is triggered, there is no highlighted game because clicking is causing a game to be selected and then immediately unselected. The keyboard selected games as expected. If I right-click, the game is selected and the context menu comes up. If I close the context menu, the game remains selected, but if I click, it immediately unselects. Something that may be related, once the game list appears, a game is selected just on mouse hover until a click is made, then it behaves as noted.

**Comment by zifnab** [comment]
> Well, I'll follow up since I have the issue and think I see where it's coming from. On the game list, if I click a game, it highlights and immediately un-highlights. My guess is the error is thrown on double click because, when the event is triggered, there is no highlighted game because clicking is causing a game to be selected and then immediately unselected. The keyboard selected games as expected. If I right-click, the game is selected and the context menu comes up. If I close the context menu, the game remains selected, but if I click, it immediately unselects. Something that may be related, once the game list appears, a game is selected just on mouse hover until a click is made, then it behaves as noted.

Thank you for the observation. It has led me to realize the that culprit of this issue (for me) is YoloMouse. Shutting down YoloMouse fixed the problem. So if you are running YoloMouse or similar mouse cursor replacement app, try shutting it down.

**Comment by Kaylakaze** [comment]
I've never even HEARD of YoloMouse let alone run something called that.

**Comment by IceLancerSR** [comment]
> > Well, I'll follow up since I have the issue and think I see where it's coming from. On the game list, if I click a game, it highlights and immediately un-highlights. My guess is the error is thrown on double click because, when the event is triggered, there is no highlighted game because clicking is causing a game to be selected and then immediately unselected. The keyboard selected games as expected. If I right-click, the game is selected and the context menu comes up. If I close the context menu, the game remains selected, but if I click, it immediately unselects. Something that may be related, once the game list appears, a game is selected just on mouse hover until a click is made, then it behaves as noted.
> 
> Thank you for the observation. It has led me to realize the that culprit of this issue (for me) is YoloMouse. Shutting down YoloMouse fixed the problem. So if you are running YoloMouse or similar mouse cursor replacement app, try shutting it down.

Yup, yolo mouse was causing crash for me on double click. Funny tho that app was only active in trey not for Ryujinx

**Comment by Ash-Forest** [comment]
I am experiencing this issue, I am not running YoloMouse but I can see that the Ava version of of LDN does not present this issue.

**Comment by NPCgit** [comment]
I have this issue and I am not running YoloMouse, the game I am trying to run is Splatoon 3 and it appears to crash with the same error.

**Comment by Nebnis** [comment]
I'm running into this issue and the culprit was indeed Yolo mouse. Killing the app made it work again. But pressing once and selecting enter works. This is such an odd issue, i just find very fascinating that a program which i'm assuming it isn't even working for this software somehow interfere with it. I wonder if yolo mouse might be causing other issues

**Comment by AwkwardTeenageBoy** [comment]
I've spent hours searching for a solution but nothing, so I came here. The same thing happens to me but I can't open a game in any way. Any fix (and no I don't have whatever yolomouse is)

**Comment by Omniphantasm** [comment]
Issue happening to me with 1.1.1052

Crashes if I double click the game to load it, doesn't crash if I select open from file and select the exact same file I tried to double click in UI. 

No non-standard software installed that I know of and was working fine back during the ToTK release days.

**Comment by CoaxialQuazar** [comment]
> > Well, I'll follow up since I have the issue and think I see where it's coming from. On the game list, if I click a game, it highlights and immediately un-highlights. My guess is the error is thrown on double click because, when the event is triggered, there is no highlighted game because clicking is causing a game to be selected and then immediately unselected. The keyboard selected games as expected. If I right-click, the game is selected and the context menu comes up. If I close the context menu, the game remains selected, but if I click, it immediately unselects. Something that may be related, once the game list appears, a game is selected just on mouse hover until a click is made, then it behaves as noted.
> 
> Thank you for the observation. It has led me to realize the that culprit of this issue (for me) is YoloMouse. Shutting down YoloMouse fixed the problem. So if you are running YoloMouse or similar mouse cursor replacement app, try shutting it down.

i was having the same error and i can confirm that shutting down input director fixed it. it seems like its related to any software that interacts with the mouse.
