### ISSUE TITLE
Mii Editor: SoundIO crashes Mii Editor on run.

### ISSUE THREAD

**Issue by Mou-Ikkai** [Ryujinx/Ryujinx#2813]
### What's the issue you encountered?

When using the audio backend SoundIO, if you open Mii Editor, the emulator will crash on a black screen.

### How can the issue be reproduced?

Set your audio backend to SoundIO, then execute Mii Editor.

### Log file
Original discord reporter's log: 
[Ryujinx_1.0.7097_2021-11-04_20-06-28.log](https://github.com/Ryujinx/Ryujinx/files/7479435/Ryujinx_1.0.7097_2021-11-04_20-06-28.log)
My log with Linux: 
[Ryujinx_1.0.7097_2021-11-04_19-25-41.log](https://github.com/Ryujinx/Ryujinx/files/7479442/Ryujinx_1.0.7097_2021-11-04_19-25-41.log)
(Stack Smashing Detected)

### Environment?

- Ryujinx version: 1.0.7097</br>
- Firmware version: 13.1.0</br>
- System Specs:
  - OS: *Linux Mint 20.2*
  - CPU: *Ryzen 9 3900X*
  - GPU: *5700XT*
  - RAM: *32GB DDR4 + 16GB NVMe Swap*

**Comment by MutantAura** [comment]
Seems fine to me on Win10.
![image](https://user-images.githubusercontent.com/44103205/140434622-1fa47bd0-d808-4591-85ce-837e62903e32.png)

Linux specific perhaps?

**Comment by Mou-Ikkai** [comment]
> Seems fine to me on Win10. ![image](https://user-images.githubusercontent.com/44103205/140434622-1fa47bd0-d808-4591-85ce-837e62903e32.png)
> 
> Linux specific perhaps?

Not Linux specific, the 1st log in my report is from the original reporter on Discord, they use Windows.

**Comment by jduncanator** [comment]
I can take a look at this.

**Comment by AcK77** [comment]
The linux log doesn't contain any error message and I can't reproduce the issue on windows here. Any extra informations about the audio specs?
The error message is `No valid channel configuration found!`.

**Comment by B3astTech** [comment]
This is currently still a issue

### What's the issue you encountered?
I did as it described and it crashed Ryujinx

### How can the issue be reproduced?
Any Linux distro > Set your audio backend to SoundIO, > Then execute Mii Editor.

### End of log
```
00:00:02.979 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:03.080 |E| HLE.OsThread.7 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: This sound device does not support PcmInt16
   at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceDriver.OpenStream(SampleFormat requestedSampleFormat, UInt32 requestedSampleRate, UInt32 requestedChannelCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceDriver.cs:line 188
   at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceSession.SetupOutputStream(Single requestedVolume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceSession.cs:line 34
   at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceDriver.OpenDeviceSession(Direction direction, IVirtualMemoryManager memoryManager, SampleFormat sampleFormat, UInt32 sampleRate, UInt32 channelCount, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceDriver.cs:line 152
   at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.OpenDeviceSession(Direction direction, IVirtualMemoryManager memoryManager, SampleFormat sampleFormat, UInt32 sampleRate, UInt32 channelCount, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 99
   at Ryujinx.Audio.Output.AudioOutputManager.OpenAudioOut(String& outputDeviceName, AudioOutputConfiguration& outputConfiguration, AudioOutputSystem& obj, IVirtualMemoryManager memoryManager, String inputDeviceName, SampleFormat sampleFormat, AudioInputConfiguration& parameter, UInt64 appletResourceUserId, UInt32 processHandle, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Output\AudioOutputManager.cs:line 218
   at Ryujinx.HLE.HOS.Services.Audio.AudioOutManager.OpenAudioOut(ServiceCtx context, String& outputDeviceName, AudioOutputConfiguration& outputConfiguration, IAudioOut& obj, String inputDeviceName, AudioInputConfiguration& parameter, UInt64 appletResourceUserId, UInt32 processHandle, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioOutManager.cs:line 27
   at Ryujinx.HLE.HOS.Services.Audio.AudioOutManagerServer.OpenAudioOut(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioOutManagerServer.cs:line 78
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 214
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1182
```

### Log

[Ryujinx_1.1.5_2022-01-23_16-25-39.log](https://github.com/Ryujinx/Ryujinx/files/7921484/Ryujinx_1.1.5_2022-01-23_16-25-39.log)

Environment?
Ryujinx version: 1.1.5

System Specs:

OS: Fedora 35
CPU: i7-2600k
GPU: 1050ti
RAM: 16GB

**Comment by edisionnano** [comment]
> This is currently still a issue
> ### What's the issue you encountered?
> 
> I did as it described and it crashed Ryujinx
> ### How can the issue be reproduced?
> 
> Any Linux distro > Set your audio backend to SoundIO > Then execute Mii Editor.
> ### End of log
> 
> ```
> 00:00:02.979 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
> 00:00:03.080 |E| HLE.OsThread.7 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.ArgumentException: This sound device does not support PcmInt16
>    at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceDriver.OpenStream(SampleFormat requestedSampleFormat, UInt32 requestedSampleRate, UInt32 requestedChannelCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceDriver.cs:line 188
>    at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceSession.SetupOutputStream(Single requestedVolume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceSession.cs:line 34
>    at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceDriver.OpenDeviceSession(Direction direction, IVirtualMemoryManager memoryManager, SampleFormat sampleFormat, UInt32 sampleRate, UInt32 channelCount, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceDriver.cs:line 152
>    at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.OpenDeviceSession(Direction direction, IVirtualMemoryManager memoryManager, SampleFormat sampleFormat, UInt32 sampleRate, UInt32 channelCount, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 99
>    at Ryujinx.Audio.Output.AudioOutputManager.OpenAudioOut(String& outputDeviceName, AudioOutputConfiguration& outputConfiguration, AudioOutputSystem& obj, IVirtualMemoryManager memoryManager, String inputDeviceName, SampleFormat sampleFormat, AudioInputConfiguration& parameter, UInt64 appletResourceUserId, UInt32 processHandle, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Output\AudioOutputManager.cs:line 218
>    at Ryujinx.HLE.HOS.Services.Audio.AudioOutManager.OpenAudioOut(ServiceCtx context, String& outputDeviceName, AudioOutputConfiguration& outputConfiguration, IAudioOut& obj, String inputDeviceName, AudioInputConfiguration& parameter, UInt64 appletResourceUserId, UInt32 processHandle, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioOutManager.cs:line 27
>    at Ryujinx.HLE.HOS.Services.Audio.AudioOutManagerServer.OpenAudioOut(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioOutManagerServer.cs:line 78
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
>    at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
>    at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 214
>    at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
>    at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1182
> ```
> 
> ### Log
> 
> [Ryujinx_1.1.5_2022-01-23_16-25-39.log](https://github.com/Ryujinx/Ryujinx/files/7921484/Ryujinx_1.1.5_2022-01-23_16-25-39.log)
> 
> Environment? Ryujinx version: 1.1.5
> 
> System Specs:
> 
> OS: Fedora 35 CPU: i7-2600k GPU: 1050ti RAM: 16GB

Hmm, this happens on every game/application. My alsa advertises S32LE by default while Ryu tries to do S16LE

**Comment by B3astTech** [comment]
> > This is currently still a issue
> > ### What's the issue you encountered?
> > I did as it described and it crashed Ryujinx
> > ### How can the issue be reproduced?
> > Any Linux distro > Set your audio backend to SoundIO > Then execute Mii Editor.
> > ### End of log
> > ```
> > 00:00:02.979 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
> > 00:00:03.080 |E| HLE.OsThread.7 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
> >  ---> System.ArgumentException: This sound device does not support PcmInt16
> >    at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceDriver.OpenStream(SampleFormat requestedSampleFormat, UInt32 requestedSampleRate, UInt32 requestedChannelCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceDriver.cs:line 188
> >    at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceSession.SetupOutputStream(Single requestedVolume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceSession.cs:line 34
> >    at Ryujinx.Audio.Backends.SoundIo.SoundIoHardwareDeviceDriver.OpenDeviceSession(Direction direction, IVirtualMemoryManager memoryManager, SampleFormat sampleFormat, UInt32 sampleRate, UInt32 channelCount, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio.Backends.SoundIo\SoundIoHardwareDeviceDriver.cs:line 152
> >    at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.OpenDeviceSession(Direction direction, IVirtualMemoryManager memoryManager, SampleFormat sampleFormat, UInt32 sampleRate, UInt32 channelCount, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 99
> >    at Ryujinx.Audio.Output.AudioOutputManager.OpenAudioOut(String& outputDeviceName, AudioOutputConfiguration& outputConfiguration, AudioOutputSystem& obj, IVirtualMemoryManager memoryManager, String inputDeviceName, SampleFormat sampleFormat, AudioInputConfiguration& parameter, UInt64 appletResourceUserId, UInt32 processHandle, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Output\AudioOutputManager.cs:line 218
> >    at Ryujinx.HLE.HOS.Services.Audio.AudioOutManager.OpenAudioOut(ServiceCtx context, String& outputDeviceName, AudioOutputConfiguration& outputConfiguration, IAudioOut& obj, String inputDeviceName, AudioInputConfiguration& parameter, UInt64 appletResourceUserId, UInt32 processHandle, Single volume) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioOutManager.cs:line 27
> >    at Ryujinx.HLE.HOS.Services.Audio.AudioOutManagerServer.OpenAudioOut(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioOutManagerServer.cs:line 78
> >    --- End of inner exception stack trace ---
> >    at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
> >    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
> >    at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
> >    at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 214
> >    at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
> >    at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1182
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Log
> > [Ryujinx_1.1.5_2022-01-23_16-25-39.log](https://github.com/Ryujinx/Ryujinx/files/7921484/Ryujinx_1.1.5_2022-01-23_16-25-39.log)
> > Environment? Ryujinx version: 1.1.5
> > System Specs:
> > OS: Fedora 35 CPU: i7-2600k GPU: 1050ti RAM: 16GB
> 
> Hmm, this happens on every game/application. My alsa advertises S32LE by default while Ryu tries to do S16LE

That's intriguing 🤔

**Comment by AcK77** [comment]
It's this still occurs ?

**Comment by GamerzHell9137** [comment]
Doesn't crash for me but maybe does for them.
![image](https://user-images.githubusercontent.com/2002038/209994931-458a3319-ebf3-4c12-9c56-39c2ac2488f5.png)
