### ISSUE TITLE
Super Mario Maker 2: crash at launch

### ISSUE THREAD

**Issue by comex** [Ryujinx/Ryujinx#3006]
### What's the issue you encountered?

As soon as I try to launch Super Mario Maker 2, Ryujinx throws an exception:
```
00:00:20.028 |I| HLE.OsThread.9 ServiceNv Create: Created map 1 with size 0x00001000!
00:00:20.061 |W| HLE.OsThread.9 ServiceNv MapBufferEx: Failed to map size 0x0000000000001000!
00:00:20.081 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 1!
00:00:20.177 |E| HLE.OsThread.9 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The LinkedList node does not belong to current LinkedList.
   at System.Collections.Generic.LinkedList`1.ValidateNode(LinkedListNode`1 )
   at System.Collections.Generic.LinkedList`1.AddAfter(LinkedListNode`1 , T )
   at Ryujinx.HLE.HOS.Services.Nv.NvMemoryAllocator.DeallocateRange(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\NvMemoryAllocator.cs:line 166
   at Ryujinx.HLE.HOS.Services.Nv.NvDrvServices.NvHostAsGpu.NvHostAsGpuDeviceFile.FreeSpace(FreeSpaceArguments& arguments) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\NvDrvServices\NvHostAsGpu\NvHostAsGpuDeviceFile.cs:line 184
   at Ryujinx.HLE.HOS.Services.Nv.NvDrvServices.NvHostAsGpu.NvHostAsGpuDeviceFile.Ioctl(NvIoctl command, Span`1 arguments) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\NvDrvServices\NvHostAsGpu\NvHostAsGpuDeviceFile.cs:line 65
   at Ryujinx.HLE.HOS.Services.Nv.INvDrvServices.Ioctl(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\INvDrvServices.cs:line 265
```

I did not modify Ryujinx.

### How can the issue be reproduced?

The crash happens as soon as I launch the game.

I tried setting Memory Manager Mode to Software, disabling PPTC, and disabling Graphics Backend Multithreading, but this did not help.

Dump/install process, for the record: On my Switch, I used Goldleaf to export firmware 13.2.0, and used nxdumptool to export `SUPER MARIO MAKER 2 v0 (01009B90006DC000) (BASE).nsp` and `SUPER MARIO MAKER 2 v327680 (01009B90006DC800) (UPD).nsp`.  In Ryujinx's, I installed the firmware, added the path containing the base game to the game directories list, and used right click -> Manage Title Updates to install and select the update.

### Log file
[Ryujinx_1.0.7175_2022-01-17_14-22-20.log](https://github.com/Ryujinx/Ryujinx/files/7884965/Ryujinx_1.0.7175_2022-01-17_14-22-20.log)

### Environment?

- Ryujinx version: 1.0.7175
- Game version: 3.0.1
- System Specs:
  - OS: Debian unstable, NVIDIA proprietary driver 470.94, kernel 5.15.5-2
  - CPU: AMD Threadripper 3970X
  - GPU: RTX 2070 Super
  - RAM: ~70GB
- Applied Mods : No

### Additional context?

Launching the Mii Editor also results in a [crash](https://github.com/Ryujinx/Ryujinx/files/7884969/Ryujinx_1.0.7175_2022-01-17_14-36-45.log), but I don't know whether this is at all related.

**Comment by EmulationFanatic** [comment]
Please verify your dumps are valid, and report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
