### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by Diggles24** [Ryujinx/Ryujinx#3007]
When I try to open settings, I get this code:

00:00:10.185 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0c
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index, Int64 offset, UInt64 upperCounter)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.HOS.Services.Time.TimeZone.TimeZoneContentManager.InitializeLocationNameCache() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Time\TimeZone\TimeZoneContentManager.cs:line 93
   at Ryujinx.Ui.Windows.SettingsWindow..ctor(MainWindow parent, Builder builder, VirtualFileSystem virtualFileSystem, ContentManager contentManager) in C:\projects\ryujinx\Ryujinx\Ui\Windows\SettingsWindow.cs:line 118
   at Ryujinx.Ui.MainWindow.Settings_Pressed(Object sender, EventArgs args) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 1545
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
Marshaling state-changed signal
00:00:15.155 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0c
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index, Int64 offset, UInt64 upperCounter)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.GetCurrentFirmwareVersion() in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\Content\ContentManager.cs:line 1036
   at Ryujinx.Ui.MainWindow.FileMenu_StateChanged(Object o, StateChangedArgs args) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 1275
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by AcK77** [comment]
You need to install keys and firmware. I suggest you to reads our guides in the wiki section. Thanks.
