### ISSUE TITLE
Controller Configuration issue

### ISSUE THREAD

**Issue by liberodark** [Ryujinx/Ryujinx#3014]
### What's the issue you encountered?

I can't configure controller all buttons stay unbound.

### How can the issue be reproduced?

Try to configure controller via GUI.

### Log file
[Ryujinx_1.0.7178_2022-01-20_16-08-46.log](https://github.com/Ryujinx/Ryujinx/files/7906342/Ryujinx_1.0.7178_2022-01-20_16-08-46.log)

### Environment?

- Ryujinx version: 1.0.7178
- Game version: All
- System Specs:
  - OS: Batocera 33
  - CPU: Ryzen 9 5900HX
  - GPU: AMD Radeon 8
  - RAM: 16 GB
- Applied Mods :  No

### Additional context?

```
Marshaling pressed signal
00:02:05.416 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> GLib.GException: Unrecognized image file format
   at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
   at Gdk.PixbufLoader.LoadFromStream(Stream input)
   at Gdk.PixbufLoader.InitFromAssemblyResource(Assembly assembly, String resource)
   at Gdk.Pixbuf..ctor(Assembly assembly, String resource, Int32 width, Int32 height)
   at Ryujinx.Ui.Windows.ControllerWindow.SetControllerSpecificFields() in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 382
   at Ryujinx.Ui.Windows.ControllerWindow.SetCurrentValues() in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 347
   at Ryujinx.Ui.Windows.ControllerWindow..ctor(MainWindow mainWindow, Builder builder, PlayerIndex controllerId) in C:\projects\ryujinx\Ryujinx\Ui\Windows\ControllerWindow.cs:line 192
   at Ryujinx.Ui.Windows.SettingsWindow.ConfigureController_Pressed(Object sender, PlayerIndex playerIndex) in C:\projects\ryujinx\Ryujinx\Ui\Windows\SettingsWindow.cs:line 676
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

**Comment by liberodark** [comment]
Fixed by deps

**Comment by lzambarda** [comment]
Experiencing the same issue on Mac, resolved with `brew install librsvg`
