### ISSUE TITLE
Minecraft Story Mode deadlock

### ISSUE THREAD

**Issue by QuackingCanary** [Ryujinx/Ryujinx#3027]
### What's the issue you encountered?

Impossible to access the menu, there is an error when I try to enter the game after the menu. "Connexion" appears, then the emulator is freezing (and quit by itself)

### How can the issue be reproduced?

Just enter the game and you'll be stuck after a few seconds when the game asks to click on the button to enter the main menu

### Environment?

###Log

`00:00:29.202 |E| HLE.GuestThread.14 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:29.386 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 220
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1182
`

- Ryujinx version: 1.1.4</br>
- Game version: 1.0.0</br>

- System Specs:
  - OS:Windows 11
  - CPU: i7-1065G7
  - GPU: Intel(R) Iris(R) Plus Graphics
  - RAM: 8Go
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please post this information on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List), if it is not already there, following the standard template format. The main repo issue tracker is for larger issues affecting the emulator and proven regressions. Game compatibility information/per-game bugs belong on the game compatibility list.
