### ISSUE TITLE
Blizzard Arcade Collection: OveflowException on boot

### ISSUE THREAD

**Issue by Itamai** [Ryujinx/Ryujinx#3037]
## Bug Report

```
Unhandled exception caught: System.OverflowException: Arithmetic operation resulted in an overflow.
   at ARMeilleure.IntermediateRepresentation.Operand.AddUse(Operation operation) in D:\a\Ryujinx\Ryujinx\ARMeilleure\IntermediateRepresentation\Operand.cs:line 215
   at ARMeilleure.Translation.RegisterToLocal.Rename(ControlFlowGraph cfg) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\RegisterToLocal.cs:line 12
   at ARMeilleure.Translation.Compiler.Compile(ControlFlowGraph cfg, OperandType[] argTypes, OperandType retType, CompilerOptions options) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Compiler.cs:line 47
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 290
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 216
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 240
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1182
```

### How can the issue be reproduced?

Boot the game and then the exception should be thrown

### Log file

[Ryujinx_1.1.7_2022-01-24_18-10-45.log](https://github.com/Ryujinx/Ryujinx/files/7927530/Ryujinx_1.1.7_2022-01-24_18-10-45.log)

### Environment?

- Ryujinx version: 1.1.7</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 11
  - CPU: Ryzen 7 3700x
  - GPU: rx580
  - RAM: 16GB
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
