### ISSUE TITLE
Cannot run games from GUI, need to load games through "Load Application from File"

### ISSUE THREAD

**Issue by IndividualZenbo21** [Ryujinx/Ryujinx#3052]
### What's the issue you encountered?

I cannot run my games from the GUI, but I can run games through "Load Application from File"

### How can the issue be reproduced?

Run a game from GUI and it crashes 

### Log file

00:00:00.014 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.015 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.016 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.016 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.016 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.019 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.028 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.028 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.028 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.028 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.028 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.029 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.030 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.030 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.030 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.034 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0-ldn2.4
00:00:00.039 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.039 |N| Application Print: CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz ; 12 logical
00:00:00.039 |N| Application Print: RAM: Total 16291 MB ; Available 8789 MB
00:00:00.041 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.041 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.068 |I| Gpu : Backend Threading (Auto): True
00:00:00.422 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen)
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### Environment?

- Ryujinx version: 1.0.0-ldn2.4
- Game version: 13.2.1
- System Specs:
  - OS: Windows 10
  - CPU: i7-10750H
  - GPU: NVIDIA GTX 1660 Ti
  - RAM: 16GB
- Applied Mods : No 

### Additional context?

Additional info about your environment: been having this problem for 2 months

**Comment by AcK77** [comment]
I think you should check your game folder path. I suggest you to come on discord (https://www.discord.gg/Ryujinx) for support. Thanks.

**Comment by Cecropis** [comment]
I'm experiencing exactly the same problem. When I double click the GUI to run the game, it will crash.
I didn't find any thing wrong with the game folder path. I've moved the game between different drives the issue maintains.

00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: False
00:00:00.007 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.011 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.011 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.012 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.013 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.014 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.015 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2684
00:00:00.016 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.020 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.020 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.020 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.020 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.020 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.021 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.021 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.021 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.021 |I| Configuration LogValueChange: AudioVolume set to: 0.69
00:00:00.022 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.022 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.022 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.025 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.337
00:00:00.029 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.029 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i7-12700KF ; 20 logical
00:00:00.029 |N| Application Print: RAM: Total 65349 MB ; Available 44269 MB
00:00:00.032 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Stub
00:00:00.032 |N| Application PrintSystemInfo: Launch Mode: UserProfile

(Ryujinx:40120): Gtk-CRITICAL **: 06:15:04.685: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
00:00:00.043 |I| Gpu : Backend Threading (Auto): True
Marshaling row-activated signal
00:00:00.206 |N| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 715
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1179
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

![image](https://user-images.githubusercontent.com/30413607/199813956-2aeefd96-b87d-4122-a906-7da2a5a42889.png)

**Comment by GamerzHell9137** [comment]
> I'm experiencing exactly the same problem. When I double click the GUI to run the game, it will crash. I didn't find any thing wrong with the game folder path. I've moved the game between different drives the issue maintains.
> 
> 00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: False 00:00:00.007 |I| Configuration LogValueChange: ResScale set to: 1 00:00:00.011 |I| Configuration LogValueChange: ResScaleCustom set to: 1 00:00:00.011 |I| Configuration LogValueChange: MaxAnisotropy set to: -1 00:00:00.012 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9 00:00:00.013 |I| Configuration LogValueChange: BackendThreading set to: Auto 00:00:00.014 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan 00:00:00.015 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2684 00:00:00.016 |I| Configuration LogValueChange: EnableDockedMode set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableVsync set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableShaderCache set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableTextureRecompression set to: False 00:00:00.020 |I| Configuration LogValueChange: EnablePtc set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableInternetAccess set to: False 00:00:00.021 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True 00:00:00.021 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0 00:00:00.021 |I| Configuration LogValueChange: AudioBackend set to: OpenAl 00:00:00.021 |I| Configuration LogValueChange: AudioVolume set to: 0.69 00:00:00.022 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe 00:00:00.022 |I| Configuration LogValueChange: ExpandRam set to: False 00:00:00.022 |I| Configuration LogValueChange: IgnoreMissingServices set to: True 00:00:00.025 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.337 00:00:00.029 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64) 00:00:00.029 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i7-12700KF ; 20 logical 00:00:00.029 |N| Application Print: RAM: Total 65349 MB ; Available 44269 MB 00:00:00.032 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Stub 00:00:00.032 |N| Application PrintSystemInfo: Launch Mode: UserProfile
> 
> (Ryujinx:40120): Gtk-CRITICAL **: 06:15:04.685: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed 00:00:00.043 |I| Gpu : Backend Threading (Auto): True Marshaling row-activated signal 00:00:00.206 |N| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 715 at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1179 --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean ) at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo ) at System.Delegate.DynamicInvokeImpl(Object[] args) at System.Delegate.DynamicInvoke(Object[] args) at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args) at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
> 
> ![image](https://user-images.githubusercontent.com/30413607/199813956-2aeefd96-b87d-4122-a906-7da2a5a42889.png)

I suggest you to come on discord (https://www.discord.gg/Ryujinx) for support. Thanks.

**Comment by Zenbo21** [comment]
> I'm experiencing exactly the same problem. When I double click the GUI to run the game, it will crash. I didn't find any thing wrong with the game folder path. I've moved the game between different drives the issue maintains.
> 
> 00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: False 00:00:00.007 |I| Configuration LogValueChange: ResScale set to: 1 00:00:00.011 |I| Configuration LogValueChange: ResScaleCustom set to: 1 00:00:00.011 |I| Configuration LogValueChange: MaxAnisotropy set to: -1 00:00:00.012 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9 00:00:00.013 |I| Configuration LogValueChange: BackendThreading set to: Auto 00:00:00.014 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan 00:00:00.015 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2684 00:00:00.016 |I| Configuration LogValueChange: EnableDockedMode set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableVsync set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableShaderCache set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableTextureRecompression set to: False 00:00:00.020 |I| Configuration LogValueChange: EnablePtc set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableInternetAccess set to: False 00:00:00.021 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True 00:00:00.021 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0 00:00:00.021 |I| Configuration LogValueChange: AudioBackend set to: OpenAl 00:00:00.021 |I| Configuration LogValueChange: AudioVolume set to: 0.69 00:00:00.022 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe 00:00:00.022 |I| Configuration LogValueChange: ExpandRam set to: False 00:00:00.022 |I| Configuration LogValueChange: IgnoreMissingServices set to: True 00:00:00.025 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.337 00:00:00.029 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64) 00:00:00.029 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i7-12700KF ; 20 logical 00:00:00.029 |N| Application Print: RAM: Total 65349 MB ; Available 44269 MB 00:00:00.032 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Stub 00:00:00.032 |N| Application PrintSystemInfo: Launch Mode: UserProfile
> 
> (Ryujinx:40120): Gtk-CRITICAL **: 06:15:04.685: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed 00:00:00.043 |I| Gpu : Backend Threading (Auto): True Marshaling row-activated signal 00:00:00.206 |N| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 715 at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1179 --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean ) at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo ) at System.Delegate.DynamicInvokeImpl(Object[] args) at System.Delegate.DynamicInvoke(Object[] args) at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args) at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
> 
> ![image](https://user-images.githubusercontent.com/30413607/199813956-2aeefd96-b87d-4122-a906-7da2a5a42889.png)

My only advice is to check the health of your hard disk drive (using hard disk sentinal and others), because apparently i had that symptom because of bad sectors in the hard disk drive, not until i fixed the bad sectors , i could run the game again (note backup all of your game data to another hard disk or SSD because when you try and fix the bad sector, the data in your drive will be formated)

**Comment by Cecropis** [comment]
> > I'm experiencing exactly the same problem. When I double click the GUI to run the game, it will crash. I didn't find any thing wrong with the game folder path. I've moved the game between different drives the issue maintains.
> > 00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: False 00:00:00.007 |I| Configuration LogValueChange: ResScale set to: 1 00:00:00.011 |I| Configuration LogValueChange: ResScaleCustom set to: 1 00:00:00.011 |I| Configuration LogValueChange: MaxAnisotropy set to: -1 00:00:00.012 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9 00:00:00.013 |I| Configuration LogValueChange: BackendThreading set to: Auto 00:00:00.014 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan 00:00:00.015 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2684 00:00:00.016 |I| Configuration LogValueChange: EnableDockedMode set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableVsync set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableShaderCache set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableTextureRecompression set to: False 00:00:00.020 |I| Configuration LogValueChange: EnablePtc set to: True 00:00:00.020 |I| Configuration LogValueChange: EnableInternetAccess set to: False 00:00:00.021 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True 00:00:00.021 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0 00:00:00.021 |I| Configuration LogValueChange: AudioBackend set to: OpenAl 00:00:00.021 |I| Configuration LogValueChange: AudioVolume set to: 0.69 00:00:00.022 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe 00:00:00.022 |I| Configuration LogValueChange: ExpandRam set to: False 00:00:00.022 |I| Configuration LogValueChange: IgnoreMissingServices set to: True 00:00:00.025 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.337 00:00:00.029 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64) 00:00:00.029 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i7-12700KF ; 20 logical 00:00:00.029 |N| Application Print: RAM: Total 65349 MB ; Available 44269 MB 00:00:00.032 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Stub 00:00:00.032 |N| Application PrintSystemInfo: Launch Mode: UserProfile
> > (Ryujinx:40120): Gtk-CRITICAL **: 06:15:04.685: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed 00:00:00.043 |I| Gpu : Backend Threading (Auto): True Marshaling row-activated signal 00:00:00.206 |N| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 715 at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1179 --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean ) at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo ) at System.Delegate.DynamicInvokeImpl(Object[] args) at System.Delegate.DynamicInvoke(Object[] args) at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args) at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
> > ![image](https://user-images.githubusercontent.com/30413607/199813956-2aeefd96-b87d-4122-a906-7da2a5a42889.png)
> 
> My only advice is to check the health of your hard disk drive (using hard disk sentinal and others), because apparently i had that symptom because of bad sectors in the hard disk drive, not until i fixed the bad sectors , i could run the game again (note backup all of your game data to another hard disk or SSD because when you try and fix the bad sector, the data in your drive will be formated)

I don't think it is a hardware issue. I've ran the game on different drives the same issue happens.

**Comment by MetrosexualGarbodor** [comment]
When this happens, click the game once and press Enter instead of double-clicking. This is also not an issue on the Avalonia UI.
