### ISSUE TITLE
Issue libpng16-16.dll ryujinx latest version and older versions just dont open

### ISSUE THREAD

**Issue by NecronStars** [Ryujinx/Ryujinx#3053]
## Bug Report

My emulator straight up crashes and i tried other versions same problem always, can somebody help me?

### What's the issue you encountered?

The emulator doesn't open and say "The Procedure Entry Point Could Not Be Located inflateValidate on the in vehicle dinamic libary D:/publish/bin/lib16-16.dll"

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file

00:00:00.086 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.090 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.100 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.101 |I| Configuration LogValueChange: MaxAnisotropy set to: 4
00:00:00.103 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.108 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.109 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.110 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.110 |I| Configuration LogValueChange: EnablePtc set to: False
00:00:00.110 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.110 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.111 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.114 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.114 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.117 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.117 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.117 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.125 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.11
00:00:00.144 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.144 |N| Application Print: CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz ; 4 logical
00:00:00.146 |N| Application Print: RAM: Total 16320 MB ; Available 11952 MB
00:00:00.150 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.150 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:01:38.905 |E| Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Program.cs:line 148

**Comment by EmulationFanatic** [comment]
Try copying the contents of the bin folder into the main publish folder?

**Comment by hjc25** [comment]
Yeah, same issues with a R5 2600 and GTX 1070. v1.1.15 and v1.1.14. Trying Vulkan build now, tried moving to C drive, tried Admin rights @EmulationFanatic already tried putting the bin folder into the publish folder and it did not work.

**Comment by ricktendo** [comment]
Same
`00:00:00.029 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.033 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.033 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.034 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.034 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.035 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.035 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x73EF
00:00:00.036 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.036 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.036 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.038 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.044 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.044 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.044 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.044 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.044 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.044 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.044 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.044 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.045 |I| Configuration LogValueChange: AudioBackend set to: SoundIo
00:00:00.045 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.045 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.045 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.045 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.045 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.048 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.747
00:00:00.051 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.051 |N| Application Print: CPU: AMD Ryzen 7 5800X 8-Core Processor ; 16 logical
00:00:00.052 |N| Application Print: RAM: Total 32682 MiB ; Available 25545 MiB
00:00:00.054 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.054 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:10.534 |E| Application : Unhandled exception caught: System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 253`
