### ISSUE TITLE
Pokemon Legends Arceus Lag always with the same pokemon in the same location -> virtual memory error

### ISSUE THREAD

**Issue by Frequel** [Ryujinx/Ryujinx#3055]
### What's the issue you encountered?
In pokemon legends Arceus when i throw a pokemon to a "moving rock" it destroy the rock and appears a graveler. When starts the battle the emulator crashes. Happens with every pokemon in my team.

No changes to Ryujinx made

### How can the issue be reproduced?

Go to Coronet Highlands at Heavenward Lookout camp.
there is a rock near the temple ruins, throw a pokemon to it to destroy it.
Appears a Graveler.
As soon as start the battle the game crashes.

### Log file

00:04:08.359 |E| HLE.GuestThread.17 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:04:08.424 |E| HLE.GuestThread.17 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 220
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1182
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 220
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1182

[Ryujinx_1.1.11_2022-01-28_18-39-55.log](https://github.com/Ryujinx/Ryujinx/files/7960969/Ryujinx_1.1.11_2022-01-28_18-39-55.log)
[Ryujinx_1.1.11_2022-01-28_19-08-38.log](https://github.com/Ryujinx/Ryujinx/files/7960970/Ryujinx_1.1.11_2022-01-28_19-08-38.log)
[Ryujinx_1.1.11_2022-01-28_19-17-22.log](https://github.com/Ryujinx/Ryujinx/files/7960971/Ryujinx_1.1.11_2022-01-28_19-17-22.log)

### Environment?

- Ryujinx version: 1.1.11</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.1</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 11
  - CPU: i7-8086K
  - GPU: GTX 1080
  - RAM: 32GB
- Applied Mods : Yes, 60fps, LoD, HD irida & Adaman

### Additional context?
N/A

**Comment by Squall-Leonhart** [comment]
I don't have this problem.

**Comment by AcK77** [comment]
Since you use some mods, I suggest you to remove them and see if the issue still happen. If yes, you can post here and we will reopen the issue, or you can open a new one. Thanks.
