### ISSUE TITLE
Pokemon Arceus Crashes After Initial Talk and Character Name Selection.

### ISSUE THREAD

**Issue by Pagliacci8** [Ryujinx/Ryujinx#3075]
## Bug Report

As described in the thread name, right after finishes the final conversation the screen goes black and Ryujinx crashes.

### Log file

00:01:27.688 |I| HLE.OsThread.9 ServiceNv Create: Created map 421 with size 0x00002000!
00:01:28.059 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorUnknown".
   at Ryujinx.Graphics.Vulkan.PipelineState.CreateGraphicsPipeline(VulkanGraphicsDevice gd, Device device, ShaderCollection program, PipelineCache cache, RenderPass renderPass) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineState.cs:line 338
   at Ryujinx.Graphics.Vulkan.PipelineBase.CreatePipeline(PipelineBindPoint pbp) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1103
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1057
   at Ryujinx.Graphics.Vulkan.PipelineBase.Draw(Int32 vertexCount, Int32 instanceCount, Int32 firstVertex, Int32 firstInstance) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 234
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_41(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 145
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131

### Environment?

- Ryujinx version: 1.1.0</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *CPU
AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
4 Cores*
  - GPU: *APU
AMD Radeon(TM) RX Vega 10 Graphics
Primário/Integrado*
  - RAM: *8GB*
- Applied Mods : No

### Additional context?

I have turned off image sharpenning and tried both enabled and not enabled docked mode.

**Comment by MetrosexualGarbodor** [comment]
This error is caused by outdated AMD drivers.
[Search for your GPU drivers here ](https://www.amd.com/en/support) and download the[ optional 22.1.2 drivers](https://cdn.discordapp.com/attachments/896922540214190092/938108041813950484/unknown.png). 

And please don't open issues for support, come to the [Discord server](https://discord.gg/ryujinx) instead.
