### ISSUE TITLE
The Legend of Zelda - Breath of the Wild Constant Crashing after about 5  min or so.... Please Help!

### ISSUE THREAD

**Issue by Blastedw0lf4** [Ryujinx/Ryujinx#3092]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

[Playing Breath of Wild and than Random constant crash. ]</br>
[ just upgrading mostly ]</br>
[ N/A. ]

### How can the issue be reproduced?

[ Simply Running and playing the game ]

### Log file

00:00:00.072 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.075 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.082 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.082 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.084 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.108 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.17
00:00:00.121 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.121 |N| Application Print: CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz ; 12 logical
00:00:00.123 |N| Application Print: RAM: Total 32623 MB ; Available 27312 MB
00:00:00.125 |N| Application PrintSystemInfo: Logs Enabled: Error
00:00:00.126 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.333 |N| Application LoadApplication: Using Firmware Version: 13.2.1
00:00:02.774 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 (4.6.0 NVIDIA 496.49)
00:00:44.601 |E| HLE.OsThread.12 SurfaceFlinger DequeueBuffer: No available buffer slots
00:00:44.602 |E| HLE.OsThread.12 SurfaceFlinger OnTransact: Error returned by transaction DequeueBuffer: Busy
00:00:00.103 |N| Application LoadApplication: Using Firmware Version: 13.2.1
00:00:01.842 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 (4.6.0 NVIDIA 496.49)
00:07:35.129 |E| GPU.MainThread Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.LoadMmeInstructionRam(Int32 argument) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 181
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 215
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 389
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100

### Environment?

- Ryujinx version: 1.1.17</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.1.17</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *Windows 10*
  - CPU: *i7-9750H*
  - GPU: *NVIDIA Corporation NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 (4.6.0 NVIDIA 496.49)*
  - RAM: *32 GB*
- Applied Mods : N/A

### Additional context?
[Ryujinx_1.1.17_2022-02-06_02-12-18.log](https://github.com/Ryujinx/Ryujinx/files/8009676/Ryujinx_1.1.17_2022-02-06_02-12-18.log)

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by Blastedw0lf4** [comment]
Update:

I just updated the nvdia drivers and now receiving this error log PLEASE SEE BELOW:


00:00:00.072 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.075 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.082 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.082 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.084 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.107 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.19
00:00:00.120 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.120 |N| Application Print: CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz ; 12 logical
00:00:00.122 |N| Application Print: RAM: Total 32623 MB ; Available 27829 MB
00:00:00.124 |N| Application PrintSystemInfo: Logs Enabled: Error
00:00:00.125 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.345 |N| Application LoadApplication: Using Firmware Version: 13.2.1
00:00:03.000 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 (4.6.0 NVIDIA 511.65)
00:20:50.512 |E| GPU.MainThread Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Memory.Tracking.MultiRegionHandle.RegisterAction(UInt64 address, UInt64 size, RegionSignal action) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MultiRegionHandle.cs:line 200
   at Ryujinx.Graphics.Gpu.Memory.BufferModifiedRangeList.ReregisterRanges(Action`2 rangeAction) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferModifiedRangeList.cs:line 347
   at Ryujinx.Graphics.Gpu.Memory.Buffer.InheritModifiedRanges(Buffer from) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 317
   at Ryujinx.Graphics.Gpu.Memory.BufferCache.CreateBufferAligned(UInt64 address, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferCache.cs:line 200
   at Ryujinx.Graphics.Gpu.Memory.BufferCache.TranslateAndCreateBuffer(MemoryManager memoryManager, UInt64 gpuVa, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferCache.cs:line 94
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.SetVertexBuffer(Int32 index, UInt64 gpuVa, UInt64 size, Int32 stride, Int32 divisor) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 171
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateVertexBufferState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 899
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 129
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 264
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 389
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100


was able to play for about 20 minutes and crashed upon arriving at a new shrine, any help is appreciated thanks!

**Comment by yell0wsuit** [comment]
Why not play on Cemu instead?

**Comment by edisionnano** [comment]
> Why not play on Cemu instead?

Thanks for your very useful comment but this is a bugtracker and bugs should be resolved for Ryujinx

**Comment by yell0wsuit** [comment]
> > Why not play on Cemu instead?
> 
> Thanks for your very useful comment but this is a bugtracker and bugs should be resolved for Ryujinx

It's already reported in compat issue: https://github.com/Ryujinx/Ryujinx-Games-List/issues/86

**Comment by edisionnano** [comment]
> Update:
> 
> I just updated the nvdia drivers and now receiving this error log PLEASE SEE BELOW:
> 
> ```
> 00:00:00.072 |I| Configuration LogValueChange: BackendThreading set to: Auto
> 00:00:00.075 |I| Configuration LogValueChange: ResScale set to: 2
> 00:00:00.082 |I| Configuration LogValueChange: ResScaleCustom set to: 1
> 00:00:00.082 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
> 00:00:00.084 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
> 00:00:00.107 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.19
> 00:00:00.120 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
> 00:00:00.120 |N| Application Print: CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz ; 12 logical
> 00:00:00.122 |N| Application Print: RAM: Total 32623 MB ; Available 27829 MB
> 00:00:00.124 |N| Application PrintSystemInfo: Logs Enabled: Error
> 00:00:00.125 |N| Application PrintSystemInfo: Launch Mode: Portable
> 00:00:00.345 |N| Application LoadApplication: Using Firmware Version: 13.2.1
> 00:00:03.000 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 (4.6.0 NVIDIA 511.65)
> 00:20:50.512 |E| GPU.MainThread Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Ryujinx.Memory.Tracking.MultiRegionHandle.RegisterAction(UInt64 address, UInt64 size, RegionSignal action) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MultiRegionHandle.cs:line 200
>    at Ryujinx.Graphics.Gpu.Memory.BufferModifiedRangeList.ReregisterRanges(Action`2 rangeAction) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferModifiedRangeList.cs:line 347
>    at Ryujinx.Graphics.Gpu.Memory.Buffer.InheritModifiedRanges(Buffer from) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 317
>    at Ryujinx.Graphics.Gpu.Memory.BufferCache.CreateBufferAligned(UInt64 address, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferCache.cs:line 200
>    at Ryujinx.Graphics.Gpu.Memory.BufferCache.TranslateAndCreateBuffer(MemoryManager memoryManager, UInt64 gpuVa, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferCache.cs:line 94
>    at Ryujinx.Graphics.Gpu.Memory.BufferManager.SetVertexBuffer(Int32 index, UInt64 gpuVa, UInt64 size, Int32 stride, Int32 divisor) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 171
>    at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateVertexBufferState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 899
>    at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 129
>    at Macro(MacroJitContext , IDeviceState , Int32 )
>    at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 264
>    at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
>    at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
>    at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 389
>    at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100
> ```
> 
> was able to play for about 20 minutes and crashed upon arriving at a new shrine, any help is appreciated thanks!

Try disabling res scaling, also try all 3 different memory manager settings (software,host,host unchecked)

**Comment by yell0wsuit** [comment]
As of now the game is unstable in Ruyjinx (as reported before, also the mods are against asking for help on Github), so I doubt those solutions will work. It's best to play in Cemu if he's impatient, or wait until the emulator has been more stable by the time BOTW2 is released.

**Comment by Blastedw0lf4** [comment]
than

> commented [3 hours ago](#issuecomment-1031046339)

your the freaking man bro! did what you told me to try and no crashes with Zelda, thanks!!!!

**Comment by Blastedw0lf4** [comment]
> > Why not play on Cemu instead?
> 
> Thanks for your very useful comment but this is a bugtracker and bugs should be resolved for Ryujinx

**Comment by yell0wsuit** [comment]
@Blastedw0lf4 Next time start here instead: https://github.com/Ryujinx/Ryujinx-Games-List/issues/86
