### ISSUE TITLE
Destination array was not long enough

### ISSUE THREAD

**Issue by ht1456749** [Ryujinx/Ryujinx#3114]
Pokémon 
when join a new map

00:32:11.695 |E| GPU.MainThread Application : Unhandled exception caught: System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.SZArrayHelper.CopyTo[T](T[] , Int32 )
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.BuffersPerStage.SetBindings(ReadOnlyCollection`1 descriptors) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1118
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 129
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 264
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 389
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100
Unhandled exception. System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.SZArrayHelper.CopyTo[T](T[] , Int32 )
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.BuffersPerStage.SetBindings(ReadOnlyCollection`1 descriptors) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1118
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 129
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 264
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 389
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100

**Comment by ht1456749** [comment]
version is 1.1.26

**Comment by ht1456749** [comment]
00:00:00.070 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.073 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.082 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.083 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.085 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.115 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.26
00:00:00.132 |N| Application Print: Operating System: Microsoft Windows 10.0.14393 (X64)
00:00:00.132 |N| Application Print: CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz ; 4 logical
00:00:00.134 |N| Application Print: RAM: Total 16339 MB ; Available 13761 MB
00:00:00.138 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.138 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.442 |N| Application LoadApplication: Using Firmware Version: 12.1.0
00:00:03.255 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1050/PCIe/SSE2 (4.6.0 NVIDIA 466.47)

**Comment by ht1456749** [comment]
the game is Pokémon  sword

**Comment by AcK77** [comment]
Please could you re open an issue following the template, this is unreadable. Thanks.

**Comment by gdkchan** [comment]
This looks like a duplicate of #2882.
