### ISSUE TITLE
Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped

### ISSUE THREAD

**Issue by ht1456749** [Ryujinx/Ryujinx#3116]
Pokémon
when enter a new map

00:00:00.070 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.073 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.082 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.083 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.085 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.115 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.26
00:00:00.132 |N| Application Print: Operating System: Microsoft Windows 10.0.14393 (X64)
00:00:00.132 |N| Application Print: CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz ; 4 logical
00:00:00.134 |N| Application Print: RAM: Total 16339 MB ; Available 13761 MB
00:00:00.138 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.138 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.442 |N| Application LoadApplication: Using Firmware Version: 12.1.0
00:00:03.255 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1050/PCIe/SSE2 (4.6.0 NVIDIA 466.47)

00:18:54.173 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000FFF
   at Ryujinx.Cpu.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 134
   at Ryujinx.Cpu.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 281
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 126
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 112
   at Ryujinx.Graphics.Gpu.Shader.GpuAccessor.GetCode(UInt64 address, Int32 minimumSize) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\GpuAccessor.cs:line 108
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(ShaderConfig config, Block block, UInt64 limitAddress, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 229
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(ShaderConfig config, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 93
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options, TranslationCounts counts) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 129
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(ThreedClassState& state, GpuChannel channel, GpuAccessorState gas, ShaderAddresses addresses) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 695
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1050
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 129
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 264
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 389
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000FFF
   at Ryujinx.Cpu.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 134
   at Ryujinx.Cpu.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 281
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 126
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 112
   at Ryujinx.Graphics.Gpu.Shader.GpuAccessor.GetCode(UInt64 address, Int32 minimumSize) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\GpuAccessor.cs:line 108
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(ShaderConfig config, Block block, UInt64 limitAddress, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 229
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(ShaderConfig config, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 93
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options, TranslationCounts counts) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 129
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(ThreedClassState& state, GpuChannel channel, GpuAccessorState gas, ShaderAddresses addresses) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 695
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1050
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 129
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 264
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 389
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100

**Comment by ht1456749** [comment]
not every time,but often

**Comment by ht1456749** [comment]
the game is Pokémon  sword

**Comment by EmulationFanatic** [comment]
You could start by upgrading to a supported version of Windows 10. It may not fix it, but it's always good to saltay up to date.
Windows 10 1607 has been deprecated since April 2019.

**Comment by Ishidad** [comment]
I'm also getting similar error while trying the Tears of the Kingdom, randomly

I'm using win 11 latest update
Ryzen 5800X3D
Radeon 5700XT

`|E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0x000000160AB71100, size=0x0000000000004710
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 139
   at Ryujinx.Graphics.Gpu.Engine.Compute.ComputeClass.SendSignalingPcasB(Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Compute\ComputeClass.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 207
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__78_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 449
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass52_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108`

**Comment by RichJoman913** [comment]
Mine give me that error when I try to boot up mario cart 8 deluxe. Was there ever a fix found. I an also on the most current version of windows 11
