### ISSUE TITLE
Vulkan Mario Golf: Super Rush full emulator crash

### ISSUE THREAD

**Issue by mrj1m0thy** [Ryujinx/Ryujinx#3282]
### What's the issue you encountered?

When running the "Mario Golf: Super Rush" game and trying to play an 18 hole match on the "Bonny Greens" course using the vulkan build. Ryujinx crashes with a "ErrorOutOfDeviceMemory" error.

### How can the issue be reproduced?

1. Run "Mario Golf: Super Rush"
2. "Play Golf"
3. "Standard Golf"
4. "Button Controls"
5. "1"
6. "Stroke Play + Take Turns"
7. (everything default here)
8. Choose any characters
9. "Bonny Greens"
10. Holes: 18
(everything else default)
11. Start game
Ryujinx will crash after a while of loading

### Log file

00:01:34.261 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:50.122 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.PipelineState.CreateGraphicsPipeline(VulkanGraphicsDevice gd, Device device, ShaderCollection program, PipelineCache cache, RenderPass renderPass) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineState.cs:line 366
   at Ryujinx.Graphics.Vulkan.PipelineBase.CreatePipeline(PipelineBindPoint pbp) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1131
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1085
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 286
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_40(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 141
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131
   at System.Threading.Thread.StartCallback()

### Environment?

- Ryujinx version: 
Fresh build from https://github.com/gdkchan/Ryujinx/commit/4dc1dadbed3fb6a8860694286d39c9644564134a
also present on Vulkan version: 1.1.0+e9819d0
- Game version: v4.0.0
- System Version: 13.2.0
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 3900X
  - GPU: AMD Radeon RX 6800 XT
  - RAM: 64GB
- Applied Mods : No

### Additional context?

I'll assume "ErrorOutOfDeviceMemory" isn't a hardware limitation :)
Running the non Vulkan version of this game just gives me super flickery textures. Enough to give me a headache if I look to long haha.

**Comment by CrusadingNinja** [comment]
@mrj1m0thy Issues with the Vulkan build should be left as a reply in the Vulkan Pull Request thread [here](https://github.com/Ryujinx/Ryujinx/pull/2518), not as an individual issue.

**Comment by MutantAura** [comment]
Correct. Please do not report bugs from an open pull request on the main issue page. This is for issues present in master.

Instead perhaps add a comment to the PR itself.
