### ISSUE TITLE
Kirby and the Forgotten Land: AudioProcessor.Worker crash

### ISSUE THREAD

**Issue by ExE-Boss** [Ryujinx/Ryujinx#3292]
### What's the issue you encountered?

Ryujinx crashed with:
```log
01:39:09.042 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation& info, Span`1 wavebuffers, VoiceUpdateState& voiceState, UInt32 targetSampleRate, Int32 sampleCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\DataSourceHelper.cs:line 66
   at Ryujinx.Audio.Renderer.Dsp.Command.DataSourceVersion2Command.Process(CommandList context) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\DataSourceVersion2Command.cs:line 107
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 142
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 225
```

### How can the issue be reproduced?

Seems to occur at random (see <https://github.com/Ryujinx/Ryujinx-Games-List/issues/3866#issuecomment-1097329284>)

### Log file

[Ryujinx_1.1.106_2022-04-22_19-51-33.log.zip](https://github.com/Ryujinx/Ryujinx/files/8543647/Ryujinx_1.1.106_2022-04-22_19-51-33.log.zip)
(is 75.2 MB uncompressed due to <https://github.com/Ryujinx/Ryujinx/issues/2794> and <https://github.com/Ryujinx/Ryujinx/issues/3231>)

### Environment?

- Ryujinx version: 1.1.106
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 7 3700X 8-Core Processor
  - GPU: NVIDIA GeForce RTX 2070
  - RAM: 32 GB
- Applied Mods : No

### Additional context?

Additional info about your environment:<br/>
N/A

**Comment by benderscruffy** [comment]
Close this as now only tracking game-specific issues on the compatibility list. Thanks.
