### ISSUE TITLE
Can't start any game - System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by sgrontflix** [Ryujinx/Ryujinx#3346]
## Bug Report

After downloading the latest version of Ryujinx (1.1.129), I can't start any game (everything was working fine before the update). I believe I had version 1.1.121 before updating.

### What's the issue you encountered?

I can't start any game.

### How can the issue be reproduced?

Open any game.

### Log file

```
00:00:00.095 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.106 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.106 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.108 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.111 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.116 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.130 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.130 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.130 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.130 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.130 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.131 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.133 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.133 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.136 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.136 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.136 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.146 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.129
00:00:00.163 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.163 |N| Application Print: CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz ; 8 logical
00:00:00.165 |N| Application Print: RAM: Total 16266 MB ; Available 9874 MB
00:00:00.170 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.170 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.124 |I| Gpu : Backend Threading (Auto): True
00:00:00.652 |N| Application LoadApplication: Using Firmware Version: 13.0.0
00:00:00.653 |I| Application LoadApplication: Loading as NSP.
00:00:00.762 |I| ModLoader QueryContentsDir: Searching mods for Title 01009B90006DC000
00:00:00.766 |I| ModLoader QueryContentsDir: Searching mods for Title 01009B90006DC000
00:00:00.786 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.983 |I| Loader LoadExeFs: Loading rtld...
00:00:01.148 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:01.148 |I| Loader LoadExeFs: Loading main...
00:00:01.762 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\Slope\App\Rom\NX64\Product\code\Slope.nss
    SDK Libraries: SDK MW+Nintendo+NEX-4_6_25-appslop
                   SDK MW+Nintendo+NintendoSDK_libcurl-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+PiaClone-5_18_98
                   SDK MW+Nintendo+PiaCommon-5_18_98
                   SDK MW+Nintendo+Pia-5_18_98
                   SDK MW+Nintendo+PiaLan-5_18_98
                   SDK MW+Nintendo+PiaLocal-5_18_98
                   SDK MW+Nintendo+PiaSession-5_18_98
                   SDK MW+Nintendo+PiaSync-5_18_98
                   SDK MW+Nintendo+PiaTransport-5_18_98
                   SDK MW+Nintendo+PiaNex-5_18_98-forNEX-4_6_2
                   SDK MW+Nintendo+NEX_MM-4_6_25
                   SDK MW+Nintendo+NintendoWare_Font-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_G3d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Vfx2-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-7_3_2-Release
                   SDK MW+Nintendo+NintendoWare_Atk-7_3_2-Release
                   SDK MW+Nintendo+NEX_DS-4_6_25
                   SDK MW+Nintendo+NEX_UT-4_6_25
                   SDK MW+Nintendo+NEX_CO-4_6_25
00:00:01.764 |I| Loader LoadExeFs: Loading sdk...
00:00:01.942 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 7.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-7_3_2-Release
00:00:02.106 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:03.111 |I| Ptc Load: Loaded Translation Cache (size: 58694852 bytes, translated functions: 39497).
00:00:03.134 |I| Ptc Load: Loaded Profiling Info (size: 138365 bytes, profiled functions: 43215).
00:00:03.599 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.Memory.WindowsShared.WindowsApiException: MapViewOfFile3 returned error code 0x3E6.
   at Ryujinx.Memory.WindowsShared.PlaceholderManager.MapViewInternal(IntPtr sharedMemory, UInt64 srcOffset, IntPtr location, IntPtr size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\WindowsShared\PlaceholderManager.cs:line 94
   at Ryujinx.Memory.WindowsShared.PlaceholderManager.MapView(IntPtr sharedMemory, UInt64 srcOffset, IntPtr location, IntPtr size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\WindowsShared\PlaceholderManager.cs:line 61
   at Ryujinx.Memory.MemoryManagement.MapView(IntPtr sharedMemory, UInt64 srcOffset, IntPtr address, UInt64 size, Boolean force4KBMap) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\MemoryManagement.cs:line 81
   at Ryujinx.Memory.MemoryBlock.MapView(MemoryBlock srcBlock, UInt64 srcOffset, UInt64 dstOffset, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 148
   at Ryujinx.Cpu.MemoryManagerHostMapped.Map(UInt64 va, UInt64 pa, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 152
   at Ryujinx.HLE.HOS.Kernel.Memory.KPageTable.MapPages(UInt64 address, KPageList pageList, KMemoryPermission permission, Boolean shouldFillPages, Byte fillValue) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KPageTable.cs:line 127
   at Ryujinx.HLE.HOS.Kernel.Memory.KPageTableBase.AllocateAndMapPages(UInt64 address, UInt64 pagesCount, KMemoryPermission permission) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KPageTableBase.cs:line 567
   at Ryujinx.HLE.HOS.Kernel.Memory.KPageTableBase.MapPages(UInt64 address, UInt64 pagesCount, MemoryState state, KMemoryPermission permission) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KPageTableBase.cs:line 543
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.Initialize(ProcessCreationInfo creationInfo, ReadOnlySpan`1 capabilities, KResourceLimit resourceLimit, MemoryRegion memRegion, IProcessContextFactory contextFactory, ThreadStart customThreadStart) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 311
   at Ryujinx.HLE.HOS.ProgramLoader.LoadNsos(KernelContext context, ProcessTamperInfo& tamperInfo, MetaLoader metaData, ProgramInfo programInfo, Byte[] arguments, IExecutable[] executables) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ProgramLoader.cs:line 154
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadExeFs(IFileSystem codeFs, MetaLoader metaData) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 668
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNca(Nca mainNca, Nca patchNca, Nca controlNca) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 527
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNsp(String nspFile) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 295
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 815
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1174
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

### Environment?

- Ryujinx version: 1.1.129</br>
- Game version: 3.0.1 (Super Mario Maker 2 - but ANY game will give the same error)</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *i7-6700HQ*
  - GPU: *NVIDIA GTX 970M*
  - RAM: *16GB*
- Applied Mods: No

### Additional context?

N/A

**Comment by GamerzHell9137** [comment]
Try this 
![image](https://user-images.githubusercontent.com/2002038/168490708-873bccde-f8ad-45ef-8247-59f095c1ced5.png)

**Comment by sgrontflix** [comment]
> Try this ![image](https://user-images.githubusercontent.com/2002038/168490708-873bccde-f8ad-45ef-8247-59f095c1ced5.png)

I can't see how that would fix my issue. I am on version 1.1.129.

**Comment by emmauss** [comment]
Please come to the discord server for support.

**Comment by MetrosexualGarbodor** [comment]
Closing as this seems like an issue on the user end.
