### ISSUE TITLE
Steam Deck / Arch Linux paths to game images don't work in CLI.

### ISSUE THREAD

**Issue by OpaqueReptile** [Ryujinx/Ryujinx#3357]
### What's the issue you encountered?

Using flatpak version of Ryujinx on the Steam Deck, trying to setup shortcuts to running games from CLI.

Trying to run from terminal gives the following popup:
![image](https://user-images.githubusercontent.com/1264375/169716770-96b7b5ec-04ac-419c-bff2-74b96ddf5e54.png)

Console output:

```
(134)(deck@steamdeck switch)$ org.ryujinx.Ryujinx /run/media/mmcblk0p1/Emulation/roms/switch/KirbyandtheForgottenLand.nsp 
00:00:00.005 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.164 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.176 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.176 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.181 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.187 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.192 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.211 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.211 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.212 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.212 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.213 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.213 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.217 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.217 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.220 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.220 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.221 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.230 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.131
00:00:00.261 |N| Application Print: Operating System: Linux 5.13.0-valve14-1-neptune-02195-g5b0f749d00fa #1 SMP PREEMPT Thu, 28 Apr 2022 00:49:57 +0000 (X64)
00:00:00.261 |N| Application Print: CPU: AMD Custom APU 0405   AmdCcxVhFf3PeiInit Entry ; 8 logical
00:00:00.264 |N| Application Print: RAM: Total 14838 MB ; Available 11832 MB
00:00:00.268 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.269 |N| Application PrintSystemInfo: Launch Mode: UserProfile
Gtk-Message: 16:29:53.955: Failed to load module "canberra-gtk-module"
00:00:00.179 |I| Gpu : Backend Threading (Auto): True

** (Ryujinx:13): WARNING **: 16:29:56.715: AT-SPI: Could not obtain desktop path or name


** (Ryujinx:13): WARNING **: 16:29:56.735: atk-bridge: get_device_events_reply: unknown signature

** (Ryujinx:13): WARNING **: 16:29:56.735: atk-bridge: get_device_events_reply: unknown signature

** (Ryujinx:13): WARNING **: 16:29:56.735: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (Ryujinx:13): WARNING **: 16:29:56.908: AT-SPI: Could not obtain desktop path or name


** (Ryujinx:13): WARNING **: 16:29:56.918: AT-SPI: Could not obtain desktop path or name


** (Ryujinx:13): WARNING **: 16:29:56.918: AT-SPI: Could not obtain desktop path or name

00:00:02.655 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Horizon.Dispose(Boolean disposing) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Horizon.cs:line 465
   at Ryujinx.HLE.Switch.Dispose(Boolean disposing) in /run/build/Ryujinx/Ryujinx.HLE/Switch.cs:line 157
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in /run/build/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 764
   at Ryujinx.Program.Main(String[] args) in /run/build/Ryujinx/Ryujinx/Program.cs:line 188
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Horizon.Dispose(Boolean disposing) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Horizon.cs:line 465
   at Ryujinx.HLE.Switch.Dispose(Boolean disposing) in /run/build/Ryujinx/Ryujinx.HLE/Switch.cs:line 157
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in /run/build/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 764
   at Ryujinx.Program.Main(String[] args) in /run/build/Ryujinx/Ryujinx/Program.cs:line 188
/app/bin/ryujinx-wrapper: line 7:    13 Aborted                 (core dumped) Ryujinx $@
```

### Logs

No idea where they're getting saved with the flatpak install.
Open Logs/Open Ryujinx options in GUI don't work.

### How can the issue be reproduced?

Can be reproduced by trying to run .nsp from CLI

### Environment?

- Ryujinx version: 1.1.131
- System Specs:
  - OS: Steam OS 3 (Arch Linux)
  - CPU: AMD Zen 2
  - GPU: AMD RDNA 2
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Something else I noticed weird with the paths on the deck, trying to add a library path on my SD card resulted in a weird symlink path(?) being recorded instead. Might be related.

![image](https://user-images.githubusercontent.com/1264375/169717005-4173fabc-b410-49b5-ac95-59085f0e2b48.png)

Results in:

![image](https://user-images.githubusercontent.com/1264375/169717015-a1bb6cf0-57dd-46b4-9eb2-ff52afbd9371.png)

**Comment by TSRBerry** [comment]
This is a flatpak permission issue, you need to grant access to this directory.
