### ISSUE TITLE
Help i can't open ryujinx

### ISSUE THREAD

**Issue by shadowkill13** [Ryujinx/Ryujinx#3415]
When i open new build ryujinx ava then it instant close. Everyone who know how to fix please show me. Thanks!

00:00:00.075 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.083 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.083 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.085 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.088 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.092 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.103 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.104 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.104 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.104 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.104 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.105 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.107 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.107 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.109 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.109 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.109 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.118 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.152
00:00:00.136 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.136 |N| Application Print: CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz ; 12 logical
00:00:00.137 |N| Application Print: RAM: Total 16235 MB ; Available 7641 MB
00:00:00.140 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.141 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:06.249 |E| Application : Unhandled exception caught: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Ryujinx.Ava.Ui.Windows.MainWindow.CheckLaunchState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Ava\Ui\Windows\MainWindow.axaml.cs:line 471
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 258
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 96
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx.Ava\Program.cs:line 55

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, go to (discord)[https://discord.gg/ryujinx] and send your log in the support channel.
