### ISSUE TITLE
ACNH Crashes on 1.1.156

### ISSUE THREAD

**Issue by ForestSpeeder** [Ryujinx/Ryujinx#3417]
### What's the issue you encountered?

After running the auto-updater to 1.1.156, animal crossing new horizons no longer boots up. This can be fixed by downgrading. The error is 
```
Fatal error. 0x80131506
Repeat 2 times:
--------------------------------
   at System.Buffer.__Memmove(Byte*, Byte*, UIntPtr)
--------------------------------
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at Ryujinx.Memory.AddressSpaceManager.ReadImpl(UInt64, System.Span`1<Byte>)
   at Ryujinx.Memory.AddressSpaceManager.GetSpan(UInt64, Int32, Boolean)
   at Ryujinx.Memory.AddressSpaceManager.GetWritableRegion(UInt64, Int32, Boolean)
   at Ryujinx.HLE.HOS.Services.Time.StaticService.ITimeZoneServiceForGlue.LoadTimeZoneRule(Ryujinx.HLE.HOS.ServiceCtx)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(Ryujinx.HLE.HOS.ServiceCtx)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32, UInt64)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
```
Why does ryujinx suggest updating to "pre-release" versions anyway?

### How can the issue be reproduced?

Try to boot up ACNH on 1.1.156?

### Log file

[Ryujinx_1.1.156_2022-06-24_21-29-27.log](https://github.com/Ryujinx/Ryujinx/files/8979804/Ryujinx_1.1.156_2022-06-24_21-29-27.log)

### Environment?

- Ryujinx version: 1.1.156
- Game version: 2.0.5
- System Specs:
  - OS: Windows 10
  - CPU: i7-9700K
  - GPU: GTX 1070
  - RAM: 16Gb
- Applied Mods : No

**Comment by gdkchan** [comment]
> Why does ryujinx suggest updating to "pre-release" versions anyway?

There is no "pre-release" version because we only have rolling releases. This has the advantage of users receiving fixes as soon as possible, but also has the advantage of high chance of something else breaking because the amount of testing each change gets is generally low.

**Comment by GamerzHell9137** [comment]
> > Why does ryujinx suggest updating to "pre-release" versions anyway?
> 
> There is no "pre-release" version because we only have rolling releases. This has the advantage of users receiving fixes as soon as possible, but also has the advantage of high chance of something else breaking because the amount of testing each change gets is generally low.

I mean tbh there's only edge cases with how Ryujinx is pushing updates and when they happen most of the time its a hotfix that gets patched up really fast. Also people should still know that its an experimental emulator, like every emulator is, issues happen.
