### ISSUE TITLE
Ryujinx LDN Settings not working with the keys and fimware

### ISSUE THREAD

**Issue by UngofaCoder** [Ryujinx/Ryujinx#3443]
I have ryujinx keys but when i open settings, its like if i didnt have the keys
Error message:Marshaling state-changed signal
00:00:16.681 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0d
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.GetCurrentFirmwareVersion()
   at Ryujinx.Ui.MainWindow.FileMenu_StateChanged(Object o, StateChangedArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
Marshaling state-changed signal
00:00:19.426 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0d
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.GetCurrentFirmwareVersion()
   at Ryujinx.Ui.MainWindow.FileMenu_StateChanged(Object o, StateChangedArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
Marshaling state-changed signal
00:00:25.855 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0d
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.GetCurrentFirmwareVersion()
   at Ryujinx.Ui.MainWindow.FileMenu_StateChanged(Object o, StateChangedArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
Marshaling state-changed signal
00:03:41.802 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0d
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.GetCurrentFirmwareVersion()
   at Ryujinx.Ui.MainWindow.FileMenu_StateChanged(Object o, StateChangedArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
Marshaling activate signal
00:03:47.034 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0d
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.HOS.Services.Time.TimeZone.TimeZoneContentManager.InitializeLocationNameCache()
   at Ryujinx.Ui.Windows.SettingsWindow..ctor(MainWindow parent, Builder builder, VirtualFileSystem virtualFileSystem, ContentManager contentManager)
   at Ryujinx.Ui.MainWindow.Settings_Pressed(Object sender, EventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
Marshaling activate signal
00:03:50.270 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0d
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.HOS.Services.Time.TimeZone.TimeZoneContentManager.InitializeLocationNameCache()
   at Ryujinx.Ui.Windows.SettingsWindow..ctor(MainWindow parent, Builder builder, VirtualFileSystem virtualFileSystem, ContentManager contentManager)
   at Ryujinx.Ui.MainWindow.Settings_Pressed(Object sender, EventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
Marshaling state-changed signal
00:03:53.885 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0d
   at LibHac.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.GetCurrentFirmwareVersion()
   at Ryujinx.Ui.MainWindow.FileMenu_StateChanged(Object o, StateChangedArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by UngofaCoder** [comment]
It does not detect the keys but on normal ryujinx yes.

**Comment by MutantAura** [comment]
This is caused by outdated keys combined with FW 14.0.0+
Please use our discord for support requests not our issue tracker. https://discord.gg/ryujinx

Thank you.

**Comment by gdkchan** [comment]
I don't think this should cause the settings window to crash though. It should show an error message instead. Something to be fixed IMO.
