### ISSUE TITLE
Unable to open Ryujinx window on Linux (Avalonia UI)

### ISSUE THREAD

**Issue by SiongSng** [Ryujinx/Ryujinx#3475]
## Bug Report

Should be related to https://github.com/AvaloniaUI/Avalonia/issues/4427
If change the start command to `LANG=en_US ./Ryujinx.ava` it can start normally

### What's the issue you encountered?
Unable to open Ryujinx window on Linux.

### How can the issue be reproduced?

run `Ryujinx.ava`

### Log file

00:00:00.147 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.152 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.152 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.153 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.154 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.156 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.163 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.163 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.163 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.163 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.163 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.163 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.164 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.164 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.165 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.165 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.165 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.169 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.182
00:00:00.182 |N| Application Print: Operating System: Linux 5.15.53-1-MANJARO #1 SMP PREEMPT Thu Jul 7 16:56:55 UTC 2022 (X64)
00:00:00.182 |N| Application Print: CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz ; 12 logical
00:00:00.183 |N| Application Print: RAM: Total 23970 MB ; Available 12483 MB
00:00:00.186 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.186 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:02.017 |E| Application : Unhandled exception caught: System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl) in /_/src/Avalonia.Visuals/Media/FontManager.cs:line 33
   at Avalonia.Media.FontManager.get_Current() in /_/src/Avalonia.Visuals/Media/FontManager.cs:line 53
   at Avalonia.Media.TextFormatting.TextCharacters.TryGetRunProperties(ReadOnlySlice`1 text, Typeface typeface, Typeface defaultTypeface, Int32& count) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 129
   at Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(ReadOnlySlice`1 text, TextRunProperties defaultProperties) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 62
   at Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 40
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 280
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 15
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 223
   at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, Double maxWidth, Double maxHeight, Double lineHeight, Int32 maxLines, IReadOnlyList`1 textStyleOverrides) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 71
   at FluentAvalonia.UI.Controls.SymbolIcon.GenerateText()
   at FluentAvalonia.UI.Controls.SymbolIcon.OnPropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.OnPropertyChangedCore[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 647
   at Avalonia.Animation.Animatable.OnPropertyChangedCore[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Animation/Animatable.cs:line 169
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 756
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 672
   at Avalonia.AvaloniaObject.InheritanceParentChanged[T](StyledPropertyBase`1 property, IAvaloniaObject oldParent) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 581
   at Avalonia.StyledPropertyBase`1.RouteInheritanceParentChanged(AvaloniaObject o, IAvaloniaObject oldParent) in /_/src/Avalonia.Base/StyledPropertyBase.cs:line 237
   at Avalonia.AvaloniaObject.set_InheritanceParent(IAvaloniaObject value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 92
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent) in /_/src/Avalonia.Styling/StyledElement.cs:line 423
   at Avalonia.StyledElement.SetLogicalParent(IList children) in /_/src/Avalonia.Styling/StyledElement.cs:line 736
   at Avalonia.StyledElement.LogicalChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 503
   at Avalonia.Visual.LogicalChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Visuals/Visual.cs:line 382
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 687
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia.Controls.ContentControl.ContentChanged(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/ContentControl.cs:line 128
   at Avalonia.Controls.ContentControl.<>c.<.cctor>b__4_0(ContentControl x, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/ContentControl.cs:line 45
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass23_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 579
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 756
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 531
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 355
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 121
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 367
   at Avalonia.Controls.ContentControl.set_Content(Object value) in /_/src/Avalonia.Controls/ContentControl.cs:line 56
   at Ryujinx.Ava.Ui.Windows.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in D:\a\Ryujinx\Ryujinx\Ryujinx.Ava\Ui/Windows/MainWindow.axaml:line 577
   at Ryujinx.Ava.Ui.Windows.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
   at Ryujinx.Ava.Ui.Windows.MainWindow.InitializeComponent() in D:\a\Ryujinx\Ryujinx\Ryujinx.Ava\Ui\Windows\MainWindow.axaml.cs:line 506
   at Ryujinx.Ava.Ui.Windows.MainWindow..ctor() in D:\a\Ryujinx\Ryujinx\Ryujinx.Ava\Ui\Windows\MainWindow.axaml.cs:line 104
   at Ryujinx.Ava.App.OnFrameworkInitializationCompleted() in D:\a\Ryujinx\Ryujinx\Ryujinx.Ava\App.axaml.cs:line 30
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\Ryujinx.Ava\Program.cs:line 55

### Environment?

- Ryujinx version: 1.1.182
- System Specs:
  - OS: Manjaro Linux
  - CPU: Intel® Core™ i5-10400F CPU @ 2.90GHz
  - GPU: NVIDIA GeForce GTX 1650 SUPER
  - RAM: 23.4 GiB
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?
System language: English
System Region: Taiwan

**Comment by PadTrick** [comment]
https://github.com/Ryujinx/Ryujinx/issues/3961#issuecomment-1341613553

**Comment by MetrosexualGarbodor** [comment]
Does this still occur on the latest version?

**Comment by SiongSng** [comment]
This still occurs in the latest version (1.1.518)

```
LANG=zh_TW ./Ryujinx
```
