### ISSUE TITLE
[Feature Request] MacOS Support

### ISSUE THREAD

**Issue by oscarbg** [Ryujinx/Ryujinx#348]
Hi,
 tested a game which works perfectly on Windows and Linux on version 1.0.1332 but on MacOS Mojave beta using same version (ryujinx-1.0.1332-osx_x64) fails:

```
Unhandled Exception: Ryujinx.Graphics.Gal.ShaderException: WARNING: Output of vertex shader 'out_attr0' not read by fragment shader
ERROR: Input of fragment shader 'in_attr0' not written by vertex shader

   at Ryujinx.Graphics.Gal.OpenGL.OGLShader.CheckProgramLink(Int32 Handle) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLShader.cs:line 259
   at Ryujinx.Graphics.Gal.OpenGL.OGLShader.BindProgram() in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLShader.cs:line 180
   at Ryujinx.HLE.Gpu.Engines.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuEngine3d.cs:line 103
   at Ryujinx.HLE.Gpu.Engines.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuEngine3d.cs:line 81
   at Ryujinx.HLE.Gpu.Engines.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuFifo.cs:line 183
   at Ryujinx.HLE.Gpu.Engines.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuFifo.cs:line 150
   at Ryujinx.HLE.Gpu.Engines.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.HLE\Gpu\Engines\NvGpuFifo.cs:line 91
   at Ryujinx.GLScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 68
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Abort trap: 6
```

**Comment by mailwl** [comment]
macos has very bad support for opengl, so, i don't think emu can be run in current state (yuzu the same)

**Comment by TuxSH** [comment]
IIRC when I tried, Ryujinx works in a VMWare virtual machine (yuzu doesn't).

**Comment by oscarbg** [comment]
ok but then why ship macOS binaries confusing users that support is there?

**Comment by oscarbg** [comment]
Ok made it not clear I was running on **AMD Vega GPU**  so "Apple devices with AMD or NVidia GPUs should be fine." doesn't apply..
altough I tested on 10.14 beta will do a test on 10.13 and close issue if it's working..

**Comment by komawoyo** [comment]
[Horrible OpenGL performance on new macbook (Nvidia to Radeon)](https://community.amd.com/thread/224990)

**Comment by ReaperOfSouls1909** [comment]
ran ryujinx just fine in macos 10.14

**Comment by jamesst20** [comment]
Unsure if it really runs. I ran just fine Ryujinx with Zelda Link's Awakening on Windows 10 (bootcamp) at 23FPS average on a Radeo Pro 5500M (Macbook Pro 16 2019) which should be able to provide more power than that.. 

I though maybe the slowliness was caused by the drivers so I tested on the native drivers (Mac OS obviously) and I couldn't get the game to run. It gets stuck there

<img width="940" alt="Screen Shot 2020-05-02 at 3 07 35 PM" src="https://user-images.githubusercontent.com/490234/80873515-1e986980-8c87-11ea-8612-d4a1678f584a.png">

**Comment by B3astTech** [comment]
No.. mac os doesn't do what it should because it doesn't support opengl 4.3 and above. Windows does on certain hardware.

In short only 2d games usually work. Nothing more

**Comment by jamesst20** [comment]
@B3astTech 

Thanks for the explanation :) It's my mistake I thought it was using Vulkan behind the scene. That explains why when I tried Yuzu I was able to play Link's Awakening at 48FPS.

**Comment by iMonZ** [comment]
What’s with switching to Vulkan?
Better support for Linux and macOS would work again with MoltenVK!

**Comment by italomandara** [comment]
I believe there's still MoltenGL if you want to stick with OPENGL but unfortunately is for OpenGL ES 2.0.
So Vulkan  via MoltenVK seems the way to go. Being a web dev don't know if I could do this myself but the author of Duckstation did a quite nice port for MacOS using that framework.

**Comment by italomandara** [comment]
And again if OpenGL is still your target couldn't be possible to use Angle? https://github.com/kakashidinho/metalangle

**Comment by edisionnano** [comment]
> And again if OpenGL is still your target couldn't be possible to use Angle? https://github.com/kakashidinho/metalangle

Ryujinx uses opengl not opengl es

**Comment by darkuser89** [comment]
https://github.com/openglonmetal/MGL

**Comment by EmulationFanatic** [comment]
Builds for macOS are now available to download from the main Ryujinx website.
