### ISSUE TITLE
Xenoblade Chronicles 3 crashes steadily when running into the second loading video

### ISSUE THREAD

**Issue by zhangyunhai210** [Ryujinx/Ryujinx#3482]
## Bug Report
Xenoblade Chronicles 3 crashes steadily when running into the second loading video

### Log file
 at System.Threading.Thread.StartCallback()
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: Ryujinx.Graphics.Shader.Decoders.Block
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey , TValue , InsertionBehavior )
   at Ryujinx.Graphics.Shader.Decoders.Decoder.PropagatePushOp(Dictionary`2 blocks, Block currBlock, Int32 pushOpIndex) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 684
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(ShaderConfig config, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 147
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 118
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(ThreedClassState& state, GpuChannel channel, GpuChannelPoolState poolState, GpuChannelGraphicsState graphicsState, ShaderAddresses addresses) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 280
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1141
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 104
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__70_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 392
   at Ryujinx.Graphics.GAL.IRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\IRenderer.cs:line 48
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 390
   at System.Threading.Thread.StartCallback()

### Environment?

- Ryujinx version: 1.1.182
- Game version: 1.0.0
- System Specs:
  - OS: windows10 19042.1826
  - CPU: R5-2600
  - GPU: 1070
  - RAM: 32GB
- Applied Mods : NO
- .net6 version: 6.0.1(x64)

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for unreleased games.
