### ISSUE TITLE
Crash when opening any kind of games

### ISSUE THREAD

**Issue by innocence07** [Ryujinx/Ryujinx#3495]
## Bug Report

After update, ryujinx (1.1.194) can no longer open any game. Tried uninstalling/reinstalling. Tried cleaning my C:/ for remaining files from ryujinx, nothing works.

### What's the issue you encountered?

Crash when opening games, tried using older version of ryujinx, same issue.

### How can the issue be reproduced?

Not sure, it did this after update.

### Log file

(Ryujinx:6516): Gtk-CRITICAL **: 13:29:35.571: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
00:00:00.065 |I| Gpu : Backend Threading (Auto): True
Marshaling row-activated signal
00:00:00.336 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 708
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1174
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### Environment?

- Ryujinx version: 1.1.194</br>

- Game version: all game</br>

- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 7 5800H
  - GPU: GeForce RTX 3070
  - RAM: 16GB
- Applied Mods : [ No ]

### Additional context?

Fresh install of Ryujinx seems to have no effect

**Comment by MetrosexualGarbodor** [comment]
Click the game once then press Enter instead of double clicking.

**Comment by XordK** [comment]
Any update on this bug? I was lucky enough to find this issue but others might not.

Ryujinx was working fine with double click until today and it seems like this should be looked into instead of closed :/

**Comment by MetrosexualGarbodor** [comment]
This is not going to be looked into as none of the developers can reproduce it and the UI with this bug is getting abandoned, one of many reasons being the fact that no one wants to work with it because it's comparatively too much work to do anything.

You can use the above workaround or start using the Avalonia UI, which can be found [here](https://github.com/Ryujinx/release-channel-master/releases). Just pick the "test-ava-ryujinx" for your operating system.

**Comment by XordK** [comment]
Awesome sauce, thanks for the response 👍
