### ISSUE TITLE
Xenoblade Chronicles 3 random crashing, log file included

### ISSUE THREAD

**Issue by Citrus333** [Ryujinx/Ryujinx#3501]
### Xenoblade Chronicles 3 random crashing

Default Vulkan Ryujinx crashes at random times, GPU spikes up to 100% and then CTD.

### How can the issue be reproduced?

Play XBC3 for a few minutes to an hour.

### Log file

00:08:16.333 |E| GPU.MainThread Gpu : VK Sync Object 1298743 failed to signal within 1000ms. Continuing...
00:08:17.334 |E| GPU.MainThread Gpu : VK Sync Object 1298744 failed to signal within 1000ms. Continuing...
00:08:21.399 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.FenceHelper.WaitAllIndefinitely(Vk api, Device device, ReadOnlySpan`1 fences) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\FenceHelper.cs:line 27
   at Ryujinx.Graphics.Vulkan.FenceHolder.Wait() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\FenceHolder.cs:line 55
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.WaitAndDecrementRef(Int32 cbIndex, Boolean refreshFence) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 307
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.FreeConsumed(Boolean wait) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 189
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Rent() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 214
   at Ryujinx.Graphics.Vulkan.PipelineFull.GetPreloadCommandBuffer() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 175
   at Ryujinx.Graphics.Vulkan.BufferHolder.SetData(Int32 offset, ReadOnlySpan`1 data, Nullable`1 cbs, Action endRenderPass) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\BufferHolder.cs:line 166
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.SetBufferData(BufferHandle buffer, Int32 offset, ReadOnlySpan`1 data) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 526
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_13(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 81
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399
   at System.Threading.Thread.StartCallback()

### Environment?

- Ryujinx version: 1.1.0+5b910e8</br>
- Game version: 1.0 and 1.1</br>
- System Specs:
  - OS:  Windows 10
  - CPU: i7 9700k
  - GPU: RTX 3080
  - RAM: 32 gb
- Applied Mods : Yes and No, tested with mods and without, crashes with same error.

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for open PRs and instead comment on the PR itself.

**Comment by Citrus333** [comment]
Sorry didn't see that there was a pull request for this!
