### ISSUE TITLE
Vulkan: ErrorOutOfDeviceMemory : Games that crash with it not due to lack of VRAM

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#3523]
### What's the issue you encountered?

Some games gives ErrorOutOfDeviceMemory where lack of VRAM is not the issue (8 GB VRAM+)

### How can the issue be reproduced?

Most of the time just booting the game:

The games that do that are:

[The Touryst](https://github.com/Ryujinx/Ryujinx-Games-List/issues/2074)

[Fast RMX](https://github.com/Ryujinx/Ryujinx-Games-List/issues/97)

### Log file

[Ryujinx_1.1.201_2022-08-01_17-52-02.log](https://github.com/Ryujinx/Ryujinx/files/9235641/Ryujinx_1.1.201_2022-08-01_17-52-02.log)

### Environment?

- Ryujinx version: 1.0.201</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3600
  - GPU: Nvidia RTX 3060 Ti
  - RAM: 16 GB
- Applied Mods : No

**Comment by Squall-Leonhart** [comment]
turn your pagefile back on if you have turned it off.

**Comment by keekyslusus** [comment]
i have a same problem with Astral chain
I tried increasing the pagefile but it didn't help

**Comment by jlarmijos** [comment]
anyway

**Comment by ttaolu** [comment]
Game: fire emblem engage
RAM: 16G
Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".

**Comment by morialo3** [comment]
Same issue here, with build  1.1.625  for Linux. Previously https://github.com/Ryujinx/Ryujinx/issues/3372 was a good enough solution suggesting raise of `vm.max_map_count`  which worked for "SMT V" but not no with "Bayonetta 3" . 
Here's my current logs :-
[Ryujinx_1.1.625_2023-02-25_17-47-22.log](https://github.com/Ryujinx/Ryujinx/files/10833731/Ryujinx_1.1.625_2023-02-25_17-47-22.log)

**Comment by Sakul6499** [comment]
Getting the same error on 1.1.750+ Windows 11, (latest: 1.1.767) in every game after some time has passed.
For example:
Breath of the Wild crashes after ~30-90m
Pokémon Scarlet/Violet after ~60-90m
Animal Crossing: New Horizon after ~120m

Sometimes it also doesn't crash at all for multiple hours or right after launching the game (especially in BotW).
Could this maybe be a form of memory leaking? I.e. some buffers on the GPU not being flushed or something like it?
I remember having a similar issue on Yuzu (hope it's allowed to talk about this here) where they have an option "Use pessimistic buffer flushes (Hack)" which does fix this issue for me!
Could we get something like that in Ryujinx maybe?

**Comment by GamerzHell9137** [comment]
> Getting the same error on 1.1.750+ Windows 11, (latest: 1.1.767) in every game after some time has passed. For example: Breath of the Wild crashes after ~30-90m Pokémon Scarlet/Violet after ~60-90m Animal Crossing: New Horizon after ~120m
> 
> Sometimes it also doesn't crash at all for multiple hours or right after launching the game (especially in BotW). Could this maybe be a form of memory leaking? I.e. some buffers on the GPU not being flushed or something like it? I remember having a similar issue on Yuzu (hope it's allowed to talk about this here) where they have an option "Use pessimistic buffer flushes (Hack)" which does fix this issue for me! Could we get something like that in Ryujinx maybe?

Why dont you check the logs? Or post a log so we can tell you?

**Comment by Sakul6499** [comment]
> Why dont you check the logs? Or post a log so we can tell you if lack of VRAM is the issue?

It includes the exact same information as above is already stated, I just wanted to add some information on this issue.
My error messages all look like this:
``` 
00:02:47.643 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:48.643 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 7681 took more than 1000ms, resuming execution...
00:04:20.153 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 182
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map, Boolean isBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 58
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, Device device, TextureCreateInfo info, Single scaleFactor, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 149
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 116
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 447
Unhandled exception. Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 182
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map, Boolean isBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 58
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, Device device, TextureCreateInfo info, Single scaleFactor, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 149
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 116
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 447
```
(Same across all games I tried)

Hardware & Settings Ryujinx writes:
``` 
00:00:00.004 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.052 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.057 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.057 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.058 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.059 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.061 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.061 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x25A0
00:00:00.062 |I| Configuration LogValueChange: AntiAliasing set to: Fxaa
00:00:00.062 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.063 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.064 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.073 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.073 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.073 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.073 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.073 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.073 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.073 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.073 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.074 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.074 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.075 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.075 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.075 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.075 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.079 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.767
00:00:00.083 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.084 |N| Application Print: CPU: AMD Ryzen 7 5800H with Radeon Graphics ; 16 logical
00:00:00.084 |N| Application Print: RAM: Total 30572 MiB ; Available 21470 MiB
00:00:00.087 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.087 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.095 |I| Gpu : Backend Threading (Auto): True
00:00:00.376 |N| Application LoadApplication: Using Firmware Version: 16.0.2
``` 
(Same across all games I tried)

When looking at Task Manager it actually shows VRAM being used at 99% capacity before the crash, then after reaching 100% it crashes with the error above.

**Comment by MutantAura** [comment]
If that is the case then this is not the same issue. You are simply experiencing VRAM exhaustion. 
Not what this issue is about. If you are running on an iGPU the OS usually only allocates 2GB of RAM to act as VRAM, this is not enough in a lot of games.

**Comment by Sakul6499** [comment]
According to the settings, I am running on my dGPU though:
![image](https://user-images.githubusercontent.com/13678392/236709470-7c0860be-6a27-41f4-8b5c-93e598717074.png)
Which has 4GB of dedicated VRAM and access to almost 16GB of shared RAM (which isn't used at all).

**Comment by MutantAura** [comment]
This still does not meet the issue definition. This issue is tracking the `ErrorOutOfDeviceMemory` crash when the VRAM  is not exhausted. What you are experiencing is simply VRAM exhaustion. 

> When looking at Task Manager it actually shows VRAM being used at 99% capacity before the crash, then after reaching 100% it crashes with the error above.

VRAM use massively depends on the game in question and certain games _can_ use more than 4GB. You can try enabling texture recompression.

**Comment by Sakul6499** [comment]
> If that is the case then this is not the same issue. You are simply experiencing VRAM exhaustion. Not what this issue is about. If you are running on an iGPU the OS usually only allocates 2GB of RAM to act as VRAM, this is not enough in a lot of games.

Oh I see, my bad. The error description is very confusing then.
However still, it starts at low VRAM usage and with time keeps increasing until it's exhausted, while also not using any shared memory available.
This seems to me like some cache or buffer not being cleared for whatever reason.

Will try texture recompression, thanks!

**Comment by GamerzHell9137** [comment]
> > If that is the case then this is not the same issue. You are simply experiencing VRAM exhaustion. Not what this issue is about. If you are running on an iGPU the OS usually only allocates 2GB of RAM to act as VRAM, this is not enough in a lot of games.
> 
> Oh I see, my bad. The error description is very confusing then. However still, it starts at low VRAM usage and with time keeps increasing until it's exhausted, while also not using any shared memory available. This seems to me like some cache or buffer not being cleared for whatever reason.
> 
> Will try texture recompression, thanks!

If you played on OpenGL this issue wouldn't happen. Vulkan can't offload to RAM automatically like OpenGL can. But yeah just like Mutant said, a lot of games are using more than 4 GB VRAM. Texture recompression on Vulkan will stop your issue happening.

**Comment by Sakul6499** [comment]
> > > If that is the case then this is not the same issue. You are simply experiencing VRAM exhaustion. Not what this issue is about. If you are running on an iGPU the OS usually only allocates 2GB of RAM to act as VRAM, this is not enough in a lot of games.
> > 
> > Oh I see, my bad. The error description is very confusing then. However still, it starts at low VRAM usage and with time keeps increasing until it's exhausted, while also not using any shared memory available. This seems to me like some cache or buffer not being cleared for whatever reason.
> > 
> > Will try texture recompression, thanks!
> 
> If you played on OpenGL this issue wouldn't happen. Vulkan can't offload to RAM automatically like OpenGL can. But yeah just like Mutant said, a lot of games are using more than 4 GB VRAM. Texture recompression on Vulkan will stop your issue happening.

Texture Recompression actually doesn't help! It just adds more time until it eventually runs out of VRAM.
The amount of VRAM being used keeps increasing by the minute either way.
And yes, I know how Vulkan works, such a feature would be pretty nice though or, like said above, other emulators have an option to force more frequent and aggressive buffer flushing.

**Comment by ttaolu** [comment]
Do you all gays have perfect firmware and prod.keys , i just want play fire emblem engage , no where download发自我的荣耀手机-------- 原始邮件 --------发件人： Lukas Weber ***@***.***>日期： 2023年5月8日周一 10:41收件人： Ryujinx/Ryujinx ***@***.***>抄送： taolu ***@***.***>, Manual ***@***.***>主    题： Re: [Ryujinx/Ryujinx] Vulkan: ErrorOutOfDeviceMemory : Games that crash with it not due to lack of VRAM (Issue #3523)



If that is the case then this is not the same issue. You are simply experiencing VRAM exhaustion. Not what this issue is about. If you are running on an iGPU the OS usually only allocates 2GB of RAM to act as VRAM, this is not enough in a lot of games.

Oh I see, my bad. The error description is very confusing then. However still, it starts at low VRAM usage and with time keeps increasing until it's exhausted, while also not using any shared memory available. This seems to me like some cache or buffer not being cleared for whatever reason.
Will try texture recompression, thanks!

If you played on OpenGL this issue wouldn't happen. Vulkan can't offload to RAM automatically like OpenGL can. But yeah just like Mutant said, a lot of games are using more than 4 GB VRAM. Texture recompression on Vulkan will stop your issue happening.

Texture Recompression actually doesn't help! It just adds more time until it eventually runs out of VRAM.
The amount of VRAM being used keeps increasing by the minute either way.
And yes, I know how Vulkan works, such a feature would be pretty nice though or, like said above, other emulators have an option to force more frequent and aggressive buffer flushing.

**Comment by Squall-Leonhart** [comment]
Linux is going to soon get VK_EXT_pageable_device_local_memory (and the NV Beta driver already has it) while Windows is missing the extension, but was previously supported on the windows 470.02 driver, this may be of use to minimize the instances of ErrorOutOfDeviceMemory.

I've raised a query with one of the nvidia vulkan contributors as to if windows is getting it.

**Comment by shadowdreamer** [comment]
```
00:00:02.527 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3060 Ti (Vulkan v1.3.236, Driver v531.41.0.0)
00:00:55.764 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:56.764 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 3220 took more than 1000ms, resuming execution...
00:03:32.968 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:03:33.968 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 20889 took more than 1000ms, resuming execution...
00:06:34.461 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:14:15.663 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:14:36.480 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:15:04.659 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:36:20.708 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:36:21.708 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 252238 took more than 1000ms, resuming execution...
00:38:52.966 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:38:53.965 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 269695 took more than 1000ms, resuming execution...
00:39:14.083 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:39:14.885 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:42:39.388 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 182
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map, Boolean isBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 58
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, Device device, TextureCreateInfo info, Single scaleFactor, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 149
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 449
```

seems to be the same issue, high chance to occur when switching menus and teleporting in the main base. is any solution now?

**Comment by TathagataDM** [comment]
I'm getting random crashes to desktop on seemingly any game. I'm getting the ErrorOutOfDeviceMemory error in the logs.

I'm using a Ryzen 9 7950X and RX 7900 XTX (24GB VRAM) and have 64GB of system RAM (DDR5-6000), using EndeavourOS.

My vm.max_map_count is 2147483642, so shouldn't be the issue, I believe.

For whatever reason I can't seem to upload a log so here's the part where the crash occurs:

00:05:08.951 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.DescriptorPoolHolder..ctor(Vk api, Device device) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/DescriptorSetManager.cs:line 22
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.AllocateDescriptorSets(Vk api, ReadOnlySpan`1 layouts) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/DescriptorSetManager.cs:line 170
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.AllocateDescriptorSet(Vk api, DescriptorSetLayout layout) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/DescriptorSetManager.cs:line 162
   at Ryujinx.Graphics.Vulkan.PipelineLayoutCacheEntry.GetNewDescriptorSetCollection(VulkanRenderer gd, Int32 commandBufferIndex, Int32 setIndex, Boolean& isNew) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/PipelineLayoutCacheEntry.cs:line 55
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/PipelineBase.cs:line 1610
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/PipelineBase.cs:line 464
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 113
   at Ryujinx.Ui.RendererWidgetBase.Render() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx/Ui/RendererWidgetBase.cs:line 448
   at System.Threading.Thread.StartCallback()

**Comment by bit0bit** [comment]
I'm not sure if it helps or not. I had Vulkan issue with my AMD win laptop with Nvidia GPU. Tried many thing as suggested by internet, but a YouTube tutorial solved my issue. Link : https://youtu.be/fCSStZCM6a8[https://youtu.be/fCSStZCM6a8](https://youtu.be/fCSStZCM6a8)

**Comment by antoniodesousa** [comment]
The game still crashes after starting a race on the latest release as of today 1.1.1141
[Ryujinx_1.1.1141_2024-01-28_17-40-53.log](https://github.com/Ryujinx/Ryujinx/files/14076909/Ryujinx_1.1.1141_2024-01-28_17-40-53.log)

**Comment by TempleOS-Enjoyer** [comment]
^Confirmed here as well, with 1.1.1239.

**Comment by GamerzHell9137** [comment]
Think this is more of a per game issue than a widespread issue, also its not a regression so im closing it.

**Comment by putimir** [comment]
I laso had the game crashing on race start. I managed to run the game by assigning 8G of memory to the iGPU (Radeon 780m on Ryzen 7840HS)
