### ISSUE TITLE
Mario Kart 8 Deluxe Wave 2 DLC Fails to Boot

### ISSUE THREAD

**Issue by remutro** [Ryujinx/Ryujinx#3546]
## Bug Report

Update 2.1.0 with 2 new cups/ 8 tracks fails to boot in Ryujinx

### What's the issue you encountered?

Mario Kart 8 Deluxe 2.1.0 update fails to boot

### How can the issue be reproduced?

Add update 2.1.0 in title management. 

### Log file

00:00:18.128 |E| HLE.GuestThread.24 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000001614ba0 (opcode 0xf3140c6e) is undefined!

at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1105

at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104

at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\State\ExecutionContext.cs:line 135

at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 61

at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168

at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32

at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40

at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265

### Environment?

Ryujinx 1.1.198
Windows 11
i7-9700k
32 MBs RAM
Nvidia 2070 Super
Samsung 970 Pro NVMe

### Additional context?

This game played great with update 2.0.0 & associated Booster Pack DLC which introduced the first 2 new cups / 8 tracks.

**Comment by jonker130** [comment]
https://github.com/Ryujinx/Ryujinx/pull/3544
here is the fix
