### ISSUE TITLE
i expected it to heavily lag but not crash

### ISSUE THREAD

**Issue by Sonic1paRadise** [Ryujinx/Ryujinx#3551]
## Bug Report

```
[00:00:01.084 |I| Configuration LogValueChange: ResScale set to: 1
00:00:01.102 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:01.103 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:01.105 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:01.108 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:01.111 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:01.114 |I| Configuration LogValueChange: PreferredGpu set to: 0x10005_0x0
00:00:01.120 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:01.154 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:01.155 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:01.156 |I| Configuration LogValueChange: EnableTextureRecompression set to: True
00:00:01.156 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:01.157 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:01.158 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:01.159 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:01.163 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:01.164 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:01.167 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:01.167 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:01.168 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:01.179 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.207
00:00:01.228 |N| Application Print: Operating System: Linux 5.10.101-amd64-desktop #20.00.05.06-release SMP Mon Mar 14 09:34:55 CST 2022 (X64)
00:00:01.228 |N| Application Print: CPU: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz ; 4 logical
00:00:01.232 |N| Application Print: RAM: Total 3783 MB ; Available 1311 MB
00:00:01.240 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:01.242 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:16.177 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:16.177 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:18.006 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:18.168 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.222 |I| Gpu : Backend Threading (Auto): True
00:00:00.617 |N| Application LoadApplication: Using Firmware Version: 14.1.2
00:00:00.617 |I| Application LoadApplication: Loading as Firmware Title (NCA).
00:00:00.694 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100000000001009
00:00:00.695 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100000000001009
00:00:00.721 |I| Loader LoadExeFs: Loading rtld...
00:00:00.940 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.940 |I| Loader LoadExeFs: Loading main...
00:00:01.097 |I| Loader PrintRoSectionInfo: main:
    Module: Q:\teamcity\buildagent\work\c9408b4e00393217\output\build\nx64\final_jp\src\.exe\miieditn.nss
    FS SDK Version: 10.7.1
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Atk-10_7_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-10_7_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-10_7_1-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-10_7_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d-10_7_1-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-10_7_1-Release
                   SDK MW+Nintendo+NintendoSDK_libz-10_7_1-Release
00:00:01.098 |I| Loader LoadExeFs: Loading sdk...
00:00:01.098 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdkEmpty
00:00:01.309 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.122 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:02.126 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:02.137 |I| Loader LoadNsos: Loading image 2 at 0x0000000008c23000...
00:00:02.227 |I| ModLoader LoadCheats: Build ids found for title 0100000000001009:
    C1ED34FD7D1962277A4555D9EC7146571218ED5D000000000000000000000000
    A03A22EB7E714A215B583BA0B992F9DA00000000000000000000000000000000
    40393B8A4E6444CE78506B176A94F6919ED673D3000000000000000000000000
00:00:02.227 |I| Loader LoadNca: Application Loaded:  v [0100000000001009] [64-bit]
00:00:02.272 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:02.614 |E| Application : Unhandled exception caught: SPB.Graphics.Exceptions.ContextException: CreateContext() failed.
   at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\GLRenderer.cs:line 49
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\GLRenderer.cs:line 36
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

### What's the issue you encountered?

Tried on i3-2120 in linux(for better gfx support)
(sorry)

### Environment?

- Ryujinx version: 1.1.207</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: ???(mii make applet from 14.1.2)</br>
[ Replace X's with the game version at time of crash. ]

**Comment by TheASVigilante** [comment]
Looks like it failed to initalize OpenGL. Are you sure you set your install up properly?

**Comment by MetrosexualGarbodor** [comment]
Please head to [discord](https://discord.gg/ryujinx) for help, GitHub is for global emulator issues.
