### ISSUE TITLE
Ryujinx LDN2.4 crashes when loading Animal Crossing: New Horizons

### ISSUE THREAD

**Issue by Hedwig7s** [Ryujinx/Ryujinx#3588]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

Animal Crossing: New Horizons crashes immediately on startup

### How can the issue be reproduced?

Just loading the game crashed it for me

### Log file

```00:00:18.533 |E| HLE.OsThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IAccountServiceForApplication: 160

Guest Stack Trace:
Process: Service, PID: 93

Raw Request Data:
00000000   01 00 18 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  A0 00 00 00 00 00 00 00   SFCI···· ·······
00000020   00 00 00 00 00 00 00 00  FA 00 00 00               ········ú···    

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Environment?

- Ryujinx version: 1.0.0-ldn2.4</br>
- Game version: 2.0.2</br>
- System Specs:
  - OS: Windows 11
  - CPU: i3-10100F
  - GPU: NVIDIA GTX 1050TI
  - RAM: 16GB
- Applied Mods : None

### Additional context?

Additional info about your environment:</br>
A google search brought me to issue [#1472](https://github.com/Ryujinx/Ryujinx/issues/1472) 
I'm using a PS3 controller if that is relevant
The issue is NOT reproducible in Ryujinx 1.1.215 or yuzu

**Comment by MetrosexualGarbodor** [comment]
Enable ignore missing services in system settings, and please ask for help in Discord, not here.

**Comment by Hedwig7s** [comment]
> Enable ignore missing services in system settings, and please ask for help in Discord, not here.

Still a bug

**Comment by MutantAura** [comment]
A bug that has been fixed and will be resolved when LDN is rebased.
Locking this thread.
