### ISSUE TITLE
Regression: World of Goo no longer boots

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#3654]
### What's the issue you encountered?

[World of Goo](https://github.com/Ryujinx/Ryujinx-Games-List/issues/255) now crashes on boot.

### How can the issue be reproduced?

Attempt to launch World of Goo in any memory manager mode or GPU backend.

### Log file

Crash on host-mapped
```
GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000FF8
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 143
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 321
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 193
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 114
   at Ryujinx.Graphics.Gpu.Shader.GpuAccessor.GetCode(UInt64 address, Int32 minimumSize) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\GpuAccessor.cs:line 74
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(ShaderConfig config, Block block, UInt64 limitAddress, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 229
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(ShaderConfig config, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 93
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 117
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(ThreedClassState& state, ProgramPipelineState& pipeline, GpuChannel channel, GpuChannelPoolState poolState, GpuChannelGraphicsState graphicsState, ShaderAddresses addresses) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 339
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1203
   at Ryujinx.Graphics.Gpu.Engine.Threed.ThreedClass.UpdateState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\ThreedClass.cs:line 122
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 129
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 argument) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 91
   at Ryujinx.Graphics.Gpu.Engine.Threed.ThreedClass.DrawEnd(Int32 argument) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\ThreedClass.cs:line 348
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.MME.MacroJit.Execute(ReadOnlySpan`1 code, IDeviceState state, Int32 arg0) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\MME\MacroJit.cs:line 36
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__73_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 401
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 99
   at System.Threading.Thread.StartCallback()
```

Crash on software-mapped
```
GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000FF8
   at Ryujinx.Cpu.Jit.MemoryManager.AssertValidAddressAndSize(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\MemoryManager.cs:line 504
   at Ryujinx.Cpu.Jit.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\MemoryManager.cs:line 435
   at Ryujinx.Cpu.Jit.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\MemoryManager.cs:line 236
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 193
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 114
   at Ryujinx.Graphics.Gpu.Shader.GpuAccessor.GetCode(UInt64 address, Int32 minimumSize) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\GpuAccessor.cs:line 74
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(ShaderConfig config, Block block, UInt64 limitAddress, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 229
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(ShaderConfig config, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 93
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 117
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(ThreedClassState& state, ProgramPipelineState& pipeline, GpuChannel channel, GpuChannelPoolState poolState, GpuChannelGraphicsState graphicsState, ShaderAddresses addresses) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 339
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1203
   at Ryujinx.Graphics.Gpu.Engine.Threed.ThreedClass.UpdateState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\ThreedClass.cs:line 122
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 129
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 argument) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 91
   at Ryujinx.Graphics.Gpu.Engine.Threed.ThreedClass.DrawEnd(Int32 argument) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\ThreedClass.cs:line 348
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.MME.MacroJit.Execute(ReadOnlySpan`1 code, IDeviceState state, Int32 arg0) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\MME\MacroJit.cs:line 36
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__73_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 401
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 99
   at System.Threading.Thread.StartCallback()
```

### Environment?

- Ryujinx version: 1.1.244
- Game version: 0.0.1
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 11
  - CPU: Ryzen 7 5800X
  - GPU: NVIDIA RTX 3080 Ti
  - RAM: 32GB
- Applied Mods : No

### Additional context?

It is not known exactly when this game regressed.

**Comment by benderscruffy** [comment]
goes ingame for me
![Ryujinx 1 1 243 - World of Goo v0 0 1 (010009E001D90000) (32-bit) 1_09_2022 12_28_03 PM](https://user-images.githubusercontent.com/2696404/187831649-c7905c0f-d339-40ae-baad-f06ef61d0ecc.png)
could be im on AMD while you are on Nvidia ??

**Comment by Ryan2603** [comment]
[Ryujinx_1.1.309_2022-10-19_00-00-39.log](https://github.com/Ryujinx/Ryujinx/files/9812475/Ryujinx_1.1.309_2022-10-19_00-00-39.log)

same crashed here, 

**What's the issue you encountered?**
https://github.com/Ryujinx/Ryujinx-Games-List/issues/255 now crashes on boot.

**How can the issue be reproduced?**
Attempt to launch World of Goo in any mode or GPU backend.

**Environment?**
Ryujinx version: 1.1.309
Game version: 0.0.2

**System Specs:**
OS: Windows 11
CPU: Ryzen 7 3600X
GPU: NVIDIA RTX 3060 Ti
Driver: NVIDIA GeForce 522.25 WHQL
RAM: 64GB
Applied Mods : No
