### ISSUE TITLE
Diablo 3 hangs in the character selection menu if Guest Internet access is enabled

### ISSUE THREAD

**Issue by Labaman** [Ryujinx/Ryujinx#3664]
### What's the issue you encountered?

Diablo 3 hangs in the character selection menu if Guest Internet access is enabled

```
00:00:36.882 |W| HLE.OsThread.5 ServiceBsd SetSocketOption: Unsupported SetSockOpt Option: SoNoSigpipe Level: Socket
00:00:37.237 |S| HLE.OsThread.16 ServiceSsl CreateContext: Stubbed. {sslVersion: Auto}
00:00:37.241 |S| HLE.OsThread.16 ServiceSsl SetOption: Stubbed. {option: DoNotCloseSocket ; value: True}
00:00:37.245 |I| HLE.OsThread.16 ServiceSsl SetHostName: crimson-switch-auth3.prod.demonware.net
00:00:37.246 |S| HLE.OsThread.16 ServiceSsl SetOption: Stubbed. {option: SkipDefaultVerify ; value: False}
00:00:37.247 |S| HLE.OsThread.16 ServiceSsl SetVerifyOption: Stubbed. {_verifyOption: PeerCa, HostName}
00:00:37.247 |S| HLE.OsThread.16 ServiceSsl SetSessionCacheMode: Stubbed. {sessionCacheMode: SessionId}
00:00:37.249 |S| HLE.OsThread.16 ServiceSsl SetIoMode: Stubbed. {_ioMode: NonBlocking}
00:00:37.570 |E| HLE.OsThread.16 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle , ReadOnlySpan`1 , Byte[]& , Int32& )
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials , SafeDeleteSslContext& , ReadOnlySpan`1 , Byte[]& , SslAuthenticationOptions )
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean )
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions )
   at System.Net.Security.SslStream.AuthenticateAsClient(String , X509CertificateCollection , SslProtocols , Boolean )
   at Ryujinx.HLE.HOS.Services.Ssl.SslService.SslManagedSocketConnection.Handshake(String hostName) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/Ssl/SslService/SslManagedSocketConnection.cs:line 92
   at Ryujinx.HLE.HOS.Services.Ssl.SslService.ISslConnection.DoHandshake(ServiceCtx context) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslConnection.cs:line 192
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 218
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 137
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /run/build/Ryujinx/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1261
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle , ReadOnlySpan`1 , Byte[]& , Int32& )
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials , SafeDeleteSslContext& , ReadOnlySpan`1 , Byte[]& , SslAuthenticationOptions )
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean )
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions )
   at System.Net.Security.SslStream.AuthenticateAsClient(String , X509CertificateCollection , SslProtocols , Boolean )
   at Ryujinx.HLE.HOS.Services.Ssl.SslService.SslManagedSocketConnection.Handshake(String hostName) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/Ssl/SslService/SslManagedSocketConnection.cs:line 92
   at Ryujinx.HLE.HOS.Services.Ssl.SslService.ISslConnection.DoHandshake(ServiceCtx context) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslConnection.cs:line 192
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 218
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 137
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in /run/build/Ryujinx/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /run/build/Ryujinx/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1261
```

### How can the issue be reproduced?

Run Diablo 3 with Guest Internet access enabled.

### Log file
[Logs_D3.zip](https://github.com/Ryujinx/Ryujinx/files/9476787/Logs_D3.zip)

### Environment?

- Ryujinx version: 1.1.248</br>
- Game version: 2.7.4.84040
- System Specs:
  - OS: Arch Linux
  - CPU: i7-10750H
  - GPU: NVIDIA RTX 2070 Super
  - RAM: 32 Gb
- Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!
