### ISSUE TITLE
Crash when starting Xenoblade Chronicles Definitive Edition

### ISSUE THREAD

**Issue by BLucky-gh** [Ryujinx/Ryujinx#3709]
## Bug Report

Xenoblade Chronicles Definitive Edition. Vulkan crashes, OpenGL works fine
## What's the issue you encountered?

Xenoblade Chronicles Definitive Edition crashes ryujinx entirely (and if i don't go out of fullscreen, sometimes either kills KDE too or leaves it in an unusable state forcing me to reboot my steam deck) when running on Vulkan. It works fine on OpenGL, but I prefer using Vulkan to get better performance at least in other games, but since there doesn't seem to be any per-game settings option, I'm stuck switching APIs before launching the game
## How can the issue be reproduced?

Start game, Crash
This seems similar to #3530 but this is a different game so I decided to open a new bug report.

## Error segment
```
(deck@steamdeck launchers)$ ./ryujinx.sh 
00:00:00.005 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.108 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.116 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.116 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.118 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x10
00:00:00.119 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.121 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.122 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x163F
00:00:00.125 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.137 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.137 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.137 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.137 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.137 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.138 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.138 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.140 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.140 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.142 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.143 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.143 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.148 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.272
00:00:00.167 |N| Application Print: Operating System: Linux 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 #1 SMP PREEMPT Mon, 08 Aug 2022 22:27:56 +0000 (X64)
00:00:00.167 |N| Application Print: CPU: AMD Custom APU 0405   AmdCcxVhFf3PeiInit Entry ; 8 logical
00:00:00.169 |N| Application Print: RAM: Total 14836 MB ; Available 12052 MB
00:00:00.173 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.174 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.245 |I| Gpu : Backend Threading (Auto): True
00:00:00.643 |N| Application LoadApplication: Using Firmware Version: 14.1.2
00:00:00.643 |I| Application LoadApplication: Loading as NSP.
00:00:00.801 |I| ModLoader QueryContentsDir: Searching mods for Title 0100FF500E34A000
00:00:00.802 |I| ModLoader QueryContentsDir: Searching mods for Title 0100FF500E34A000
00:00:00.823 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.847 |I| Loader LoadExeFs: Loading rtld...
00:00:01.029 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:01.029 |I| Loader LoadExeFs: Loading main...
00:00:01.363 |I| Loader PrintRoSectionInfo: main:
    Module: D:\monolithsoft\xxsw\prog\application\bfsw\NX64\ROM_Master\bfsw.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-9_3_1-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-9_3_1-Release
00:00:01.363 |I| Loader LoadExeFs: Loading subsdk0...
00:00:01.435 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-9_3_1-Release
00:00:01.436 |I| Loader LoadExeFs: Loading sdk...
00:00:01.596 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 9.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-9_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-9_3_1-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-9_3_1-Release
00:00:01.706 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.947 |I| Ptc Load: Loaded Translation Cache (size: 15163057 bytes, translated functions: 12403).
00:00:01.961 |I| Ptc Load: Loaded Profiling Info (size: 40694 bytes, profiled functions: 12408).
00:00:02.295 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:02.298 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:02.310 |I| Loader LoadNsos: Loading image 2 at 0x0000000009b6f000...
00:00:02.314 |I| Loader LoadNsos: Loading image 3 at 0x000000000a27c000...
00:00:02.340 |I| ModLoader LoadCheats: Build ids found for title 0100FF500E34A000:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    92C78BB3DCBBC3F7A3CAF601D7B85F7A36C20907000000000000000000000000
    5A7ADA8DD7447C10AA244944F64D0AFF17C50539000000000000000000000000
    AD3FDFBD62A5F4B082D385FFE420D4400ABB831D000000000000000000000000
00:00:02.340 |I| Loader LoadNca: Application Loaded: Xenoblade Chronicles: Definitive Edition v1.1.2 [0100ff500e34a000] [64-bit]
00:00:02.359 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:02.393 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:02.816 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD RADV VANGOGH (Vulkan v1.3.211, Driver v22.1.99)
00:00:02.855 |I| GPU.MainThread Gpu LoadShaders: Loading 118 shaders from the cache...
00:00:03.801 |I| GPU.MainThread Gpu LoadShaders: Rebuilding 118 shaders...
00:00:04.582 |I| GPU.MainThread Gpu LoadShaders: Rebuilt 118 shaders successfully.
00:00:04.582 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:04.845 |I| HLE.GuestThread.15 Ptc LoadTranslations: 12403 translated functions loaded
00:00:04.862 |I| HLE.GuestThread.15 Ptc MakeAndSaveTranslations: 0 of 5 functions translated | Thread count: 7
00:00:05.090 |I| HLE.GuestThread.15 Ptc MakeAndSaveTranslations: 5 of 5 functions translated | Thread count: 7 in 0.2267904 s
00:00:05.309 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:05.337 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:05.338 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:05.339 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:05.356 |S| HLE.OsThread.16 ServicePctl Initialize: Stubbed. 
00:00:05.822 |I| Ptc Save: Saved Translation Cache (size: 15144510 bytes, translated functions: 12408).
00:00:06.696 |S| HLE.OsThread.16 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72338313338724352}
00:00:06.710 |S| HLE.OsThread.16 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:06.718 |W| HLE.GuestThread.15 KernelSvc : MapSharedMemory() = InvalidMemRange
00:00:06.725 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:06.730 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:06.757 |S| HLE.OsThread.16 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:06.758 |S| HLE.OsThread.16 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:06.759 |S| HLE.OsThread.16 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:06.759 |S| HLE.OsThread.16 ServiceAm LockExit: Stubbed. 
00:00:06.791 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:06.804 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:06.842 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:06.901 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:06.993 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:06.995 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:06.997 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:06.997 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:06.999 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:07.000 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:07.000 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:07.004 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:07.125 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.125 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.125 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.125 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.125 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.126 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.126 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.126 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.126 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.126 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.126 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.126 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.325 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:07.342 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:07.343 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 92 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:07.349 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 4 Players: Player1,Player2,Player3,Handheld
00:00:07.780 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:07.786 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:07.919 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:09.052 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:09.119 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:00:11.061 |E| Gpu : VK Sync Object 15 failed to signal within 1000ms. Continuing...
radv/amdgpu: The CS has been cancelled because the context is lost.
00:00:22.304 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 247
   at Ryujinx.Graphics.Vulkan.CommandBufferScoped.Dispose() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferScoped.cs:line 42
   at Ryujinx.Graphics.Vulkan.PersistentFlushBuffer.GetTextureData(CommandBufferPool cbp, TextureView view, Int32 size, Int32 layer, Int32 level) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PersistentFlushBuffer.cs:line 78
   at Ryujinx.Graphics.Vulkan.TextureView.GetData(CommandBufferPool cbp, PersistentFlushBuffer flushBuffer, Int32 layer, Int32 level) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\TextureView.cs:line 872
   at Ryujinx.Graphics.Vulkan.TextureView.GetData(Int32 layer, Int32 level) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\TextureView.cs:line 849
   at Ryujinx.Graphics.GAL.Multithreading.Resources.ThreadedTexture.GetData(Int32 layer, Int32 level) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\Resources\ThreadedTexture.cs:line 106
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataSliceFromGpu(Span`1 output, Int32 layer, Int32 level, Boolean blacklist, ITexture texture) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 1091
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.FlushTextureDataSliceToGuest(Boolean tracked, Int32 sliceIndex, ITexture texture) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 418
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.<>c__DisplayClass66_0.<FlushAction>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 1409
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.BackgroundContextAction(Action action, Boolean alwaysBackground) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 579
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.BackgroundContextAction(Action action, Boolean alwaysBackground) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 248
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.FlushAction(TextureGroupHandle handle, UInt64 address, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 1407
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.<>c__DisplayClass44_0.<RegisterAction>b__0(UInt64 address, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 575
   at Ryujinx.Memory.Tracking.RegionHandle.Signal(UInt64 address, UInt64 size, Boolean write, IList`1& handleIterable) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\RegionHandle.cs:line 170
   at Ryujinx.Memory.Tracking.VirtualRegion.Signal(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\VirtualRegion.cs:line 28
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 239
Unhandled exception. Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 247
   at Ryujinx.Graphics.Vulkan.CommandBufferScoped.Dispose() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferScoped.cs:line 42
   at Ryujinx.Graphics.Vulkan.PersistentFlushBuffer.GetTextureData(CommandBufferPool cbp, TextureView view, Int32 size, Int32 layer, Int32 level) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PersistentFlushBuffer.cs:line 78
   at Ryujinx.Graphics.Vulkan.TextureView.GetData(CommandBufferPool cbp, PersistentFlushBuffer flushBuffer, Int32 layer, Int32 level) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\TextureView.cs:line 872
   at Ryujinx.Graphics.Vulkan.TextureView.GetData(Int32 layer, Int32 level) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\TextureView.cs:line 849
   at Ryujinx.Graphics.GAL.Multithreading.Resources.ThreadedTexture.GetData(Int32 layer, Int32 level) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\Resources\ThreadedTexture.cs:line 106
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataSliceFromGpu(Span`1 output, Int32 layer, Int32 level, Boolean blacklist, ITexture texture) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 1091
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.FlushTextureDataSliceToGuest(Boolean tracked, Int32 sliceIndex, ITexture texture) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 418
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.<>c__DisplayClass66_0.<FlushAction>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 1409
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.BackgroundContextAction(Action action, Boolean alwaysBackground) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 579
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.BackgroundContextAction(Action action, Boolean alwaysBackground) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 248
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.FlushAction(TextureGroupHandle handle, UInt64 address, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 1407
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.<>c__DisplayClass44_0.<RegisterAction>b__0(UInt64 address, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 575
   at Ryujinx.Memory.Tracking.RegionHandle.Signal(UInt64 address, UInt64 size, Boolean write, IList`1& handleIterable) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\RegionHandle.cs:line 170
   at Ryujinx.Memory.Tracking.VirtualRegion.Signal(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\VirtualRegion.cs:line 28
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 239
./ryujinx.sh: line 24: 104432 Aborted                 (core dumped) /home/deck/Applications/publish/Ryujinx

```
[Core dump here](https://gofile.io/d/KARZnG) 
## Environment?

    Ryujinx version: 1.1.272 (installed via emudeck)
    Game version: happens both on Xenoblade C. DE 1.0.0 and 1.1.2
    System Specs:
        OS: Linux (SteamOS)
        CPU: AMD Custom APU (Steam Deck)
        GPU: AMD Custom APU (Steam Deck)
        RAM: 16GB shared
    Applied Mods : none

**Comment by edisionnano** [comment]
What does ryujinx.sh do?

**Comment by BLucky-gh** [comment]
Oh right I didin't even notice I used the script, force of habit.
ryujinx.sh is a script provided by emudeck that falls back to the flatpak version of ryujinx if it wasn't installed via emudeck or smth
the comment says appimage because they try to use appimages where possible, in the case of ryujinx they just copy the executable and a couple more files that are needed (as far as I understood) in a folder in ~

here's the contents:

```sh
#!/bin/sh
emuName="Ryujinx" #parameterize me
emufolder="$HOME/Applications/publish" # has to be applications for ES-DE to find it

#find full path to emu executable
exe=$(find $emufolder -iname "${emuName}" | sort -n | cut -d' ' -f 2- | tail -n 1 2>/dev/null)

#if appimage doesn't exist fall back to flatpak.
if [[ $exe == '' ]]; then
    #flatpak
    flatpakApp=$(flatpak list --app --columns=application | grep $emuName)
    exe="/usr/bin/flatpak run "$flatpakApp
else
#make sure that file is executable
    chmod +x $exe
fi
#run the executable with the params.
#Fix first '
param="${@}"
substituteWith='"'
param=${param/\'/"$substituteWith"}
#Fix last ' on command
param=$(echo "$param" | sed 's/.$/"/')
eval "${exe} ${param}"
```

**Comment by F1ReB4LL** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/686 - I have a similar crash with a similar message on Away: Journey to the Unexpected with Vulkan (no problems with OpenGL).

**Comment by EmulationFanatic** [comment]
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!

**Comment by BLucky-gh** [comment]
> Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!

Well, #3530 was reported here so I figured I'd do the same
