### ISSUE TITLE
Intel UHD 630 Graphic Problem

### ISSUE THREAD

**Issue by win3200** [Ryujinx/Ryujinx#3737]
Ryujinx v1.1.282 version was no problem.
but After Update Ryujinx v1.1.289 or Windows 11 Build 25211.1001, It's occured problem

00:00:01.178 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player2
00:00:01.251 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Initialization failed, none of the available GPUs meets the minimum requirements.
   at Ryujinx.Graphics.Vulkan.VulkanInitialization.FindSuitablePhysicalDevice(Vk api, Instance instance, SurfaceKHR surface, String preferredGpuId) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanInitialization.cs:line 225
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.SetupContext(GraphicsDebugLevel logLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 250
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.Initialize(GraphicsDebugLevel logLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 495
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.Initialize(GraphicsDebugLevel logLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 352
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 396
   at System.Threading.Thread.StartCallback()

it is playing game, Exit.....
I don't know if it's because of Ryujinx or because of Windows

**Comment by MetrosexualGarbodor** [comment]
Download the newest Intel graphics drivers from Intel's website and install them.
