### ISSUE TITLE
Bayonetta 3 - Hidden Book chapter not working

### ISSUE THREAD

**Issue by tedios** [Ryujinx/Ryujinx#3811]
What's the issue you encountered?

It seems Ryujinx is struggling to load/correct XCI/NCA, as the chapter seems to be like a mini XCI/re-load I think

How can the issue be reproduced?
Try loading the hidden/chapter book

Environment?
Ryujinx version: 1.1.335
Game version: 1.1.0 
Cheats/Mods: All disabled

System Specs:
OS: Windows 10 Pro
Version: 21H2
CPU: AMD Ryzen 9 5900X (12) @ 3.7GHz
Memory: 32 GB
GPU: Nvidia RTX 3080 12GB

Ryujinx Settings:
System section
Vsync: ON
PPTC: Enabled
FS Integrity Checks: Enabled
Audio Backend: SDL2
Memory Manager Mode: Host (fast)
Expand DRAM Size to 6GB
Ignore Missing services

Graphics section
Graphics Backend Multithreading: Auto
Graphics Backend: Vulkan
Shader Cache: Enabled
Resolution Scale: Native

Before load 
![bayo1](https://user-images.githubusercontent.com/98846561/198886822-2bd9532c-dd2f-4842-897e-9b14f6686bc8.png)

After load
![bayo2](https://user-images.githubusercontent.com/98846561/198886836-478631ed-87bb-46cf-b445-868ae5344a2e.png)

Log snap
![bayo3](https://user-images.githubusercontent.com/98846561/198886847-7e040e7a-80a8-4dcc-94a5-8acc35dd4664.png)

Attaching log as well
[Ryujinx_1.1.335_2022-10-30_17-17-32.log](https://github.com/Ryujinx/Ryujinx/files/9896162/Ryujinx_1.1.335_2022-10-30_17-17-32.log)

**Comment by OldManKain** [comment]
This is not an emulator related issue, please join us in discord for support.
https://discord.gg/ryujinx

**Comment by tedios** [comment]
Joined, anyone specific you want me to pm/reach ?

**Comment by OldManKain** [comment]
Head to the support channel.

**Comment by MetrosexualGarbodor** [comment]
Turns out this **is** an emulator issue: the book chapter seems to be coded as a different game, but Ryujinx can't open it.

`00:01:38.770 |W| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:01:38.782 |W| GUI.WindowThread ServiceNv Close: Closing channel
00:01:38.802 |I| HLE.OsThread.7 AudioRenderer ReleaseSessionId: Unregistered output (0)
00:00:00.003 |I| Gpu : Backend Threading (Auto): True
00:00:00.131 |N| Application LoadApplication: Using Firmware Version: 14.1.2
00:00:00.131 |I| Application LoadApplication: Loading as XCI.
00:00:00.131 |E| Loader LoadXci: Unable to load XCI: Could not find Main NCA`

It just stays like this after trying to access it.
![image](https://user-images.githubusercontent.com/79612681/198899979-d3fe44bb-c3d5-4525-a7f8-3c2f47222865.png)

**Comment by xlj44400** [comment]
00:00:00.001 |I| Gpu : Backend Threading (On): True
00:00:00.088 |N| Application LoadApplication: Using Firmware Version: 15.0.0
00:00:00.088 |I| Application LoadApplication: Loading as NSP.
00:00:00.096 |E| Application : Unhandled exception caught: LibHac.Common.HorizonResultException: ResultFsPathNotFound (2002-0001)
   at LibHac.Common.ThrowHelper.ThrowResult(Result result)
   at LibHac.FsSystem.PartitionFileSystem.DoOpenFile(UniqueRef`1& outFile, Path& path, OpenMode mode)
   at LibHac.Fs.Fsa.IFileSystem.OpenFile(UniqueRef`1& file, U8Span path, OpenMode mode)
   at Ryujinx.HLE.HOS.ApplicationLoader.ReadNpdm(IFileSystem fs) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 528
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadExeFs(IFileSystem codeFs, MetaLoader metaData, Boolean isHomebrew) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 594
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNsp(String nspFile) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 292
   at Ryujinx.HLE.Switch.LoadNsp(String nspFile) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Switch.cs:line 95
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 822
   at Ryujinx.Ui.MainWindow.HandleRelaunch() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1513
   at Ryujinx.Ui.MainWindow.SwitchToGameTable() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 957
   at Ryujinx.Ui.MainWindow.<CreateGameWindow>b__93_0(Object <p0>, EventArgs <p1>) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 984
   at Gtk.Application.InvokeCB.Invoke()
   at GLib.Timeout.TimeoutProxy.Handler()
00:00:05.235 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: 'K:\switch_game\news\ARMS.xci' Error: System.IO.IOException: 数据错误(循环冗余检查)。 : 'K:\switch_game\news\ARMS.xci'
   at System.IO.RandomAccess.ReadAtOffset(SafeFileHandle , Span`1 , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 )
   at System.IO.Strategies.OSFileStreamStrategy.Read(Byte[] , Int32 , Int32 )
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 , ArraySegment`1 )
   at System.IO.Strategies.BufferedFileStreamStrategy.Read(Span`1 )
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 )
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.Fs.XciHeader.DetermineXciSubStorages(IStorage& keyAreaStorage, IStorage& bodyStorage, IStorage baseStorage)
   at LibHac.Tools.Fs.XciHeader..ctor(KeySet keySet, Stream stream)
   at LibHac.Tools.Fs.Xci..ctor(KeySet keySet, IStorage storage)
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 128
00:00:11.024 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: 'K:\switch_game\news\[UPD] ARMS [01009B500007C800][v1048576].nsp' Error: System.IO.IOException: 数据错误(循环冗余检查)。 : 'K:\switch_game\news\[UPD] ARMS [01009B500007C800][v1048576].nsp'
   at System.IO.RandomAccess.ReadAtOffset(SafeFileHandle , Span`1 , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 )
   at System.IO.Strategies.OSFileStreamStrategy.Read(Byte[] , Int32 , Int32 )
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 , ArraySegment`1 )
   at System.IO.Strategies.BufferedFileStreamStrategy.Read(Span`1 )
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.FsSystem.PartitionFile.DoRead(Int64& bytesRead, Int64 offset, Span`1 destination, ReadOption& option)
   at LibHac.Fs.Fsa.IFile.Read(Int64& bytesRead, Int64 offset, Span`1 destination, ReadOption& option)
   at LibHac.Fs.FileStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.NcaUtils.NcaHeader.DecryptHeader(KeySet keySet, IStorage storage)
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 228

yes this is 100% crash

**Comment by Snake69208** [comment]
It doen't work for me too,exact like yours,i don't know the prroblem is from emulator or xci/nsp rom.
