### ISSUE TITLE
|E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.  ---> LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.

### ISSUE THREAD

**Issue by Rafaps12** [Ryujinx/Ryujinx#3855]
00:02:41.361 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0e
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel, Boolean leaveCompressed)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.ContentManager.GetCurrentFirmwareVersion() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\FileSystem\ContentManager.cs:line 1035
   at Ryujinx.Ui.MainWindow.FileMenu_StateChanged(Object o, StateChangedArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1283
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by MutantAura** [comment]
Redump your prod keys. This is also a support query, join the discord for further assistance.
