### ISSUE TITLE
Regression: Super Smash Bros Ultimate adventure mode crashing since 1.1.361

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [Ryujinx/Ryujinx#3871]
To reproduce, open the game and go to Spirits > Adventure mode. The game will crash before showing the save files.

```
00:00:36.888 |E| HLE.OsThread.10 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Gpu.GpuChannel.MemoryUnmappedHandler(Object sender, UnmapEventArgs e) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\GpuChannel.cs:line 82
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Map(UInt64 pa, UInt64 va, UInt64 size, PteKind kind) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 389
   at Ryujinx.HLE.HOS.Services.Nv.NvDrvServices.NvHostAsGpu.NvHostAsGpuDeviceFile.MapBufferEx(MapBufferExArguments& arguments) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Nv\NvDrvServices\NvHostAsGpu\NvHostAsGpuDeviceFile.cs:line 323
   at Ryujinx.HLE.HOS.Services.Nv.NvDrvServices.NvHostAsGpu.NvHostAsGpuDeviceFile.Ioctl(NvIoctl command, Span`1 arguments) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Nv\NvDrvServices\NvHostAsGpu\NvHostAsGpuDeviceFile.cs:line 52
   at Ryujinx.HLE.HOS.Services.Nv.INvDrvServices.Ioctl(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Nv\INvDrvServices.cs:line 250
   at InvokeStub_INvDrvServices.Ioctl(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 320
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
   at System.Threading.Thread.StartCallback()
```

[Ryujinx_1.1.361_2022-11-20_00-50-54.log](https://github.com/Ryujinx/Ryujinx/files/10048211/Ryujinx_1.1.361_2022-11-20_00-50-54.log)

1.1.359 works:

![image](https://user-images.githubusercontent.com/79612681/202877732-f231389b-38ce-4a66-99f0-646869063b79.png)

![image](https://user-images.githubusercontent.com/79612681/202877778-d2967f57-5a58-4873-9f7f-ef2277a0346d.png)

**Comment by MarkLanders777** [comment]
I can confirm the issue, it doesnt load the save file in WOL using last version of master
