### ISSUE TITLE
I can't see the options menu

### ISSUE THREAD

**Issue by akaelover** [Ryujinx/Ryujinx#3879]
`00:00:08.556 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.Windows.SettingsWindow..ctor(MainWindow parent, Builder builder, VirtualFileSystem virtualFileSystem, ContentManager contentManager) in /tmp/portage/games-emulation/ryujinx-1.1.368/work/Ryujinx-bd412afb9fdf859643e26d2668874e3dc9cd41df/Ryujinx/Ui/Windows/SettingsWindow.cs:line 203
   at Ryujinx.Ui.MainWindow.Settings_Pressed(Object sender, EventArgs args) in /tmp/portage/games-emulation/ryujinx-1.1.368/work/Ryujinx-bd412afb9fdf859643e26d2668874e3dc9cd41df/Ryujinx/Ui/MainWindow.cs:line 1545
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
`
It is compiled with this ebuild in Gentoo https://github.com/Tatsh/tatsh-overlay/blob/master/games-emulation/ryujinx/ryujinx-1.1.366.ebuild

The version is 1.1.368

**Comment by AcK77** [comment]
Could you please send a full log file ?

**Comment by akaelover** [comment]
Yes, I have been absent for covid

Log /usr/bin/Logs/Ryujinx_1.1.368_2022-11-21_08-34-43.log

00:00:00.121 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.124 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.132 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.132 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.134 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.139 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.151 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.151 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.151 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.151 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.152 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.152 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.154 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.154 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.156 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.157 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.157 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.164 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.368
00:00:00.187 |N| Application Print: Operating System: Linux 6.0.8-gentoo #1 SMP PREEMPT_DYNAMIC Sat Nov 12 08:27:19 CET 2022 (X64)
00:00:00.187 |N| Application Print: CPU: AMD Ryzen 7 2700X Eight-Core Processor ; 16 logical
00:00:00.189 |N| Application Print: RAM: Total 15890 MB ; Available 13758 MB
00:00:00.192 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.192 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:08.556 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.Windows.SettingsWindow..ctor(MainWindow parent, Builder builder, VirtualFileSystem virtualFileSystem, ContentManager contentManager) in /tmp/portage/games-emulation/ryujinx-1.1.368/work/Ryujinx-bd412afb9fdf859643e26d2668874e3dc9cd41df/Ryujinx/Ui/Windows/SettingsWindow.cs:line 203
   at Ryujinx.Ui.MainWindow.Settings_Pressed(Object sender, EventArgs args) in /tmp/portage/games-emulation/ryujinx-1.1.368/work/Ryujinx-bd412afb9fdf859643e26d2668874e3dc9cd41df/Ryujinx/Ui/MainWindow.cs:line 1545
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by AcK77** [comment]
Seems to be something wrong with your configuration file, I suggest you to come on our Discord for support. You have to know we don't support custom builds too.
Thanks
