### ISSUE TITLE
Regression: scanning an amiibo on Windows for a playable character crashes Super Smash Bros Ultimate

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [Ryujinx/Ryujinx#3895]
Scanning any playable character Amiibo crashes on their taunt animation. 
Occurs in latest master, 1.1.3, LDN 2.5, 3.0.1, but not on LDN 2.4, so the regression must have been somewhere **between 1.0.7093 and 1.1.3**.
Amiibo that give other bonuses work fine. Linux works fine.

https://user-images.githubusercontent.com/79612681/203854630-b228ca76-9e4c-49a5-b147-596e64401682.mp4

```
00:01:20.940 |E| HLE.GuestThread.14 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000004000.
00:01:21.005 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 220
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1182
```

Works on LDN 2.4
![image](https://user-images.githubusercontent.com/79612681/203857356-38df5164-4bb8-441c-bf3e-b39ff8b998d1.png)

[Ryujinx_1.1.3_2022-11-24_19-12-45.log](https://github.com/Ryujinx/Ryujinx/files/10086990/Ryujinx_1.1.3_2022-11-24_19-12-45.log)
[Ryujinx_1.1.384_2022-11-24_19-52-38.log](https://github.com/Ryujinx/Ryujinx/files/10087049/Ryujinx_1.1.384_2022-11-24_19-52-38.log)

**Comment by german77** [comment]
1.1.384 seems to work just fine 
![image](https://user-images.githubusercontent.com/5944268/203872356-2ab81ebe-15a1-4e4a-a4f5-d9bd0f031e7b.png)

**Comment by Neo210** [comment]
I am using 1.1.897 and loading an amiibo in smash bros loads like this. Select amiibo, select character color. it loads the screen and then the game freezes with the same error as above, I believe. 

"00:01:10.925 |E| HLE.GuestThread.21 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000004000.
00:01:10.968 |E| HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
"
I tried downloading 1.1.384 as above but it did not work for me. 
Win 10
RAMM: 64 Gb

**Comment by german77** [comment]
Crashes in this place are very likely due invalid mii data
