### ISSUE TITLE
homebrew app store crash before loading the store list

### ISSUE THREAD

**Issue by CrazyDani** [Ryujinx/Ryujinx#3918]
## Missing Service Call

Hey, my problem is that I want to use the homebrew app store, but when I try to start it it just starts loading and then the emulator crashes (guest internet access is already enabled and i am using the ldn version 

00:00:11.133 |E| HLE.OsThread.17 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.Types.AddrInfoSerialized.Read(ReadOnlySpan`1 buffer, ReadOnlySpan`1& rest) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Sockets\Sfdnsres\Types\AddrInfoSerialized.cs:line 55
   at Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver.DeserializeAddrInfos(IVirtualMemoryManager memory, UInt64 address, UInt64 size) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Sockets\Sfdnsres\IResolver.cs:line 575
   at Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver.GetAddrInfoRequestImpl(ServiceCtx context, UInt64 responseBufferPosition, UInt64 responseBufferSize, Boolean withOptions, UInt64 optionsBufferPosition, UInt64 optionsBufferSize) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Sockets\Sfdnsres\IResolver.cs:line 499
   at Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver.GetAddrInfoRequest(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Sockets\Sfdnsres\IResolver.cs:line 159
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 320
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261

**Comment by gdkchan** [comment]
You should include the crash log and exception message.
