### ISSUE TITLE
[macOS: GPU] R4G4B4A4 texture format not supported on macOS

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx#3951]
### What's the issue you encountered?

When attempting to load a R4G4B4A4 on the macOS build, Ryujinx will crash with a ErrorFormatNotSupported error.
I noticed the error in Super Kirby Clash, but there should be similar issues in Vroom in the night sky, Ni no Kuni 1, and Ys 8.
```
00:03:11.769 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorFormatNotSupported".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 248
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/PipelineFull.cs:line 204
   at Ryujinx.Graphics.GAL.Multithreading.Commands.SetRenderTargetsCommand.Run(SetRenderTargetsCommand& command, ThreadedRenderer threaded, IRenderer renderer) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.GAL/Multithreading/Commands/SetRenderTargetsCommand.cs:line 21
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_74(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 209
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 107
   at Ryujinx.Ava.AppHost.RenderLoop() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Ava/AppHost.cs:line 860
   at System.Threading.Thread.StartCallback()
```

### How can the issue be reproduced?

**Super Kirby Clash**:

- Press up on the mission board
- Select any mission
- Select your character
- "Change role"

Attempting to recreate any screenshots from this PR will also likely have the same effect: https://github.com/Ryujinx/Ryujinx/pull/3696

### Log file

[R4G4B4A4.log](https://github.com/Ryujinx/Ryujinx/files/10116935/R4G4B4A4.log)

### Environment?

- Ryujinx version: 1.1.0-macos1
- Game version: 1.0.1
- System Specs:
  - OS: macOS Monterey (12.6)
  - CPU: Intel Core i7-10700K
  - GPU: AMD Radeon Pro 5700 XT 16 GB
  - RAM: 32 GiB
- Applied Mods : No

### Additional context?

Ryujinx is not stable on the machine I tested on, but this is likely an issue regardless of Mac hardware.

**Comment by riperiperi** [comment]
Note that it is supported, just not on x86/Rosetta.
