### ISSUE TITLE
Game: DragonQuestBuilders need Service

### ISSUE THREAD

**Issue by MichalSy** [Ryujinx/Ryujinx#399]
Game loads 4 minutes maps and crashes with the following message:
System.NotImplementedException: fsp-srv IFileSystemProxy: 202

Full Stacktrace:
```
Unhandled Exception: System.NotImplementedException: fsp-srv IFileSystemProxy: 202
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in \switch\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, AMemory Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in \switch\Ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 43
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.SendSyncRequest(AThreadState ThreadState, Int64 CmdPtr, Int64 Size, Int32 Handle) in C:\Games\switch\Ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 242
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.SvcSendSyncRequest(AThreadState ThreadState) in \switch\Ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 216
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.SvcCall(Object sender, AInstExceptionEventArgs e) in \switch\Ryujinx\Ryujinx.HLE\HOS\Kernel\SvcHandler.cs:line 97
   at ChocolArm64.State.AThreadState.OnSvcCall(Int64 Position, Int32 Imm) in \switch\Ryujinx\ChocolArm64\State\AThreadState.cs:line 112
   at _ZN2nn3svc7aarch644lp6415SendSyncRequestENS0_6HandleE(AThreadState , AMemory )
   at ChocolArm64.ATranslatedSub.Execute(AThreadState ThreadState, AMemory Memory) in \switch\Ryujinx\ChocolArm64\ATranslatedSub.cs:line 119
   at ChocolArm64.ATranslator.ExecuteSubroutineA64(AThreadState State, AMemory Memory, Int64 Position) in \switch\Ryujinx\ChocolArm64\ATranslator.cs:line 91
   at ChocolArm64.ATranslator.ExecuteSubroutine(AThread Thread, Int64 Position) in \switch\Ryujinx\ChocolArm64\ATranslator.cs:line 52
   at ChocolArm64.AThread.<Execute>b__16_0() in \switch\Ryujinx\ChocolArm64\AThread.cs:line 45
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by jduncanator** [comment]
http://switchbrew.org/index.php/Filesystem_services#OpenDataStorageByDataId

**Comment by AcK77** [comment]
Closed in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/59
