### ISSUE TITLE
Regression: Nier Automata crashes after loading a save file since 1.1.419

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [Ryujinx/Ryujinx#4076]
### What's the issue you encountered?

Nier Automata crashes on Vulkan and hangs on OpenGL after loading a save file since 1.1.419/#4004.

```
00:00:28.056 |E| HLE.GuestThread.15 Gpu : VK Sync Object 34468 failed to signal within 1000ms. Continuing...
00:00:29.057 |E| HLE.GuestThread.15 Gpu : VK Sync Object 34469 failed to signal within 1000ms. Continuing...
00:00:30.057 |E| HLE.GuestThread.15 Gpu : VK Sync Object 34470 failed to signal within 1000ms. Continuing...
00:00:31.058 |E| HLE.GuestThread.15 Gpu : VK Sync Object 34468 failed to signal within 1000ms. Continuing...
00:00:31.059 |S| HLE.OsThread.9 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075 ; isAtRest: True}
00:00:31.059 |S| HLE.OsThread.9 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075 ; isAtRest: True}
00:00:31.268 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:31.594 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\Window.cs:line 339
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_31(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 122
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 401
   at System.Threading.Thread.StartCallback()
```

![image](https://user-images.githubusercontent.com/79612681/206646245-1f35134e-f932-4354-92ed-e58b06541415.png)

### How can the issue be reproduced?

Start a new save file and load it. The game will crash before the first cutscene begins.

Game works on both backends on 1.1.418:
![image](https://user-images.githubusercontent.com/79612681/206646913-dd3d8a89-aba7-4d10-981a-edec8962edb2.png)
![image](https://user-images.githubusercontent.com/79612681/206646934-26caa403-220d-41c4-a322-bff9d4dc0bcb.png)

### Log file
[Ryujinx_1.1.418_2022-12-09_06-54-19.log](https://github.com/Ryujinx/Ryujinx/files/10192521/Ryujinx_1.1.418_2022-12-09_06-54-19.log)
[Ryujinx_1.1.419_2022-12-09_06-56-07.log](https://github.com/Ryujinx/Ryujinx/files/10192522/Ryujinx_1.1.419_2022-12-09_06-56-07.log)

### Environment?

- Ryujinx version: 1.1.418, 1.1.419
- Game version: 1.0.2
- System Specs:
  - OS: Windows 10
  - CPU: i7-10700
  - GPU: NVIDIA RTX 3070
  - RAM: 32GiB
- Applied Mods : No

**Comment by noah1468** [comment]
I confirmed that it runs normally in the old version. Download and run the version below 400
