### ISSUE TITLE
Software keyboard font exception error.

### ISSUE THREAD

**Issue by akindo83** [Ryujinx/Ryujinx#4103]
### What's the issue you encountered?

Game does not boot.

Terminated with font exception error.

### How can the issue be reproduced?

Just run games. Maybe games using software keyboard?

Some games boot ok. (maybe not using software keyboard?)
- Bayonetta 3 ver 1.0

Some games boot ok when it's version 1.0. But if I install update 1.5.1, then not boot with same exception error.
- Monster hunter double cross.

### Log file

00:00:09.086 |E| HLE.OsThread.17 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: None of these fonts were found in the system: 맑은 고딕, Liberation Sans, FreeSans, DejaVu Sans!
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRendererBase.CreateFonts(String uiThemeFontFamily) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardRendererBase.cs:line 138
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRendererBase..ctor(IHostUiTheme uiTheme) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardRendererBase.cs:line 108
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRenderer..ctor(IHostUiTheme uiTheme) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardRenderer.cs:line 26
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboardApplet.Start(AppletSession normalSession, AppletSession interactiveSession) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardApplet.cs:line 105
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor.Start(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 86
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 320
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261

### Environment?

- Ryujinx version: 1.1.0 - ldn 3.0.1 
- Game version: 
- System Specs:
  - OS: Windows 11
  - CPU: Intel 12700f
  - GPU: NVIDIA RTX 3070
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Tested on korean OS. Sorry for my poor english.

**Comment by MetrosexualGarbodor** [comment]
This should be fixed in 1.1.1221. Can you please update Ryujinx and test?
