### ISSUE TITLE
Ryujinx LDN can't open settings

### ISSUE THREAD

**Issue by cario00** [Ryujinx/Ryujinx#4127]
i've installed ryujinx correctly but i can't open the setting, the program send me this problem:
00:00:26.897 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.Windows.SettingsWindow..ctor(MainWindow parent, Builder builder, VirtualFileSystem virtualFileSystem, ContentManager contentManager) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx\Ui\Windows\SettingsWindow.cs:line 360
   at Ryujinx.Ui.Windows.SettingsWindow..ctor(MainWindow parent, VirtualFileSystem virtualFileSystem, ContentManager contentManager) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx\Ui\Windows\SettingsWindow.cs:line 124
   at Ryujinx.Ui.MainWindow.Settings_Pressed(Object sender, EventArgs args) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx\Ui\MainWindow.cs:line 1640
   at InvokeStub_EventHandler.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

How can i fix this problem?
Thanks

**Comment by EmulationFanatic** [comment]
Judging by the small part of the log you've uploaded, you need to update your GPU drivers. Come to Discord for support.
