### ISSUE TITLE
Crash to desktop when upscaling Pokemon Violet/Scarlet using Vulkan on AMD in Windows.

### ISSUE THREAD

**Issue by DebugDotLog** [Ryujinx/Ryujinx#4150]
### What's the issue you encountered?

Pokemon S/V has played well since launch on my system. However, upscaling the game beyond "Native (720p/1080p)" results in both versions of the game crashing to desktop (right before rendering). The console displays an error message (pasted below). The logs do not.

Switching back to native resolution, the game plays fine.
I tested Chocobo's Mystery Dungeon EVERY BUDDY! upscaled, no issues launching the game.

No changes have been made to my Ryujinx install.
I've tried executing the application normally and as an administrator.

### Log file

[Ryujinx_1.1.481_2022-12-19_13-51-52.log](https://github.com/Ryujinx/Ryujinx/files/10261970/Ryujinx_1.1.481_2022-12-19_13-51-52.log)

### Environment?

- Ryujinx version: 1.1.481

- Game version: Scarlet 1.0.0 & Violet 1.0.0/1.1.0

- System Specs:
  - OS: Windows 10 Pro 22H2
  - CPU: R5 3600
  - GPU: AMD Radeon 6750 XT 12GB
  - RAM: 32GB
- Applied Mods : No

### Additional context?

edit: Same crash/console output on Ryujinx version 1.1.0-ldn3.0.1

If any further testing is needed, I'm happy to help.

I quickly copied the console output before it crashed:
```
00:00:06.034 |D| HLE.OsThread.10 ServiceNv PrintResult: SubmitGpfifoEx returned result Success
00:00:06.118 |D| GPU.MainThread Gpu SetScale: Rescaling 1024x1024 R8Uint to (1 to 2).
00:00:06.119 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1024x1024 to 2048x2048
00:00:06.124 |D| GPU.MainThread Gpu SetScale: Rescaling 1024x1024 D32Float to (1 to 2).
00:00:06.124 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1024x1024 to 2048x2048
00:00:06.131 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 R11G11B10Float to (1 to 2).
00:00:06.131 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.136 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 D24UnormS8Uint to (1 to 2).
00:00:06.136 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.142 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 R8G8B8A8Srgb to (1 to 2).
00:00:06.142 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.148 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 R8G8B8A8Unorm to (1 to 2).
00:00:06.148 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.153 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 R8G8B8A8Unorm to (1 to 2).
00:00:06.153 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.158 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 R11G11B10Float to (1 to 2).
00:00:06.162 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.168 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 D24UnormS8Uint to (1 to 2).
00:00:06.168 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.170 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R16Float to (1 to 2).
00:00:06.170 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.171 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 D24UnormS8Uint to (1 to 2).
00:00:06.171 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.191 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R8G8B8A8Unorm to (1 to 2).
00:00:06.191 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.192 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R8G8B8A8Unorm to (1 to 2).
00:00:06.192 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.193 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R8G8B8A8Unorm to (1 to 2).
00:00:06.193 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.194 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R11G11B10Float to (1 to 2).
00:00:06.194 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.198 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R16G16B16A16Float to (1 to 2).
00:00:06.198 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.201 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R16G16B16A16Float to (1 to 2).
00:00:06.201 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.202 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R8Unorm to (1 to 2).
00:00:06.202 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.207 |D| GPU.MainThread Gpu SetScale: Rescaling 1024x1024 D32Float to (1 to 2).
00:00:06.207 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1024x1024 to 2048x2048
00:00:06.211 |D| GPU.MainThread Gpu SetScale: Rescaling 1024x1024 R8Uint to (1 to 2).
00:00:06.211 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1024x1024 to 2048x2048
00:00:06.212 |D| HLE.OsThread.10 ServiceNv PrintResult: EventRegister returned result Success
00:00:06.215 |D| HLE.OsThread.10 ServiceNv PrintResult: EventWaitAsync returned result TryAgain
00:00:06.221 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R11G11B10Float to (1 to 2).
00:00:06.221 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.225 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 D24UnormS8Uint to (1 to 2).
00:00:06.225 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.225 |D| GPU.MainThread Gpu SetScale: Rescaling 960x540 R16G16B16A16Float to (1 to 2).
00:00:06.225 |D| GPU.MainThread Gpu SetScale:   Copy performed: 960x540 to 1920x1080
00:00:06.235 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 R8G8B8A8Srgb to (1 to 2).
00:00:06.235 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.240 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 R8G8B8A8Unorm to (1 to 2).
00:00:06.240 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.244 |D| HLE.OsThread.10 ServiceNv PrintResult: SubmitGpfifoEx returned result Success
00:00:06.248 |D| HLE.OsThread.10 ServiceNv PrintResult: EventWaitAsync returned result TryAgain
00:00:06.258 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 R11G11B10Float to (1 to 2).
00:00:06.258 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.263 |D| GPU.MainThread Gpu SetScale: Rescaling 1920x1080 R8G8B8A8Unorm to (1 to 2).
00:00:06.263 |D| GPU.MainThread Gpu SetScale:   Copy performed: 1920x1080 to 3840x2160
00:00:06.263 |D| HLE.OsThread.10 ServiceNv PrintResult: SubmitGpfifoEx returned result Success
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Silk.NET.Vulkan.Vk.CmdBlitImage(Silk.NET.Vulkan.CommandBuffer, Silk.NET.Vulkan.Image, Silk.NET.Vulkan.ImageLayout, Silk.NET.Vulkan.Image, Silk.NET.Vulkan.ImageLayout, UInt32, Silk.NET.Vulkan.ImageBlit ByRef, Silk.NET.Vulkan.Filter)
   at Ryujinx.Graphics.Vulkan.TextureCopy.Blit(Silk.NET.Vulkan.Vk, Silk.NET.Vulkan.CommandBuffer, Silk.NET.Vulkan.Image, Silk.NET.Vulkan.Image, Ryujinx.Graphics.GAL.TextureCreateInfo, Ryujinx.Graphics.GAL.TextureCreateInfo, Ryujinx.Graphics.GAL.Extents2D, Ryujinx.Graphics.GAL.Extents2D, Int32, Int32, Int32, Int32, Int32, Int32, Boolean, Silk.NET.Vulkan.ImageAspectFlags, Silk.NET.Vulkan.ImageAspectFlags)
   at Ryujinx.Graphics.Vulkan.TextureView.<BlitDepthStencilWithBuffer>g__SlowBlit|42_0(Ryujinx.Graphics.Vulkan.TextureStorage, Ryujinx.Graphics.Vulkan.TextureStorage, Silk.NET.Vulkan.ImageAspectFlags, <>c__DisplayClass42_0 ByRef)
   at Ryujinx.Graphics.Vulkan.TextureView.BlitDepthStencilWithBuffer(Ryujinx.Graphics.Vulkan.VulkanRenderer, Ryujinx.Graphics.Vulkan.CommandBufferScoped, Ryujinx.Graphics.Vulkan.TextureView, Ryujinx.Graphics.Vulkan.TextureView, Ryujinx.Graphics.GAL.Extents2D, Ryujinx.Graphics.GAL.Extents2D)
   at Ryujinx.Graphics.Vulkan.TextureView.CopyToImpl(Ryujinx.Graphics.Vulkan.CommandBufferScoped, Ryujinx.Graphics.Vulkan.TextureView, Ryujinx.Graphics.GAL.Extents2D, Ryujinx.Graphics.GAL.Extents2D, Boolean)
   at Ryujinx.Graphics.Vulkan.TextureView.CopyTo(Ryujinx.Graphics.GAL.ITexture, Ryujinx.Graphics.GAL.Extents2D, Ryujinx.Graphics.GAL.Extents2D, Boolean)
   at Ryujinx.Graphics.GAL.Multithreading.Commands.Texture.TextureCopyToScaledCommand.Run(Ryujinx.Graphics.GAL.Multithreading.Commands.Texture.TextureCopyToScaledCommand ByRef, Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer, Ryujinx.Graphics.GAL.IRenderer)
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper+<>c.<InitLookup>b__5_21(System.Span`1<Byte>, Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer, Ryujinx.Graphics.GAL.IRenderer)
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.RunCommand(System.Span`1<Byte>, Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer, Ryujinx.Graphics.GAL.IRenderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(System.Action)
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.Thread+StartHelper.RunWorker()
   at System.Threading.Thread+StartHelper.Run()
   at System.Threading.Thread.StartCallback()
   ```

**Comment by MutantAura** [comment]
Please report game-specific issues on the compatibility pages: https://github.com/Ryujinx/Ryujinx-Games-List/issues
Join the discord for further support queries: https://discord.gg/ryujinx
