### ISSUE TITLE
(Pokemon Legends: Arceus) Shader fails to decode

### ISSUE THREAD

**Issue by AnonymousDucky4** [Ryujinx/Ryujinx#4153]
### What's the issue you encountered?
I was attempting to decompile some shaders to be able to read the shader source. Unfortunatly it crashes on a specific shader (`Shader0069.bin`).

When running from source, it seems the decoder attempts to read this file beyond the file size limit.
Might be just a simple 'add a check', but I'm assuming there's more to it.

![image](https://user-images.githubusercontent.com/119038804/208671692-373965ab-d325-485c-a2fe-c96380913e10.png)

### How can the issue be reproduced?

1. In Ryujinx Graphics Settings, select the path to dump shaders.
    a. Make sure you restart
    b. If you don't get any shaders in the folder after launching the game, temporarily disable the shader cache
2. Launch Pokemon Legends: Arceus with the latest update
    a. Shaders should now be dumped, you can exit the game again
3. Go to the folder you selected in step 1
    a. Open the Dumps01 -> Full folder
    b. There should be 85 shaders in the folder
4. Run Ryujinx.ShaderTools.exe using `Shader0069.bin` from the `Full` folder above and the error should appear

### Log file

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(ShaderConfig config, Block block, UInt64 limitAddress, UInt64 startAddress) in C:\Users\Admin\Documents\Projects\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 233
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(ShaderConfig config, UInt64 startAddress) in C:\Users\Admin\Documents\Projects\Ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 93
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options) in C:\Users\Admin\Documents\Projects\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 108
   at Ryujinx.Graphics.Shader.Translation.Translator.CreateContext(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options) in C:\Users\Admin\Documents\Projects\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 29
```
### Environment?

- Ryujinx version: 1.1.481</br>
- Game version: 1.1.1</br>
- System Specs:
  - OS: Windows 11
  - CPU: N/A
  - GPU: NVIDIA RTX 3090Ti
  - RAM: 32GiB
- Applied Mods : No

### Additional context?

Additional info about your environment: 
Source was compiled from commit [6268170a10](https://github.com/Ryujinx/Ryujinx/tree/6268170a104740ee0d9d99e9ca88c96e1b52ef4b)

**Comment by gdkchan** [comment]
Maybe it is a compute shader, have you tried to pass the `--compute` argument?

**Comment by AnonymousDucky4** [comment]
😅 Ahha, yes it was a compute shader. Something threw me off and made me think it was a vertex/fragment shader combo.

Anyway thanks for pointing that out. It now converted perfectly fine :)
