### ISSUE TITLE
Unhandled exception caught: System.IO.FileNotFoundException: Could not find or load the native library: vulkan-1.dll Attempted: "vulkan-1.dll"

### ISSUE THREAD

**Issue by marcpre** [Ryujinx/Ryujinx#4184]
## Bug Report

I downloaded the *.zip `ryujinx-1.1.492-win_x64` from the ryujinx website.

After unzipping it it looks like the following:

![image](https://user-images.githubusercontent.com/30902582/209715743-4fed9d34-b5ab-4bda-8287-6f1b7577c7c3.png)

I correctly configured ryujinx, however I get the following error in the log files:

```
00:00:04.593 |E| GUI.RenderLoop Application : Unhandled exception caught: System.IO.FileNotFoundException: Could not find or load the native library: vulkan-1.dll Attempted: "vulkan-1.dll", "C:\Users\admin\Desktop\ryujinx-1.1.492-win_x64\publish\vulkan-1.dll"
File name: 'vulkan-1.dll'
   at Silk.NET.Core.Loader.LibraryLoader.ThrowLibNotFound(String name, PathResolver resolver)
   at Silk.NET.Core.Loader.LibraryLoader.LoadNativeLibrary(String name, PathResolver pathResolver)
   at Silk.NET.Core.Loader.UnmanagedLibrary..ctor(String name, LibraryLoader loader, PathResolver pathResolver)
   at Silk.NET.Core.Loader.UnmanagedLibrary..ctor(String name)
   at Silk.NET.Core.Contexts.DefaultNativeContext..ctor(String name)
   at Silk.NET.Vulkan.Vk.CreateDefaultContext(String n)
   at Silk.NET.Vulkan.Vk.GetApi()
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.SetupContext(GraphicsDebugLevel logLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 259
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.Initialize(GraphicsDebugLevel logLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 543
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.Initialize(GraphicsDebugLevel logLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 357
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 396
   at System.Threading.Thread.StartCallback()
```

### How can the issue be reproduced?

Just download the latest build from the ryujinx website. ;)

The `vulkan-1.dll` is missing.

### Log file

```
00:00:00.448 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.554 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.555 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.557 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.559 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.560 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.561 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.566 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.954 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.954 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.955 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.955 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.955 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.955 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.955 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.955 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.957 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.957 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.958 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.958 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.958 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.964 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.492
00:00:00.971 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.971 |N| Application Print: CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz ; 4 logical
00:00:00.973 |N| Application Print: RAM: Total 8084 MiB ; Available 3720 MiB
00:00:00.977 |N| Application PrintSystemInfo: Logs Enabled: Debug, Info, Warning, Error, Guest, Stub
00:00:00.978 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.287 |I| Gpu : Backend Threading (Auto): True
00:00:02.070 |N| Application LoadApplication: Using Firmware Version: 15.0.1
00:00:02.071 |I| Application LoadApplication: Loading as NSP.
00:00:02.159 |I| ModLoader QueryContentsDir: Searching mods for Title 0100152000022000
00:00:02.170 |I| ModLoader QueryContentsDir: Searching mods for Title 0100152000022000
00:00:02.191 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:02.531 |I| Loader LoadExeFs: Loading rtld...
00:00:02.578 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:02.578 |I| Loader LoadExeFs: Loading main...
00:00:02.958 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\TurboS\App\Rom\NX32\Product\TurboS.nss
    SDK Libraries: SDK MW+Nintendo+PiaCommon-5_2_5
                   SDK MW+Nintendo+Pia-5_2_5
                   SDK MW+Nintendo+NEX-4_0_7-apptrbs
                   SDK MW+Nintendo+NintendoSDK_gfx-0_12_16-Release
                   SDK MW+Nintendo+NintendoWare_G3d-0_12_16-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-0_12_16-Release
                   SDK MW+Nintendo+NintendoWare_Atk-0_12_16-Release
                   SDK MW+Nintendo+PiaInet-5_2_5
                   SDK MW+Nintendo+PiaLan-5_2_5
                   SDK MW+Nintendo+PiaSession-5_2_5
                   SDK MW+Nintendo+PiaTransport-5_2_5
                   SDK MW+Nintendo+PiaLocal-5_2_5
                   SDK MW+Nintendo+NintendoWare_Font-0_12_16-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-0_12_16-Release
                   SDK MW+Nintendo+NEX_MM-4_0_7
                   SDK MW+Nintendo+NEX_DS-4_0_7
                   SDK MW+Nintendo+NEX_RK-4_0_7
00:00:02.959 |I| Loader LoadExeFs: Loading subsdk0...
00:00:03.003 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: nvn
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_NVN-0_12_16-Release
00:00:03.003 |I| Loader LoadExeFs: Loading subsdk1...
00:00:03.007 |I| Loader PrintRoSectionInfo: subsdk1:
    Module: nnDisplay
00:00:03.007 |I| Loader LoadExeFs: Loading subsdk2...
00:00:03.010 |I| Loader PrintRoSectionInfo: subsdk2:
    Module: libz
00:00:03.010 |I| Loader LoadExeFs: Loading subsdk3...
00:00:03.018 |I| Loader PrintRoSectionInfo: subsdk3:
    Module: libcurl
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-0_12_16-Release
00:00:03.018 |I| Loader LoadExeFs: Loading subsdk4...
00:00:03.144 |I| Loader PrintRoSectionInfo: subsdk4:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-0_12_16-Release
00:00:03.144 |I| Loader LoadExeFs: Loading sdk...
00:00:03.300 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 0.17.16
    SDK Libraries: SDK MW+Nintendo+NintendoSdk_nnSdk-0_12_16-Release
00:00:03.569 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:04.022 |I| Loader LoadNsos: Loading image 0 at 0x0000000000200000...
00:00:04.028 |I| Loader LoadNsos: Loading image 1 at 0x0000000000206000...
00:00:04.046 |I| Loader LoadNsos: Loading image 2 at 0x0000000001512000...
00:00:04.049 |I| Loader LoadNsos: Loading image 3 at 0x00000000016ab000...
00:00:04.050 |I| Loader LoadNsos: Loading image 4 at 0x00000000016d3000...
00:00:04.050 |I| Loader LoadNsos: Loading image 5 at 0x00000000016e6000...
00:00:04.050 |I| Loader LoadNsos: Loading image 6 at 0x0000000001723000...
00:00:04.055 |I| Loader LoadNsos: Loading image 7 at 0x0000000001c9c000...
00:00:04.075 |I| ModLoader LoadCheats: Build ids found for title 0100152000022000:
    74DAC2371A39AC4C9149B42CCE6590E1EDCB6970000000000000000000000000
    B5C39B5B7C62A88EC25FA897858C874E00000000000000000000000000000000
    5B109840874BB2C4AAF79D658314A918EEAFCB4A000000000000000000000000
    65FB977974677204ABF177847587AB2EE44E2CB1000000000000000000000000
    FC36857DA0C342FAB0755DA8D911584EF603BF80000000000000000000000000
    DF815B134BED7DAAFD826286D2E003CD60367B3D000000000000000000000000
    DB90EC869D595DD3BB6A55753A0B59CC0AAF8E2F000000000000000000000000
    66C55BF0D8B166F81AC71BFC179191FD5B8A9A33000000000000000000000000
00:00:04.076 |I| Loader LoadNca: Application Loaded: Mario Kart 8 Deluxe v1.0.0 [0100152000022000] [32-bit]
00:00:04.120 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:04.216 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:04.593 |E| GUI.RenderLoop Application : Unhandled exception caught: System.IO.FileNotFoundException: Could not find or load the native library: vulkan-1.dll Attempted: "vulkan-1.dll", "C:\Users\admin\Desktop\ryujinx-1.1.492-win_x64\publish\vulkan-1.dll"
File name: 'vulkan-1.dll'
   at Silk.NET.Core.Loader.LibraryLoader.ThrowLibNotFound(String name, PathResolver resolver)
   at Silk.NET.Core.Loader.LibraryLoader.LoadNativeLibrary(String name, PathResolver pathResolver)
   at Silk.NET.Core.Loader.UnmanagedLibrary..ctor(String name, LibraryLoader loader, PathResolver pathResolver)
   at Silk.NET.Core.Loader.UnmanagedLibrary..ctor(String name)
   at Silk.NET.Core.Contexts.DefaultNativeContext..ctor(String name)
   at Silk.NET.Vulkan.Vk.CreateDefaultContext(String n)
   at Silk.NET.Vulkan.Vk.GetApi()
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.SetupContext(GraphicsDebugLevel logLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 259
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.Initialize(GraphicsDebugLevel logLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 543
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.Initialize(GraphicsDebugLevel logLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 357
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 396
   at System.Threading.Thread.StartCallback()

```

### Environment?

- Ryujinx version: ryujinx-1.1.493-win_x64</br>
- Game version: all these games</br>

![image](https://user-images.githubusercontent.com/30902582/209716205-5c6b2f0f-d0a7-4864-a370-f3a864b37f1f.png)

- System Specs:
  - OS: WIN 10
  - CPU: Processor	Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
  - GPU: NVIDIA GeForce 840M
  - RAM: 8 GB
- Applied Mods : No

**Comment by yogithesymbian** [comment]
did alr you solve this issue ? i have same issue
