### ISSUE TITLE
Crash fire emblem engage with amd

### ISSUE THREAD

**Issue by Nossoc30** [Ryujinx/Ryujinx#4342]
## Bug Report

Hey everyone.
Having bought a new computer, I decided to emulate the new fire emblem.
But randomly, I have crashes with ErrorOutOfdeviceMemory" in the logs.
I have the last keys released and the firmware.
I tried to play with enable texture recompression but nothing to do 
### Log file

GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 180
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 57
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, PhysicalDevice physicalDevice, Device device, TextureCreateInfo info, Single scaleFactor, Auto1 foreignAllocation) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 162
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_5(Span1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 64
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx\Ui\RendererWidgetBase.cs:line 401
   at System.Threading.Thread.StartCallback()

- Ryujinx version: 1.0.15

- Game version: 1.1.0<
[
- System Specs:
  - OS: *Windows 10)
  - CPU: *i5-12400f
  - GPU: 	AMD Radeon RX 6650 XT
  - RAM: 32g
- Applied Mods :  No

**Comment by MetrosexualGarbodor** [comment]
Enable texture recompression, and please don't open issues for help, we have discord for that
