### ISSUE TITLE
[Bug] ArgumentOutOfRangeException using LDN 3.1.0

### ISSUE THREAD

**Issue by Haceo** [Ryujinx/Ryujinx#4423]
### Description of the issue

ACNH v2.0.6 FW 15.0.1 game crashes application when opening local wireless

### Reproduction steps

Boot application, boot game with settings as directed by ldn-mitm usage, try to open gates for players to join or try to visit other players with local wireless, game saves, application crashes

### Log file

00:01:18.796 |I| HLE.OsThread.15 ServiceLdn : Initialize LanDiscovery using IP: 192.168.0.133
00:01:18.822 |E| HLE.OsThread.15 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.LdnMitm.LanDiscovery..ctor(LdnMitmClient parent, IPAddress ipAddress, IPAddress ipv4mask) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\LdnMitm\LanDiscovery.cs:line 106
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.LdnMitm.LdnMitmClient..ctor(HLEConfiguration config) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\LdnMitm\LdnMitmClient.cs:line 27
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.IUserLocalCommunicationService.InitializeImpl(ServiceCtx context, UInt64 pid, Int32 nifmRequestId) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\IUserLocalCommunicationService.cs:line 1146
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.IUserLocalCommunicationService.Initialize(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\IUserLocalCommunicationService.cs:line 1111
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 320
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1262
   at System.Threading.Thread.StartCallback()

### OS

Windows 10

### Ryujinx version

1.1.0-ldn3.1.0

### Game version

2.0.6

### CPU

i7-12700KF

### GPU

MSI RTX 3060

### RAM

64GB

### List of applied mods

N/A

### Additional context?

N/A

**Comment by AcK77** [comment]
Should be fixed in LDN 3.1.3: [https://www.patreon.com/posts/introducing-ldn3-74910544](https://www.patreon.com/posts/introducing-ldn3-74910544)

(I'll reopen the issue if the crash is still reported)
