### ISSUE TITLE
[Bug]Ryujinx crashed when I start the game "DRAGON QUEST XI S"

### ISSUE THREAD

**Issue by Shihta** [Ryujinx/Ryujinx#4511]
### Description of the issue

I built the latest Ryujinx by myself and try to use it for playing "DRAGON QUEST XI S"
Ryujinx crashed when I start the game "DRAGON QUEST XI S"

### Reproduction steps

1. start Ryujinx
2. start "DRAGON QUEST XI S"

### Log file

[Ryujinx-Logs.zip](https://github.com/Ryujinx/Ryujinx/files/10890938/Ryujinx-Logs.zip)

https://user-images.githubusercontent.com/5186176/222945948-c5978cc6-3dbb-4aa6-b717-ed5175a97cc5.mov

the log in console:
```
00:00:02.609 |D| Ui : [Verbose] [Property] 'X' changed from '272.7210299876813' to '289.2363326295357' with priority 'Animation' (TranslateTransform #35088115)
00:00:02.618 |T| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = TimedOut
00:00:02.618 |T| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic(mutexAddress: 0x00000000906CF6BC, condVarAddress: 0x00000000906CF6C0, handle: 0x00170028, timeout: 0x0000000000988E5C)
00:00:02.618 |T| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic() = TimedOut
00:00:02.618 |T| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic(mutexAddress: 0x00000000906CF5FC, condVarAddress: 0x00000000906CF600, handle: 0x00168027, timeout: 0x0000000000988FFD)
00:00:02.618 |I| HLE.GuestThread.21 Cpu PrintGuestStackTrace: Guest stack trace:
Process: JackGame, PID: 96
   0x0000000009667320	main:0x1663320
   0x00000000096671d8	main:0x16631d8
   0x00000000096c4828	main:0x16c0828
   0x00000000082c27e4	main:0x2be7e4
   0x00000000082bbfc8	main:0x2b7fc8
   0x00000000082cb6e4	main:0x2c76e4
   0x000000001189be88	sdk:0x329e88
   0x00000000118a0294	sdk:0x32e294
   0x0000000000000000


00:00:02.619 |I| HLE.GuestThread.21 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x000000120c1ce7c8 (SP:-0x0258)
	X[01]:	0x0000000000000020
	X[02]:	0x0000000000000000
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000000
	X[09]:	0x0000000000000038
	X[10]:	0x0000000000000000
	X[11]:	0x0000000000000057
	X[12]:	0x000000000000003f
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x0000000012174370
	X[17]:	0x0000000011a495e0 (sdk:0x4d75e0)	=> toupper
	X[18]:	0x0000000000000000
	X[19]:	0x00000000888ba930
	X[20]:	0x0000000000000010
	X[21]:	0x0000000000000001
	X[22]:	0x000000120c1ce680 (SP:-0x0110)
	X[23]:	0x000000120c1ce720 (SP:-0x01b0)
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x000000000f882000
	X[27]:	0x000000000f87d000
	X[28]:	0x000000000ed84000
	FP:	0x000000120c1ce5a0 (SP:-0x0030)
	LR:	0x0000000009667320 (main:0x1663320)	=>
	SP:	0x000000120c1ce570 (SP)
	PC:	0x000000000966e198 (main:0x166a198)	=>


00:00:02.619 |E| HLE.GuestThread.21 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000020.
00:00:02.625 |D| Ui : [Verbose] [Property] 'X' changed from '289.2363326295357' to '305.23252255678483' with priority 'Animation' (TranslateTransform #35088115)
00:00:02.628 |T| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = TimedOut
00:00:02.628 |T| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic(mutexAddress: 0x00000000906CF6BC, condVarAddress: 0x00000000906CF6C0, handle: 0x00170028, timeout: 0x0000000000989169)
00:00:02.628 |T| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic() = TimedOut
00:00:02.628 |T| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic(mutexAddress: 0x00000000906CF5FC, condVarAddress: 0x00000000906CF600, handle: 0x00168027, timeout: 0x0000000000989206)
00:00:02.638 |T| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = TimedOut
00:00:02.638 |T| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic(mutexAddress: 0x00000000906CF6BC, condVarAddress: 0x00000000906CF6C0, handle: 0x00170028, timeout: 0x0000000000989065)
00:00:02.638 |T| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic() = TimedOut
00:00:02.638 |T| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic(mutexAddress: 0x00000000906CF5FC, condVarAddress: 0x00000000906CF600, handle: 0x00168027, timeout: 0x000000000098923A)
00:00:02.641 |D| Ui : [Verbose] [Property] 'X' changed from '305.23252255678483' to '320.68547895376935' with priority 'Animation' (TranslateTransform #35088115)
00:00:02.643 |E| HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /Users/shihta/workspace/Ryujinx/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 277
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in /Users/shihta/workspace/Ryujinx/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 212
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.DataAbort(MemoryTracking tracking, UInt64 vcpu, UInt32 esr) in /Users/shihta/workspace/Ryujinx/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 219
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /Users/shihta/workspace/Ryujinx/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 179
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /Users/shihta/workspace/Ryujinx/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 146
   at Ryujinx.Cpu.AppleHv.HvCpuContext.Execute(IExecutionContext context, UInt64 address) in /Users/shihta/workspace/Ryujinx/Ryujinx.Cpu/AppleHv/HvCpuContext.cs:line 30
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in /Users/shihta/workspace/Ryujinx/Ryujinx.HLE/HOS/ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /Users/shihta/workspace/Ryujinx/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /Users/shihta/workspace/Ryujinx/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 277
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in /Users/shihta/workspace/Ryujinx/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 212
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.DataAbort(MemoryTracking tracking, UInt64 vcpu, UInt32 esr) in /Users/shihta/workspace/Ryujinx/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 219
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /Users/shihta/workspace/Ryujinx/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 179
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /Users/shihta/workspace/Ryujinx/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 146
   at Ryujinx.Cpu.AppleHv.HvCpuContext.Execute(IExecutionContext context, UInt64 address) in /Users/shihta/workspace/Ryujinx/Ryujinx.Cpu/AppleHv/HvCpuContext.cs:line 30
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in /Users/shihta/workspace/Ryujinx/Ryujinx.HLE/HOS/ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /Users/shihta/workspace/Ryujinx/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()
Abort trap: 6
```

### OS

macOS Monterey 12.5.1

### Ryujinx version

b8556530f2b160db70ff571adf25ae26d4b8f58f

### Game version

1.0.3

### CPU

M2

### GPU

M2 

### RAM

24G

**Comment by asandyguy** [comment]
not try to double-click run the game may work

**Comment by Shihta** [comment]
> not try to double-click run the game may work

OMG you are right, I can start it by `File` -> `Load Application From File`

so should I keep this issue open?

**Comment by Shihta** [comment]
This problem no longer exists, it should have been resolved in one of the fixes.

**Comment by Jorc0** [comment]
Just happened to me on 1.1.895

**Comment by Jorc0** [comment]
> Just happened to me on 1.1.895 (on another game)

Nevermind, as i changed ryujinx folder drive, updates deleted, so re-adding the update fixes it

**Comment by AlexisMPaz** [comment]
> > Just happened to me on 1.1.895 (on another game)
> 
> Nevermind, as i changed ryujinx folder drive, updates deleted, so re-adding the update fixes it

hi, how do you delete the updates?
