### ISSUE TITLE
[Regression] Extract logo from a game with an update shows an error

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#4521]
### Description of the issue

Extracting a logo with an update applied causing an error to pop up, it's unknown what version causes this issue
![image](https://user-images.githubusercontent.com/100526773/223634796-fc3ad645-43bb-4ec3-a7a7-dc03477b7aca.png)

### Reproduction steps

apply an update and try and extract a logo

### Log file

[Ryujinx_1.1.650_2023-03-08_06-19-30.log](https://github.com/Ryujinx/Ryujinx/files/10917760/Ryujinx_1.1.650_2023-03-08_06-19-30.log)

### OS

Arch Linux

### Ryujinx version

1.1.650

**Comment by OldManKain** [comment]
Confirmed not working on Windows 11.

**Comment by jensengillett** [comment]
I've taken a stab at extracting logos from my own games. Windows 10, Ryujinx 1.1.662. Oddly enough, instead of getting a pop-up dialog, the program just hard crashes for me instead, though the logs still show the same error.

Disabling the update file (even just switching to 'no update' in the update selector) makes the feature work properly and extracts the logos successfully, so it's definitely something to do with selecting an update file. My guess would be that it's trying to find the files within the update file instead of the base file, and they don't exist in that file (hence 'section 2 does not exist'), thus causing the program to freak out.

Here's the part of the log that matters:
```
00:00:05.397 |E| GUI.NcaSectionExtractorThread Application : Unhandled exception caught: System.ArgumentException: NCA section 2 does not exist. (Parameter 'index')
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenSectionStorage(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorageWithPatch(Nca patchNca, Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorageWithPatch(Nca patchNca, Int32 index, IntegrityCheckLevel integrityCheckLevel, Boolean leaveCompressed)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorageWithPatch(Nca patchNca, Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystemWithPatch(Nca patchNca, Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.Ui.Widgets.GameTableContextMenu.<>c__DisplayClass14_0.<ExtractSection>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\Widgets\GameTableContextMenu.cs:line 272
   at System.Threading.Thread.StartCallback()```
   
Hopefully this helps!
