### ISSUE TITLE
[Bug] Hyrule Warrior Age of Calamity Crash

### ISSUE THREAD

**Issue by dels07** [Ryujinx/Ryujinx#4575]
### Description of the issue

I got crash when in Hyrule Outpost scenario, in second part while play as Link, attached log and save file

[hw_aoc.zip](https://github.com/Ryujinx/Ryujinx/files/11030110/hw_aoc.zip)

currently using Ryujinx build from master at `17620d18db8d4a67e4b917596c760107d26fadc5` and use default graphic settings

### Reproduction steps

- Play Hyrule Outpost main scenario
- After fight with first boss, the game will switch to Link
- It will randomly crash while fighting opponent

### Log file

[Ryujinx_1.1.1+1.1.0_2023-03-21_21-59-24.log](https://github.com/Ryujinx/Ryujinx/files/11030119/Ryujinx_1.1.1%2B1.1.0_2023-03-21_21-59-24.log)

Relevant errors
```
00:30:33.198 |E| [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 9): Invalid Resource (00000009:kIOGPUCommandBufferCallbackErrorInvalidResource)
00:30:33.225 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in /Users/deli/Documents/Playground/Ryujinx/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 315
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in /Users/deli/Documents/Playground/Ryujinx/Ryujinx.Graphics.Vulkan/PipelineFull.cs:line 219
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id, Boolean strict) in /Users/deli/Documents/Playground/Ryujinx/Ryujinx.Graphics.Vulkan/SyncManager.cs:line 70
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /Users/deli/Documents/Playground/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in /Users/deli/Documents/Playground/Ryujinx/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 115
   at Ryujinx.Ava.AppHost.RenderLoop() in /Users/deli/Documents/Playground/Ryujinx/Ryujinx.Ava/AppHost.cs:line 826
   at System.Threading.Thread.StartCallback()
```

### OS

Ventura 13.2.1

### Ryujinx version

1.1.1

### Game version

1.3.0

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro

### RAM

16GB

**Comment by AcK77** [comment]
What if you use the provided build on www.ryujinx.org ?
