### ISSUE TITLE
Run Homebrew whit SDL2 support, Mac OSX 10.13.6 

### ISSUE THREAD

**Issue by Donas4Ceos** [Ryujinx/Ryujinx#458]
LOG:

Unhandled Exception: System.ArgumentException: BlendFactor "0" is not valid!
   at Ryujinx.Graphics.Gal.OpenGL.OGLEnumConverter.GetBlendFactor(GalBlendFactor BlendFactor) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLEnumConverter.cs:line 320
   at Ryujinx.Graphics.Gal.OpenGL.OGLPipeline.Bind(GalPipelineState New) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLPipeline.cs:line 299
   at Ryujinx.Graphics.NvGpuEngine3d.DispatchRender(NvGpuVmm Vmm, GalPipelineState State) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 772
   at Ryujinx.Graphics.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 123
   at Ryujinx.Graphics.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 79
   at Ryujinx.Graphics.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 173
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 120
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GLScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Abort trap: 6

**Comment by Thog** [comment]
Do you have any code example that cause this error?

**Comment by gdkchan** [comment]
Well, this indicates that the GPU is being used, which suggests hardware acceleration. Last time I checked SDL2 on switch was software rendered.

**Comment by Donas4Ceos** [comment]
here the source:


#include <string.h>
#include <stdio.h>

#include <switch.h>
#include "common.hpp"



static void Term_Services(void)
{


	IMG_Quit();

	SDL_DestroyRenderer(RENDERER);
	SDL_FreeSurface(WINDOW_SURFACE);
	SDL_DestroyWindow(WINDOW);


	SDL_Quit();
	romfsExit();
}

static void Init_Services(void)
{
	romfsInit();
	SDL_Init(SDL_INIT_EVERYTHING);


	SDL_CreateWindowAndRenderer(1280, 720, 0, &WINDOW, &RENDERER);

	WINDOW_SURFACE = SDL_GetWindowSurface(WINDOW);

	SDL_SetRenderDrawBlendMode(RENDERER, SDL_BLENDMODE_BLEND);

	SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "2");

	IMG_Init(IMG_INIT_PNG | IMG_INIT_JPG);


}

void SDL_ClearScreen(SDL_Renderer *renderer, SDL_Color colour)
{
	SDL_SetRenderDrawColor(renderer, colour.r, colour.g, colour.b, colour.a);
	SDL_RenderClear(renderer);
}

void SDL_DrawRect(SDL_Renderer *renderer, int x, int y, int w, int h, SDL_Color colour)
{
	SDL_Rect rect;
	rect.x = x; rect.y = y; rect.w = w; rect.h = h;
	SDL_SetRenderDrawColor(RENDERER, colour.r, colour.g, colour.b, colour.a);
	SDL_RenderFillRect(RENDERER, &rect);
}


int main(int argc, char **argv)
{

		Init_Services();

		MENU_DEFAULT_STATE = MENU_STATE_HOME;


				SDL_ClearScreen(RENDERER,  BLACK_BG);
				SDL_RenderClear(RENDERER);
				SDL_DrawRect(RENDERER, 0, 0, 1280, 40, WHITE);	// Status bar
				SDL_DrawRect(RENDERER, 0, 40, 1280, 100, WHITE);	// Menu bar

				SDL_RenderPresent(RENDERER);

		    while(appletMainLoop())
		    {

		    	
		        hidScanInput();
		        u64 kDown = hidKeysDown(CONTROLLER_P1_AUTO);
		        if (kDown & KEY_PLUS) break; // break in order to return to hbmenu


		    }

		Term_Services();

		return 0;

}

**Comment by Donas4Ceos** [comment]
![sdlguinx](https://user-images.githubusercontent.com/12439494/46973305-6f854480-d086-11e8-92b8-6038b78bb76f.png)

please change to .nro

this Homebrew is only for testing SDL2 in Emu, only draw a white Rect

regards
