### ISSUE TITLE
[Bug]click button in Settings will crash

### ISSUE THREAD

**Issue by ht1456749** [Ryujinx/Ryujinx#4592]
### Description of the issue

![无标题](https://user-images.githubusercontent.com/11936836/227511708-db1ff7bb-9104-4e1f-a6ce-132e87c9247c.png)
click the button in the left，such as 【System】【CPU】【INPUT】，click them for three times，ryujinx will crash.

00:00:56.498 |E| Application : Unhandled exception caught: System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at Avalonia.Skia.FontManagerImpl.TryMatchCharacter(Int32 codepoint, FontStyle fontStyle, FontWeight fontWeight, FontFamily fontFamily, CultureInfo culture, Typeface& fontKey) in /_/src/Skia/Avalonia.Skia/FontManagerImpl.cs:line 36
   at Avalonia.Media.FontManager.TryMatchCharacter(Int32 codepoint, FontStyle fontStyle, FontWeight fontWeight, FontFamily fontFamily, CultureInfo culture, Typeface& typeface) in /_/src/Avalonia.Visuals/Media/FontManager.cs:line 151
   at Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(ReadOnlySlice`1 text, TextRunProperties defaultProperties) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 58
   at Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 34
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 314
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 202
   at FluentAvalonia.UI.Controls.FontIcon.GenerateText()
   at FluentAvalonia.UI.Controls.FontIcon.OnPropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.Animation.Animatable.OnPropertyChangedCore[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Animation/Animatable.cs:line 92
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 788
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 509
   at Avalonia.PropertyStore.PriorityValue`1.RaiseValueChanged(IValueSink sink, IAvaloniaObject owner, AvaloniaProperty property, Optional`1 oldValue, Optional`1 newValue) in /_/src/Avalonia.Base/PropertyStore/PriorityValue.cs:line 202
   at Avalonia.ValueStore.BatchUpdate.End() in /_/src/Avalonia.Base/ValueStore.cs:line 409
   at Avalonia.AvaloniaObject.EndBatchUpdate() in /_/src/Avalonia.Base/AvaloniaObject.cs:line 468
   at Avalonia.StyledElement.ApplyStyling() in /_/src/Avalonia.Styling/StyledElement.cs:line 350
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 654
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 654
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 654
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 654
   at Avalonia.Controls.Button.OnAttachedToLogicalTree(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Button.cs:line 245
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 654
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 654
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 654
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 654
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 654
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent) in /_/src/Avalonia.Styling/StyledElement.cs:line 412
   at Avalonia.StyledElement.SetLogicalParent(IList children) in /_/src/Avalonia.Styling/StyledElement.cs:line 732
   at Avalonia.Visual.LogicalChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Visuals/Visual.cs:line 382
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 691
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 141
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 788
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 509
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 353
   at Avalonia.ValueStore.SetExisting[T](Object slot, StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 266
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 98
   at Avalonia.Controls.ContentControl.set_Content(Object value) in /_/src/Avalonia.Controls/ContentControl.cs:line 56
   at Ryujinx.Ava.UI.Windows.SettingsWindow.NavPanelOnSelectionChanged(Object sender, NavigationViewSelectionChangedEventArgs e) in D:\a\Ryujinx\Ryujinx\Ryujinx.Ava\UI\Windows\SettingsWindow.axaml.cs:line 85

### Reproduction steps

click the button in the left，such as 【System】【CPU】【INPUT】，click them for three times，ryujinx will crash

### Log file

[Ryujinx_1.1.678_2023-03-24_19-27-01.log](https://github.com/Ryujinx/Ryujinx/files/11061609/Ryujinx_1.1.678_2023-03-24_19-27-01.log)

### OS

windows 10

### Ryujinx version

test-ava-ryujinx-1.1.678-win_x64

### CPU

i5 12400F

### GPU

1060

### RAM

16G

**Comment by AcK77** [comment]
Duplicated of #4589
