### ISSUE TITLE
[Bug]p5r crash

### ISSUE THREAD

**Issue by cellYmax** [Ryujinx/Ryujinx#4622]
### Description of the issue

i got crash when play p5r in the third palace
i use default graphic settings

### Reproduction steps

1.in the third palace
2.fight with any enemy,
3.it will crash while defeat the enemy

### Log file

00:23:07.787 |E| HLE.GuestThread.16 Application : Unhandled exception caught: System.Exception: Unhandled guest exception Unknown.
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 182
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 160
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

macos 13.3

### Ryujinx version

1.1.0-macOS1

### Game version

1.0.2

### CPU

m1 pro

### RAM

16GB

**Comment by gdkchan** [comment]
You should attach a save.

**Comment by cellYmax** [comment]
> You should attach a save.

Sorry, I don't know what the save file is. There are three folders 
<img width="271" alt="1111111" src="https://user-images.githubusercontent.com/85604200/229158116-8fe99b89-e628-4ac1-93e4-3b6aba7fba3a.png">

**Comment by gdkchan** [comment]
It's none of those. You need to right click on the game on the games list, then click on open user save directory.

**Comment by cellYmax** [comment]
> It's none of those. You need to right click on the game on the games list, then click on open user save directory.

thanks a lot. this is my save files
[save.zip](https://github.com/Ryujinx/Ryujinx/files/11123503/save.zip)
