### ISSUE TITLE
[CPU] opcode missing while launching homebrews which use borealis

### ISSUE THREAD

**Issue by PoloNX** [Ryujinx/Ryujinx#4656]
### CPU instruction

```
00:00:03.122 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000815c6fc (opcode 0xd50320ff) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1106
   at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\State\ExecutionContext.cs:line 150
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()
```

### Instruction name

I don't understand sorry

### Required by

It's for every homebrew which use borealis. The example here crash : 
https://github.com/XITRIX/borealis

Here is a .nro already compiled of it : 
[borealis_demo.zip](https://github.com/Ryujinx/Ryujinx/files/11182868/borealis_demo.zip)

**Comment by gdkchan** [comment]
This seems to be the XPACLRI instruction that the Switch CPU does not support (it is pointer authentication related). Are you sure this homebrew actually works on the Switch? It sounds like it was compiled targeting the wrong CPU.

**Comment by bylaws** [comment]
These instructions are in NOP space, and as such are valid to emit when targeting armv8.0, they just won't do anything

**Comment by gdkchan** [comment]
Right, XPACD/XPACI are undefined according to the manual if the PAE extension is not supported, but XPACLRI just doesn't do anything.

**Comment by gdkchan** [comment]
This is on the "HINT" encoding space. I think it is technically a regression from #3694 since we had all HINT instructions handled as NOP before that.

**Comment by PoloNX** [comment]
> This seems to be the XPACLRI instruction that the Switch CPU does not support (it is pointer authentication related). Are you sure this homebrew actually works on the Switch? It sounds like it was compiled targeting the wrong CPU.

Yes it works on my switch

I don’t understand everything because I’m not very good in the development of emulator. If you want more information ask me

**Comment by PoloNX** [comment]
Hi, there is a new error. Here it is :
```
00:00:03.108 |E| HLE.OsThread.8 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy: 201

Guest Stack Trace:
Process: Service, PID: 85

Raw Request Data:
00000000   01 00 18 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 00 00 00 00  C9 00 00 00 00 00 00 00   SFCI····É·······
00000020   00 10 00 00 00 00 00 01  02 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 256
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 196
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 109
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1262
   at System.Threading.Thread.StartCallback()
   
 ```

**Comment by MutantAura** [comment]
> Hi, there is a new error.

There is already an issue open for this: https://github.com/Ryujinx/Ryujinx/issues/3064
