### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Citrus1609** [Ryujinx/Ryujinx#4682]
### Description of the issue

when i try to open a game my game don't shows up and the logs are strange 

### Reproduction steps

i just click on load application from file and then my game but nothing happens

### Log file

00:00:00.377 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Ryujinx.HLE.Loaders.Executables.NsoExecutable..ctor(IStorage inStorage, String name) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Loaders\Executables\NsoExecutable.cs:line 52
   at Ryujinx.HLE.Loaders.Processes.ProcessLoader.LoadNxo(String path) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Loaders\Processes\ProcessLoader.cs:line 202
   at Ryujinx.HLE.Switch.LoadProgram(String fileName) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Switch.cs:line 90
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean isFirmwareTitle) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 781
   at Ryujinx.Ui.MainWindow.RunApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 826
   at Ryujinx.Ui.MainWindow.Load_Application_File(Object sender, EventArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1248
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### OS

Widows 10

### Ryujinx version

1.0.720

### Game version

1.6.0

### Additional context?

that's the legend of zelda botw btw

**Comment by CoolFrenchPerson** [comment]
Manually re-download ryujinx and join our discord for the kinds of issues : https://discord.gg/ryujinx

**Comment by gdkchan** [comment]
You should be loading a XCI or NSP file. The error sounds like you extracted the game is trying to load it incorrectly.

**Comment by OldManKain** [comment]
Please join us in our discord https://discord.gg/ryujinx and head over to your operating system channel for troubleshooting issues.
