### ISSUE TITLE
[Bug]The key file has been placed but an error is still reported

### ISSUE THREAD

**Issue by hongzhi725** [Ryujinx/Ryujinx#4728]
### Description of the issue

Mac M1
The key file has been placed in the correct address 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/17839970/234482957-bb664d1c-b4f8-4c73-af82-8b8829b7c4c5.png">

Error Info. :
![image](https://user-images.githubusercontent.com/17839970/234482787-9d7d6c5b-6d64-49b8-a6dd-fe146ac9c9ee.png)

### Reproduction steps

ABOVE

### Log file

[Ryujinx_ 1.1.0-macos1_2023-04-26_13-58-49.log](https://github.com/Ryujinx/Ryujinx/files/11329495/Ryujinx_.1.1.0-macos1_2023-04-26_13-58-49.log)

### OS

Mac 13.3.1 (22E261) M1

### Ryujinx version

1.1.0-macos1

**Comment by hongzhi725** [comment]
Step:
1. place the "prod.keys" file into the system folder.
2. Tools -> Install Firmware -> Install a firmware from XCI or ZIP.
3. Report an error as shown above

**Comment by jackandcarter** [comment]
I also have the same issue on intel Mac. Keys are there, but firmware install complains they aren't.

**Comment by jackandcarter** [comment]
this is my log

 00:00:00.118 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:11.803 |E| Application HandleFirmwareInstallation: LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0f

**Comment by gdkchan** [comment]
Are the keys up to date? Have you tried installing older firmware?

**Comment by jackandcarter** [comment]
both match, I've tried 16.0.1, as well as 16.0 for both firmware and keys

**Comment by hongzhi725** [comment]
keys: 16.0.1
firmware: 16.0.1 & 16.0.2
both match

**Comment by Lucas0819** [comment]
+1

**Comment by Lucas0819** [comment]
keys: 16.0.1
firmware: 16.0.1 & 16.0.2

**Comment by fechy** [comment]
+1

**Comment by TimeZlicer** [comment]
just for comparison, building for master works

'''
00:00:00.034 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.739-macos+680e54802
00:00:00.037 |N| Application Print: Operating System: Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112 (Arm64)
00:00:00.037 |N| Application Print: CPU: Apple M2^@ ; 8 logical
00:00:00.037 |N| Application Print: RAM: Total 24576 MiB ; Available 12661 MiB
00:00:00.038 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.038 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.372 |N| Application LoadGuestApplication: Using Firmware Version: 16.0.2
'''

**Comment by k1nz** [comment]
same problem in `win10 21H2`

logs:
```
00:00:21.657 |E| Application HandleInstallerDialog: LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0f
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index, Int64 offset, UInt64 upperCounter)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel, Boolean leaveCompressed)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(NcaSectionType type, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.ContentManager.<VerifyFirmwarePackage>g__VerifyAndGetVersionZip|44_1(ZipArchive archive, <>c__DisplayClass44_0&) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\FileSystem\ContentManager.cs:line 781
   at Ryujinx.HLE.FileSystem.ContentManager.VerifyFirmwarePackage(String firmwarePackage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\FileSystem\ContentManager.cs:line 683
   at Ryujinx.Ui.MainWindow.HandleInstallerDialog(FileChooserNative fileChooser) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 1430
```

**Comment by bboczeng** [comment]
Apparently this is a silly error, if you open the key files you will find `key_area_key_application_00` to `key_area_key_application_0e`, and I have no idea why this firmware is requesting `0f`.

must be a silly bug looping around

**Comment by PhiZero** [comment]
```
|E| Application HandleFirmwareInstallation: LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0f
```
This error indicates you're missing keys, quite and simple. 
You're all seemingly missing key_area_application_0f, which is required as part of the newer firmwares (16.0.1, 16.0.2)
![image](https://user-images.githubusercontent.com/7350221/235663883-e3e70a28-6fc4-4e8a-aef2-e9ca4a09b1b2.png)

Please just dump your keys again using the latest version of Lockpick RCM. This is not a Ryujinx bug.

**Comment by DJChief** [comment]
where can i find these prod.keys ?

**Comment by bboczeng** [comment]
not sure why you deleted my comments. the same keys used for YUZU works fine with their 16.0.1 firmware
just assuming 16.0 keys have `0f` without confirming, or even providing a working key file is 
just trying to hide that Ryujinx had a stupid bug (compared to Yuzu)

**Comment by bboczeng** [comment]
i have reasons to believe you are just iterating from 00 to 0f without even knowing what you are doing; while Yuzu is able to actually check and fix the bugs for 16.0.1 . It is my comment that makes you finally realize it is a 0f key error; simply deleting my comments makes you a unprofessional , small-mined petty man..

I will not, never use or sponsor your projects in the future ever.

**Comment by gdkchan** [comment]
You can't post keys here since it is copyrighted content.

**Comment by bboczeng** [comment]
i have checked all the YUZU 16..0 key files (supposedly they use the same keys as Ryujinx). it doesn't have 0f and it works fine.

**Comment by gdkchan** [comment]
The original post is about an error decrypting the firmware on macOS and the build we released last year. Are you having the same problem? If not, it might be a different issue. And your comments are not very constructive in general.

**Comment by bboczeng** [comment]
Apparently @jackandcarter  reported ```Key Name: key_area_key_application_0f``` error and this issue has been referenced multiple times elsewhere regarding exactly this `0f` issue
and it is because of me that the Ryujinx author realized the root cause and closed this issue, prematurely I would say.  As I would recall there is no such 16.0 keys on earth that has a `0f` entry. unless everyone dumped the wrong one

**Comment by gdkchan** [comment]
We have been closing old issues recently, if you look at recent activity on the repo you will see that a lot of issues have been closed on the past hours, no one is trying to target this issue specifically or trying to hide the fact that yuzu can parse a keys file or whatever.

**Comment by bboczeng** [comment]
that's not my point. I used YUZU as an example that it is not because we didn't know how to flush/update our old key files, in fact every install is fresh. its just like telling us to restart our computer to magically solve many windows bugs (which won't)

This issue will persist, closing it won't actually resolve it

**Comment by PhiZero** [comment]
> As I would recall there is no such 16.0 keys on earth that has a `0f` entry. unless everyone dumped the wrong one

Yes, that is exactly it. You may skirt around it and say "dumped the wrong one", but the reality is just that everyone with this issue downloaded outdated keys. 

The proof is that the correct filesize for the current up to date key file is around 14.2KB, and the one you all _collectively_ have is 13KB.

![image](https://user-images.githubusercontent.com/7350221/235777342-4e63a05e-50f7-4af0-a224-4bcb5d5e2452.png)


This is the correct file size. There should be 251 keys (lines) currently. Anything smaller than this is missing keys, the end.
