### ISSUE TITLE
[Bug] Cannot install Firmware on Macos13(Apple M1 Pro)

### ISSUE THREAD

**Issue by marc-shen** [Ryujinx/Ryujinx#4746]
### Description of the issue

I have already put the `prod.keys` to the correct position. Then I tried to install the firmware file. I have tried the ways to install it from zip and from a directory. However both of two ways failed.

It shows:
>RYU-0001: Keys not found
>Ryujinx was unable to find your 'prod.keys' file
>For more information on how to fix this error, follow our Setup Guide.

### Reproduction steps

I have already put the `prod.keys` to the correct position. Then I tried to install the firmware file. I have tried the ways to install it from zip and from a directory. However both of two ways failed.

### Log file

00:00:00.029 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.031 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.031 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.031 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.031 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.032 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.032 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.033 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.037 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.037 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.037 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.037 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.037 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.037 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.037 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.037 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.037 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.037 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.038 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.038 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.038 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.038 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.040 |N| Application PrintSystemInfo: Ryujinx Version:  1.1.0-macos1
00:00:00.043 |N| Application Print: Operating System: Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 (Arm64)
00:00:00.043 |N| Application Print: CPU: Apple M1 Pro ; 10 logical
00:00:00.043 |N| Application Print: RAM: Total 16384 MiB ; Available Unknown
00:00:00.044 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.045 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:13.680 |E| Application HandleFirmwareInstallation: LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0f
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index, Int64 offset, UInt64 upperCounter)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel, Boolean leaveCompressed)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(NcaSectionType type, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.ContentManager.<VerifyFirmwarePackage>g__VerifyAndGetVersionZip|44_1(ZipArchive archive, <>c__DisplayClass44_0&) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/FileSystem/ContentManager.cs:line 786
   at Ryujinx.HLE.FileSystem.ContentManager.VerifyFirmwarePackage(String firmwarePackage) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/FileSystem/ContentManager.cs:line 688
   at Ryujinx.Ava.Ui.ViewModels.MainWindowViewModel.HandleFirmwareInstallation(String filename) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Ava/Ui/ViewModels/MainWindowViewModel.cs:line 1424
00:06:46.395 |E| Application HandleFirmwareInstallation: LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_0f
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index, Int64 offset, UInt64 upperCounter)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel, Boolean leaveCompressed)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(NcaSectionType type, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.ContentManager.<VerifyFirmwarePackage>g__VerifyAndGetVersionZip|44_1(ZipArchive archive, <>c__DisplayClass44_0&) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/FileSystem/ContentManager.cs:line 786
   at Ryujinx.HLE.FileSystem.ContentManager.VerifyFirmwarePackage(String firmwarePackage) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/FileSystem/ContentManager.cs:line 688
   at Ryujinx.Ava.Ui.ViewModels.MainWindowViewModel.HandleFirmwareInstallation(String filename) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Ava/Ui/ViewModels/MainWindowViewModel.cs:line 1424

### OS

MacOS 13.3.1

### Ryujinx version

1.1.0-macos1

### Game version

?

### CPU

M1pro

### GPU

M1pro

### RAM

16

**Comment by TimeZlicer** [comment]
Good day

prod.keys need to match the firmware version that you are trying to install

Do try to extract prod.keys again, or try installing an older firmware version (that matches the prod.keys)

**Comment by TimeZlicer** [comment]
similar to https://github.com/Ryujinx/Ryujinx/issues/4728

**Comment by DJChief** [comment]
where can I find prod.keys and firmware that works?

**Comment by lnchan** [comment]
> As suggested by:
> 
> ```
> 00:00:13.680 |E| Application HandleFirmwareInstallation: LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
> Key Type: Common
> Key Name: key_area_key_application_0f
> ```
> 
> You miss new keys introduced in 16.x. Dump them again from your switch and update them. You can go to our discord for support. Thanks.

Is it possible that the macOS build was built using a HacLib version prior to 0.17.0, as it released around the same period? It seems that the macOS version that was released was based on a private branch, and as such I cannot track what it was built from.
This would explain issues related to 15.0.0+ firmwares that people seem to be having trouble with on macOS (this issue is not the only such example, from what I can see).
