### ISSUE TITLE
[Bug] Unsupported stencil/depth buffer format B8G8R8A8Unorm (macOS 13.3.1, Ryujinx 1.1.0-macos1)

### ISSUE THREAD

**Issue by lnchan** [Ryujinx/Ryujinx#4748]
### Description of the issue

AI: The Somnium Files, at specific moments, will crash the emulator due to an unimplemented texture format. It seems like it is supported by MoltenVK, but I could be wrong. This could be likely due to the very old macOS build of Ryujinx for Apple Silicon...

This issue does not seem to occur on latest Ryujinx with Intel Xe Graphics on Vulkan (Fedora 38), though the performance is terrible compared to Apple Silicon.

```
00:02:55.217 |E| GUI.RenderThread Application : Unhandled exception caught: System.ArgumentException: "B8G8R8A8Unorm" is not a supported depth or stencil format.
   at Ryujinx.Graphics.Vulkan.TextureStorage.CreateAliasedColorForDepthStorageUnsafe(Format format) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/TextureStorage.cs:line 176
   at Ryujinx.Graphics.Vulkan.TextureView.CopyToImpl(CommandBufferScoped cbs, TextureView dst, Extents2D srcRegion, Extents2D dstRegion, Boolean linearFilter) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/TextureView.cs:line 292
   at Ryujinx.Graphics.Vulkan.TextureView.CopyTo(ITexture destination, Extents2D srcRegion, Extents2D dstRegion, Boolean linearFilter) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/TextureView.cs:line 286
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_21(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 101
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 107
   at Ryujinx.Ava.AppHost.RenderLoop() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Ava/AppHost.cs:line 860
   at System.Threading.Thread.StartCallback()
```

### Reproduction steps

[Here to download my save files for AI: The Somnium Files (necessary to reproduce)](https://s3.helene.moe/shared/ryujinx-report-savedata-2023-05-01.zip). Important spoilers ahead!

The above file is an archive of the save data for the game (the entire bis/user folder, but this should not contain any save data except for this game). AI: The Somnium Files has the ID `0000000000000004`, if the save meta is not necessary (which it probably isn't).

To reproduce the crash, load the game, load the first save file (not the autosave), and the game should crash immediately after showing a sequence of events through a floating flowchart. This may not happen every time, and also happens with texture recompression enabled or flushed shader caches.

### Log file

[Ryujinx_ 1.1.0-macos1_2023-04-30_20-39-58.log](https://github.com/Ryujinx/Ryujinx/files/11366111/Ryujinx_.1.1.0-macos1_2023-04-30_20-39-58.log)

### OS

macOS Ventura 13.3.1

### Ryujinx version

1.1.0-macos1

### Game version

1.0.1

### CPU

Apple M1 (MacBook Air)

### GPU

Apple M1 (8 cores)

### RAM

16GB

### Additional context?

I am willing to try if this issue is still present in the latest commit on the `master` branch, but I have yet to compile it for Apple Silicon.

**Comment by gdkchan** [comment]
This is an invalid texture copy (you can't copy depth to color textures). #4723 is supposed to prevent those cases from happening.

**Comment by lnchan** [comment]
I have tried reproducing on a build based on the `master` branch with your changes cherry-picked, and it seems to have fixed the problem. Thank you!
