### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Linad1666** [Ryujinx/Ryujinx#4754]
### Description of the issue

I decided to play monster hunter generation. Before that, everything worked, but today I got this error.
![sMJ3PAWdToc](https://user-images.githubusercontent.com/132306490/235534801-09558c43-8896-443a-a2e0-f8316895ffc1.jpg)

### Reproduction steps

The fact is that I didn't conjure anything like that and certainly didn't rummage through the settings. I just started the program, and then the game. after launching, a malfunction popped up in the command line and a black screen appeared on the emulator

### Log file

00:00:00.002 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.021 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.022 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.023 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.023 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.024 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.029 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.041 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.042 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.042 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.042 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.042 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.043 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.044 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.044 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.044 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.051 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0-ldn2.4
00:00:00.057 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.057 |N| Application Print: CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz ; 4 logical
00:00:00.058 |N| Application Print: RAM: Total 8130 MB ; Available 2208 MB
00:00:00.060 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.060 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.109 |I| Gpu : Backend Threading (Auto): True
00:00:00.444 |N| Application LoadApplication: Using Firmware Version: 14.0.0
00:00:00.444 |I| Application LoadApplication: Loading as NSP.
00:00:00.509 |I| ModLoader QueryContentsDir: Searching mods for Title 0100770008DD8000
00:00:00.528 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.542 |I| Loader LoadExeFs: Loading rtld...
00:00:00.644 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.644 |I| Loader LoadExeFs: Loading main...
00:00:00.983 |I| Loader PrintRoSectionInfo: main:
    Module: D:\ev1738_ts\Rabbit\buildout\MasterReleaseNXNX32\output\Rabbit_RoApplicationMTFMasterReleaseNX.nss
    SDK Libraries: SDK MW+Nintendo+NEX-4_4_0-AGQ
                   SDK MW+Nintendo+NEX_UT-4_4_0
                   SDK MW+Nintendo+NEX_MM-4_4_0
                   SDK MW+Nintendo+NEX_DS-4_4_0
                   SDK MW+Nintendo+PiaCommon-5_2_15
                   SDK MW+Nintendo+Pia-5_2_15
                   SDK MW+Nintendo+PiaInet-5_2_15
                   SDK MW+Nintendo+PiaLocal-5_2_15
                   SDK MW+Nintendo+PiaSession-5_2_15
                   SDK MW+Nintendo+PiaTransport-5_2_15
                   SDK MW+Nintendo+NintendoSDK_libcurl-4_4_2-Release
00:00:00.983 |I| Loader LoadExeFs: Loading subsdk0...
00:00:01.060 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-4_4_2-Release
00:00:01.060 |I| Loader LoadExeFs: Loading sdk...
00:00:01.171 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 4.4.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-4_4_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-4_4_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-4_4_2-Release
00:00:01.268 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.930 |I| Ptc Load: Loaded Translation Cache (size: 39966959 bytes, translated functions: 63614).
00:00:01.947 |I| Ptc Load: Loaded Profiling Info (size: 200003 bytes, profiled functions: 60424).
00:00:02.194 |I| Loader LoadNsos: Loading image 0 at 0x0000000000200000...
00:00:02.198 |I| Loader LoadNsos: Loading image 1 at 0x0000000000204000...
00:00:02.218 |I| Loader LoadNsos: Loading image 2 at 0x000000000234b000...
00:00:02.221 |I| Loader LoadNsos: Loading image 3 at 0x0000000002919000...
00:00:02.232 |I| ModLoader LoadCheats: Build ids found for title 0100770008DD8000:
    E74A8D1013372A3A1088AB5458807FB7F87925D1000000000000000000000000
    FB08F1D20FD1204FE7070672777F869B00000000000000000000000000000000
    C2774FA4CACE9ECC6A712BFC839214C19515F36E000000000000000000000000
    CB8E7F9A74A4A854FF013489ECC1E8B0DEF23A75000000000000000000000000
00:00:02.238 |I| ModLoader LoadCheats: Installing cheat '<60 FPS Cheat>'
00:00:02.255 |I| Loader LoadNca: Application Loaded: MONSTER HUNTER GENERATIONS ULTIMATE v1.4.0 [0100770008dd8000] [32-bit]
00:00:02.256 |I| HLE.TamperMachine TamperMachine TamperRunner: TamperMachine thread running
00:00:02.266 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:02.466 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:02.699 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (4.6.0 NVIDIA 531.61)
00:00:02.760 |E| GPU.MainThread Application : Unhandled exception caught: System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheCollection.EnsureArchiveUpToDate()
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheCollection.FlushToArchive()
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheCollection.Load()
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheCollection..ctor(String baseCacheDirectory, CacheHashType hashType, CacheGraphicsApi graphicsApi, String shaderProvider, String cacheName, UInt64 version)
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheManager..ctor(CacheGraphicsApi graphicsApi, CacheHashType hashType, String shaderProvider, String titleId, UInt64 shaderCodeGenVersion)
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.Initialize()
   at Ryujinx.Graphics.Gpu.GpuContext.InitializeShaderCache()
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception. System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheCollection.EnsureArchiveUpToDate()
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheCollection.FlushToArchive()
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheCollection.Load()
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheCollection..ctor(String baseCacheDirectory, CacheHashType hashType, CacheGraphicsApi graphicsApi, String shaderProvider, String cacheName, UInt64 version)
   at Ryujinx.Graphics.Gpu.Shader.Cache.CacheManager..ctor(CacheGraphicsApi graphicsApi, CacheHashType hashType, String shaderProvider, String titleId, UInt64 shaderCodeGenVersion)
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.Initialize()
   at Ryujinx.Graphics.Gpu.GpuContext.InitializeShaderCache()
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### OS

Windows 10 

### Ryujinx version

14.0.0

### Game version

1.4.0

### CPU

intel core i5 4460

### GPU

msi gtx 1050ti 4gb

### RAM

8gb

### List of applied mods

![image](https://user-images.githubusercontent.com/132306490/235535740-c28d07d2-5c26-4b69-a8d9-3a0c3d85425c.png)
![image](https://user-images.githubusercontent.com/132306490/235535772-729b5a14-47bb-4324-861e-d28b648be2ca.png)

**Comment by OldManKain** [comment]
Does it work without the mod?  Also please join us in our Discord  https://discord.gg/ryujinx for troubleshooting issues.
