### ISSUE TITLE
[Bug] Only on vulkan. Random crashes when loading new stuff ErrorDeviceLost

### ISSUE THREAD

**Issue by frankwalter1301** [Ryujinx/Ryujinx#4764]
### Description of the issue

In the games I tried I randomly get a crash when I enter in a new map and it starts laggging a lot. For example when I travel to a new world in super mario odyssey or loading a new circuit in super mario kart 8 deluxe. It does not happen always, It seems to me it happens when it is too heavy. It is not consistent because if I restart the game it will work, but maybe it will crash in another place. It happens only on vulkan.

I have a nvidia rtx 3070, 8gb ram ddr3 and amd fx 8 core. it works pretty well when it does not crash, with 40-60 fps.

This is the error log.
`00:01:00.485 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 215
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\SyncManager.cs:line 46
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_4(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 62
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399
   at System.Threading.Thread.StartCallback()`

### Reproduction steps

It does not seem consistent.

### Log file

riujinx deleted it. aI'm trying reproducing it.

### OS

windows 11

### Ryujinx version

last

### List of applied mods

none

**Comment by riperiperi** [comment]
Does it crash or doesn't it? It can't both crash and run slowly. The last part could just be because you're running an amd fx cpu, none of which are fast enough to get 60fps on every stage in SMO.

**Comment by frankwalter1301** [comment]
it runs very good. Then in a particular scene it fastly become increasingly lagging and then it crash. I dont think it is the cpu. Because when I restart the game it does not lag at all (and do not crash) even in the same scene and the problem disappear using opengl.

**Comment by frankwalter1301** [comment]
I updated the drivers and now the FPS are a lot more stable on 60FPS. Maybe with this version the engine resets are managed in a correct way. Anyway I'll update the issue.

**Comment by riperiperi** [comment]
It's probably host imported memory misbehaving again. I'll need to add something to disable it for older nvidia drivers.

**Comment by frankwalter1301** [comment]
everything work perfectly! This emulator works perfectly. Your work is amazing!
