### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zzb16888** [Ryujinx/Ryujinx#4826]
### Description of the issue

00:02:24.356 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 470322 bytes, profiled functions: 136214).
00:02:54.351 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 470460 bytes, profiled functions: 136252).
00:02:59.186 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 96
 UserId: 00000000000000010000000000000000
 Room: death
 Report: {
    "PlayTime": 2507,
    "ReleaseVersion": 1296,
    "PlayDataUniqueID": 1471819124,
    "Victim": "Enemy_Zonau_Robot_Junior",
    "VictimBaseProcId": 530,
    "Affiliation": "EnemyZonau",
    "DeathReason": "LifeDepleted",
    "SubDeathReason": "LifeDepleted_Normal",
    "DeathLocation_X": 86.81357,
    "DeathLocation_Y": 1497.9873,
    "DeathLocation_Z": 1528.0016,
    "MurderSuspect": "Player",
    "MurderSuspectBaseProcId": 329,
    "MurderSuspectAction": "BasicAttack",
    "MurderSuspectSubAction": "Drawn",
    "MurderWeapon": "Weapon_Sword_021",
    "CurrentSceneHash": 562925626,
    "system_report_tag": 2175206328
}

00:03:18.343 |E| GPU.MainThread Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000015F8CAD100.
00:03:18.381 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in /Users/zbz/Ryujinx/src/Ryujinx.Memory/MemoryBlock.cs:line 441
   at Ryujinx.Cpu.Jit.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in /Users/zbz/Ryujinx/src/Ryujinx.Cpu/Jit/MemoryManager.cs:line 506
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetComputeShader(GpuChannel channel, GpuChannelPoolState poolState, GpuChannelComputeState computeState, UInt64 gpuVa) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs:line 206
   at Ryujinx.Graphics.Gpu.Engine.Compute.ComputeClass.SendSignalingPcasB(Int32 argument) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs:line 207
   at Ryujinx.Ava.AppHost.<RenderLoop>b__98_1() in /Users/zbz/Ryujinx/src/Ryujinx.Ava/AppHost.cs:line 873
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass52_0.<RunLoop>b__0() in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 108
   at System.Threading.Thread.StartCallback()

### Reproduction steps

00:02:24.356 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 470322 bytes, profiled functions: 136214).
00:02:54.351 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 470460 bytes, profiled functions: 136252).
00:02:59.186 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 96
 UserId: 00000000000000010000000000000000
 Room: death
 Report: {
    "PlayTime": 2507,
    "ReleaseVersion": 1296,
    "PlayDataUniqueID": 1471819124,
    "Victim": "Enemy_Zonau_Robot_Junior",
    "VictimBaseProcId": 530,
    "Affiliation": "EnemyZonau",
    "DeathReason": "LifeDepleted",
    "SubDeathReason": "LifeDepleted_Normal",
    "DeathLocation_X": 86.81357,
    "DeathLocation_Y": 1497.9873,
    "DeathLocation_Z": 1528.0016,
    "MurderSuspect": "Player",
    "MurderSuspectBaseProcId": 329,
    "MurderSuspectAction": "BasicAttack",
    "MurderSuspectSubAction": "Drawn",
    "MurderWeapon": "Weapon_Sword_021",
    "CurrentSceneHash": 562925626,
    "system_report_tag": 2175206328
}

00:03:18.343 |E| GPU.MainThread Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000015F8CAD100.
00:03:18.381 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in /Users/zbz/Ryujinx/src/Ryujinx.Memory/MemoryBlock.cs:line 441
   at Ryujinx.Cpu.Jit.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in /Users/zbz/Ryujinx/src/Ryujinx.Cpu/Jit/MemoryManager.cs:line 506
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetComputeShader(GpuChannel channel, GpuChannelPoolState poolState, GpuChannelComputeState computeState, UInt64 gpuVa) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs:line 206
   at Ryujinx.Graphics.Gpu.Engine.Compute.ComputeClass.SendSignalingPcasB(Int32 argument) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs:line 207
   at Ryujinx.Ava.AppHost.<RenderLoop>b__98_1() in /Users/zbz/Ryujinx/src/Ryujinx.Ava/AppHost.cs:line 873
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass52_0.<RunLoop>b__0() in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 108
   at System.Threading.Thread.StartCallback()

### Log file

00:02:24.356 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 470322 bytes, profiled functions: 136214).
00:02:54.351 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 470460 bytes, profiled functions: 136252).
00:02:59.186 |I| HLE.OsThread.16 ServicePrepo ProcessPlayReport: 
PlayReport log:
 Kind: Normal
 Pid: 96
 UserId: 00000000000000010000000000000000
 Room: death
 Report: {
    "PlayTime": 2507,
    "ReleaseVersion": 1296,
    "PlayDataUniqueID": 1471819124,
    "Victim": "Enemy_Zonau_Robot_Junior",
    "VictimBaseProcId": 530,
    "Affiliation": "EnemyZonau",
    "DeathReason": "LifeDepleted",
    "SubDeathReason": "LifeDepleted_Normal",
    "DeathLocation_X": 86.81357,
    "DeathLocation_Y": 1497.9873,
    "DeathLocation_Z": 1528.0016,
    "MurderSuspect": "Player",
    "MurderSuspectBaseProcId": 329,
    "MurderSuspectAction": "BasicAttack",
    "MurderSuspectSubAction": "Drawn",
    "MurderWeapon": "Weapon_Sword_021",
    "CurrentSceneHash": 562925626,
    "system_report_tag": 2175206328
}

00:03:18.343 |E| GPU.MainThread Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000015F8CAD100.
00:03:18.381 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in /Users/zbz/Ryujinx/src/Ryujinx.Memory/MemoryBlock.cs:line 441
   at Ryujinx.Cpu.Jit.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in /Users/zbz/Ryujinx/src/Ryujinx.Cpu/Jit/MemoryManager.cs:line 506
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetComputeShader(GpuChannel channel, GpuChannelPoolState poolState, GpuChannelComputeState computeState, UInt64 gpuVa) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs:line 206
   at Ryujinx.Graphics.Gpu.Engine.Compute.ComputeClass.SendSignalingPcasB(Int32 argument) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs:line 207
   at Ryujinx.Ava.AppHost.<RenderLoop>b__98_1() in /Users/zbz/Ryujinx/src/Ryujinx.Ava/AppHost.cs:line 873
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass52_0.<RunLoop>b__0() in /Users/zbz/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 108
   at System.Threading.Thread.StartCallback()

### OS

mac

### Ryujinx version

1.1.1.0

**Comment by gdkchan** [comment]
Please do not open issues about leaked games.
