### ISSUE TITLE
[Bug] InvalidMemoryRegionException causes crash

### ISSUE THREAD

**Issue by sean5446** [Ryujinx/Ryujinx#4855]
### Description of the issue

While playing Zelda, Ryujinx crashes. Usually when encountering an enemy or attackable animal. 

### Reproduction steps

Seems to usually happen when encountering an enemy or attackable animal while playing Zelda. 

### Log file

```
00:00:00.043 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.047 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.048 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.048 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.049 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.050 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.050 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1B81
00:00:00.051 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.051 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.051 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.053 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.061 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.061 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.061 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.061 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.061 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.061 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.061 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.061 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.062 |I| Configuration LogValueChange: AudioBackend set to: SoundIo
00:00:00.062 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.062 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.062 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.062 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.062 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.066 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.767
00:00:00.070 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.070 |N| Application Print: CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz ; 16 logical
00:00:00.071 |N| Application Print: RAM: Total 65471 MiB ; Available 53404 MiB
00:00:00.074 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.074 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.059 |I| Gpu : Backend Threading (Auto): True
00:00:00.558 |N| Application LoadApplication: Using Firmware Version: 16.0.2
00:00:00.558 |I| Application LoadApplication: Loading as XCI.
```

First time encounter:
```
00:10:38.751 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0x000000160415D100, size=0x0000000000003F60
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 138
   at Ryujinx.Graphics.Gpu.Engine.Compute.ComputeClass.SendSignalingPcasB(Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Compute\ComputeClass.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 207
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__78_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 449
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass52_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108
```

Second time:
```
02:10:39.905 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 486911 bytes, profiled functions: 141394).
02:10:57.048 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0x000000163EC22100, size=0x0000000000004710
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 138
   at Ryujinx.Graphics.Gpu.Engine.Compute.ComputeClass.SendSignalingPcasB(Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Compute\ComputeClass.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 207
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__78_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 449
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass52_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108
   at System.Threading.Thread.StartCallback()
```

### OS

Windows 11 

### Ryujinx version

1.1.767

### Game version

1.0.0

### CPU

i9-9900k

### GPU

NVIDIA GTX 1070

### RAM

64GB

**Comment by gdkchan** [comment]
Please do not open issues for leaked games.
