### ISSUE TITLE
[Bug] Crash on Zelda Breath of the wild after game save load

### ISSUE THREAD

**Issue by Astrojoinl** [Ryujinx/Ryujinx#4856]
### Description of the issue

After a game save load, the application closes

### Reproduction steps

Open the game, load last save, and get error

### Log file

00:00:57.511 |E| HLE.GuestThread.26 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:57.553 |E| HLE.GuestThread.26 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266

### OS

windows 10 64 bits

### Ryujinx version

1.1.768

### Game version

1.6.0

### CPU

Ryzen 5 3600

### GPU

NVIDIA RTX 4070ti

### RAM

24GB

### List of applied mods

None

**Comment by OldManKain** [comment]
Please post the full log we can't help with just snippits.

**Comment by Squall-Leonhart** [comment]
Same output as #4838

**Comment by Astrojoinl** [comment]
this is the full log: 
[Ryujinx_1.1.766_2023-05-07_23-33-03.log](https://github.com/Ryujinx/Ryujinx/files/11423480/Ryujinx_1.1.766_2023-05-07_23-33-03.log)

The Ryujinx 1.1.735 doesnt have the error

**Comment by AcK77** [comment]
What if you remove all installed cheats ?
