### ISSUE TITLE
[Bug] Crash Playing SuperSmashBros 

### ISSUE THREAD

**Issue by madutra** [Ryujinx/Ryujinx#4881]
### Description of the issue

Its crashing when playing the game Super Smash Bros, i'm running on a 3060Ti Gddr6x and Ryzen 3700x, i'm using Vulkan as well, it shouldn't be happening with my configs. I'm going to put the end of the error down here. 

at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.b__5_4(Span1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 62 at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131 at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108 at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399 at System.Threading.Thread.StartCallback()

Thank you guys for the attention!

### Reproduction steps

Just playing adventure mode on super Smash bros, sometime it will happen. 

### Log file

at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.b__5_4(Span1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 62 at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131 at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108 at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399 at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

last

### Game version

13.0.1

### CPU

ryzen 3700x

### GPU

nvidia 3060 ti gdrr6x

### RAM

32gb

### List of applied mods

every mod available.

**Comment by MetrosexualGarbodor** [comment]
Closing as there's not anywhere near enough information, the only log posted is half an error

**Comment by madutra** [comment]
Following instructions, i'm putting the log of the error

[Ryujinx_1.1.799_2023-05-14_14-02-21.log](https://github.com/Ryujinx/Ryujinx/files/11472557/Ryujinx_1.1.799_2023-05-14_14-02-21.log)
