### ISSUE TITLE
[Bug] Unable to run, reporting this error GLib.GException

### ISSUE THREAD

**Issue by iischajn** [Ryujinx/Ryujinx#4943]
### Description of the issue

00:00:01.639 |E| Application : Unhandled exception caught: GLib.GException: Unrecognized image file format
   at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
   at Gdk.PixbufLoader.Write(Byte[] bytes, UInt32 count)
   at Gdk.PixbufLoader.LoadFromStream(Stream input)
   at Gdk.PixbufLoader.InitFromAssemblyResource(Assembly assembly, String resource)
   at Gdk.PixbufLoader..ctor(Assembly assembly, String resource)
   at Gdk.Pixbuf..ctor(Assembly assembly, String resource)
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 159
   at Ryujinx.Ui.MainWindow..ctor() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 148
   at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 264

### Reproduction steps

click Ryujinx.exe

### Log file

[Ryujinx_1.1.799_2023-05-14_18-03-37.log](https://github.com/Ryujinx/Ryujinx/files/11471622/Ryujinx_1.1.799_2023-05-14_18-03-37.log)

### OS

windows10

### Ryujinx version

1.1.799

**Comment by MutantAura** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
