### ISSUE TITLE
[Bug] When TOTK start, Ryujinx always be crashed.

### ISSUE THREAD

**Issue by Ande0401** [Ryujinx/Ryujinx#4959]
### Description of the issue

1.1.800 ava ryujinx can't play totk on my windows computer.Everytime I open totk ,the console will appearing yellow and red codes ,but I don't know their meaning.Here is the crash codes.

### Reproduction steps

Just open 1.1.0 TOTK on 1.1.800 AVA Ryujinx(Firmware 16.0.3  keys 16.0.2) will be flashback,and the console shows yellow codes then red codes and crashed.
![issue 2023-05-15 173142](https://github.com/Ryujinx/Ryujinx/assets/133645969/2fa75e8f-b30e-4429-a31e-9ef9791b0bfe)

### Log file

00:00:21.686 |W| HLE.GuestThread.21 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.23 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.24 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.28 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.25 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.36 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.26 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.30 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.52 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.29 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.62 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.31 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.33 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.32 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.34 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.38 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.35 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.37 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.41 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.42 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.43 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.54 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.55 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.51 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.59 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.53 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.60 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.57 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.58 KernelSvc : WaitForAddress() = TerminationRequested
00:00:21.686 |W| HLE.GuestThread.61 KernelSvc : WaitForAddress() = TerminationRequested
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1878
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3569
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266
[Ryujinx_1.1.800_2023-05-15_17-31-07.log](https://github.com/Ryujinx/Ryujinx/files/11476462/Ryujinx_1.1.800_2023-05-15_17-31-07.log)

### OS

Windows 11

### Ryujinx version

Ava 1.1.800

### Game version

TOTK 1.1.0

### CPU

i5 10400F

### GPU

Nvidia GTX 1660

### RAM

16GB

### List of applied mods

None Mod also be crashed.

### Additional context?

On recently version,this crash always hapenned,I don't know how to fix this ,but I see a few onlline users can play TOTK well on 1.1.800 version, and also some user can't play like me. So ,can this bug fix in future?

**Comment by MutantAura** [comment]
GitHub is not for support queries, please join the discord: https://discord.gg/ryujinx
Thanks.

**Comment by existancewhy** [comment]
amogus
