### ISSUE TITLE
[Bug] Can not load Zelda Tears of the Kingdom on Mac M1 Max

### ISSUE THREAD

**Issue by beginor** [Ryujinx/Ryujinx#4963]
### Description of the issue

Can not load Zelda TOTK on Mac M1 Max, always crash. I have tried both totk 1.0.0 and 1.1.0.

### Reproduction steps

Just double click the game in game list.

### Log file

```
00:00:00.034 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.036 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.036 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.036 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.037 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.037 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.037 |I| Configuration LogValueChange: PreferredGpu set to: 0x106B_0xD0303EF
00:00:00.038 |I| Configuration LogValueChange: AntiAliasing set to: Fxaa
00:00:00.038 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.038 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.042 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.799
00:00:00.045 |N| Application Print: Operating System: Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 (Arm64)
00:00:00.045 |N| Application Print: CPU: Apple M1 Max ; 10 logical
00:00:00.045 |N| Application Print: RAM: Total 65536 MiB ; Available 36960 MiB
00:00:00.047 |N| Application PrintSystemInfo: Logs Enabled: Error, Guest
00:00:00.047 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.485 |N| Application LoadGuestApplication: Using Firmware Version: 16.0.2
00:00:00.959 |E| .NET ThreadPool Worker [mvk-info] MoltenVK version 1.2.0, supporting Vulkan version 1.2.231.
00:00:00.959 |E| .NET ThreadPool Worker 	The following 83 Vulkan extensions are supported:
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_16bit_storage v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_8bit_storage v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_bind_memory2 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_buffer_device_address v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_create_renderpass2 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_dedicated_allocation v3
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_depth_stencil_resolve v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_descriptor_update_template v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_device_group v4
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_device_group_creation v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_driver_properties v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_dynamic_rendering v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_external_fence v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_external_fence_capabilities v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_external_memory v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_external_memory_capabilities v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_external_semaphore v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_external_semaphore_capabilities v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_fragment_shader_barycentric v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_get_memory_requirements2 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_get_physical_device_properties2 v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_get_surface_capabilities2 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_imageless_framebuffer v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_image_format_list v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_maintenance1 v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_maintenance2 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_maintenance3 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_multiview v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_portability_subset v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_push_descriptor v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_relaxed_block_layout v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_sampler_mirror_clamp_to_edge v3
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_sampler_ycbcr_conversion v14
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_separate_depth_stencil_layouts v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_shader_draw_parameters v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_shader_float_controls v4
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_shader_float16_int8 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_shader_subgroup_extended_types v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_spirv_1_4 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_storage_buffer_storage_class v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_surface v25
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_swapchain v70
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_swapchain_mutable_format v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_timeline_semaphore v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_uniform_buffer_standard_layout v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_KHR_variable_pointers v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_buffer_device_address v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_debug_marker v4
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_debug_report v10
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_debug_utils v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_descriptor_indexing v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_fragment_shader_interlock v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_hdr_metadata v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_host_query_reset v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_image_robustness v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_inline_uniform_block v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_memory_budget v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_metal_objects v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_metal_surface v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_post_depth_coverage v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_private_data v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_robustness2 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_sample_locations v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_scalar_block_layout v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_separate_stencil_usage v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_shader_stencil_export v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_shader_viewport_index_layer v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_subgroup_size_control v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_swapchain_colorspace v4
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_texel_buffer_alignment v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_texture_compression_astc_hdr v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_EXT_vertex_attribute_divisor v3
00:00:00.959 |E| .NET ThreadPool Worker 		VK_AMD_gpu_shader_half_float v2
00:00:00.959 |E| .NET ThreadPool Worker 		VK_AMD_negative_viewport_height v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_AMD_shader_image_load_store_lod v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_AMD_shader_trinary_minmax v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_IMG_format_pvrtc v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_INTEL_shader_integer_functions2 v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_GOOGLE_display_timing v1
00:00:00.959 |E| .NET ThreadPool Worker 		VK_MVK_macos_surface v3
00:00:00.960 |E| .NET ThreadPool Worker 		VK_MVK_moltenvk v36
00:00:00.960 |E| .NET ThreadPool Worker 		VK_NV_fragment_shader_barycentric v1
00:00:00.960 |E| .NET ThreadPool Worker 		VK_NV_glsl_shader v1
00:00:00.960 |E| .NET ThreadPool Worker [mvk-info] GPU device:
00:00:00.960 |E| .NET ThreadPool Worker 		model: Apple M1 Max
00:00:00.960 |E| .NET ThreadPool Worker 		type: Integrated
00:00:00.960 |E| .NET ThreadPool Worker 		vendorID: 0x106b
00:00:00.960 |E| .NET ThreadPool Worker 		deviceID: 0xd0303ef
00:00:00.960 |E| .NET ThreadPool Worker 		pipelineCacheUUID: 260BAD42-0D03-03EF-0000-000000000000
00:00:00.960 |E| .NET ThreadPool Worker 	supports the following Metal Versions, GPU's and Feature Sets:
00:00:00.960 |E| .NET ThreadPool Worker 		Metal Shading Language 2.4
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Apple 7
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Apple 6
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Apple 5
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Apple 4
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Apple 3
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Apple 2
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Apple 1
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Mac 2
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Mac 1
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Common 3
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Common 2
00:00:00.960 |E| .NET ThreadPool Worker 		GPU Family Common 1
00:00:00.960 |E| .NET ThreadPool Worker 		macOS GPU Family 2 v1
00:00:00.960 |E| .NET ThreadPool Worker 		macOS GPU Family 1 v4
00:00:00.960 |E| .NET ThreadPool Worker 		macOS GPU Family 1 v3
00:00:00.960 |E| .NET ThreadPool Worker 		macOS GPU Family 1 v2
00:00:00.960 |E| .NET ThreadPool Worker 		macOS GPU Family 1 v1
00:00:00.960 |E| .NET ThreadPool Worker [mvk-info] Created VkInstance for Vulkan version 1.2.0, as requested by app, with the following 3 Vulkan extensions enabled:
00:00:00.960 |E| .NET ThreadPool Worker 		VK_KHR_surface v25
00:00:00.960 |E| .NET ThreadPool Worker 		VK_EXT_debug_utils v2
00:00:00.960 |E| .NET ThreadPool Worker 		VK_EXT_metal_surface v1
00:00:00.977 |E| .NET ThreadPool Worker [mvk-info] Vulkan semaphores using Metal implicit guarantees within a single queue.
00:00:00.978 |E| .NET ThreadPool Worker [mvk-info] Created VkDevice to run on GPU Apple M1 Max with the following 9 Vulkan extensions enabled:
00:00:00.978 |E| .NET ThreadPool Worker 		VK_KHR_portability_subset v1
00:00:00.978 |E| .NET ThreadPool Worker 		VK_KHR_push_descriptor v2
00:00:00.978 |E| .NET ThreadPool Worker 		VK_KHR_shader_float16_int8 v1
00:00:00.978 |E| .NET ThreadPool Worker 		VK_KHR_swapchain v70
00:00:00.978 |E| .NET ThreadPool Worker 		VK_EXT_descriptor_indexing v2
00:00:00.978 |E| .NET ThreadPool Worker 		VK_EXT_fragment_shader_interlock v1
00:00:00.978 |E| .NET ThreadPool Worker 		VK_EXT_robustness2 v1
00:00:00.978 |E| .NET ThreadPool Worker 		VK_EXT_shader_stencil_export v1
00:00:00.978 |E| .NET ThreadPool Worker 		VK_EXT_subgroup_size_control v2
00:00:01.022 |E| .NET ThreadPool Worker [mvk-info] Created 3 swapchain images with initial size (1512, 846) and contents scale 1.0 for screen DELL U2421E.
00:00:01.023 |N| GUI.RenderThread Gpu PrintGpuInformation: Apple Apple M1 Max (Vulkan v1.2.231, Driver v0.2.2008)
00:00:05.967 |E| HLE.GuestThread.27 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000001593890000.
00:00:05.970 |E| HLE.GuestThread.21 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000001593890000.
00:00:05.991 |E| HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 277
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 212
00:00:05.991 |E| HLE.GuestThread.27 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 277
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 212

```

### OS

macOS 13.3.1 (a)

### Ryujinx version

1.1.799

### Game version

1.0.0, 1.1.0

### CPU

Apple M1 MAX

### GPU

Apple M1 MAX

### RAM

64GB

**Comment by MutantAura** [comment]
GitHub is not for support queries, please join the discord: https://discord.gg/ryujinx
Thanks.
