### ISSUE TITLE
[Bug] TotK crashes after most recent update

### ISSUE THREAD

**Issue by NAlexH2** [Ryujinx/Ryujinx#4980]
### Description of the issue

After the most recent update, I had to re-install Ryujinx because it decided to delete itself (not the first time this has happened so not an issue for me to re-download etc.) but once I start up TotK I get a nasty stack trace referencing a directory that doesn't exist.

### Reproduction steps

- Download most recent RJ release
- Initialize everything and start completely fresh (deleting appdata folder)
- Start TotK
- Crash

### Log file

```
00:00:00.038 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.041 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.042 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.042 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.043 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.043 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.044 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2204
00:00:00.044 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
00:00:00.045 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.045 |I| Configuration LogValueChange: ScalingFilterLevel set to: 100
00:00:00.046 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.054 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.054 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.054 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.054 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.054 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.054 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.054 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.055 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.055 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.055 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.055 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.058 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.800
00:00:00.061 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.061 |N| Application Print: CPU: AMD Ryzen 9 5900X 12-Core Processor ; 24 logical
00:00:00.062 |N| Application Print: RAM: Total 130993 MiB ; Available 111363 MiB
00:00:00.064 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.065 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.091 |I| Gpu : Backend Threading (Auto): True
00:00:00.333 |N| Application LoadApplication: Using Firmware Version: 15.0.1
00:00:00.333 |I| Application LoadApplication: Loading as XCI.
00:00:00.360 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.361 |I| ModLoader AddModsFromDirectory: Found mod '<0100f2c0115b6000 ExeFs>' [E]
00:00:00.361 |I| ModLoader AddModsFromDirectory: Found mod '<0100f2c0115b6000 ExeFs>' [E]
00:00:00.362 |I| ModLoader QueryContentsDir: Searching mods for Title 0100F2C0115B6000
00:00:00.364 |I| Loader Load: Loading rtld...
00:00:00.370 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.370 |I| Loader Load: Loading main...
00:00:00.654 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\EX-King\App\Rom\NX64\Product_Optimize\code\EX-King.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Vfx2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d2-15_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Meshoptimizer_For_MeshCodec-0_15_0-Release
                   SDK MW+Microsoft+Havok_Cloth-2022_1
                   SDK MW+Microsoft+Havok_Animation-2022_1
                   SDK MW+Microsoft+Havok_AI-2022_1
00:00:00.654 |I| Loader Load: Loading subsdk0...
00:00:00.677 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-15_3_1-Release
00:00:00.677 |I| Loader Load: Loading sdk...
00:00:00.727 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 15.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-15_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-15_3_1-Release
00:00:00.734 |I| ModLoader ApplyProgramPatches: Matching IPSwitch patch '1.1.0.pchtxt' in '<0100f2c0115b6000 ExeFs>' bid=D5AD6AC71EF53E3E52417C1B81DBC9B4142AA3B3
00:00:00.736 |I| ModLoader Parse: IPSwitch:    print_values 0x90eac4 <= 41008052
00:00:00.736 |I| ModLoader Parse: IPSwitch:    print_values 0xebd258 <= 41008052
00:00:00.736 |I| ModLoader Parse: IPSwitch:    print_values 0x90ea90 <= 55008052
00:00:00.736 |I| ModLoader Parse: IPSwitch:    print_values 0x90eb38 <= 55008052
00:00:00.737 |I| ModLoader Parse: IPSwitch:    print_values 0x19bf204 <= 1f2003d5
00:00:00.737 |I| ModLoader Parse: IPSwitch:    print_values 0x19ca768 <= 1f2003d5
00:00:00.738 |I| ModLoader ApplyProgramPatches: Matching IPSwitch patch '1.1.0.pchtxt' in '<0100f2c0115b6000 ExeFs>' bid=D5AD6AC71EF53E3E52417C1B81DBC9B4142AA3B3
00:00:00.738 |I| ModLoader Parse: IPSwitch:    print_values 0xe555f4 <= E00313AA
00:00:00.742 |I| ModLoader Patch: Patching address offset 90e990 <= 55 00 80 52 len=4
00:00:00.742 |I| ModLoader Patch: Patching address offset 90e9c4 <= 41 00 80 52 len=4
00:00:00.742 |I| ModLoader Patch: Patching address offset 90ea38 <= 55 00 80 52 len=4
00:00:00.742 |I| ModLoader Patch: Patching address offset e554f4 <= E0 03 13 AA len=4
00:00:00.742 |I| ModLoader Patch: Patching address offset ebd158 <= 41 00 80 52 len=4
00:00:00.742 |I| ModLoader Patch: Patching address offset 19bf104 <= 1F 20 03 D5 len=4
00:00:00.742 |I| ModLoader Patch: Patching address offset 19ca668 <= 1F 20 03 D5 len=4
00:00:00.837 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.848 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:00.849 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:00.876 |I| Loader LoadNsos: Loading image 2 at 0x000000000c731000...
00:00:00.879 |I| Loader LoadNsos: Loading image 3 at 0x000000000cdda000...
00:00:00.887 |I| ModLoader LoadCheats: Build ids found for title 0100F2C0115B6000:
    7501ABFE55FA41CFFEB46BD619BDCBF45B9CAE3A000000000000000000000000
    D5AD6AC71EF53E3E52417C1B81DBC9B4142AA3B3000000000000000000000000
    A6BB7C6FFA9673769FA74ED3D7B054191F25D29C000000000000000000000000
    B9046C31EB5D31271BE970FE732D38DF49C6AA21000000000000000000000000
00:00:00.889 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.971 |I| Loader Start: Application Loaded: The Legend of Zelda: Tears of the Kingdom v1.1.0 [0100f2c0115b6000] [64-bit]
00:00:01.587 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.599 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.972 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3090 (Vulkan v1.3.236, Driver v531.79.0.0)
00:00:01.980 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:01.986 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.475 |S| HLE.OsThread.22 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.585 |S| HLE.OsThread.22 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.589 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.593 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.674 |S| HLE.OsThread.22 ServicePctl Initialize: Stubbed. 
00:00:05.488 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:05.488 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:05.489 |S| HLE.OsThread.22 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:05.489 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:05.490 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:05.720 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:05.744 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:05.746 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:05.841 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:05.879 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.927 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:05.928 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:05.929 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:05.931 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:05.931 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:05.931 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:05.932 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:05.936 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:06.028 |S| HLE.OsThread.22 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72324500776771584}
00:00:06.033 |S| HLE.OsThread.22 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:06.035 |S| HLE.OsThread.22 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:06.075 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:06.078 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:06.079 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:07.589 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.589 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:09.745 |S| HLE.OsThread.9 ServiceHid ActivateMouse: Stubbed. {appletResourceUserId: 1}
00:00:09.748 |S| HLE.OsThread.9 ServiceHid ActivateKeyboard: Stubbed. {appletResourceUserId: 1}
00:00:10.684 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:10.687 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV11
00:00:10.717 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:10.718 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:10.726 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:10.795 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:10.832 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:10.834 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:11.896 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:11.896 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:11.915 |I| HLE.OsThread.22 ServiceAm SetTerminateResult: Result = 0x0007d402 (ResultFsTargetNotFound (2002-1002)).
00:00:12.163 |I| HLE.GuestThread.40 Cpu PrintGuestStackTrace: Guest stack trace:
Process: The Legend of Zelda: Tears of the Kingdom, PID: 98
   0x000000000ce69d80	sdk:0x8fd80	
   0x000000000ce69e48	sdk:0x8fe48	
   0x000000000ce69f28	sdk:0x8ff28	
   0x000000000ceaeeec	sdk:0xd4eec	
   0x0000000008e59cb4	main:0xe55cb4	
   0x0000000008e59518	main:0xe55518	
   0x0000000008e593a8	main:0xe553a8	
   0x000000000a84b68c	main:0x284768c	
   0x000000000a34dee8	main:0x2349ee8	
   0x000000000aa37638	main:0x2a33638	
   0x000000000cf04518	sdk:0x12a518	
   0x000000000cf0a2f4	sdk:0x1302f4	
   0x0000000000000000


00:00:12.169 |I| HLE.GuestThread.40 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x00000049cfeb1ba8 (SP:-0x01d8)
	X[02]:	0x0000000000000004
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000100000000
	X[09]:	0x000000000cdda000 (sdk:0x0000)	=> 
	X[10]:	0xfefefefefefefeff
	X[11]:	0x0000008000000000
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000002
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000002
	X[16]:	0x000000000ce6b700 (sdk:0x91700)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x000000000dae0520
	X[18]:	0x0000000000000000
	X[19]:	0x00000049cfeb1ba8 (SP:-0x01d8)
	X[20]:	0x0000000000000000
	X[21]:	0x000000000d88a757
	X[22]:	0x000000000d88a757
	X[23]:	0x0000000000000000
	X[24]:	0x000000000d88a757
	X[25]:	0x00000049cfeb1b50 (SP:-0x0180)
	X[26]:	0x000000000d88a757
	X[27]:	0x000000000ce69e48 (sdk:0x8fe48)	=> 
	X[28]:	0x0000000000000000
	FP:	0x00000049cfeb19d0 (SP)
	LR:	0x000000000ce6b718 (sdk:0x91718)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x00000049cfeb19d0 (SP)
	PC:	0x000000000cf32494 (sdk:0x158494)	=> 


00:00:12.177 |W| HLE.GuestThread.21 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.24 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.36 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.23 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.25 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.28 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.26 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.52 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.29 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.30 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.62 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.31 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.33 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.32 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.38 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.34 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.35 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.41 KernelSvc : SendSyncRequest() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.37 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.42 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.54 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.43 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:12.177 |W| HLE.GuestThread.55 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:12.178 |W| HLE.GuestThread.59 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.178 |W| HLE.GuestThread.51 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.178 |W| HLE.GuestThread.60 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.178 |W| HLE.GuestThread.53 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.178 |W| HLE.GuestThread.57 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.178 |W| HLE.GuestThread.58 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.178 |W| HLE.GuestThread.61 KernelSvc : WaitForAddress() = TerminationRequested
00:00:12.222 |E| HLE.GuestThread.40 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1878
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3569
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266
```

### OS

Windows 11

### Ryujinx version

1.1.800

### Game version

1.1.0

### CPU

Ryzen 5900x

### GPU

RTX 3090

### RAM

128Gb

### List of applied mods

30FPS
disableFSRAndFullResShadows

**Comment by NAlexH2** [comment]
Resolved itself.
