### ISSUE TITLE
[Bug] GUI.RenderThread Application : Unhandled exception caught: System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.

### ISSUE THREAD

**Issue by yogithesymbian** [Ryujinx/Ryujinx#5005]
### Description of the issue

```
GUI.RenderThread Application : Unhandled exception caught: System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
```

<details>
  <summary>Full Log [1]</summary>
 
  ### Log
  ```js
00:00:00.055 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.058 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.058 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.059 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.059 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.060 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.060 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.062 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.069 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.069 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.069 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.069 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.069 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.069 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.069 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.069 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.070 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.070 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.070 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.070 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.070 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.070 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.074 |N| Application PrintSystemInfo: Ryujinx Version:  1.1.0-macos1
00:00:00.078 |N| Application Print: Operating System: Darwin 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103 (Arm64)
00:00:00.078 |N| Application Print: CPU: Apple M1 ; 8 logical
00:00:00.079 |N| Application Print: RAM: Total 8192 MiB ; Available Unknown
00:00:00.081 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.081 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:02.907 |W| .NET ThreadPool Worker Application LoadApplications: Failed to fetch the public games JSON from the API. Player and game count in the game list will be unavailable.
00:01:28.548 |I| Configuration LogValueChange: PreferredGpu set to: 
00:01:35.911 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.162 |I| Gpu : Backend Threading (Auto): True
00:00:00.394 |N| Application LoadGuestApplication: Using Firmware Version: 16.0.1
00:00:00.394 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.426 |I| ModLoader QueryContentsDir: Searching mods for Title 010019401051C000
00:00:00.428 |I| ModLoader QueryContentsDir: Searching mods for Title 010019401051C000
00:00:00.432 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.438 |I| Loader LoadExeFs: Loading rtld...
00:00:00.466 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.466 |I| Loader LoadExeFs: Loading main...
00:00:00.557 |I| Loader PrintRoSectionInfo: main:
    Module: C:\Users\admin\AppData\Local\Temp\tmpbj7tr85b\strikers.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Font-13_3_0-Release
                   SDK MW+Nintendo+NEX_MM-4_6_17
                   SDK MW+Nintendo+NEX-4_6_17-appntmg
                   SDK MW+Nintendo+NintendoSDK_libcurl-13_3_0-Release
                   SDK MW+Nintendo+NintendoSDK_libz-13_3_0-Release
                   SDK MW+Nintendo+NEX_R2-4_6_17
                   SDK MW+Nintendo+NEX_RK-4_6_17
                   SDK MW+Nintendo+NEX_SS-4_6_17
                   SDK MW+Nintendo+NEX_UT-4_6_17
                   SDK MW+Nintendo+PiaTransport-5_38_0
                   SDK MW+Nintendo+Pia-5_38_0_59024
                   SDK MW+Nintendo+PiaCommon-5_38_0
                   SDK MW+Nintendo+PiaSession-5_38_0
                   SDK MW+Nintendo+PiaLocal-5_38_0
                   SDK MW+Nintendo+PiaNex-5_38_0-forNEX-4_6_6
                   SDK MW+Nintendo+NEX_CO-4_6_17
                   SDK MW+Nintendo+NintendoSDK_gfx-13_3_0-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-13_3_0-Release
00:00:00.557 |I| Loader LoadExeFs: Loading subsdk0...
00:00:00.581 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-13_3_0-Release
00:00:00.581 |I| Loader LoadExeFs: Loading sdk...
00:00:00.636 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdkEn
    FS SDK Version: 13.3.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-13_3_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-13_3_0-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-13_3_0-Release
00:00:00.666 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.707 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:00.708 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:00.712 |I| Loader LoadNsos: Loading image 2 at 0x000000000955a000...
00:00:00.713 |I| Loader LoadNsos: Loading image 3 at 0x0000000009bf4000...
00:00:00.719 |I| ModLoader LoadCheats: Build ids found for title 010019401051C000:
    567CDD4C5251494C5CD70822E3CCC740C190C2B2000000000000000000000000
    2E90F0815B1F92A1CBF013B3F4D358F41D729F4E000000000000000000000000
    7E9F31F59E001CF5D9B546FFB233F4805C952F4B000000000000000000000000
    7F7710633C020A32018C8715523EBEE7C87BEA88000000000000000000000000
00:00:00.719 |I| Loader LoadNca: Application Loaded: Mario Strikers: Battle League v1.3.2 [010019401051c000] [64-bit]
00:00:00.741 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:00.752 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:00.784 |E| GUI.RenderThread Application : Unhandled exception caught: System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetNormalizedCodeBasePath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetDepsJsonPath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly, IDependencyContextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.LoadDefault()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.DependencyModel.DependencyContext.get_Default()
   at Silk.NET.Core.Loader.DefaultPathResolver.TryLocateNativeAssetInRuntimesFolder(String name, String baseFolder, String& result)
   at Silk.NET.Core.Loader.DefaultPathResolver.CoreEnumeratePossibleLibraryLoadTargets(String name, Boolean noLinuxTraverse)+MoveNext()
   at Silk.NET.Core.Loader.LibraryLoader.LoadWithResolver(String name, PathResolver pathResolver)
   at Silk.NET.Core.Loader.LibraryLoader.TryLoadNativeLibrary(String[] names, PathResolver pathResolver, IntPtr& result)
   at Silk.NET.Core.Loader.LibraryLoader.TryLoadNativeLibrary(String name, PathResolver pathResolver, IntPtr& result)
   at Silk.NET.Core.Loader.LibraryLoader.LoadNativeLibrary(String name, PathResolver pathResolver)
   at Silk.NET.Core.Loader.UnmanagedLibrary..ctor(String name, LibraryLoader loader, PathResolver pathResolver)
   at Silk.NET.Core.Loader.UnmanagedLibrary..ctor(String name)
   at Silk.NET.Core.Contexts.DefaultNativeContext..ctor(String name)
   at Silk.NET.Vulkan.Vk.CreateDefaultContext(String n)
   at Silk.NET.Vulkan.Vk.GetApi()
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.SetupContext(GraphicsDebugLevel logLevel) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs:line 264
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.Initialize(GraphicsDebugLevel logLevel) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs:line 575
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.Initialize(GraphicsDebugLevel logLevel) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 352
   at Ryujinx.Ava.AppHost.RenderLoop() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Ava/AppHost.cs:line 851
   at System.Threading.Thread.StartCallback()

  ```
</details>

### Reproduction steps

1. backup my game into external hard drive exFat
2. delete my game on internal harddrive
3. restore my game into internal harddrive
4. then this happend

### Log file

<details>
<summary>Full Log [2]</summary>

```js
00:00:00.055 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.058 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.058 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.058 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.059 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.060 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.060 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.061 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.069 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.069 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.069 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.069 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.069 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.069 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.069 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.069 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.070 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.070 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.070 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.070 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.070 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.070 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.074 |N| Application PrintSystemInfo: Ryujinx Version:  1.1.0-macos1
00:00:00.078 |N| Application Print: Operating System: Darwin 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103 (Arm64)
00:00:00.078 |N| Application Print: CPU: Apple M1 ; 8 logical
00:00:00.079 |N| Application Print: RAM: Total 8192 MiB ; Available Unknown
00:00:00.081 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.081 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:02.911 |W| .NET ThreadPool Worker Application LoadApplications: Failed to fetch the public games JSON from the API. Player and game count in the game list will be unavailable.

```
<details>

### OS

Macbook Pro M1

### Ryujinx version

1.1.0-macos1

### Game version

1.0.0

### CPU

-

### GPU

-

### RAM

8GB

### List of applied mods

nothing

### Additional context?

the game auto crash after restore.

**Comment by AcK77** [comment]
Based on log, no GPU seems to be selected (for a strange reason), could you try again with a default config file.
The exception seems to happen at the Silk.NET side.
I close this issue since reset config file should fix it. (Can be reopen in future if a real issue still exists)
