### ISSUE TITLE
[Bug] HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!

### ISSUE THREAD

**Issue by TheRealZeagan** [Ryujinx/Ryujinx#5035]
### Description of the issue

Crashes while playing Pokemon Scarlet often.
Nothing specific in particular causes the crash. 
Crashes while running around and also in cut scenes.
The crashes seems random.
Anything from 5-45ish minutes of playtime.

### Reproduction steps

Cant force reproduce it other than just playing and then randomly it crashes.

### Log file

00:00:00.021 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.024 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.024 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.024 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.024 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.025 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.025 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2684
00:00:00.025 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
00:00:00.026 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.026 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.026 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.027 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.027 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.027 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.027 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.027 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.027 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.027 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.027 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.027 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.027 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.027 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.027 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.027 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.027 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.029 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.809
00:00:00.031 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.031 |N| Application Print: CPU: 13th Gen Intel(R) Core(TM) i9-13900K ; 32 logical
00:00:00.032 |N| Application Print: RAM: Total 65305 MiB ; Available 58350 MiB
00:00:00.033 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error
00:00:00.033 |N| Application PrintSystemInfo: Launch Mode: Custom Path C:\Games\Pokemon Scarlet-Violet\Data
00:00:00.663 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:00.181 |N| Application LoadApplication: Using Firmware Version: 15.0.1
00:00:02.011 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 4090 (Vulkan v1.3.236, Driver v531.79.0.0)
00:12:14.430 |E| HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1878
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3485
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266
   at System.Threading.Thread.StartCallback()

### OS

Windows 10

### Ryujinx version

1.1.809

### Game version

1.0.1

### CPU

I9-13900K

### GPU

NVIDIA RTX 4090

### RAM

64GB

### List of applied mods

60fps from theboy181

### Additional context?

I sometimes get this warning in cmd then it crashes.
(Ryujinx:6568): GLib-GObject-WARNING **: 17:20:50.453: g_object_remove_toggle_ref: couldn't find toggle ref 00007ff677583224(0000020dc17c1300)

**Comment by MetrosexualGarbodor** [comment]
Please use discord for support queries: https://discord.gg/ryujinx
Thanks.
