### ISSUE TITLE
[Bug] Totk doesn`t start after double click on it (always)

### ISSUE THREAD

**Issue by michhess** [Ryujinx/Ryujinx#5050]
### Description of the issue

Recently I installed Ryujinx to play Totk, but when i truing launch it, game doesn`t start. Firmware and keys version 16.0.2.

### Reproduction steps

1. Launch Ryujinx and then TotK 1.1.1
2. Double click on the game (totk)
3. It doesn`t start

### Log file

00:00:00.001 |I| Gpu : Backend Threading (Auto): True
00:00:00.093 |N| Application LoadApplication: Using Firmware Version: 16.0.2
00:00:00.094 |I| Application LoadApplication: Loading as NSP.
00:00:00.095 |E| Loader Load: No ExeFS found in NCA
00:00:00.095 |W| Loader GetNpdm: NPDM file not found, using default values!
Marshaling row-activated signal
00:00:00.145 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Number of allowed tracked regions exceeded.
   at Ryujinx.Cpu.MemoryEhMeilleure..ctor(MemoryBlock addressSpace, MemoryBlock addressSpaceMirror, MemoryTracking tracking) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\MemoryEhMeilleure.cs:line 31
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped..ctor(MemoryBlock backingMemory, UInt64 addressSpaceSize, Boolean unsafeMode, InvalidAccessHandler invalidAccessHandler) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 92
   at Ryujinx.HLE.HOS.ArmProcessContextFactory.Create(KernelContext context, UInt64 pid, UInt64 addressSpaceSize, InvalidAccessHandler invalidAccessHandler, Boolean for64Bit) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContextFactory.cs:line 75
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.InitializeMemoryManager(ProcessCreationFlags flags) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1077
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.Initialize(ProcessCreationInfo creationInfo, ReadOnlySpan`1 capabilities, KResourceLimit resourceLimit, MemoryRegion memRegion, IProcessContextFactory contextFactory, ThreadStart customThreadStart)
   at Ryujinx.HLE.Loaders.Processes.ProcessLoaderHelper.LoadNsos(Switch device, KernelContext context, MetaLoader metaLoader, BlitStruct`1 applicationControlProperties, Boolean diskCacheEnabled, Boolean allowCodeMemoryForJit, String name, UInt64 programId, Byte[] arguments, IExecutable[] executables) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Loaders\Processes\ProcessLoaderHelper.cs:line 363
   at Ryujinx.HLE.Loaders.Processes.Extensions.FileSystemExtensions.Load(IFileSystem exeFs, Switch device, BlitStruct`1 nacpData, MetaLoader metaLoader, Boolean isHomebrew) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Loaders\Processes\Extensions\FileSystemExtensions.cs:line 115
   at Ryujinx.HLE.Loaders.Processes.ProcessLoader.LoadNsp(String path) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Loaders\Processes\ProcessLoader.cs:line 79
   at Ryujinx.HLE.Switch.LoadNsp(String nspFile) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Switch.cs:line 85
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean isFirmwareTitle) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 792
   at Ryujinx.Ui.MainWindow.RunApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 842
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 1179
   at InvokeStub_RowActivatedHandler.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### OS

Windows 10

### Ryujinx version

1.1.815

### Game version

1.1.1

### CPU

Intel Core i3 10100F

### GPU

Nvidia GTX 1660 super

### RAM

16GB

**Comment by michhess** [comment]
Where can I find your Discord?
