### ISSUE TITLE
Pokemon Scarlet and Pokemon Violet both crashing on picking profile [apple apple silicon ] [Bug]

### ISSUE THREAD

**Issue by d9j** [Ryujinx/Ryujinx#5068]
### Description of the issue

starting game. choosing language. 
navigates the profile picker and crashing ,.
 .tested last 10 releases of Ryujinx.

game version 1.0.0 ~ 1.3.0

### Reproduction steps

starting game. choosing language. 
navigates the profile picker and crashing ,.
 .tested last 10 releases of Ryujinx.

### Log file

00:00:02.644 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:00:03.106 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:03.219 |E| .NET ThreadPool Worker [mvk-info] Created 3 swapchain images with initial size (2184, 1230) and contents scale 2.0 for screen Built-in Retina Display.
00:00:06.385 |E| .NET ThreadPool Worker 2023-05-23 11:09:02.006 Ryujinx[31730:732391] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
00:00:07.909 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:08.041 |E| GUI.RenderThread Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Vulkan.BufferState.BindTransformFeedbackBuffer(VulkanRenderer gd, CommandBufferScoped cbs, UInt32 binding) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/BufferState.cs:line 28
   at Ryujinx.Graphics.Vulkan.PipelineBase.SetTransformFeedbackBuffers(ReadOnlySpan`1 buffers) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Vulkan/PipelineBase.cs:line 1122
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CommitGraphicsBindings() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Gpu/Memory/BufferManager.cs:line 555
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount, Int32 drawFirstVertex, Int32 drawVertexCount) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs:line 120
   at Macro(MacroJitContext, IDeviceState, Int32)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs:line 207
   at Ryujinx.Ava.AppHost.<RenderLoop>b__99_1() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/AppHost.cs:line 900
   at Ryujinx.Graphics.GAL.IRenderer.RunLoop(Action gpuLoop) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Graphics.GAL/IRenderer.cs:line 57
   at Ryujinx.Ava.AppHost.RenderLoop() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/AppHost.cs:line 883
   at System.Threading.Thread.StartCallback()

### OS

macos 13.2.1 (22D68)

### Ryujinx version

1.1.818

### CPU

m1 max 64 gb

**Comment by d9j** [comment]
attached log

[log.log](https://github.com/Ryujinx/Ryujinx/files/11539586/log.log)
