### ISSUE TITLE
[Bug] Open Story of Seasons: Friends of Mineral Town with error.

### ISSUE THREAD

**Issue by xuecangqiuye** [Ryujinx/Ryujinx#5116]
### Description of the issue

Open Story of Seasons: Friends of Mineral Town with error.

### Reproduction steps

it happens when loading the game.
![image](https://github.com/Ryujinx/Ryujinx/assets/39404875/22ff65a9-9dd0-4013-97bf-6136bae59871)

### Log file

```log
00:00:00.046 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.052 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.053 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.053 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.054 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.055 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.056 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1C20
00:00:00.057 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.059 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.059 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.076 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.824
00:00:00.082 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.082 |N| Application Print: CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz ; 12 logical
00:00:00.083 |N| Application Print: RAM: Total 16243 MiB ; Available 10979 MiB
00:00:00.086 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.086 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.513 |N| Application LoadApplication: Using Firmware Version: 16.0.3
00:00:02.930 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1060 (Vulkan v1.3.236, Driver v531.79.0.0)
00:00:06.381 |W| HLE.GuestThread.21 KernelSvc : MapSharedMemory() = InvalidMemoryRegion
00:00:07.061 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:00:14.946 |W| HLE.GuestThread.21 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:14.946 |W| HLE.GuestThread.23 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:14.946 |W| HLE.GuestThread.26 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:14.946 |W| HLE.GuestThread.24 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:14.946 |W| HLE.GuestThread.27 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:14.946 |W| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:14.946 |W| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:14.946 |W| HLE.GuestThread.34 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:14.946 |W| HLE.GuestThread.30 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:15.042 |E| HLE.GuestThread.25 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1878
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3392
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266

```

### OS

win11

### Ryujinx version

1.1.824

### Game version

1.1.6

### CPU

i7-8750h

### GPU

gtx1060

### RAM

16

### List of applied mods

no mods

### Additional context?

Firmware
16.0.3

**Comment by AcK77** [comment]
Please enable default logging and send a new file, because your log file is incomplete and it's useless as-is. Thanks.

**Comment by TCSRekts** [comment]
How did you fix it?
