### ISSUE TITLE
[Bug] Opening >3 instances of Ryujinx at the same time crashes the emulator (due to being used by another process)

### ISSUE THREAD

**Issue by yell0wsuit** [Ryujinx/Ryujinx#5172]
### Description of the issue

Per discussion in PR #5163, users may open many instances to play multiplayer games (or something idk). But the problem is that opening more than 3 instances of Ryujinx at the same time will crash the 4th instance.
This is because the emulator tries to overwrite the oldest log, but that oldest log is being used by the previous instance. Also the maximum log file written is only 3, so there's that.

### Reproduction steps

Open 3 instances of Ryujinx, then open the 4th one.
Alternately, open Ryujinx quickly 3 times in a row will cause the issue.

### Log file

```
00:00:00.090 |E| Application : Unhandled exception caught: System.IO.IOException: The process cannot access the file 'E:\Nintendo emulators\ryujinx\Logs\Ryujinx_1.1.842_2023-05-31_11-17-37.log' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String)
   at System.IO.FileInfo.Delete()
   at Ryujinx.Common.Logging.FileLogTarget..ctor(String path, String name, FileShare fileShare, FileMode fileMode) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\Logging\Targets\FileLogTarget.cs:line 29
   at Ryujinx.Common.Logging.FileLogTarget..ctor(String path, String name) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\Logging\Targets\FileLogTarget.cs:line 16
   at Ryujinx.Ui.Common.Configuration.LoggerModule.ReloadFileLogger(Object sender, ReactiveEventArgs`1 e) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\Configuration\LoggerModule.cs:line 82
   at Ryujinx.Common.ReactiveObject`1.set_Value(T value) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\ReactiveObject.cs:line 39
   at Ryujinx.Ui.Common.Configuration.ConfigurationState.Load(ConfigurationFileFormat configurationFileFormat, String configurationFilePath) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\Configuration\ConfigurationState.cs:line 1400
   at Ryujinx.Ava.Program.ReloadConfig() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ava\Program.cs:line 158
   at Ryujinx.Ava.Program.Initialize(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ava\Program.cs:line 104
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ava\Program.cs:line 47
```

### OS

Windows 11

### Ryujinx version

1.1.842

### Additional context?

Proposed solutions:
- If the log file limit is reached, temporarily write more logs (depending on the number of Ryujinx instances), then clear the old ones. (Sound like bad idea)
- Write more logs by default. 10 seems to be OK, but also allow users to adjust the maximum log file written.
  - Also implement a setting to allow users to automatically clear old logs for specified date.

**Comment by githubawn** [comment]
a current workaround is using https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#portable-mode
