### ISSUE TITLE
[Bug]TOTK crash

### ISSUE THREAD

**Issue by 2584191127** [Ryujinx/Ryujinx#5256]
### Description of the issue

When I was playing TOTK, this pop-up window suddenly appeared, and then Ryujinx was forced to quit
![批注 2023-06-07 095503](https://github.com/Ryujinx/Ryujinx/assets/78305714/91b7ea2d-6280-4e0b-b710-c863949b76fe)

### Reproduction steps

I don't know how to reproduce it, but this issue has happened twice.

### Log file

[Ryujinx_1.1.866_2023-06-06_20-15-22.log](https://github.com/Ryujinx/Ryujinx/files/11671908/Ryujinx_1.1.866_2023-06-06_20-15-22.log)

### OS

win10 22H2

### Ryujinx version

1.1.866

### Game version

1.1.2

### CPU

AMD Ryzen 7 4800U with Radeon Graphics

### GPU

AMD Radeon(TM) Graphics

### RAM

16GB

**Comment by 2584191127** [comment]
[Ryujinx_1.1.869_2023-06-08_12-17-16.log](https://github.com/Ryujinx/Ryujinx/files/11684037/Ryujinx_1.1.869_2023-06-08_12-17-16.log)
this issue hanpens again

**Comment by AcK77** [comment]
Is this happen without mods ?

**Comment by LoneBoco** [comment]
Google suggests it may be a computer issue like a failing hard drive.  It is an exception being thrown outside of the CLR so you can't try/catch it.  That's why the error is not being shown in the logs.  Try looking at your computer's event viewer to see if anything is being recorded there.

**Comment by 2584191127** [comment]
> Is this happen without mods ?

I have the following mods
https://gamebanana.com/mods/445703
https://gamebanana.com/mods/446768
https://gamebanana.com/mods/443165
https://gamebanana.com/mods/443354
https://gamebanana.com/mods/446865
https://gamebanana.com/mods/444723
https://gamebanana.com/mods/447510

**Comment by 2584191127** [comment]
> Google suggests it may be a computer issue like a failing hard drive. It is an exception being thrown outside of the CLR so you can't try/catch it. That's why the error is not being shown in the logs. Try looking at your computer's event viewer to see if anything is being recorded there.

OK, I will try finding it

**Comment by 2584191127** [comment]
> Google suggests it may be a computer issue like a failing hard drive. It is an exception being thrown outside of the CLR so you can't try/catch it. That's why the error is not being shown in the logs. Try looking at your computer's event viewer to see if anything is being recorded there.

Is it this？

日志名称:          Application
来源:            .NET Runtime
日期:            2023/6/10 20:34:24
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-2ON9CLD
描述:
Application: Ryujinx.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Ryujinx.Graphics.Vulkan.PersistentFlushBuffer.GetTextureData(Ryujinx.Graphics.Vulkan.CommandBufferPool, Ryujinx.Graphics.Vulkan.TextureView, Int32)
   at Ryujinx.Graphics.Vulkan.TextureView.GetData()
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper+<>c.<InitLookup>b__5_1[[Ryujinx.Graphics.GAL.Multithreading.Commands.Texture.TextureGetDataCommand, Ryujinx.Graphics.GAL, Version=1.1.881.0, Culture=neutral, PublicKeyToken=null]](System.Span`1<Byte>, Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer, Ryujinx.Graphics.GAL.IRenderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(System.Threading.ThreadStart)
   at Ryujinx.Ui.RendererWidgetBase.Render()

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-06-10T12:34:24.5312480Z" />
    <EventRecordID>3845</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-2ON9CLD</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Ryujinx.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Ryujinx.Graphics.Vulkan.PersistentFlushBuffer.GetTextureData(Ryujinx.Graphics.Vulkan.CommandBufferPool, Ryujinx.Graphics.Vulkan.TextureView, Int32)
   at Ryujinx.Graphics.Vulkan.TextureView.GetData()
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper+&lt;&gt;c.&lt;InitLookup&gt;b__5_1[[Ryujinx.Graphics.GAL.Multithreading.Commands.Texture.TextureGetDataCommand, Ryujinx.Graphics.GAL, Version=1.1.881.0, Culture=neutral, PublicKeyToken=null]](System.Span`1&lt;Byte&gt;, Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer, Ryujinx.Graphics.GAL.IRenderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(System.Threading.ThreadStart)
   at Ryujinx.Ui.RendererWidgetBase.Render()
</Data>
  </EventData>
</Event>

**Comment by MutantAura** [comment]
Can you update your AMD GPU drivers: https://www.amd.com/en/support (they are extremely out of date), and try without the mods.

**Comment by 2584191127** [comment]
> Can you update your AMD GPU drivers: https://www.amd.com/en/support (they are extremely out of date), and try without the mods.

After installing the AMD driver, the textures in the game disappeared, I forgot to take a screenshot, because I immediately uninstalled the driver

**Comment by 2584191127** [comment]
> Can you update your AMD GPU drivers: https://www.amd.com/en/support (they are extremely out of date), and try without the mods.

I update the drivers again, and the game became like this
![image](https://github.com/Ryujinx/Ryujinx/assets/78305714/0a1469c5-0095-47c1-8a8f-8420da72e778)
