### ISSUE TITLE
[Bug] 00:00:00.003 |E| Application : Unhandled exception caught: System.IO.DirectoryNotFoundException: Source directory not found:

### ISSUE THREAD

**Issue by chuliang007** [Ryujinx/Ryujinx#5259]
### Description of the issue

I downloaded and installed the Ryujinx test version 1.1.869 on M1 Max, and encountered the error below that I couldn't open the app: 

Last login: Thu Jun  8 01:53:35 on console
/Applications/Ryujinx.app/Contents/MacOS/Ryujinx ; exit;                        
(base) chuliangguo@chuliangs-MacBook-Pro ~ % /Applications/Ryujinx.app/Contents/MacOS/Ryujinx ; exit;
00:00:00.003 |E| Application : Unhandled exception caught: System.IO.DirectoryNotFoundException: Source directory not found: /Users/chuliangguo/.config/Ryujinx
   at Ryujinx.Common.Configuration.AppDataManager.CopyDirectory(String sourceDir, String destinationDir) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Configuration/AppDataManager.cs:line 124
   at Ryujinx.Common.Configuration.AppDataManager.Initialize(String baseDirPath) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Configuration/AppDataManager.cs:line 101
   at Ryujinx.Ava.Program.Initialize(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/Program.cs:line 90
   at Ryujinx.Ava.Program.Main(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/Program.cs:line 47
Unhandled exception. System.IO.DirectoryNotFoundException: Source directory not found: /Users/chuliangguo/.config/Ryujinx
   at Ryujinx.Common.Configuration.AppDataManager.CopyDirectory(String sourceDir, String destinationDir) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Configuration/AppDataManager.cs:line 124
   at Ryujinx.Common.Configuration.AppDataManager.Initialize(String baseDirPath) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Configuration/AppDataManager.cs:line 101
   at Ryujinx.Ava.Program.Initialize(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/Program.cs:line 90
   at Ryujinx.Ava.Program.Main(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/Program.cs:line 47
zsh: abort      /Applications/Ryujinx.app/Contents/MacOS/Ryujinx

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

### Reproduction steps

Open Ryujinx Console

### Log file

Last login: Thu Jun  8 01:53:35 on console
/Applications/Ryujinx.app/Contents/MacOS/Ryujinx ; exit;                        
(base) chuliangguo@chuliangs-MacBook-Pro ~ % /Applications/Ryujinx.app/Contents/MacOS/Ryujinx ; exit;
00:00:00.003 |E| Application : Unhandled exception caught: System.IO.DirectoryNotFoundException: Source directory not found: /Users/chuliangguo/.config/Ryujinx
   at Ryujinx.Common.Configuration.AppDataManager.CopyDirectory(String sourceDir, String destinationDir) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Configuration/AppDataManager.cs:line 124
   at Ryujinx.Common.Configuration.AppDataManager.Initialize(String baseDirPath) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Configuration/AppDataManager.cs:line 101
   at Ryujinx.Ava.Program.Initialize(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/Program.cs:line 90
   at Ryujinx.Ava.Program.Main(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/Program.cs:line 47
Unhandled exception. System.IO.DirectoryNotFoundException: Source directory not found: /Users/chuliangguo/.config/Ryujinx
   at Ryujinx.Common.Configuration.AppDataManager.CopyDirectory(String sourceDir, String destinationDir) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Configuration/AppDataManager.cs:line 124
   at Ryujinx.Common.Configuration.AppDataManager.Initialize(String baseDirPath) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Common/Configuration/AppDataManager.cs:line 101
   at Ryujinx.Ava.Program.Initialize(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/Program.cs:line 90
   at Ryujinx.Ava.Program.Main(String[] args) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Ava/Program.cs:line 47
zsh: abort      /Applications/Ryujinx.app/Contents/MacOS/Ryujinx

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

### OS

MacOS Ventura

### Ryujinx version

1.1.869

**Comment by AcK77** [comment]
Can you delete `/Users/chuliangguo/.config/Ryujinx` symlink and try again ?

**Comment by chuliang007** [comment]
> Can you delete `/Users/chuliangguo/.config/Ryujinx` symlink and try again ?

It works. Thanks!
