### ISSUE TITLE
Unhandled Exception: System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by mtcdood** [Ryujinx/Ryujinx#531]
Upon loading Chocolate Doom homebrew
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at Ryujinx.HLE.HOS.Services.FspSrv.IStorage.Read(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\FspSrv\IStorage.cs:line 43
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 96
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 236
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by RyadaProductions** [comment]
Are you sure you have a .wad file in the same directory as the .nro? Because it is working for me in master. I get the same behaviour without a wad file

**Comment by mtcdood** [comment]
I have a .wad file in the directory. I was using 1.0.2110.

**Comment by RyadaProductions** [comment]
What is the name of your wad file? do you also have an empty `tmp` folder and both cfg files?
the wad should work if you call it doom.wad

**Comment by mtcdood** [comment]
Copying the shipped `doom1.wad` to `doom.wad` had no effect. Placing an empty directory called `tmp` where `Ryujinx.exe` was located had no effect and placing the directory where `chocolate-doom.nro` and `doom.wad` were located had no effect.

**Comment by RyadaProductions** [comment]
What is the directory you are running `chocolate-doom.nro` from? The expected location is `%AppData%\Roaming\RyuFs\sdmc` otherwise Ryujinx won't have enough permissions and it will lock up in the exact exception you are experiencing right now.

**Comment by mtcdood** [comment]
It works with the files in that location.
