### ISSUE TITLE
[Bug] |E| GPU.MainThread Application : Unhandled exception caught: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by cppfreshman** [Ryujinx/Ryujinx#5421]
### Description of the issue

When I played Persona5 Royal, sometimes Ryujinx crashed with this log.  But my edition is 1.1.1325, so I'm not sure whether it`s caused by this reason.

Here is the exception log.
|E| GPU.MainThread Application : Unhandled exception caught: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.Dispose() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 1439
   at Ryujinx.Graphics.Gpu.Image.Texture.DecrementReferenceCount() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 1531
   at Ryujinx.Graphics.Gpu.Image.Texture.DecrementReferenceCount(TexturePool pool, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 1557
   at Ryujinx.Graphics.Gpu.Image.TexturePool.InvalidateRangeImpl(UInt64 address, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 220
   at Ryujinx.Memory.Tracking.MultiRegionHandle.QueryModified(UInt64 address, UInt64 size, Action`2 modifiedAction) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MultiRegionHandle.cs:line 148
   at Ryujinx.Graphics.Gpu.Image.TexturePool.CheckModified() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 156
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings(ShaderSpecializationState specState) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 358
   at Ryujinx.Graphics.Gpu.Image.TextureManager.CommitComputeBindings(ShaderSpecializationState specState) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 382
   at Ryujinx.Graphics.Gpu.Engine.Compute.ComputeClass.SendSignalingPcasB(Int32 argument) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Compute\ComputeClass.cs:line 241
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 128
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__75_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 403
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 99
   at System.Threading.Thread.StartCallback()

### Reproduction steps

not more

### Log file

[Ryujinx_1.1.325_2023-07-01_19-54-52.log](https://github.com/Ryujinx/Ryujinx/files/11926019/Ryujinx_1.1.325_2023-07-01_19-54-52.log)

### OS

Win 11

### Ryujinx version

1.1.135

### Game version

cracked and not know

### CPU

i5-13500H

### GPU

intel iRIS Xe 80eu

### RAM

16GB

**Comment by cppfreshman** [comment]
If any grammer fault, I'll sorry for that 🍡

**Comment by GamerzHell9137** [comment]
Update Ryujinx trough the updater in the app and try again.

**Comment by MutantAura** [comment]
Please use our [Discord ](https://discord.gg/ryujinx) for general support queries in future.
Thanks.
