### ISSUE TITLE
[Bug]《Plants vs. Zombies: Battle for Neighborville 》quitting unexpected

### ISSUE THREAD

**Issue by aceandy** [Ryujinx/Ryujinx#5438]
### Description of the issue

《Plants vs. Zombies: Battle for Neighborville 》
The game cannot display properly and will automatically exit when starting to run. Please help resolve this issue. Thank you very much!

### Reproduction steps

1. Running the game (chaotic graphics display)
<img width="1226" alt="iShot2023-07-07 20 24 14" src="https://github.com/Ryujinx/Ryujinx/assets/38141640/9d595264-59cb-4ea5-9296-20d3de40906e">

2. Confirm local operation

3. Confirm User Agreement

4. Program automatically exits

```
00:00:34.177 |E| AudioRendererManager.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Server.Voice.VoiceState.FlushWaveBuffers(UInt32 waveBufferCount, Memory`1[] voiceUpdateStates, UInt32 channelCount) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Server/Voice/VoiceState.cs:line 549
   at Ryujinx.Audio.Renderer.Server.Voice.VoiceState.UpdateParametersForCommandGeneration(Memory`1[] voiceUpdateStates) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Server/Voice/VoiceState.cs:line 575
   at Ryujinx.Audio.Renderer.Server.CommandGenerator.GenerateVoices() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Server/CommandGenerator.cs:line 366
   at Ryujinx.Audio.Renderer.Server.AudioRenderSystem.GenerateCommandList(CommandList& commandList) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs:line 587
   at Ryujinx.Audio.Renderer.Server.AudioRenderSystem.SendCommands() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs:line 671
   at Ryujinx.Audio.Renderer.Server.AudioRendererManager.SendCommands() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Server/AudioRendererManager.cs:line 251
```

### Log file
[Ryujinx_1.1.952_2023-07-06_17-33-50.log](https://github.com/Ryujinx/Ryujinx/files/11966834/Ryujinx_1.1.952_2023-07-06_17-33-50.log)

**Comment by aceandy** [comment]
[Ryujinx_1.1.952_2023-07-06_17-33-50.log](https://github.com/Ryujinx/Ryujinx/files/11966823/Ryujinx_1.1.952_2023-07-06_17-33-50.log)

**Comment by AcK77** [comment]
Could you please report that at: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3437
Since it's a game specific issue, I close.
Thanks
