### ISSUE TITLE
[Bug] MMBNLC2 consistently just closes at around 1h48m of playtime

### ISSUE THREAD

**Issue by pubct** [Ryujinx/Ryujinx#5520]
### Description of the issue

Megaman Battle Network Legacy Collection Vol 2
Same error codes in all logs.
```
|E| Ryujinx.NvdecProcessor Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000100
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 137
   at Ryujinx.Graphics.Gpu.Memory.PhysicalMemory.GetSpan(UInt64 address, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\PhysicalMemory.cs:line 122
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 206
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 104
   at Ryujinx.Graphics.Nvdec.Image.SurfaceWriter.Write(MemoryManager gmm, ISurface surface, UInt32 lumaOffset, UInt32 chromaOffset) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Nvdec\Image\SurfaceWriter.cs:line 39
   at Ryujinx.Graphics.Nvdec.NvdecDevice.Decode(ApplicationId applicationId)
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\AsyncWorkQueue.cs:line 45
```
Doesn't happen with another playable-category game. (Only tested one.)

### Reproduction steps

Play the game for 1 hour and 48 minutes long.

### Log file

| Log | Game ver | GPU drv | Mod |
| - | :-: | :-: | :-: |
| [Ryujinx_1.1.955_2023-07-07_02-15-02.zip](https://github.com/Ryujinx/Ryujinx/files/12234681/Ryujinx_1.1.955_2023-07-07_02-15-02.zip) | 1.0.2 | 528.02 | Yes |
| [Ryujinx_1.1.956_2023-07-09_05-03-24.zip](https://github.com/Ryujinx/Ryujinx/files/12234690/Ryujinx_1.1.956_2023-07-09_05-03-24.zip)<br>[Ryujinx_1.1.966_2023-07-21_03-46-47.zip](https://github.com/Ryujinx/Ryujinx/files/12234695/Ryujinx_1.1.966_2023-07-21_03-46-47.zip)<br>[Ryujinx_1.1.972_2023-08-01_05-40-17.zip](https://github.com/Ryujinx/Ryujinx/files/12234699/Ryujinx_1.1.972_2023-08-01_05-40-17.zip) | 1.0.3 | 536.40 | No |
| [Ryujinx_1.1.972_2023-08-02_03-02-01.zip](https://github.com/Ryujinx/Ryujinx/files/12234674/Ryujinx_1.1.972_2023-08-02_03-02-01.zip) | 1.0.3 | 536.67 | No |

All with DLC.
All on v16.0.3 firmware.

### OS

Windows 10

### Ryujinx version

Check above

### CPU

i5-4460

### GPU

Nvidia GTX 1070 Ti

### RAM

16GB

### Additional context?

Happens even before v1.1.955, I believe. Just that I did not realize they all closes at around 1h48m.

**Comment by AcK77** [comment]
As you asked in https://github.com/Ryujinx/Ryujinx-Games-List/issues/4608 yes please report the current state in the issue of the Games Compatibility List.
Since it's a game specific issue, I close this one.
Thanks.
