### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DracosDragon** [Ryujinx/Ryujinx#5532]
### Description of the issue

Ryujinx, after updating to 1.1.1974, experiences a full crash to desktop when attempting to load the 1.0.0 version of The Legend of Zelda: Tears of the Kingdom. 

### Reproduction steps

Update to 1.1.1974 from a significantly older version that had the game, mod files, and save already installed. Then run Tears of the Kingdom.

### Log file

[Ryujinx_1.1.974_2023-08-04_20-35-36.log](https://github.com/Ryujinx/Ryujinx/files/12265403/Ryujinx_1.1.974_2023-08-04_20-35-36.log)
Relevant section from right before crash:
00:01:01.479 |E| HLE.GuestThread.21 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000150.
00:01:01.540 |E| HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\MemoryBlock.cs:line 440
   at Ryujinx.Cpu.Jit.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 505
   at Ryujinx.Cpu.Jit.MemoryManager.ReadTracked[T](UInt64 va) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 153
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 60
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264

### OS

Windows 10

### Ryujinx version

1.1.1974

### Game version

1.0.0

### CPU

AMD Ryzen 5 2600, 3.4 GHz, 6-core.

### GPU

GeForce RTX 2060 6gb

### RAM

32GB

### List of applied mods

Mods are as follows:
- A fix for over 30fps causing black screens for 1.0.0 TOTK
- A fix for cutscenes at over 30fps.
- Dynamic FPS
- NoLootBoxes
- SotAW Improvement
- VisualFixes_1008P_Chuck_totk
- VisualFixes_AnisotropicFix_totk
- VisualFixes_DisableFSR_totk
- VisualFixes_ShadowResolution_totk

### Additional context?

Issue only present for Tears of the Kingdom, as far as i can tell. Loading another game did not experience this error.

**Comment by piplup55** [comment]
visualfixes is not made for ryujinx and it's not needed remove all visualfixes and purge pptc, Right click the game > Cache Management > Queue PPTC Rebuild. If that doesn't work, open the PPTC directory and delete its contents.

**Comment by MetrosexualGarbodor** [comment]
Closing as this is not a Ryujinx issue.

**Comment by DracosDragon** [comment]
I was unaware of visualfixes being incompatiable, apologies. The issues, however, continue to persist after removal and PPTC rebuild, so i feel they are unrelated to the current issue.

**Comment by OldManKain** [comment]
Still a mod issue, remove all mods.
