### ISSUE TITLE
[Bug] Red Dead Redemption crashes loading game

### ISSUE THREAD

**Issue by xinelogit** [Ryujinx/Ryujinx#5595]
### Description of the issue

Game start correctly but crashes when trying to start the game, no saves stored, it happens with save directory empty.

### Reproduction steps

Start game.
In game menu choose regular mode to load initial cinematic. 

### Log file

Process: Red Dead Redemption, PID: 100
   0x0000000057724d80	sdk:0x8fd80	
   0x0000000057724e48	sdk:0x8fe48	
   0x0000000057724f28	sdk:0x8ff28	
   0x00000000577696a8	sdk:0xd46a8	
   0x000000000859eb0c	main:0x9ab0c	d11::SwitchSaveDataManager_c::DoLoad(d11::SaveDataParamsBase_c&, d11::IntrusivePtr_c<d11::SaveDataBuffer_c>&):0x0048
   0x0000000014ccb328

00:01:20.258 |I| HLE.GuestThread.28 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000004a11fa5788 (SP:-0x01c8)
	X[02]:	0x0000000000000004
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000100000000
	X[09]:	0x0000000057695000 (sdk:0x0000)	=> 
	X[10]:	0xfefefefefefefeff
	X[11]:	0x0000008000000000
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000002
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000002
	X[16]:	0x0000000057726700 (sdk:0x91700)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x000000005839b520
	X[18]:	0x0000000000000000
	X[19]:	0x0000004a11fa5788 (SP:-0x01c8)
	X[20]:	0x0000000000000000
	X[21]:	0x0000000058145757
	X[22]:	0x0000000058145757
	X[23]:	0x0000000000000000
	X[24]:	0x0000000058145757
	X[25]:	0x0000004a11fa5740 (SP:-0x0180)
	X[26]:	0x0000000058145757
	X[27]:	0x0000000057724e48 (sdk:0x8fe48)	=> 
	X[28]:	0x0000004a11fa59a0 (SP:-0x03e0)
	FP:	0x0000004a11fa55c0 (SP)
	LR:	0x0000000057726718 (sdk:0x91718)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x0000004a11fa55c0 (SP)
	PC:	0x00000000577ed494 (sdk:0x158494)	=> 

00:01:20.266 |W| HLE.GuestThread.23 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.26 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.25 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.37 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.27 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.33 KernelSvc : SendSyncRequest() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.38 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.45 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.35 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.30 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.31 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.40 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.47 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.32 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.44 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.46 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.39 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.43 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.42 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.50 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.266 |W| HLE.GuestThread.41 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.309 |E| HLE.GuestThread.28 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1924
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3410
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 60
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264

### OS

Windows 11

### Ryujinx version

1.1.997

### Game version

1.0.1

### CPU

Ryzen 5800x

### GPU

Nvidia RTX 4090

### RAM

32GB

### List of applied mods

None

**Comment by OldManKain** [comment]
That is a generic crash, please join us in our [Discord](https://discord.gg/ryujinx) for troubleshooting the issue.
