### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by anito9999** [Ryujinx/Ryujinx#5620]
### Description of the issue

due to some issues I had to reinstall my OS the emulator was on another drive along with the games now not only is it not detecting my games one's that were working fine before my clean install if I try and load a game manually I am getting the errors below.

00:00:00.019 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1000
00:00:00.022 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.022 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i7-12700K ; 20 logical
00:00:00.022 |N| Application Print: RAM: Total 65286 MiB ; Available 40877 MiB
00:00:00.023 |N| Application PrintSystemInfo: Logs Enabled: <None>
00:00:00.023 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.228 |N| Application LoadApplication: Using Firmware Version: 16.0.2
Marshaling activate signal
00:00:00.282 |N| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Text.Json.JsonException: '\' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '\' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader&, JsonTypeInfo, ReadStack& )
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState&, JsonReaderState&, ReadStack&, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStream[TValue](Stream, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream, JsonTypeInfo`1)
   at Ryujinx.Common.Utilities.JsonHelper.DeserializeFromFile[T](String filePath, JsonTypeInfo`1 typeInfo) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\Utilities\JsonHelper.cs:line 53
   at Ryujinx.HLE.Loaders.Processes.Extensions.PartitionFileSystemExtensions.TryLoad(PartitionFileSystem partitionFileSystem, Switch device, String path, String& errorMessage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Loaders\Processes\Extensions\PartitionFileSystemExtensions.cs:line 91
   at Ryujinx.HLE.Loaders.Processes.ProcessLoader.LoadXci(String path) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Loaders\Processes\ProcessLoader.cs:line 47
   at Ryujinx.HLE.Switch.LoadXci(String xciFile) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Switch.cs:line 77
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean isFirmwareTitle) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 840
   at Ryujinx.Ui.MainWindow.RunApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 899
   at Ryujinx.Ui.MainWindow.Load_Application_File(Object sender, EventArgs args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 1324
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### Reproduction steps

I just run the emulator and load a game. tried switching to portable mode but issue still persists.

If I try and exit the app I get this message below in red.

00:05:36.844 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey)
   at Ryujinx.HLE.Loaders.Processes.ProcessLoader.get_ActiveApplication() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Loaders\Processes\ProcessLoader.cs:line 27
   at Ryujinx.Ui.MainWindow.End() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 1119
   at Ryujinx.Ui.MainWindow.Exit_Pressed(Object sender, EventArgs args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 1371
   at InvokeStub_EventHandler.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### Log file

00:00:00.020 |I| Configuration LogValueChange: ResScale set to: 4
00:00:00.023 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.023 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.024 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.024 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.025 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.025 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2206
00:00:00.025 |I| Configuration LogValueChange: AntiAliasing set to: SmaaLow
00:00:00.026 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.026 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.027 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.031 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.031 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.031 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.032 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.032 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.032 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.032 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.032 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.032 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.032 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.032 |I| Configuration LogValueChange: AudioVolume set to: 0.8
00:00:00.032 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.032 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.032 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.033 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.034 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1000
00:00:00.037 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.037 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i7-12700K ; 20 logical
00:00:00.038 |N| Application Print: RAM: Total 65286 MiB ; Available 39711 MiB
00:00:00.039 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Stub
00:00:00.040 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.885 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: 'F:\Switch Games\Xenoblade Chronicles 2 [0100E95004038000] [v917504] (1G+1U+7D).xci' Error: System.Text.Json.JsonException: '\' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '\' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader&, JsonTypeInfo, ReadStack& )
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState&, JsonReaderState&, ReadStack&, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStream[TValue](Stream, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream, JsonTypeInfo`1)
   at Ryujinx.Common.Utilities.JsonHelper.DeserializeFromFile[T](String filePath, JsonTypeInfo`1 typeInfo) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\Utilities\JsonHelper.cs:line 53
   at Ryujinx.Ui.App.Common.ApplicationLibrary.GetGameUpdateData(VirtualFileSystem fileSystem, String titleId, Int32 programIndex, String& updatePath) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 929
   at Ryujinx.Ui.App.Common.ApplicationLibrary.IsUpdateApplied(String titleId, IFileSystem& updatedControlFs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 809
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 248
00:00:00.887 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: 'F:\Switch Games\Xenoblade Chronicles 3 [010074F013262000][v0][US](nsw2u.in).nsp' Error: System.Text.Json.JsonException: '\' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '\' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader&, JsonTypeInfo, ReadStack& )
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState&, JsonReaderState&, ReadStack&, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStream[TValue](Stream, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream, JsonTypeInfo`1)
   at Ryujinx.Common.Utilities.JsonHelper.DeserializeFromFile[T](String filePath, JsonTypeInfo`1 typeInfo) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\Utilities\JsonHelper.cs:line 53
   at Ryujinx.Ui.App.Common.ApplicationLibrary.GetGameUpdateData(VirtualFileSystem fileSystem, String titleId, Int32 programIndex, String& updatePath) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 929
   at Ryujinx.Ui.App.Common.ApplicationLibrary.IsUpdateApplied(String titleId, IFileSystem& updatedControlFs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 809
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 248
00:00:00.890 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: 'F:\Switch Games\Xenoblade Chronicles Definitive Edition [0100FF500E34A000] [v131072] (1G+1U).xci' Error: System.Text.Json.JsonException: '\' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '\' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader&, JsonTypeInfo, ReadStack& )
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState&, JsonReaderState&, ReadStack&, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStream[TValue](Stream, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream, JsonTypeInfo`1)
   at Ryujinx.Common.Utilities.JsonHelper.DeserializeFromFile[T](String filePath, JsonTypeInfo`1 typeInfo) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\Utilities\JsonHelper.cs:line 53
   at Ryujinx.Ui.App.Common.ApplicationLibrary.GetGameUpdateData(VirtualFileSystem fileSystem, String titleId, Int32 programIndex, String& updatePath) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 929
   at Ryujinx.Ui.App.Common.ApplicationLibrary.IsUpdateApplied(String titleId, IFileSystem& updatedControlFs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 809
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 248
00:00:00.891 |W| GUI.ApplicationLibraryThread Application LoadApplications: The file encountered was not of a valid type. File: 'F:\X\Red Dead Redemption v0 (01007820196A6000) (BASE).nsp' Error: System.Text.Json.JsonException: '\' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '\' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader&, JsonTypeInfo, ReadStack& )
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState&, JsonReaderState&, ReadStack&, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStream[TValue](Stream, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream, JsonTypeInfo`1)
   at Ryujinx.Common.Utilities.JsonHelper.DeserializeFromFile[T](String filePath, JsonTypeInfo`1 typeInfo) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\Utilities\JsonHelper.cs:line 53
   at Ryujinx.Ui.App.Common.ApplicationLibrary.GetGameUpdateData(VirtualFileSystem fileSystem, String titleId, Int32 programIndex, String& updatePath) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 929
   at Ryujinx.Ui.App.Common.ApplicationLibrary.IsUpdateApplied(String titleId, IFileSystem& updatedControlFs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 809
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 248

### OS

Windows 11

### Ryujinx version

1.1.1000

### Game version

1.0

### CPU

i7 12700K

### GPU

RTX3080

### RAM

64GB

**Comment by MetrosexualGarbodor** [comment]
Please use our [Discord](https://discord.gg/ryujinx) for general support queries.
Thanks.
