### ISSUE TITLE
[Bug] Ryujinx doesn't open

### ISSUE THREAD

**Issue by HutsieMats** [Ryujinx/Ryujinx#5641]
### Description of the issue

Ryujinx doesn't open, it has an error and then crashes immediately. Not an expert, so i don't know how to fix this issue. 

### Reproduction steps

I try to start up ryujinx, but it gives an error and then closes.

### Log file

[Ryujinx_1.1.1004_2023-09-02_20-05-47.log](https://github.com/Ryujinx/Ryujinx/files/12504548/Ryujinx_1.1.1004_2023-09-02_20-05-47.log)

### OS

Windows 10

### Ryujinx version

1.1.1004

### CPU

Intel i5

### RAM

8GB

### List of applied mods

None

### Additional context?

Application : Unhandled exception caught: GLib.GException: Unrecognized image file format
at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
at Gdk.PixbufLoader.Write(Byte[] bytes, UInt32 count)
at Gdk.PixbufLoader.LoadFromStream(Stream input)
at Gdk.PixbufLoader.InitFromAssemblyResource(Assembly assembly, String resource)
at Gdk.PixbufLoader..ctor(Assembly assembly, String resource)
at Gdk.Pixbuf..ctor(Assembly assembly, String resource)
at Ryujinx.Ui.MainWindow..ctor(Builder builder) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 159
at Ryujinx.Ui.MainWindow..ctor() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\MainWindow.cs:line 148
at Ryujinx.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 264

**Comment by AcK77** [comment]
Try to download the emulator again, unzip it, and if you have an antivirus, add an exception to it for Ryujinx.

**Comment by AcK77** [comment]
No more answer, I close.
