### ISSUE TITLE
[Bug] `IPurchaseEventManager.PopPurchasedProductInfo` might need some rework

### ISSUE THREAD

**Issue by makigumo** [Ryujinx/Ryujinx#5746]
### Description of the issue

The game `The Settlers: New Allies` (https://github.com/Ryujinx/Ryujinx-Games-List/issues/4681) seems to rely on different behavior of `IPurchaseEventManager.PopPurchasedProductInfo` than is currently implemented.

Currently it is writing an array and returns `ResultCode.Success`.

This results in the game going into an endless loop with a black screen on game startup.

When this is changed to return `(ResultCode)((400 << 9) | 164)` the game is progressing as expected. Writing the array may also not be required, but someone more knowledgable in RE might to have a look at it.

On Windows 11 changing the ResultCode seems to fix the issue and the game is playable.
On macOS the game is also progressing further (showing warning screen), but crashes in a different, maybe related, spot. 

### Current behavior
* Start game.
  *  Game is stuck on a black screen.

### Expected behavior:
* Start game.
  * Game progresses to warning screen and game menu.

### Log file

https://github.com/Ryujinx/Ryujinx-Games-List/issues/4681

### Crash on macOS after changing the returned ResultCode to `(ResultCode)((400 << 9) | 164)`
```log
00:00:32.435 |I| HLE.GuestThread.36 Cpu PrintGuestStackTrace: Guest stack trace:
Process: セトラーズ®：新たな仲間たち, PID: 107
   0x000000000c2293f0	main:0x3d253f0	
   0x000000000c237c0c	main:0x3d33c0c	
   0x000000000c2388c4	main:0x3d348c4	
   0x000000000856e8b4	main:0x6a8b4	
   0x000000000855b840	main:0x57840	
   0x000000000856e8b4	main:0x6a8b4	
   0x000000000856e774	main:0x6a774	
   0x0000000008560404	main:0x5c404	
   0x0000000013bed578	sdk:0x129578	
   0x0000000013bf3b54	sdk:0x12fb54	
   0x0000000000000000


00:00:32.455 |I| HLE.GuestThread.36 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x00000000148167d0
	X[02]:	0x0000000000000028
	X[03]:	0x0000000000000008
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000000
	X[09]:	0x0000000000000000
	X[10]:	0x0000000000000000
	X[11]:	0x000000004f434653
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000002
	X[14]:	0x0000000000000004
	X[15]:	0x0000000000000000
	X[16]:	0x00000000147b5bf8
	X[17]:	0x0000000013db9e70 (sdk:0x2f5e70)	=> nn::ec::detail::ShopServiceAccessServer::ToResult(nn::Result)
	X[18]:	0x0000000000000000
	X[19]:	0x00000017c5440050
	X[20]:	0x00000000138ec220
	X[21]:	0x00000000138ec238
	X[22]:	0x00000049e60fbb60 (SP:-0x00b0)
	X[23]:	0x00000049e60fbc60 (SP:-0x01b0)
	X[24]:	0x0000000000000046
	X[25]:	0x0000000000000000
	X[26]:	0x00000017c4660018
	X[27]:	0x0000000df8475800
	X[28]:	0x00000000000000c2
	FP:	0x00000049e60fbb00 (SP:-0x0050)
	LR:	0x0000000013db6e1c (sdk:0x2f2e1c)	=> nn::ec::ShopServiceAccessor::Request(nn::ec::ShopServiceAccessor::AsyncResponse*, nn::account::Uid const&, nn::ec::ShopService::Method, char const*, nn::ec::ShopServiceAccessor::PostData const&, nn::TimeSpan):0x01ac
	SP:	0x00000049e60fbab0 (SP)
	PC:	0x0000000013db9e70 (sdk:0x2f5e70)	=> nn::ec::detail::ShopServiceAccessServer::ToResult(nn::Result)


00:00:32.455 |E| HLE.GuestThread.36 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:32.522 |E| HLE.GuestThread.36 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /Volumes/Data/Develop/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in /Volumes/Data/Develop/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 212
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /Volumes/Data/Develop/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in /Volumes/Data/Develop/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 212
```

### OS

all OS

### Ryujinx version

1.0.1036

### Game version

1.0.4

**Comment by Eli0t77** [comment]
Thanks for investigating, hope it can be fixed soon
Not sure if linking the yuzu implementation is allowed or needed but __github.com/yuzu-emu/yuzu/pull/11540
