### ISSUE TITLE
Starlink Battle for Atlas crashing

### ISSUE THREAD

**Issue by MufasasBalls** [Ryujinx/Ryujinx#5748]
### Description of the issue

Out of memory when trying to play Starlink Battle for Atlas. 

### Reproduction steps

Trying to load the game past the main menu. 

### Log file

00:00:00.034 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.037 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.038 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.038 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.039 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.039 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.040 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2216
00:00:00.040 |I| Configuration LogValueChange: AntiAliasing set to: Fxaa
00:00:00.041 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.041 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.042 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.048 |I| Configuration LogValueChange: EnableMacroHLE set to: False
00:00:00.048 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.048 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.048 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.048 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.048 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.049 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.049 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.049 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.049 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.049 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.049 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.052 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1037
00:00:00.055 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.055 |N| Application Print: CPU: AMD Ryzen 9 5900X 12-Core Processor ; 24 logical
00:00:00.056 |N| Application Print: RAM: Total 32679 MiB ; Available 22582 MiB
00:00:00.058 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.058 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.679 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.687 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.713 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.718 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.747 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.772 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:01.776 |W| GUI.ApplicationLibraryThread Application LoadApplications: Last played string "Never" is invalid for current system culture, skipping (did current culture change?)
00:00:08.459 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.044 |I| Gpu : Backend Threading (Auto): True
00:00:00.258 |N| Application LoadApplication: Using Firmware Version: 16.1.0
00:00:00.258 |I| Application LoadApplication: Loading as NSP.
00:00:00.279 |I| ModLoader QueryContentsDir: Searching mods for Title 01002CC003FE6000
00:00:00.280 |I| ModLoader QueryContentsDir: Searching mods for Title 01002CC003FE6000
00:00:00.281 |I| Loader Load: Loading rtld...
00:00:00.287 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.287 |I| Loader Load: Loading main...
00:00:00.946 |I| Loader PrintRoSectionInfo: main:
    Module: Y:\code\sm_output\retail_nx_vs2017\Onward_NX64_Retail.nss
    SDK Libraries: SDK MW+Microsoft+Havok-2014_2
                   SDK MW+Microsoft+Havok_Physics-2014_2
                   SDK MW+Microsoft+Havok_AI-2014_2
                   SDK MW+Nintendo+NintendoSDK_libcurl-6_4_0-Release
00:00:00.946 |I| Loader Load: Loading sdk...
00:00:00.982 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 6.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-6_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-6_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-6_4_0-Release
00:00:01.076 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:04.076 |I| Ptc Load: Loaded Translation Cache (size: 287714130 bytes, translated functions: 204682).
00:00:04.112 |I| Ptc Load: Loaded Profiling Info (size: 559842 bytes, profiled functions: 203883).
00:00:04.121 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:04.122 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:04.204 |I| Loader LoadNsos: Loading image 2 at 0x00000000180fc000...
00:00:04.210 |I| ModLoader LoadCheats: Build ids found for title 01002CC003FE6000:
    09AA0F157B8CF44DF373510612A0452A4803B2AB000000000000000000000000
    13C816F2A273653CBCD3DE1FE7C3494100000000000000000000000000000000
    E29BE8AD6778527AA248310D0C71A8A51C4643A3000000000000000000000000
00:00:04.212 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:04.280 |I| Loader Start: Application Loaded: Starlink: Battle for Atlas™ v1.0.6 [01002cc003fe6000] [64-bit]
00:00:04.287 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:04.299 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:04.581 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3080 (Vulkan v1.3.242, Driver v537.13.0.0)
00:00:04.588 |I| GPU.MainThread Gpu LoadShaders: Loading 44 shaders from the cache...
00:00:04.691 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:07.641 |I| HLE.GuestThread.30 Ptc LoadTranslations: 203877 translated functions loaded
00:00:07.684 |I| HLE.GuestThread.30 Ptc MakeAndSaveTranslations: 0 of 6 functions translated | Thread count: 23
00:00:07.756 |I| HLE.GuestThread.30 Ptc MakeAndSaveTranslations: 6 of 6 functions translated | Thread count: 23 in 0.070958 s
00:00:07.855 |S| HLE.OsThread.31 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:07.859 |S| HLE.OsThread.31 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:07.859 |S| HLE.OsThread.31 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:07.859 |S| HLE.OsThread.31 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:07.867 |S| HLE.OsThread.31 ServicePctl Initialize: Stubbed. 
00:00:07.920 |S| HLE.OsThread.31 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72106797250273280}
00:00:07.924 |S| HLE.OsThread.31 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:07.926 |S| HLE.OsThread.31 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:07.976 |S| HLE.OsThread.5 ServiceBsd RegisterClient: Stubbed. 
00:00:07.977 |S| HLE.OsThread.5 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:07.991 |S| HLE.OsThread.31 ServiceNifm CreateRequest: Stubbed. {version: 2}
00:00:07.992 |S| HLE.OsThread.31 ServiceNifm Submit: Stubbed. 
00:00:07.992 |S| HLE.OsThread.31 ServiceNifm GetRequestState: Stubbed. 
00:00:07.992 |S| HLE.OsThread.31 ServiceNifm GetResult: Stubbed. 
00:00:08.369 |S| HLE.OsThread.31 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: True ; unknownFlag3: False}
00:00:08.369 |S| HLE.OsThread.31 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:08.369 |S| HLE.OsThread.31 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:08.369 |S| HLE.OsThread.31 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:08.416 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:08.421 |I| HLE.OsThread.31 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:08.434 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:08.446 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:08.479 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:08.479 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:08.480 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:08.480 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:08.481 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:08.481 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:08.481 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:08.490 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:08.490 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:08.490 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:08.491 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:08.494 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:08.494 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:08.494 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:08.494 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:08.494 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:08.494 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:08.495 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:08.496 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:08.538 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 2}
00:00:08.539 |I| GUI.WindowThread Hid SetupNpad: Disconnected Controller ProController from Player1
00:00:08.541 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Handheld'
00:00:08.541 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 3 Players: Player1,Player2,Handheld
00:00:08.541 |S| HLE.OsThread.9 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:08.542 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:08.542 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 107 ; appletResourceUserId: 1 ; type: ProController, Handheld}
00:00:08.544 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.544 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131076 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131076}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 6 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 6}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131331 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131331}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131332 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131332}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 262 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 262}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65799 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65799}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 139267 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.545 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 139267}
00:00:08.546 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 139268 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.546 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 139268}
00:00:08.546 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 8198 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.546 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 8198}
00:00:08.546 |S| HLE.OsThread.9 ServiceHid SetGyroscopeZeroDriftMode: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 73735 ; _gyroscopeZeroDriftMode: Tight}
00:00:08.546 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 73735}
00:00:08.546 |S| HLE.OsThread.9 ServiceHid ActivateDebugPad: Stubbed. {appletResourceUserId: 1}
00:00:08.783 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:08.797 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 2048
00:00:09.013 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:09.014 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV5
00:00:09.027 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:09.027 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:09.044 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:09.061 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:09.922 |S| HLE.OsThread.31 ServiceSsl SetInterfaceVersion: Stubbed. {interfaceVersion: 3}
00:00:10.480 |S| HLE.OsThread.31 ServiceNifm Submit: Stubbed. 
00:00:10.481 |S| HLE.OsThread.31 ServiceNifm GetRequestState: Stubbed. 
00:00:10.481 |S| HLE.OsThread.31 ServiceNifm GetResult: Stubbed. 
00:00:10.538 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...

00:01:31.650 |E| HLE.GuestThread.35 Application : Unhandled exception caught: System.OutOfMemoryException: JIT Cache exhausted.
   at ARMeilleure.Translation.Cache.JitCache.Allocate(Int32 codeSize) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Cache\JitCache.cs:line 157
   at ARMeilleure.Translation.Cache.JitCache.Map(CompiledFunction func) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Cache\JitCache.cs:line 110
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 222
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 164
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 60
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264

### OS

Windows 11

### Ryujinx version

1.1.1037

### Game version

1.0.6

### CPU

Ryzen 5900x

### GPU

RTX 3080

### RAM

32GB

### List of applied mods

None

**Comment by MufasasBalls** [comment]
I have tried enabling and disabling every option I can think of and still no work around. Has someone had this issue? Every other game I have runs fine and the game ran fine on 1.0.0 but 1.0.6 is needed after the main tutorial sections of the game and ever since updating it, I cannot get past it no matter what PC I play it on.

**Comment by Nicalay2** [comment]
I have the exact same issue.

**Comment by Sapelain** [comment]
I was coming to say the same thing. When the game loads, the program closes by itself.

**Comment by darreldearth** [comment]
Still doing it on v1.1.1330 

The game launches and works fine for about 15 seconds then crashes, but there's no visual glitches or audio problems. Just crashes. Maybe they will look into fixing the crash since the game seems to work fine if it wouldnt crash.
