### ISSUE TITLE
[Bug] Crash every second time right after game start.

### ISSUE THREAD

**Issue by BoostCookie** [Ryujinx/Ryujinx#5813]
### Description of the issue

Every second time I start Ryujinx it crashes right after the game launches.
I can get to the welcome screen in Mario Kart and then it immediately crashes.
Then I restart Ryujinx and it works.
If I close Ryujinx later and start it again, it does not work again. So it only works every second time.

### Reproduction steps

Use: Artix Linux, sway window manager (Wayland)

- Start Ryujinx
- Start Mario Kart

### Log file

```
00:01:18.342 |I| HLE.GuestThread.64 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Mario Kart 8 Deluxe, PID: 119
   0x0000000000f497f4	main:0x8457f4	


00:01:18.344 |I| HLE.GuestThread.64 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000003e74
	X[01]:	0x0000000000000000
	X[02]:	0x0000000000000000
	X[03]:	0x00000000fffffff8
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x000000000140bac0
	X[09]:	0x000000007caf430c
	X[10]:	0x0000000078b84e50
	X[11]:	0x0000000007944360 (SP:-0x7944360)
	X[12]:	0x0000000078e00330
	X[13]:	0x0000000007944350 (SP:-0x7944350)
	X[14]:	0x000000000101de68 (main:0x919e68)	=>
	X[15]:	0x0000000000000000
	X[16]:	0x0000000000000000
	X[17]:	0x0000000000000000
	X[18]:	0x0000000000000000
	X[19]:	0x0000000000000000
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x0000000000000000
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x0000000000000000
	LR:	0x0000000000000000
	SP:	0x0000000000000000
	PC:	0x000000000101a4ac (main:0x9164ac)	=>


00:01:18.344 |E| HLE.GuestThread.64 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000003000.
00:01:18.398 |E| HLE.GuestThread.64 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 212
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 212
```

### OS

Artix Linux

### Ryujinx version

1.1.1052

### Game version

2.3.0

### CPU

AMD Ryzen 5 1600X

### GPU

AMD ATI Radeon RX Vega 56

### RAM

16 GiB

### Additional context?

Window manager: Sway

**Comment by AcK77** [comment]
Could you provide a full log file please? Thanks!

**Comment by BoostCookie** [comment]
No log files are created, even though I've ticked all the checkboxes in the log settings.
```
% pwd
/home/bob/.config/Ryujinx
% fd -I -i log .
%
```

But also I cannot reproduce the bug anymore. I looked which packages got updated since last time, and indeed there are some good candidates:
```
[2023-10-17T22:58:14+0200] [ALPM] upgraded dotnet-host (7.0.11.sdk111-1 -> 7.0.12.sdk112-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded dotnet-runtime (7.0.11.sdk111-1 -> 7.0.12.sdk112-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded lib32-harfbuzz (8.2.1-1 -> 8.2.1-2)
[2023-10-17T22:58:14+0200] [ALPM] upgraded lib32-libglvnd (1.6.0-1 -> 1.7.0-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded lib32-libxrandr (1.5.3-1 -> 1.5.4-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded libheif (1.16.2-3.1 -> 1.17.0-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded libmupdf (1.23.3-4 -> 1.23.4-3)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-common (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-audio-pa (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-ui-opengl (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-ui-spice-core (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-audio-spice (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-img (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-system-x86-firmware (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-system-x86 (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-base (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-block-curl (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-block-dmg (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-block-nfs (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-block-ssh (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-chardev-spice (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-display-qxl (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-display-virtio-gpu (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-display-virtio-gpu-gl (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-display-virtio-gpu-pci (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-display-virtio-gpu-pci-gl (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-display-virtio-vga (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-display-virtio-vga-gl (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-s390x-virtio-gpu-ccw (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-usb-host (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-usb-redirect (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-hw-usb-smartcard (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-pr-helper (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-tools (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-ui-curses (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-ui-gtk (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded qemu-ui-spice-app (8.1.1-2 -> 8.1.2-1)
[2023-10-17T22:58:14+0200] [ALPM] upgraded sdl2 (2.28.3-1 -> 2.28.4-1)
```

So I downgraded dotnet-host, dotnet-runtime, and sdl2 and tried to reproduce the bug again, but it still did not crash. Ryujinx has nothing to do with qemu, right? So I have no idea why it works now.

Should I just close this bug?

**Comment by gdkchan** [comment]
There is a better description of the issue here: https://github.com/Ryujinx/Ryujinx-Games-List/issues/244#issuecomment-1324988405

**Comment by AcK77** [comment]
Log files aren’t stored in the config folder but near the executable.

Since it seems to be a game related issue and not a package one, I close it because it’s already reported in our game list.
Thanks.

**Comment by BoostCookie** [comment]
> Log files aren’t stored in the config folder but near the executable.

The executable is in `/usr/bin` which should not contain logfiles. According to the [XDG Base Directory specification](https://wiki.archlinux.org/title/XDG_Base_Directory) it should probably go to  `$XDG_CACHE_HOME/Ryujinx`. But ok, that is a different issue.

**Comment by QueenLinuxGlitch** [comment]
Experiencing this issue currently, can confirm it is every second time
[Ryujinx_1.1.1093_2023-11-25_22-38-30.log](https://github.com/Ryujinx/Ryujinx/files/13465931/Ryujinx_1.1.1093_2023-11-25_22-38-30.log)
