### ISSUE TITLE
[Bug] There was an error finding the specified savedata: ResultFsTargetLocked (2002-0007)

### ISSUE THREAD

**Issue by rollercoaster** [Ryujinx/Ryujinx#5868]
### Description of the issue

On a fresh Ryujinx install, I get this error in the logs on startup and on every right click > open user save directory. If I try to launch a game, it tries to start and then crashes.

The funny thing is if I directly launch a game using arguments, the game works well and this error is not present in the logs. Then if I Stop Emulation, it returns to the game list, and I can use it without error.

![image](https://github.com/Ryujinx/Ryujinx/assets/578962/8852a793-bbe1-4773-b50f-79ad5729ecd8)

### Reproduction steps

As Above.

### Startup

00:00:00.006 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.079 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.089 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.089 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.091 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.093 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.094 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.095 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x1681
00:00:00.096 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.097 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.097 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.100 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.114 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.114 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.114 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.114 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.114 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.114 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.114 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.115 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.115 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.116 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.116 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.117 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.117 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.118 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.118 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.125 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.126 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1067
00:00:00.133 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.134 |N| Application Print: CPU: AMD Ryzen 7 6800U with Radeon Graphics ; 16 logical
00:00:00.136 |N| Application Print: RAM: Total 13053 MiB ; Available 7852 MiB
00:00:00.141 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.141 |N| Application PrintSystemInfo: Launch Mode: Portable
**00:00:01.391 |W| Application FixUnindexedSystemSaves: Error ResultFsTargetLocked (2002-0007) when fixing extra data for system save data 0x8000000000000030**

### GAME LAUNCH:

00:00:00.005 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.065 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.074 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.075 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.076 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.077 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.079 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.080 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x1681
00:00:00.081 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.082 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.082 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.086 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.096 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.097 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.097 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.097 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.097 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.097 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.097 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.097 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.097 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.098 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.099 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.099 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.100 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.100 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.100 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.109 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.109 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1067
00:00:00.116 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.116 |N| Application Print: CPU: AMD Ryzen 7 6800U with Radeon Graphics ; 16 logical
00:00:00.118 |N| Application Print: RAM: Total 13053 MiB ; Available 7931 MiB
00:00:00.122 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.122 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:01.447 |W| Application FixUnindexedSystemSaves: Error ResultFsTargetLocked (2002-0007) when fixing extra data for system save data 0x8000000000000030
00:00:00.135 |I| Gpu : Backend Threading (Auto): True
00:00:00.604 |N| Application LoadApplication: Using Firmware Version: 16.1.0
00:00:00.604 |I| Application LoadApplication: Loading as NSP.
00:00:00.648 |I| ModLoader QueryContentsDir: Searching mods for Title 0100C1F0051B6000
00:00:00.649 |I| ModLoader QueryContentsDir: Searching mods for Title 0100C1F0051B6000
00:00:00.652 |I| Loader Load: Loading rtld...
00:00:00.665 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.665 |I| Loader Load: Loading main...
00:00:00.857 |I| Loader PrintRoSectionInfo: main:
    Module: D:\Agent\pipelines\full_rs12\bin\NX64\Production\GameFramework.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-4_4_0-Release
                   SDK MW+Nintendo+NEX_DS-4_3_1
                   SDK MW+Nintendo+NEX-4_3_1-
                   SDK MW+Nintendo+NEX_RK-4_3_1
00:00:00.857 |I| Loader Load: Loading subsdk0...
00:00:00.895 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-4_4_0-Release
00:00:00.895 |I| Loader Load: Loading sdk...
00:00:00.957 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 4.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-4_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-4_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-4_4_0-Release
00:00:01.139 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.755 |I| Ptc Load: Loaded Translation Cache (size: 33360478 bytes, translated functions: 32423).
00:00:01.774 |I| Ptc Load: Loaded Profiling Info (size: 111645 bytes, profiled functions: 31893).
00:00:01.789 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:01.791 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:01.845 |I| Loader LoadNsos: Loading image 2 at 0x000000000e96e000...
00:00:01.848 |I| Loader LoadNsos: Loading image 3 at 0x000000000f054000...
00:00:01.862 |I| ModLoader LoadCheats: Build ids found for title 0100C1F0051B6000:
    D33817C0C763D8FAF97D9A6534C19DB231FF7271000000000000000000000000
    F48BD40D89B529C114F17C7909FE6AA400000000000000000000000000000000
    D9DE423EFC1512328C3C05378C7CB03173FACDE3000000000000000000000000
    BA520906609C503227871A314A94FB5F6CCBE444000000000000000000000000
00:00:01.866 |I| Application EnsureSaveData: Ensuring required savedata exists.
**00:00:01.952 |E| Application EnsureSaveData: Error calling EnsureApplicationSaveData. Result code ResultFsTargetLocked (2002-0007)**
00:00:02.032 |I| Loader Start: Application Loaded: Donkey Kong Country: Tropical Freeze v1.0.2 [0100c1f0051b6000] [64-bit]
00:00:02.046 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:02.075 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:02.445 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD Radeon(TM) Graphics (Vulkan v1.3.262, Driver v2.0.283)
00:00:02.459 |I| GPU.MainThread Gpu LoadShaders: Loading 207 shaders from the cache...
00:00:02.730 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:03.706 |I| HLE.GuestThread.42 Ptc LoadTranslations: 31893 translated functions loaded
00:00:03.895 |S| HLE.OsThread.43 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:03.901 |S| HLE.OsThread.43 ServiceAm AcquireForegroundRights: Stubbed.
00:00:03.902 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:03.903 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:03.921 |S| HLE.OsThread.43 ServicePctl Initialize: Stubbed.
00:00:06.757 |W| HLE.GuestThread.42 KernelSvc : SetHeapSize(address: 0x0000000000000000) = LimitReached
00:00:06.758 |W| HLE.GuestThread.42 KernelSvc : SetHeapSize(address: 0x0000000000000000) = LimitReached
00:00:06.758 |W| HLE.GuestThread.42 KernelSvc : SetHeapSize(address: 0x0000000000000000) = LimitReached
00:00:06.758 |W| HLE.GuestThread.42 KernelSvc : SetHeapSize(address: 0x0000000000000000) = LimitReached
00:00:06.758 |W| HLE.GuestThread.42 KernelSvc : SetHeapSize(address: 0x0000000000000000) = LimitReached
00:00:06.904 |S| HLE.OsThread.43 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:06.904 |S| HLE.OsThread.43 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:06.907 |S| HLE.OsThread.43 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:06.908 |S| HLE.OsThread.43 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:06.908 |S| HLE.OsThread.43 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:06.909 |S| HLE.OsThread.43 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72270830659919872}
00:00:07.112 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed.
00:00:07.119 |W| HLE.GuestThread.42 KernelSvc : MapSharedMemory() = InvalidMemoryRegion
00:00:07.122 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 0}
00:00:07.124 |S| HLE.OsThread.9 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:07.129 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Handheld,Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8
00:00:07.129 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 119 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:07.131 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:07.145 |I| HLE.OsThread.43 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:07.177 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed.
00:00:07.200 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed.
00:00:07.202 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed.
00:00:07.202 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed.
00:00:07.202 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed.
00:00:07.202 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed.
00:00:07.280 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed.
00:00:07.281 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed.
00:00:07.282 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed.
00:00:07.282 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed.
00:00:07.284 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed.
00:00:07.284 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed.
00:00:07.285 |S| HLE.OsThread.10 ServiceNv SetPriority: Stubbed.
00:00:07.288 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed.
00:00:07.444 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:07.449 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV4
00:00:07.486 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:07.487 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:07.529 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:07.591 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:12.445 |S| HLE.OsThread.43 ServicePctl CheckFreeCommunicationPermission: Stubbed.
00:00:12.683 |G| HLE.OsThread.20 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 12s
    Thread: MainThread
    Filename: D:/Agent/pipelines/full_rs12/Game/Gamestate/Area/CGameAreaLoader.cpp
    Line: 149
    Function: ContinueLoad
    Message: [Load] Starting load of room: F07AA912-01F9-40BF-B110-7563ABDFABF6

00:00:12.697 |S| HLE.OsThread.43 ServicePctl CheckFreeCommunicationPermission: Stubbed.
00:00:18.701 |G| HLE.OsThread.20 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 18s
    Thread: MainThread
    Filename: D:/Agent/pipelines/full_rs12/Game/Gamestate/Area/CGameAreaLoader.cpp
    Line: 410
    Function: ContinueLoad
    Message: [Load] Finished load of room: F07AA912-01F9-40BF-B110-7563ABDFABF6

00:00:19.125 |I| HLE.GuestThread.46 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Donkey Kong Country: Tropical Freeze, PID: 119
   0x0000000008508070   main:0x4070     NFSUtility::build_os_path_current(rstl::basic_string<char, rstl::char_traits<char>, rstl::rmemory_allocator> const&):0x002c
   0x000000000852e37c   main:0x2a37c    NFSImmediate::get_path_exists(bool*, rstl::basic_string<char, rstl::char_traits<char>, rstl::rmemory_allocator> const&):0x0018
   0x0000000008548f38   main:0x44f38    CFSCommandGetPathExists::operator()(NGameFile::EResult&):0x0020
   0x0000000008548aa4   main:0x44aa4    CFSCommand::Execute():0x0024
   0x000000000852a384   main:0x26384    CFSWorkerThreaded::Execute(IFSCommand&):0x0050
   0x0000000008529a0c   main:0x25a0c    CFSWorkerThreaded::StaticThreadMain(void*):0x0074
   0x0000000008506500   main:0x2500
   0x000000000f0e5b48   sdk:0x91b48
   0x000000000f0e9b24   sdk:0x95b24
   0x0000000000000000

00:00:19.127 |I| HLE.GuestThread.46 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
        X[00]:  0x0000000009a25bbc
        X[01]:  0x000000000000003a
        X[02]:  0x000000000852a4bc (main:0x264bc)       =>
        X[03]:  0x000000100fd039f8 (SP:-0xfffffffff7c93bf8)
        X[04]:  0x0000000000000000
        X[05]:  0x0000000000000000
        X[06]:  0x0000000000000000
        X[07]:  0x0000000000000000
        X[08]:  0x000000000000003a
        X[09]:  0xfefefefefefefeff
        X[10]:  0x0000008000000000
        X[11]:  0x4b5a47ff5e4b5a48
        X[12]:  0x0000000000000000
        X[13]:  0x0000000000000000
        X[14]:  0x0000000000000000
        X[15]:  0x0000000000000000
        X[16]:  0x000000000f9ecd68
        X[17]:  0x000000000f436020 (sdk:0x3e2020)       => __strchrnul
        X[18]:  0x0000000000000001
        X[19]:  0x000000000e307c60
        X[20]:  0x000000100fd03a38 (SP:-0xfffffffff7c93c38)
        X[21]:  0x0000000009a25bb8
        X[22]:  0x000000100fd039f8 (SP:-0xfffffffff7c93bf8)
        X[23]:  0x0000000000000000
        X[24]:  0x0000000000000000
        X[25]:  0x0000000000000000
        X[26]:  0x0000000000000000
        X[27]:  0x0000000000000000
        X[28]:  0x0000000000000000
        FP:     0x000000101806fe20 (SP:-0x0020)
        LR:     0x0000000008507e7c (main:0x3e7c)        =>
        SP:     0x000000101806fe00 (SP)
        PC:     0x000000000f436020 (sdk:0x3e2020)       => __strchrnul

00:00:19.127 |E| HLE.GuestThread.46 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:19.223 |E| HLE.GuestThread.46 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 60
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 60
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264

### OS

Windows 11

### Ryujinx version

1.1.1067

### Game version

Various

### CPU

AMD 6800U

### GPU

Integrated

### RAM

16GB

### List of applied mods

None

**Comment by rollercoaster** [comment]
Running as Admin fixes the error.

**Comment by rollercoaster** [comment]
Running as Right Click > Admin fixes the error but running from shortcut does not need this workaround.

I tried running "icacls d:\Emulator /t /q /c /reset" CMD which runs successfully but has no effect on the issue.

Finally solved this by taking ownership and propagating it to all child objects of the "bis" folder. (Step 4 here: https://www.thewindowsclub.com/change-files-and-folders-permissions-in-windows-10)

**Comment by rollercoaster** [comment]
On auto update from 1.1.1067 to 1.1.1069, this issue came back, and I had to reset permissions again.

No changes were made to the system or files and no games added removed. I wonder what is causing this.
