### ISSUE TITLE
[Bug] Baten Kaitos Crash Upon Loading

### ISSUE THREAD

**Issue by elunesgraces** [Ryujinx/Ryujinx#5873]
### Description of the issue

Baten Kaitos crashes during the loading screen when attempting to play either of the two games within. 

Problem started with revision 1067 and remains in 1068.

### Reproduction steps

1. Load Baten Kaitis I&II HD Remaster
2. Select Baten Kaitos I from the main menu
3. Loading bar within game starts
4. Ryujinx shuts down

### Log file

00:00:07.835 |E| HLE.OsThread.4 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Services.ServerBase.AddSessionObj(Int32 serverSessionHandle, IpcService obj) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 131
   at Ryujinx.HLE.HOS.Services.ServerBase.AddSessionObj(KServerSession serverSession, IpcService obj) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 111
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetService(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 103
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetServiceTipc(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 54
   at InvokeStub_IUserInterface.GetServiceTipc(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Ryujinx.HLE.HOS.Services.IpcService.CallTipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 179
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 460
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1251

### OS

Windows 10

### Ryujinx version

1067/1068

### Game version

1.0.1

### CPU

Ryzen 5600x

### GPU

3060ti

### RAM

16gm

### List of applied mods

English language dub mod

**Comment by OldManKain** [comment]
I cannot recreate this issue, please join us in our [Discord](https://discord.gg/ryujinx) for general trouble shooting.
![image](https://github.com/Ryujinx/Ryujinx/assets/47503099/ed4377ee-38f5-43a6-8f47-0a06c44044a0)

![image](https://github.com/Ryujinx/Ryujinx/assets/47503099/0eb453d0-fd62-4b25-9c93-1ad7a70fe1a4)
