### ISSUE TITLE
[Bug] [Cheats] Any HEAP Code Crashes Digimon Story Cyber Sleuth: Complete Edition under OpenGL

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [Ryujinx/Ryujinx#5879]
### Description of the issue

I am trying to use cheats for Digimon Story Cyber Sleuth: Complete Edition (which is a 2-game compilation of the games Digimon Story Cyber Sleuth and Digimon Story Cyber Sleuth: Hacker's Memory, which were originally released on the Playstation Vita and PS4; this compilation includes all DLC ever released for the games as well. Upon starting a new game, you can select one story at a time to play through.), and although all Main NSO cheats work fine, any HEAP codes that are known to work fine on console crash the emulator as soon as they are enabled, with this seemingly unrelated, but very much related, error:

```
|E| GUI.RenderLoop Application : Unhandled exception caught: System.InvalidOperationException: DepthStencil copy to buffer is not supported for layer/level > 0.
   at Ryujinx.Graphics.OpenGL.Image.TextureView.CopyTo(BufferRange range, Int32 layer, Int32 level, Int32 stride) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.OpenGL\Image\TextureView.cs:line 301
   at Ryujinx.Graphics.GAL.Multithreading.Commands.Texture.TextureCopyToBufferCommand.Run(TextureCopyToBufferCommand& command, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\Commands\Texture\TextureCopyToBufferCommand.cs:line 26
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 448
```

The cheats I am trying to use are for v1.0.2 of the game, and are the following:

```
[Max Money (HM)]
04100000 0D8976B4 0098967F

[Max Stats (CS)]
021F0000 0D85F97C 0000270F
021F0000 0D85F980 0000270F
021F0000 0D85F988 000003E7
021F0000 0D85F98C 000003E7
021F0000 0D85F992 000003E7
021F0000 0D85F996 000003E7
021F0000 0D85F99A 000003E7
021F0000 0D85F99E 000003E7
011F0000 0D85FB1E 00000003
021F0000 0D85FBBC 0000270F
021F0000 0D85FBC0 0000270F
021F0000 0D85FBC8 000003E7
021F0000 0D85FBCC 000003E7
021F0000 0D85FBD2 000003E7
021F0000 0D85FBD6 000003E7
021F0000 0D85FBDA 000003E7
021F0000 0D85FBDE 000003E7
011F0000 0D85FD5E 00000003
021F0000 0D85FDFC 0000270F
021F0000 0D85FE00 0000270F
021F0000 0D85FE08 000003E7
021F0000 0D85FE0C 000003E7
021F0000 0D85FE12 000003E7
021F0000 0D85FE16 000003E7
021F0000 0D85FE1A 000003E7
021F0000 0D85FE1E 000003E7
011F0000 0D85FF9E 00000003
```

I enabled the first one in a new game in Hacker's Memory, which is the game it is designed for. The game freezes, then crashes shortly after, as soon as it is enabled, and crashes the emulator on the first frame if enabled from the start.

The second one was added later, is designed for the original Cyber Sleuth, and when enabled behaves exactly the same as the first listed code, regardless of when it is activated.

The thing is, these codes are verified working on console, so they should, in theory, also work on the emulator, but they don't, which leads me to believe it is a bug with this specific game.

### Reproduction steps

1. Create the cheat file for the game, with a title ID of 010014E00DB56000 and a build ID of 92A6C699E4BAE7DA, and add the aforementioned verified working codes.
2. Start v1.0.2 of Digimon Story Cyber Sleuth: Complete Edition (TID: 010014E00DB56000; BID: 92A6C699E4BAE7DA)

The next step depends on which game is selected. If Cyber Sleuth is selected, complete the first chapter so you unlock your first Digimon, then do step 3A below:

3A. Save the game, then enable the second code listed in the list of cheats.

Result: The game freezes, then crashes shortly afterward, with the aforementioned error.

If Hacker's Memory is selected, merely start the game and play through the opening segments, then do step 3B below:

3B. Save the game, then enable the first cheat in the list of cheats.

Result: The game freezes, then crashes shortly afterward, with the aforementioned error.

### Log file

[Ryujinx_1.1.1069_2023-11-02_01-35-07.log](https://github.com/Ryujinx/Ryujinx/files/13235515/Ryujinx_1.1.1069_2023-11-02_01-35-07.log)

### OS

Windows 10 22H2

### Ryujinx version

1.1.1069

### Game version

1.0.2

### CPU

i7-7700

### GPU

MSI Gaming NVIDIA GeForce GTX 1060 3GB

### RAM

16GB

### List of applied mods

Cheats only

**Comment by OldManKain** [comment]
As was discussed earlier in discord this is a user error you are trying to use 1.0.3 cheats on the 1.0.2 game.   I have tested myself that the [heap]+[main] cheats work as intended on Ryujinx.
![image](https://github.com/Ryujinx/Ryujinx/assets/47503099/e6157978-bef9-4b20-93a6-df6d1940d160)

**Comment by M1CR0H4CK3R** [comment]
> As was discussed earlier in discord this is a user error you are trying to use 1.0.3 cheats on the 1.0.2 game. I have tested myself that the [heap]+[main] cheats work as intended on Ryujinx. ![image](https://user-images.githubusercontent.com/47503099/280140635-e6157978-bef9-4b20-93a6-df6d1940d160.png)

The cheats in your image and the cheat that I am certain is actually for v1.0.2 are 2 different cheats. Have you even TRIED to verify my specific cheat? If not, then this most certainly isn't 'completed'.

**Comment by M1CR0H4CK3R** [comment]
However, I will concede that, at the minimum, it is possible that the cheat I am using is wrong now that I see HEAP codes working on v1.0.3.

**Comment by M1CR0H4CK3R** [comment]
Okay, I updated my game to v1.0.3 and used the cheats you listed, and I am STILL getting the exact same crash, this time with cheats that are confirmed working with v1.0.3, so something is definitely wrong.

**Comment by gdkchan** [comment]
There is a difference in the tests, @OldManKain is using Vulkan while you're testing with OpenGL. This is important since your log indicates that the crash happens in the OpenGL backend. Although it still seems odd that a cheat would cause that error, maybe it is not the main problem but just a side effect of it.

**Comment by M1CR0H4CK3R** [comment]
> There is a difference in the tests, @OldManKain is using Vulkan while you're testing with OpenGL. This is important since your log indicates that the crash happens in the OpenGL backend. Although it still seems odd that a cheat would cause that error, maybe it is not the main problem but just a side effect of it.

I get graphical glitches with Vulkan, but it boots: 
![image](https://github.com/Ryujinx/Ryujinx/assets/1993598/ff807256-eb2b-4619-8e5f-2e6a135a5573)

**Comment by M1CR0H4CK3R** [comment]
Yeah, the game is unplayable in Vulkan for me, so this is a bug with OpenGL for this game. The bug only seems to affect HEAP codes for some reason...

**Comment by M1CR0H4CK3R** [comment]
@OldManKain Can this be reopened? Turns out it is indeed a bug, but with OpenGL.

**Comment by OldManKain** [comment]
> @OldManKain Can this be reopened? Turns out it is indeed a bug, but with OpenGL.

That is above my paygrade.   If a dev feels it is worth it they can reopen it.

**Comment by M1CR0H4CK3R** [comment]
Okay, it appears that it is this bug that is happening to me: #3584

**Comment by M1CR0H4CK3R** [comment]
And I do indeed have many tabs open in Chrome.

**Comment by M1CR0H4CK3R** [comment]
Well, even after fixing that issue, the game still runs at 15 FPS at maximum, so OpenGL is my only option, sadly.

**Comment by gdkchan** [comment]
Will keep it open as it appears to be a legitimate issue with the emulator.
