### ISSUE TITLE
System.NotImplementedException: ngc:u When launching games

### ISSUE THREAD

**Issue by ZepedaJake** [Ryujinx/Ryujinx#5977]
### Description of the issue

Game begins to load then application crashes with error above.
Windows is up to date.
Graphics drivers up to date.
Tried Avalonia build and get same result.

This is on a fresh download, no mods/cheats.

### Reproduction steps

Run Ryujinx
Enter or Double click game.

### Log file

[Ryujinx_1.1.0-ldn3.1.3_2023-11-22_13-34-38.log](https://github.com/Ryujinx/Ryujinx/files/13443421/Ryujinx_1.1.0-ldn3.1.3_2023-11-22_13-34-38.log)

ERROR: 
00:00:09.194 |E| HLE.OsThread.4 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: ngc:u
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetService(ServiceCtx context)
   at InvokeStub_IUserInterface.GetServiceTipc(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at Ryujinx.HLE.HOS.Services.IpcService.CallTipcMethod(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\IpcService.cs:line 162
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 320
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1262
   at System.Threading.Thread.StartCallback()

### OS

Windows 10

### Ryujinx version

1.1.0-ldn3.1.3

### Game version

1.0.0

### CPU

i5-12600K

### GPU

NVIDIA RTX 3070

### RAM

32GB

### List of applied mods

None

**Comment by MutantAura** [comment]
Super Mario Wonder does not have LDN functionality.
Please use the main build from our website: https://ryujinx.org/download

**Comment by ZepedaJake** [comment]
Ah so simple. Thank you very much.
