### ISSUE TITLE
[Bug] Hogwarts Legacy often crashes

### ISSUE THREAD

**Issue by axisdrama** [Ryujinx/Ryujinx#6139]
### Description of the issue

Hogwarts Legacy is crashing often. Here are some of the logs before the most recent crash. Similar to the ends of other logs. I am playing on a Mac mini M2 8GB and am using Jump Desktop to mirror the display to my iPad.

### Reproduction steps

Play Hogwarts Legacy. Experience unexpected and frequent crashes.

### Log file

00:02:06.344 |S| HLE.OsThread.43 ServiceAm SetScreenShotPermission: Stubbed. {screenShotPermission: True}
00:02:25.203 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:03:02.280 |I| HLE.GuestThread.46 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Hogwarts Legacy, PID: 119
   0x000000000911f8d0	main:0xc1b8d0	
   0x0000000014326af0	sdk:0x130af0	
   0x000000001432c9b4	sdk:0x1369b4	
   0x0000000000000000

00:03:02.283 |I| HLE.GuestThread.46 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000001800c0a6c0
	X[01]:	0x0000000000000000
	X[02]:	0x0000000000000000
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000003
	X[09]:	0x00000000e0000002
	X[10]:	0x00000000000000b5
	X[11]:	0x0000000000800000
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000018
	X[14]:	0x0000006563a00a50
	X[15]:	0x0000000000000000
	X[16]:	0x0000000014f32588
	X[17]:	0x000000001432df00 (sdk:0x137f00)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x0000000000000001
	X[19]:	0x0000001800c0a6c0
	X[20]:	0x00000000d017ee9e
	X[21]:	0x0000001800c0a6f8
	X[22]:	0x0000000000000080
	X[23]:	0x0000000012234000
	X[24]:	0x0000001800c0a6d8
	X[25]:	0x00000000ffffffff
	X[26]:	0x0000000012210000
	X[27]:	0x0000001800c0a708
	X[28]:	0x0000001800c0a6d8
	FP:	0x00000049d2cdff10 (SP:-0x0050)
	LR:	0x000000000dcbdf9c (main:0x57b9f9c)	=> 
	SP:	0x00000049d2cdfec0 (SP)
	PC:	0x000000000dcbd914 (main:0x57b9914)	=> 

00:03:02.283 |E| HLE.GuestThread.46 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000003.
00:03:02.311 |E| HLE.GuestThread.46 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 277
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.DataAbort(MemoryTracking tracking, UInt64 vcpu, UInt32 esr) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 240
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 200
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 159
   at Ryujinx.Cpu.AppleHv.HvCpuContext.Execute(IExecutionContext context, UInt64 address) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvCpuContext.cs:line 27
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/ArmProcessContext.cs:line 60
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()

### OS

Mac OS Sonoma 14.2.1 (23C71)

### Ryujinx version

1.1.1110

### Game version

1.0.2

### CPU

M2

### RAM

8GB

### List of applied mods

None

**Comment by AinaKrim** [comment]
Hi! Tell me, please, do you have any problems as in the topic #5942?

**Comment by axisdrama** [comment]
I knew this thread talked about the lighting issues, which I do have, but didn’t realize it also talked about multiple crashes. Yes, it seems similar to these problems.  On Jan 16, 2024, at 4:35 AM, AinaKrim ***@***.***> wrote:﻿
Hi! Tell me, please, do you have any problems as in the topic #5942?
