### ISSUE TITLE
[Bug]LEGO The Incredibles [0100f19006e04000] fails to boot

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6193]
### Description of the issue

fails to boot 
just crashes out straight away
00:00:07.939 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0x0000002052F70000, size=0x0000000000870000
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 139
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 347
   at Ryujinx.Graphics.Gpu.Memory.PhysicalMemory.GetSpan(MultiRange range, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\PhysicalMemory.cs:line 148
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeFull() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 640
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 614
   at Ryujinx.Graphics.Gpu.Image.Texture.InitializeData(Boolean isView, Boolean withData) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 284
   at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\TextureCache.cs:line 568
   at Ryujinx.Graphics.Gpu.Window.Present(Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Window.cs:line 203
   at Ryujinx.HLE.Switch.PresentFrame(Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Switch.cs:line 114
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__79_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 477
   at System.Threading.Thread.StartCallback()

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1141_2024-01-28_17-01-19.log](https://github.com/Ryujinx/Ryujinx/files/14075455/Ryujinx_1.1.1141_2024-01-28_17-01-19.log)

### OS

Windows 10

### Ryujinx version

1.1.1141

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
Since it's a game specific issue, I created an issue here: https://github.com/Ryujinx/Ryujinx-Games-List/issues/4868

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
