### ISSUE TITLE
[Bug]Oddworld Soulstorm [0100D210177C6000][v0] crashes out nearly straight away

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6205]
### Description of the issue

crashes out the emulator nearly straight away
00:00:23.513 |E| HLE.GuestThread.44 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1932
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3461
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()
and more it didnt print in the log aswell
![Screenshot 2024-01-29 173713](https://github.com/Ryujinx/Ryujinx/assets/139027919/43bcd93b-2cc6-486d-aa51-ece479c212f5)

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1141_2024-01-29_17-36-01.log](https://github.com/Ryujinx/Ryujinx/files/14082389/Ryujinx_1.1.1141_2024-01-29_17-36-01.log)

### OS

Windows 10

### Ryujinx version

1.1.1141

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by piplup55** [comment]
`ResultFsPermissionDenied (2002-6400)` here usually means Ryujinx has been denied access to the save folder for this game. Most of the time it’s solved if you delete the save folder: `Right click the game > Open User Save Directory.` Backup the contents if you care about the save. Go up 2 levels and delete the selected folder. Run the game again. 

If this doesn’t fix it, check that Ryujinx isn’t on a protected folder (such as the desktop or the root of a drive) and that a third party antivirus (if you have one) isn’t blocking Ryujinx from using the save folder. If all else fails, make a portable install and bring over your caches and saves from the previous install.

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/4222 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
