### ISSUE TITLE
[Bug]Mahjong Solitaire Refresh 01008C300B624000 crashes out nearly straight away

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6230]
### Description of the issue

crashes out the emulator nearly straight away

00:00:13.156 |I| HLE.GuestThread.46 Cpu PrintGuestStackTrace: Guest stack trace:
Process: 上海 Refresh, PID: 123
   0x000000000be91d64	sdk:0x4dd64	nn::diag::detail::InvokeAbortObserver(nn::diag::AbortInfo const&):0x0054
   0x000000000be90770	sdk:0x4c770	nn::diag::detail::VAbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, std::__va_list):0x00a0
   0x000000000be90844	sdk:0x4c844	
   0x000000000be9e8d4	sdk:0x5a8d4	
   0x000000000a2f620c	main:0x1df220c	
   0x0000000008766728	main:0x262728	
   0x00000000088181a8	main:0x3141a8	
   0x0000000008818248	main:0x314248	
   0x0000000008694cbc	main:0x190cbc	
   0x0000000008694bb0	main:0x190bb0	
   0x0000000008c3b5e4	main:0x7375e4	
   0x0000000008504234	main:0x0234	
   0x0000000009600e74	main:0x10fce74	
   0x000000000966c9a4	main:0x11689a4	
   0x000000000965fb88	main:0x115bb88	
   0x0000000009b6a8c8	main:0x16668c8	
   0x0000000009b6ad28	main:0x1666d28	
   0x0000000009b6a76c	main:0x166676c	
   0x0000000009b2b4d4	main:0x16274d4	
   0x0000000009bfc3d4	main:0x16f83d4	
   0x0000000009bfc004	main:0x16f8004	
   0x0000000009bfbbb8	main:0x16f7bb8	
   0x0000000009bfcea4	main:0x16f8ea4	
   0x0000000009bfd524	main:0x16f9524	
   0x00000000096cf43c	main:0x11cb43c	
   0x000000000965c8f4	main:0x11588f4	nnMain:0x0614
   0x000000000bec892c	sdk:0x8492c	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)()):0x004c
   0x00000000085000ac	rtld:0x00ac	

00:00:13.157 |I| HLE.GuestThread.46 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x000000000aadb747
	X[01]:	0x000000000c70ec40
	X[02]:	0x000000000c70ec40
	X[03]:	0x0000000000000000
	X[04]:	0x000000000c70ec40
	X[05]:	0x000000000c70ec40
	X[06]:	0x000000000c70ec40
	X[07]:	0x000000100cd035e0 (SP:-0x01a0)
	X[08]:	0x000000000aadb747
	X[09]:	0x0000000000000000
	X[10]:	0x000000100cd03440 (SP)
	X[11]:	0x000000100cd03440 (SP)
	X[12]:	0x0000000000000000
	X[13]:	0x000000000c70ec40
	X[14]:	0x000000000c70ec40
	X[15]:	0x000000208d9e09d8
	X[16]:	0x000000000c93cd90
	X[17]:	0x000000000bef90e0 (sdk:0xb50e0)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Enter()
	X[18]:	0x0000000000000000
	X[19]:	0x000000100cd034c0 (SP:-0x0080)
	X[20]:	0x000000000c95a630
	X[21]:	0x000000000b6bffc0
	X[22]:	0x000000000c70ec40
	X[23]:	0x000000000c70ec40
	X[24]:	0x000000100cd035e0 (SP:-0x01a0)
	X[25]:	0x000000000c70ec40
	X[26]:	0x000000000c70ec40
	X[27]:	0x0000000000000001
	X[28]:	0x0000000000000000
	FP:	0x000000100cd03440 (SP)
	LR:	0x000000000965c214 (main:0x1158214)	=> 
	SP:	0x000000100cd03440 (SP)
	PC:	0x0000000009701ee0 (main:0x11fdee0)	=> 

00:00:13.189 |E| HLE.GuestThread.46 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000965c214 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1096
   at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\State\ExecutionContext.cs:line 161
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1152_2024-01-31_16-30-28.log](https://github.com/Ryujinx/Ryujinx/files/14109207/Ryujinx_1.1.1152_2024-01-31_16-30-28.log)

### OS

Windows 10

### Ryujinx version

1.1.1151

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This is already reported in https://github.com/Ryujinx/Ryujinx-Games-List/issues/607 since a long time.
You can report games specific issues in https://github.com/Ryujinx/Ryujinx-Games-List/ instead of here.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
