### ISSUE TITLE
[Bug] Logs is denied.

### ISSUE THREAD

**Issue by willianholtz** [Ryujinx/Ryujinx#6252]
### Description of the issue

A couple of builds ago I had this problem, the app doesn't open because it says it doesn't have access to the logs.

### Reproduction steps

Just Open on linux.

### Log file

As it no longer generates logs, I have to send the log that comes out through the terminal:

```
[willian@archlinux ~]$ ryujinx
00:00:00.005 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.077 |E| Application : Unhandled exception caught: System.UnauthorizedAccessException: Access to the path '/opt/ryujinx/Logs' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String, UnixFileMode)
   at System.IO.FileSystem.CreateDirectory(String)
   at System.IO.DirectoryInfo.Create()
   at Ryujinx.Common.Logging.Targets.FileLogTarget.PrepareLogFile(String path) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Common/Logging/Targets/FileLogTarget.cs:line 29
   at Ryujinx.Ui.Common.Configuration.LoggerModule.ReloadFileLogger(Object sender, ReactiveEventArgs`1 e) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ui.Common/Configuration/LoggerModule.cs:line 88
   at Ryujinx.Common.ReactiveObject`1.set_Value(T value) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Common/ReactiveObject.cs:line 39
   at Ryujinx.Ui.Common.Configuration.ConfigurationState.Load(ConfigurationFileFormat configurationFileFormat, String configurationFilePath) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs:line 1433
   at Ryujinx.Ava.Program.ReloadConfig() in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/Program.cs:line 153
   at Ryujinx.Ava.Program.Initialize(String[] args) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/Program.cs:line 101
   at Ryujinx.Ava.Program.Main(String[] args) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/Program.cs:line 47
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/opt/ryujinx/Logs' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String, UnixFileMode)
   at System.IO.FileSystem.CreateDirectory(String)
   at System.IO.DirectoryInfo.Create()
   at Ryujinx.Common.Logging.Targets.FileLogTarget.PrepareLogFile(String path) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Common/Logging/Targets/FileLogTarget.cs:line 29
   at Ryujinx.Ui.Common.Configuration.LoggerModule.ReloadFileLogger(Object sender, ReactiveEventArgs`1 e) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ui.Common/Configuration/LoggerModule.cs:line 88
   at Ryujinx.Common.ReactiveObject`1.set_Value(T value) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Common/ReactiveObject.cs:line 39
   at Ryujinx.Ui.Common.Configuration.ConfigurationState.Load(ConfigurationFileFormat configurationFileFormat, String configurationFilePath) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs:line 1433
   at Ryujinx.Ava.Program.ReloadConfig() in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/Program.cs:line 153
   at Ryujinx.Ava.Program.Initialize(String[] args) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/Program.cs:line 101
   at Ryujinx.Ava.Program.Main(String[] args) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/Program.cs:line 47
/usr/bin/ryujinx, linha 20:  1137 Abortado                (imagem do núcleo gravada)$COMMAND "$SCRIPT_DIR/$RYUJINX_BIN" "$@"

```

### OS

Arch Linux

### Ryujinx version

Ryujinx-git 1.1.1157.r0.g24c8b0edc-1

**Comment by TSRBerry** [comment]
Should be fixed by #6238

**Comment by willianholtz** [comment]
Not yet. Look what happens when you click OK after activating the log. 

`00:00:09.252 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:09.287 |E| Application : Unhandled exception caught: System.UnauthorizedAccessException: Access to the path '/opt/ryujinx/Logs' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String, UnixFileMode)
   at System.IO.FileSystem.CreateDirectory(String)
   at System.IO.DirectoryInfo.Create()
   at Ryujinx.Common.Logging.Targets.FileLogTarget.PrepareLogFile(String path) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Common/Logging/Targets/FileLogTarget.cs:line 29
   at Ryujinx.Ui.Common.Configuration.LoggerModule.ReloadFileLogger(Object sender, ReactiveEventArgs`1 e) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ui.Common/Configuration/LoggerModule.cs:line 88
   at Ryujinx.Common.ReactiveObject`1.set_Value(T value) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Common/ReactiveObject.cs:line 39
   at Ryujinx.Ava.UI.ViewModels.SettingsViewModel.SaveSettings() in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs:line 568
   at Ryujinx.Ava.UI.ViewModels.SettingsViewModel.OkButton() in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs:line 604
   at CompiledAvaloniaXaml.XamlIlTrampolines.Ryujinx.Ava:Ryujinx.Ava.UI.ViewModels.SettingsViewModel+OkButton_0!CommandExecuteTrampoline(Object, Object)
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.CommandAccessorPlugin.CommandAccessor.Command.Execute(Object)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice, UInt64, IInputRoot, Point, PointerPointProperties, KeyModifiers, IInputElement )
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs)
   at Avalonia.ManualRawEventGrouperDispatchQueue.DispatchNext()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode )
   at Ryujinx.Ava.Program.Main(String[] args) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/Program.cs:line 51
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/opt/ryujinx/Logs' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String, UnixFileMode)
   at System.IO.FileSystem.CreateDirectory(String)
   at System.IO.DirectoryInfo.Create()
   at Ryujinx.Common.Logging.Targets.FileLogTarget.PrepareLogFile(String path) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Common/Logging/Targets/FileLogTarget.cs:line 29
   at Ryujinx.Ui.Common.Configuration.LoggerModule.ReloadFileLogger(Object sender, ReactiveEventArgs`1 e) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ui.Common/Configuration/LoggerModule.cs:line 88
   at Ryujinx.Common.ReactiveObject`1.set_Value(T value) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Common/ReactiveObject.cs:line 39
   at Ryujinx.Ava.UI.ViewModels.SettingsViewModel.SaveSettings() in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs:line 568
   at Ryujinx.Ava.UI.ViewModels.SettingsViewModel.OkButton() in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs:line 604
   at CompiledAvaloniaXaml.XamlIlTrampolines.Ryujinx.Ava:Ryujinx.Ava.UI.ViewModels.SettingsViewModel+OkButton_0!CommandExecuteTrampoline(Object, Object)
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.CommandAccessorPlugin.CommandAccessor.Command.Execute(Object)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice, UInt64, IInputRoot, Point, PointerPointProperties, KeyModifiers, IInputElement )
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs)
   at Avalonia.ManualRawEventGrouperDispatchQueue.DispatchNext()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode )
   at Ryujinx.Ava.Program.Main(String[] args) in /home/main-builder/pkgwork/src/Ryujinx/src/Ryujinx.Ava/Program.cs:line 51
/usr/bin/ryujinx, linha 20: 20503 Abortado                (imagem do núcleo gravada)$COMMAND "$SCRIPT_DIR/$RYUJINX_BIN" "$@"
`

**Comment by willianholtz** [comment]
Sorry, I downloaded the trial version, but I generated the master version log. I was able to test it again here and now it works normally
