### ISSUE TITLE
[Bug] TOTK Crash: Crash on startup after updating Ryujinx

### ISSUE THREAD

**Issue by xArkailzx** [Ryujinx/Ryujinx#6264]
### Description of the issue

Ryujinx crash right before the game finishes to load. Had no problems before updating from 1.1.1160 to 1.1.1163.

### Reproduction steps

- Update to 1.1.1163
- Launch TOTK

### Log file

00:01:58.308 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 281
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 272
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 268
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreateGraphicsPipelineIfNeeded() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1532
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 453
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 448

### OS

Windows 11

### Ryujinx version

1.1.1163

### Game version

1.2.1

### CPU

Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz   3.50 GHz

### GPU

NVIDIA Quadro P4000

### RAM

64GB

### List of applied mods

![image](https://github.com/Ryujinx/Ryujinx/assets/78084119/f4f8239c-d100-4aa4-ac07-36d3d3d6d2d8)

### Additional context?

May or may not crash when removing some mods. I don't know exactly which.

(PS: Issue is probably a duplicate from an other, but I wanted to add the ryujinx update factor.)

**Comment by AcK77** [comment]
Try to remove graphics mods, that could leads to corrupted shader cache or this kind of issue.
On top of that you can try to purge the shader cache too.
If it's still happen without mods, this issue could be reopened, you can goes to our discord for support too.
Thanks.

**Comment by xArkailzx** [comment]
> Try to remove graphics mods, that could leads to corrupted shader cache or this kind of issue. On top of that you can try to purge the shader cache too. If it's still happen without mods, this issue could be reopened, you can goes to our discord for support too. Thanks.

I removed both graphics mods and purged the shader cache, but it still crashes with the same error, Awhile, I updated to 1.1.1188.
It'll probably work without any mods, but half of them is for QoL and Performance.

**Comment by xArkailzx** [comment]
UPDATE: Removing some mods seems to fix the issue. However, I don't know if that's because some mods cause this or just too much mods loaded,
