### ISSUE TITLE
[Bug]Danger Mouse [01003ed0099b0000] crashes out the emulator after the title screen

### ISSUE THREAD

**Issue by ScottNash042** [Ryujinx/Ryujinx#6286]
### Description of the issue

crashes out after the title screen
00:00:12.186 |E| HLE.OsThread.47 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1, ExceptionDispatchInfo)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean, Byte[], CancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String, X509CertificateCollection , SslProtocols, Boolean)
   at Ryujinx.HLE.HOS.Services.Ssl.SslService.SslManagedSocketConnection.Handshake(String hostName) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Ssl\SslService\SslManagedSocketConnection.cs:line 121
   at Ryujinx.HLE.HOS.Services.Ssl.SslService.ISslConnection.DoHandshake(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Ssl\SslService\ISslConnection.cs:line 191
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object, Span`1, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object, Span`1, BindingFlags)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### Reproduction steps

load the game

### Log file

[Ryujinx_1.1.1173_2024-02-10_12-51-58.log](https://github.com/Ryujinx/Ryujinx/files/14227972/Ryujinx_1.1.1173_2024-02-10_12-51-58.log)

### OS

Windows 10

### Ryujinx version

1.1.1173

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb

**Comment by AcK77** [comment]
This happen because the game try to connect to the game server, which will not work with the emulator.
You can report this game specific issue in https://github.com/Ryujinx/Ryujinx-Games-List/issues/1324 instead of here if you want to.
Thanks.

**Comment by ScottNash042** [comment]
why close them all
the games list is a waste of time
all the games in the list have not been update for 2-4 years except for the AAA games
