### ISSUE TITLE
[Bug] Avalonia crashes when stopping emulation on OpenGL

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#6319]
### Description of the issue

GDK shows the same issue but it doesn't crash, only Avalonia has this issue with OpenGL

Avalonia:

```
00:00:09.852 |I| HLE.OsThread.7 AudioRenderer ReleaseSessionId: Unregistered output (0)
00:00:09.923 |W| GUI.WindowThread Ui MakeCurrent: Failed to bind OpenGL context: SPB.Graphics.Exceptions.ContextException: MakeCurrent() failed with error 0xaa
   at SPB.Platform.WGL.WGLOpenGLContext.MakeCurrent(NativeWindowBase window)
   at Ryujinx.Ava.UI.Renderer.EmbeddedWindowOpenGL.MakeCurrent(Boolean unbind, Boolean shouldThrow) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ava\UI\Renderer\EmbeddedWindowOpenGL.cs:line 69
```

GDK:

```
00:01:59.752 |W| UI Dispose: Failed to bind OpenGL context: SPB.Graphics.Exceptions.ContextException: MakeCurrent() failed with error 0xaa
   at SPB.Platform.WGL.WGLOpenGLContext.MakeCurrent(NativeWindowBase window)
   at Ryujinx.UI.OpenGLRenderer.Dispose(Boolean disposing) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\OpenGLRenderer.cs:line 119
```

### Reproduction steps

Just start and stop emulation on Avalonia with the OpenGL renderer.

### Log file

N/A

### OS

Windows 10

### Ryujinx version

1.1.1193

**Comment by Littl3Guy** [comment]
I can't trigger the crash on AMD Windows.
[Ryujinx_1.1.1192_2024-02-15_13-26-16.log](https://github.com/Ryujinx/Ryujinx/files/14301040/Ryujinx_1.1.1192_2024-02-15_13-26-16.log)
