### ISSUE TITLE
 Mario Party Superstars crash when choosing second profile

### ISSUE THREAD

**Issue by Trihy** [Ryujinx/Ryujinx#6323]
### Description of the issue

Emulator crash when selecting 2 players and choose to change 2nd player profile. It doesnt crash with any specific message, it just close itself. If you let the default profile (guest) for 2nd player, it wont crash.

### Reproduction steps

Just choose two player and click or press A on `guest` for second player profile change. Instant crash.

(I have more than one profile created on emulator settings)

### Log file

None

### OS

Windows 11

### Ryujinx version

1.1.1197

### Game version

1.0 and 1.1.1

### CPU

i7 9700

### GPU

AMD 6700

### RAM

16GB

### List of applied mods

None

### Additional context?

None

**Comment by TheEarthrise** [comment]
I can confirm this. If you chose to link the 2nd player to a profile, the game crashes instantly.
`00:00:25.803 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.820 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.836 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.853 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.869 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.886 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.903 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.919 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.936 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.955 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:25.958 |S| HLE.OsThread.49 ServiceAm GetLibraryAppletLaunchableEvent: Stubbed. 
00:00:25.962 |I| HLE.OsThread.49 ServiceAm .ctor: Applet 'PlayerSelect' created.
00:00:25.972 |S| HLE.OsThread.49 ServiceAm TryPopFromFriendInvitationStorageChannel: Stubbed. 
00:00:26.067 |I| HLE.OsThread.49 ServiceAm SetTerminateResult: Result = 0x0035f202 (ResultFsNotMounted (2002-6905)).
00:00:26.193 |I| HLE.GuestThread.48 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Mario Party Superstars, PID: 125
   0x000000000ad06038	sdk:0x145038	
   0x000000000ad060f8	sdk:0x1450f8	
   0x000000000ad7d54c	sdk:0x1bc54c	
   0x0000000008b35444	main:0x631444	
   0x0000000008b35294	main:0x631294	
   0x0000000008b10ccc	main:0x60cccc	
   0x0000000008888860	main:0x384860	bex::GMSystemSave::Load(int):0x00b0
   0x00000011b2c13e00
   0x00000000086338bc	main:0x12f8bc	
   0x000000000af10730	sdk:0x34f730	nn::os::detail::CallFiberFunction(nn::os::FiberType* (*)(void*), void*):0x0014


00:00:26.194 |I| HLE.GuestThread.48 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x00000049a3ea3c60 (SP:-0x01c0)
	X[02]:	0x0000000000000004
	X[03]:	0x000000000000000c
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000100000000
	X[09]:	0x000000000abc1000 (sdk:0x0000)	=> 
	X[10]:	0x0000000000c696c8
	X[11]:	0x0000000000800000
	X[12]:	0x0000000000000000
	X[13]:	0x000000000000000e
	X[14]:	0x0000000000000002
	X[15]:	0x0000000000000000
	X[16]:	0x000000000ad07870 (sdk:0x146870)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x000000000b82a6c8
	X[18]:	0x0000000000000000
	X[19]:	0x00000049a3ea3c60 (SP:-0x01c0)
	X[20]:	0x0000000000000000
	X[21]:	0x000000000b5dfd5c
	X[22]:	0x000000000b5dfd5c
	X[23]:	0x0000000000000000
	X[24]:	0x000000000b5dfd5c
	X[25]:	0x00000049a3ea3c20 (SP:-0x0180)
	X[26]:	0x000000000b5dfd5c
	X[27]:	0x000000000ad060f8 (sdk:0x1450f8)	=> 
	X[28]:	0x0000006619f3a060
	FP:	0x00000049a3ea3aa0 (SP)
	LR:	0x000000000ad07888 (sdk:0x146888)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x00000049a3ea3aa0 (SP)
	PC:	0x000000000af60bd4 (sdk:0x39fbd4)	=> 


00:00:26.202 |W| HLE.GuestThread.56 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.50 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.52 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.64 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.51 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.57 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.53 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.59 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.76 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.54 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.79 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.61 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.55 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.58 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.62 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.63 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.66 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.65 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.71 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.67 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.72 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.68 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.74 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.69 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.77 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.70 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.80 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.73 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.75 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.78 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.202 |W| HLE.GuestThread.81 KernelSvc : WaitForAddress() = TerminationRequested
00:00:26.205 |I| HLE.OsThread.15 AudioRenderer Stop: Stopping renderer id 0
00:00:26.205 |I| HLE.OsThread.15 AudioRenderer Stop: Stopped renderer id 0
00:00:26.205 |I| HLE.OsThread.15 AudioRenderer ReleaseSessionId: Unregistered renderer (0)
00:00:26.209 |I| AudioProcessor.Worker AudioRenderer Work: Stopping audio processor
00:00:26.243 |I| HLE.OsThread.15 AudioRenderer StopLocked: Stopped audio renderer
00:00:26.244 |E| HLE.GuestThread.48 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1933
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3461
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264`
