### ISSUE TITLE
[Bug] Crash when open setting menu or starting game.

### ISSUE THREAD

**Issue by kimbeast** [Ryujinx/Ryujinx#6329]
### Description of the issue

About a month ago, when I clicked the settings menu or tried to start a game, the emulator crashed with the following error:.
But I enjoyed playing games before.

```
Application: Ryujinx.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Silk.NET.Vulkan.Vk.EnumeratePhysicalDevices(Silk.NET.Vulkan.Instance, UInt32 ByRef, Silk.NET.Vulkan.PhysicalDevice ByRef)
   at Silk.NET.Vulkan.VkOverloads.EnumeratePhysicalDevices(Silk.NET.Vulkan.Vk, Silk.NET.Vulkan.Instance, System.Span`1<UInt32>, System.Span`1<Silk.NET.Vulkan.PhysicalDevice>)
   at Ryujinx.Graphics.Vulkan.VulkanInstance.EnumeratePhysicalDevices(Ryujinx.Graphics.Vulkan.VulkanPhysicalDevice[] ByRef)
   at Ryujinx.Graphics.Vulkan.VulkanInitialization.GetSuitablePhysicalDevices(Silk.NET.Vulkan.Vk)
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.GetPhysicalDevices()
   at Ryujinx.UI.Windows.SettingsWindow.UpdatePreferredGpuComboBox()
   at Ryujinx.UI.Windows.SettingsWindow..ctor(Ryujinx.UI.MainWindow, Gtk.Builder, Ryujinx.HLE.FileSystem.VirtualFileSystem, Ryujinx.HLE.FileSystem.ContentManager)
   at Ryujinx.UI.Windows.SettingsWindow..ctor(Ryujinx.UI.MainWindow, Ryujinx.HLE.FileSystem.VirtualFileSystem, Ryujinx.HLE.FileSystem.ContentManager)
   at Ryujinx.UI.MainWindow.Settings_Pressed(System.Object, System.EventArgs)
   at DynamicClass.InvokeStub_EventHandler.Invoke(System.Object, System.Span`1<System.Object>)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Delegate.DynamicInvoke(System.Object[])
   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)
   at GLib.SignalClosure.Invoke(GLib.ClosureInvokedArgs)
   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)
   at Gtk.Application.Run()
   at Ryujinx.Program.Main(System.String[])

```

### Reproduction steps

*  Click Setting
*  Start any game.

### Log file

Application: Ryujinx.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Silk.NET.Vulkan.Vk.EnumeratePhysicalDevices(Silk.NET.Vulkan.Instance, UInt32 ByRef, Silk.NET.Vulkan.PhysicalDevice ByRef)
   at Silk.NET.Vulkan.VkOverloads.EnumeratePhysicalDevices(Silk.NET.Vulkan.Vk, Silk.NET.Vulkan.Instance, System.Span`1<UInt32>, System.Span`1<Silk.NET.Vulkan.PhysicalDevice>)
   at Ryujinx.Graphics.Vulkan.VulkanInstance.EnumeratePhysicalDevices(Ryujinx.Graphics.Vulkan.VulkanPhysicalDevice[] ByRef)
   at Ryujinx.Graphics.Vulkan.VulkanInitialization.GetSuitablePhysicalDevices(Silk.NET.Vulkan.Vk)
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.GetPhysicalDevices()
   at Ryujinx.UI.Windows.SettingsWindow.UpdatePreferredGpuComboBox()
   at Ryujinx.UI.Windows.SettingsWindow..ctor(Ryujinx.UI.MainWindow, Gtk.Builder, Ryujinx.HLE.FileSystem.VirtualFileSystem, Ryujinx.HLE.FileSystem.ContentManager)
   at Ryujinx.UI.Windows.SettingsWindow..ctor(Ryujinx.UI.MainWindow, Ryujinx.HLE.FileSystem.VirtualFileSystem, Ryujinx.HLE.FileSystem.ContentManager)
   at Ryujinx.UI.MainWindow.Settings_Pressed(System.Object, System.EventArgs)
   at DynamicClass.InvokeStub_EventHandler.Invoke(System.Object, System.Span`1<System.Object>)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Delegate.DynamicInvoke(System.Object[])
   at GLib.Signal.ClosureInvokedCB(System.Object, GLib.ClosureInvokedArgs)
   at GLib.SignalClosure.Invoke(GLib.ClosureInvokedArgs)
   at GLib.SignalClosure.MarshalCallback(IntPtr, IntPtr, UInt32, IntPtr, IntPtr, IntPtr)
   at Gtk.Application.Run()
   at Ryujinx.Program.Main(System.String[])

### OS

Windows 11 Home 23H2

### Ryujinx version

1.1.1199

### CPU

AMD Ryzen Z1 Extreme ; 16 logical

### GPU

AMD Radeon

### RAM

8GB

**Comment by avikpl1911** [comment]
Has it been happening since then

**Comment by avikpl1911** [comment]
Did u try modifying the settings values while running the game

**Comment by kimbeast** [comment]
The strange thing is that it doesn't always happen.
After several attempts, in some cases (I don't know the exact pattern) I was able to enter the game or the settings.
I am trying to figure out what program caused the conflict.

**Comment by kimbeast** [comment]
I think that the symptom has been gone after removing the App, "OpenCL™, OpenGL®, and Vulkan® Compatibility Pack"

https://www.rogally.pro/blogs/app-crashing-fix-rog-ally

**Comment by Shahil-Ayato** [comment]
This should be posted on our discord as a support inquiry, this is an issue with your system not the emulator.
