### ISSUE TITLE
[Bug] After applying a game update to a game, the update is not applied

### ISSUE THREAD

**Issue by Modifyinc** [Ryujinx/Ryujinx#6391]
### Description of the issue

After upgrading to v1.1.1217, I lost all updates I had applied to my games. When checking the games individually, they still show the correct update is selected, but Ryujinx still shows it as 1.0.0 to the right of the game icons. Playing any of the games also shows v1.0.0 in the title screen, and game saves that were previously working with updates applied, now will not load due to a version mismatch.

Removing and re-adding the updates back did not fix it.
Deleting the Ryujinx folder under Appdata\Roaming\ did not fix it.
Re-downloading Ryujinx 1217 and installing in a different directory, and basically starting fresh, did not fix it.

NOTE: I tried to follow the instructions from the FAQ to post the issue on Discord, but it told me my account was too new to join Ryujinx. To please try again later...later being who knows when.

### Reproduction steps

Every time I open Ryujinx, then select and apply an update to any game.

### Log file

[Ryujinx_1.1.1217_2024-03-03_13-49-04.log](https://github.com/Ryujinx/Ryujinx/files/14474204/Ryujinx_1.1.1217_2024-03-03_13-49-04.log)

### OS

Windows 10

### Ryujinx version

1.1.1217

### Game version

1.0.0

### CPU

AMD FX 8350

### GPU

Nvidia GTX 1660 Super

### RAM

16 GB

### List of applied mods

None

**Comment by IsaacMarovitz** [comment]
This is a visual issue in the Avalonia UI

**Comment by F1ReB4LL** [comment]
A sub-problem with a particular game and its updates, UI crashes after adding an update when trying to open a list of updates.

```
Unhandled exception caught: System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.FormatException: The input string '1_6248' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1)
   at System.Number.ThrowOverflowOrFormatException[TChar,TInteger](ParsingStatus, ReadOnlySpan`1)
   at System.Number.ParseBinaryInteger[TChar,TInteger](ReadOnlySpan`1, NumberStyles, NumberFormatInfo)
   at System.Int32.Parse(ReadOnlySpan`1 s, NumberStyles style, IFormatProvider provider)
   at System.Version.TryParseComponent(ReadOnlySpan`1, String, Boolean, Int32& )
   at System.Version.ParseVersion(ReadOnlySpan`1, Boolean)
   at System.Version.Parse(String)
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel.<>c.<SortUpdates>b__24_0(TitleUpdateModel first, TitleUpdateModel second) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 141
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(Span`1, Comparison`1, Int32, Int32)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1, Int32, Comparison`1)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1, Comparison`1)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1, Comparison`1)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1, Comparison`1)
   at System.Collections.Generic.List`1.Sort(Comparison`1)
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel.SortUpdates() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 129
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel.LoadUpdates() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 122
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel..ctor(VirtualFileSystem virtualFileSystem, UInt64 titleId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 106
   at Ryujinx.Ava.UI.Windows.TitleUpdateWindow..ctor(VirtualFileSystem virtualFileSystem, UInt64 titleId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\TitleUpdateWindow.axaml.cs:line 29
   at Ryujinx.Ava.UI.Windows.TitleUpdateWindow.Show(VirtualFileSystem virtualFileSystem, UInt64 titleId, String titleName) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\TitleUpdateWindow.axaml.cs:line 36
   at Ryujinx.Ava.UI.Controls.ApplicationContextMenu.OpenTitleUpdateManager_Click(Object sender, RoutedEventArgs args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Controls\ApplicationContextMenu.axaml.cs:line 101
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode )
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 51
```

[Ryujinx_1.1.1221_2024-03-08_20-44-57.log](https://github.com/Ryujinx/Ryujinx/files/14541741/Ryujinx_1.1.1221_2024-03-08_20-44-57.log)
