### ISSUE TITLE
[Bug] Emulator crashes when stopping the emulation while playing games with the OpenGL renderer

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#6393]
### Description of the issue

The error in log shows as:

```
00:01:25.701 |W| GUI.WindowThread UI MakeCurrent: Failed to bind OpenGL context: SPB.Graphics.Exceptions.ContextException: MakeCurrent() failed with error 0xaa
   at SPB.Platform.WGL.WGLOpenGLContext.MakeCurrent(NativeWindowBase window)
   at Ryujinx.Ava.UI.Renderer.EmbeddedWindowOpenGL.MakeCurrent(Boolean unbind, Boolean shouldThrow) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Renderer\EmbeddedWindowOpenGL.cs:line 69
```

### Reproduction steps

1. Change to OpenGL
2. Stop emulation
3. Crash

### Log file

n/a

### OS

Windows 10

### Ryujinx version

1.1.1217

**Comment by LukeWarnut** [comment]
Remains an issue on Ryujinx 1.1.1363
