### ISSUE TITLE
[Bug]Unicorn Overlord Archive loading failed

### ISSUE THREAD

**Issue by EriczjrWinter** [Ryujinx/Ryujinx#6452]
### Description of the issue

For unknown reasons, when the game progresses to certain areas, its saves may fail to load and cause the emulator to crash.

### Reproduction steps

After reading one of the archives that triggered the issue, it can cause the problem to occur both on the title page and in the game.

### Log file

Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 277
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()

### OS

Window 10

### Ryujinx version

1.1.1221

### Game version

Unicorn Overlord 1.0.1 HK

### CPU

i7-11800H

### GPU

RTX 3060Laptop

### RAM

16GB

### List of applied mods

no mods

**Comment by EriczjrWinter** [comment]
Logs when
[Uploading Ryujinx_1.1.1222_2024-03-10_23-05-14.log…]()
 crash started

**Comment by JazzGlobal** [comment]
Do you know which archives you read to encounter this problem?

**Comment by EriczjrWinter** [comment]
> Do you know which archives you read to encounter this problem?

I do some test after that,Maybe is the game bug.
When I set myself up in a town in another country as a guard mercenary and fired them in the mercenary center of another country in the game, reading this save will only cause the game to freeze and crash.
I think for some reason, it seems that the game will try to read the data of these fired mercenaries and the guard information of the configured towns when reading saves, but they have already been fired by me before I remove the guard of the town, and then The game will attempt to read this invalid data.

**Comment by irrweg** [comment]
Have the same issues since Version 1.1.283. 
With Version 1.1.282 the game worked fine on my Steam Deck.

On Windows with AMD GPU it works fine with every version of Ryujinx.

Tried to downgrade manually but getting an error, without proper config of EmuDeck.
