### ISSUE TITLE
[Bug] Super Mario Party crashing at the beginning with Vulkan

### ISSUE THREAD

**Issue by TheEarthrise** [Ryujinx/Ryujinx#6478]
### Description of the issue

After setting up player count and pressing "OK" the whole emulator crashes instantly.

### Reproduction steps

Just start the game and press "OK", the emulator will crash. The game starts fine with OpenGL.

### Log file

```
00:00:13.138 |S| HLE.OsThread.7 ServiceHid EndPermitVibrationSession: Stubbed. 
00:00:13.337 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 125 ; appletResourceUserId: 1 ; type: JoyconLeft, JoyconRight}
00:00:21.122 |S| HLE.OsThread.7 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 6}
00:00:21.991 |S| HLE.OsThread.7 ServiceHid EndPermitVibrationSession: Stubbed. 
00:00:22.103 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 125 ; appletResourceUserId: 1 ; type: JoyconLeft, JoyconRight}
00:00:26.208 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 281
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\Window.cs:line 456
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 918
```

### OS

Windows 11

### Ryujinx version

1.1.1224

### Game version

1.1.0

### CPU

AMD Ryzen 7800X3D

### GPU

nVidia RTX 4090

### RAM

64 GB DDR5 6000

### List of applied mods

None.

**Comment by piplup55** [comment]
`ErrorDeviceLost` is a generic driver crash, you can't do much if anything about it, further more you didn't fill out the needed info and even deleted part of the template

**Comment by TheEarthrise** [comment]
Wow, just closing it like that? If the info is needed, then make it mandatory, which it isn't, that's why I removed it.

**Comment by TheEarthrise** [comment]
Besides that: the game is starting fine on Yuzu, so there should be something that is fixable.

**Comment by TheEarthrise** [comment]
So now you're marking my comments as spam? Maybe just ask for non-mandatory information if needed, instead of just closing bug reports?

**Comment by piplup55** [comment]
> make it mandatory

the reason it's not **mandatory** is so people don't have to fill it out when reporting a GUI issues this was discussed on discord iirc

> so now you're marking my comments as spam

i didn't mark anyone comment as spam

**Comment by TheEarthrise** [comment]
I can't read the whole discord to get something like that. This game is running fine with Volkan on "other emulators", so there should be a fix for that. I'm just using the latest nVidia drivers, so I can't believe this is not fixable. I'll add the hardware specs above.

**Comment by gdkchan** [comment]
I can reproduce it here on NVIDIA, so I will re-open the issue.

**Comment by gdkchan** [comment]
According to Muffin it's a regression caused by #4714, to be confirmed.

**Comment by Littl3Guy** [comment]
I get the crash as far back as 1.1.628
[Ryujinx_1.1.628_2024-03-13_15-10-16.log](https://github.com/Ryujinx/Ryujinx/files/14592922/Ryujinx_1.1.628_2024-03-13_15-10-16.log)

**Comment by GamerzHell9137** [comment]
> I get the crash as far back as 1.1.628 [Ryujinx_1.1.628_2024-03-13_15-10-16.log](https://github.com/Ryujinx/Ryujinx/files/14592922/Ryujinx_1.1.628_2024-03-13_15-10-16.log)

Not the same issue.

**Comment by Littl3Guy** [comment]
Well it crashes in the same spot with a simular error :shrug:

**Comment by Littl3Guy** [comment]
Fwiw the crash I'm getting is between 1.1.474 and 1.1.500

**Comment by GamerzHell9137** [comment]
> I get the crash as far back as 1.1.628 [Ryujinx_1.1.628_2024-03-13_15-10-16.log](https://github.com/Ryujinx/Ryujinx/files/14592922/Ryujinx_1.1.628_2024-03-13_15-10-16.log)

Can't replicate

**Comment by Littl3Guy** [comment]
Well I guess AMD GPU's broke with 1.1.499 and Nvidia broke with 1.1.821 (I notice both mention scaling)
[Ryujinx_1.1.499_2024-03-13_15-51-41.log](https://github.com/Ryujinx/Ryujinx/files/14593302/Ryujinx_1.1.499_2024-03-13_15-51-41.log)

**Comment by TheEarthrise** [comment]
I can confirm that the Vulkan crash with nVidia GPU starts from version 1.1.822. WIth version 1.1.821 the game starts fine.

**Comment by ArsenicBismuth** [comment]
@TheEarthrise Confirmed on my side, with Vulkan on Nvidia GPU, 1.1.821 works perfectly.

**Comment by Angelredondo** [comment]
I am having it crash on Steamdeck what can I do to stop it from crashing?

**Comment by legend800** [comment]
Just tried Super Mario Party on 1.1.1309 on Vulkan but confirm it still crashes post the Pad select screen. Log attached. Error:
"GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".

Works fine on OGL but obviously missing shadows in many games. Tried vsync on/off and Memory mode=software/fast, multi-threaded=on/off, clearing all caches but always crashes at that spot.

Config:
Windows 11 64-bit
GeForce GTX 3070
AMD Ryzen 5900x
32GB RAM

[Log.txt](https://github.com/Ryujinx/Ryujinx/files/15310847/Log.txt)

**Comment by Dropshock20XX** [comment]
Hey there y'all,

Admittedly I am still new to this, if anything else I just wanted to share my experience. I can replicate this issue on my end as well. The issue only occurs when I'm using Vulkan, and I tried both of my Nvidia GPU's. OpenGL works as a workaround, but not ideal. My logs show the same error mentioned in this thread: "ErrorOutOfDeviceMemory"

[Ryujinx.log](https://github.com/user-attachments/files/15922963/Ryujinx.log)

**Comment by zitapis-git** [comment]
Same here, problem only on Vulcan 

OS
Windows 11

Ryujinx version
1.1.1262

Game version
1.1.0

CPU
I7 14700K

GPU
nVidia RTX 4070ti  driver version 556.12

RAM
32 GB DDR5 5200

List of applied mods
None.

**Comment by jochuan** [comment]
This same crash is happening with me on vulkan

**Comment by zitapis-git** [comment]
I switched to Yuzu to play this game and i have to say it seems to be better so far. Also i found a  save file that has all characters unlocked for Yuzu which i couldnt find for Ryunjinx. I got it from here if anyone's interetsted https://gbatemp.net/threads/anyone-have-a-super-mario-party-save-with-all-the-mini-games-unlocked.521391/  (Timemaster comment)
