### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by bleachar** [Ryujinx/Ryujinx#6527]
### Description of the issue

Mario Party  Superstars

### Reproduction steps

After playing for a 5 min if it starts a mini game, the game crashes:

this is the log:
00:06:09.169 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 70576 bytes, profiled functions: 20822).
00:06:10.034 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 281
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 272
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 268
   at Ryujinx.Graphics.GAL.Multithreading.Commands.SetRenderTargetsCommand.Run(SetRenderTargetsCommand& command, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\Commands\SetRenderTargetsCommand.cs:line 21
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 918
   at System.Threading.Thread.StartCallback()

### Log file

[Ryujinx_1.1.1239_2024-03-18_20-51-18.log](https://github.com/Ryujinx/Ryujinx/files/14641865/Ryujinx_1.1.1239_2024-03-18_20-51-18.log)

### OS

Windows 11

### Ryujinx version

1.1.1239

### Game version

1.1.0

### CPU

i7-12700H

### GPU

Nnvidia RTX 3050

### RAM

16 GB

**Comment by Critical-shat** [comment]
Same here. think the vulkan compatibility for ryujinx needs to be updated

**Comment by MutantAura** [comment]
Please use the discord for general support: https://discord.gg/ryujinx
