### ISSUE TITLE
Prince Of Persia: The Lost Crown New Update Crash [Bug]

### ISSUE THREAD

**Issue by pedramalipour** [Ryujinx/Ryujinx#6567]
### Description of the issue

I run Prince Of Persia: The Lost Crown with latest update and dlc but it crash on startup. Also I run it on latest Ryujinx.
But it happend even with previous updates, if I disable update game run successfully but I need run with new update.

Ryujinx Version: 1.1.1247
Firmware: v17.0.1

![Screenshot 2024-03-27 173632](https://github.com/Ryujinx/Ryujinx/assets/20190573/767c08eb-5913-4c3d-bdb1-a04391ee8481)

### Reproduction steps

I just run game with below dlc and update and it crash!

![1](https://github.com/Ryujinx/Ryujinx/assets/20190573/e3479c30-641e-4f17-bfb8-ea49db446fc1)
![2](https://github.com/Ryujinx/Ryujinx/assets/20190573/63a2a9c4-b48e-4a90-8fc4-b10f68cc0bc2)

### Log file

00:00:10.198 |E| HLE.GuestThread.48 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1933
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3461
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
   at Ryujinx.Cpu.Jit.JitExecutionContext.SupervisorCallHandler(ExecutionContext context, UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 99
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\State\ExecutionContext.cs:line 156
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()
Unhandled exception. Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1933
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3461
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
   at Ryujinx.Cpu.Jit.JitExecutionContext.SupervisorCallHandler(ExecutionContext context, UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 99
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\State\ExecutionContext.cs:line 156
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1247

### Game version

17.0.1

### CPU

i3-10100

### GPU

Nvidia RTX 2060 Super 8 GB

### RAM

32 GB

**Comment by MetrosexualGarbodor** [comment]
We do not support custom builds. Download Ryujinx from our website and dump the game files from your Switch.
