### ISSUE TITLE
[Bug] Crash Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".

### ISSUE THREAD

**Issue by DiegcD** [Ryujinx/Ryujinx#6669]
### Description of the issue

Super Smash Brothers Ultimate with the HewDraw Remix mod crashes on the loading screen between the character select screen and the fight starting. On the screen that shows the characters that will fight.

### Reproduction steps

Copy the HDR mod to the correct folder
Launch the game
Select characters
Press + to start the fight
On the loading screen it crashes

### Log file

`00:06:08.387 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 281
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 273
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\Window.cs:line 344
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 925
   at System.Threading.Thread.StartCallback()`

### OS

Windows 11 Pro 22631.3447

### Ryujinx version

1.1.1281

### Game version

13.0.2

### CPU

i9-13900HX

### GPU

NVIDIA RTX 4070 Mobile

### RAM

32GB

### List of applied mods

HDR

### Additional context?

I'm a noob, hopefully the log can provide enough information to resolve the crash. I'm willing to provide more info if needed.

**Comment by MAX22hack** [comment]
Idk
