### ISSUE TITLE
[Bug] Unexpected API error "ErrorDeviceLost"

### ISSUE THREAD

**Issue by mjsommer** [Ryujinx/Ryujinx#6711]
### Description of the issue

New Ryujinx setup on Windows 11, running Splatoon 3, on initial game start, getting the following error:

```
00:00:16.211 |D| HLE.OsThread.8 ServiceNv PrintResult: EventSignal returned result Success
00:00:16.211 |W| HLE.OsThread.8 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:16.851 |D| AudioProcessor.Worker AudioRenderer Work: DSP too slow (exceeded by 26833500ns)
00:00:16.856 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
```

### Reproduction steps

1. Clean setup on Windows 11
2. Only one game installed, Splatoon 3
3. Start game
4. Colors and music starts, then game crashes

### Log file

```
00:00:16.210 |D| HLE.OsThread.8 ServiceNv AllocateRange: Allocating range from 0x324340000 to 0x324350000.
00:00:16.210 |D| HLE.OsThread.8 ServiceNv AllocateRange: Created smaller address range from 0x324350000 to 0x10000000000.
00:00:16.210 |D| HLE.OsThread.8 ServiceNv PrintResult: MapBufferEx returned result Success
00:00:16.211 |D| HLE.OsThread.8 ServiceNv PrintResult: EventSignal returned result Success
00:00:16.211 |W| HLE.OsThread.8 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:16.851 |D| AudioProcessor.Worker AudioRenderer Work: DSP too slow (exceeded by 26833500ns)
00:00:16.856 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 281
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 272
   at Ryujinx.Graphics.Vulkan.CommandBufferScoped.Dispose() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferScoped.cs:line 42
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 268
   at Ryujinx.Graphics.Vulkan.PipelineFull.SignalAttachmentChange() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 354
   at Ryujinx.Graphics.Vulkan.PipelineBase.SetRenderTargetColorMasks(ReadOnlySpan`1 componentMask) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1068
```

### OS

Windows 11

### Ryujinx version

1.1.1291

### Game version

1.0.0

### CPU

12th Gen Intel(R) Core(TM) i5-12400   2.50 GHz

### GPU

Intel UHD Graphics 730

### RAM

64GB :)

### List of applied mods

None

**Comment by mjsommer** [comment]
Update: The game "Mario Kart 8 Deluxe NSP, XCI ROM + v3.0.1 Update + All DLCs" works fine, whereas "Splatoon 3 NSP, XCI ROM + v7.2.0 Update + Side Order DLC" will crash the emulator on startup. They were both downloaded from: https://eggnsemulator.com/
