### ISSUE TITLE
[Bug] Breath of the Wild - Crash during early cutscene

### ISSUE THREAD

**Issue by LazerDickMcCheese** [Ryujinx/Ryujinx#6779]
### Description of the issue

During the prologue, the mandatory cutscene involving the old man at the Temple of Time crashes Ryujinx. I've tested multiple saves, but it keeps crashing the same frame the "+  skip" option pops up.

### Reproduction steps

I just played the prologue as expected, and it keeps crashing at a mandatory cutscene. No settings in Ryujinx have been changed, and it happens regardless of windowed or fullscreen.

### Log file

00:05:17.282 |E| HLE.OsThread.6 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.ReadBlock(CacheBlock block, Int64 index)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1297

### Game version

1.6.0

### CPU

i9-10900F

### GPU

NVIDIA GeForce RTX 2080

### RAM

16GB

### List of applied mods

I originally had the following "installed" (I have no idea if they were even working):
-Another Life Expansion
-Instant Cooking
-No Loot Boxes

 However, I removed them to see if that would fix the crash...it still crashes.

### Additional context?

Aside from a few fps dips, it was performing perfectly until this crash. Ryujinx completely closes.

**Comment by ekuland** [comment]
Your game files are corrupted. Redump them from your switch. Use the [discord ](https://discord.gg/ryujinx)for support instead.
