### ISSUE TITLE
[Bug] ServiceAudio GetWorkBufferSize: Library Revision REV12 is not supported!

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx#6792]
### Description of the issue

ANIMAL WELL - 010020D01AD24000 (both v1.0.0 and v 1.0.2) crashes with a weird message, probably indicating some missing Ryujinx feature?

```
00:00:04.822 |W| HLE.OsThread.15 ServiceAudio GetWorkBufferSize: Library Revision REV12 is not supported!
00:00:04.837 |I| HLE.OsThread.51 ServiceAm SetTerminateResult: Result = 0x00000499 (2153-0002).
00:00:04.905 |I| HLE.GuestThread.50 Cpu PrintGuestStackTrace: Guest stack trace:
Process: ANIMAL WELL, PID: 127
   0x000000002bf36e94	sdk:0x97e94	
   0x000000002bf36f48	sdk:0x97f48	
   0x000000002bf37028	sdk:0x98028	
   0x000000002c0834cc	sdk:0x1e44cc	
   0x00000000085127fc	main:0xd7fc	
   0x0000000008505e68	main:0x0e68	
   0x0000000008513a6c	main:0xea6c	nnMain:0x005c
   0x000000002bfa41e4	sdk:0x1051e4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000085000d8	rtld:0x00d8	


00:00:04.907 |I| HLE.GuestThread.50 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000004a10008510 (SP:-0x0200)
	X[02]:	0x0000000000000004
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000100000000
	X[09]:	0x000000002c9c3100
	X[10]:	0x0000000100000000
	X[11]:	0x0000000000000001
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000000
	X[15]:	0x000000000000000e
	X[16]:	0x000000002c996c20
	X[17]:	0x000000002bf387b0 (sdk:0x997b0)	=> nn::diag::detail::Abort(nn::Result const*)
	X[18]:	0x0000000000000000
	X[19]:	0x0000004a10008510 (SP:-0x0200)
	X[20]:	0x0000000000000000
	X[21]:	0x000000002c742f50
	X[22]:	0x000000002c742f50
	X[23]:	0x0000000000000000
	X[24]:	0x000000002c742f50
	X[25]:	0x0000004a10008490 (SP:-0x0180)
	X[26]:	0x000000002c742f50
	X[27]:	0x000000002bf36f48 (sdk:0x97f48)	=> 
	X[28]:	0x0000000000000000
	FP:	0x0000004a10008310 (SP)
	LR:	0x000000002bf387c8 (sdk:0x997c8)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x0000004a10008310 (SP)
	PC:	0x000000002c001868 (sdk:0x162868)	=> 


00:00:04.917 |W| HLE.GuestThread.52 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:04.963 |E| HLE.GuestThread.50 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1933
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3461
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
   at Ryujinx.Cpu.Jit.JitExecutionContext.SupervisorCallHandler(ExecutionContext context, UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 99
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\State\ExecutionContext.cs:line 156
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()
```

### Reproduction steps

Just run the game, crashes instantly, shows nothing.

### Log file

[Ryujinx_1.1.1298_ANIMAL_WELL_1.0.0_crash.log](https://github.com/Ryujinx/Ryujinx/files/15272839/Ryujinx_1.1.1298_ANIMAL_WELL_1.0.0_crash.log)
[Ryujinx_1.1.1298_ANIMAL_WELL_1.0.2_crash.log](https://github.com/Ryujinx/Ryujinx/files/15272840/Ryujinx_1.1.1298_ANIMAL_WELL_1.0.2_crash.log)

### OS

Windows 11

### Ryujinx version

1.1.1298

### Game version

1.0.0, 1.0.2

### CPU

i5-11400H

### GPU

NVIDIA GeForce RTX 3050 Laptop GPU

### RAM

24GB

**Comment by figgefigge** [comment]
Can confirm this issue on Linux for game version 1.0.0, 1.0.2 and 1.0.3. 

### Log 
[Ryujinx_1.1.1298+a23d8cb92f3f1bb8dc144f4d9fb3fddee749feae_2024-05-13_23-49-05.log](https://github.com/Ryujinx/Ryujinx/files/15300455/Ryujinx_1.1.1298%2Ba23d8cb92f3f1bb8dc144f4d9fb3fddee749feae_2024-05-13_23-49-05.log)

### OS 
Arch Linux x86_64 (Kernel: 6.8.9-arch1-1) 

### Ryujinx Version 
1.1.1298+a23d8cb92f3f1bb8dc144f4d9fb3fddee749feae

### Game version 
v1.0.3 
' ~/Downloads/Animal Well [NSP] ❯ cksum Animal\ Well\ \[010020D01AD24800\]\[v196608\].nsp                       1m 34s 00:42:15
254444031 38244118 Animal Well [010020D01AD24800][v196608].nsp
'

### CPU 
Intel i7-14700K

### GPU
Intel(R) Graphics (RPL-S) (Vulkan v1.3.274, Driver v24.0.6)

### RAM
32 GB
