### ISSUE TITLE
[Bug]Luigis Mansion Crash

### ISSUE THREAD

**Issue by Phoenix12309** [Ryujinx/Ryujinx#6811]
### Description of the issue

Ryujinx crash when i start the Game

### Reproduction steps

Dont can start the game

### Log file

00:00:07.744 |E| HLE.OsThread.6 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'None' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Ryujinx.HLE.FileSystem.ContentManager.GetLocation(UInt64 titleId, NcaContentType contentType, StorageId storageId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\FileSystem\ContentManager.cs:line 462
   at Ryujinx.HLE.FileSystem.ContentManager.GetInstalledStorage(UInt64 titleId, NcaContentType contentType, StorageId storageId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\FileSystem\ContentManager.cs:line 347
   at Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy.OpenDataStorageByDataId(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\IFileSystemProxy.cs:line 823
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object, Span`1, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object, Span`1, BindingFlags)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

### OS

Windowas 10

### Ryujinx version

17.0.0

### CPU

i3-4130

### GPU

NVIDIA GeForce GTX 960

### RAM

16 Gb

**Comment by MetrosexualGarbodor** [comment]
Update your keys and dump your DLC from your Switch again.

In the future, please use the discord's support channels for help, instead of opening issues.
