### ISSUE TITLE
crashes when load game

### ISSUE THREAD

**Issue by sir1st** [Ryujinx/Ryujinx#6816]
### Description of the issue

00:00:11.004 |E| HLE.OsThread.21 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletOE.ApplicationProxyService.ApplicationProxy.IApplicationFunctions: 180

Guest Stack Trace:
Process: Service, PID: 98

Raw Request Data:
00000000   01 00 20 00 03 00 00 00  00 00 00 00 00 00 00 00   ·· ·············
00000010   53 46 43 49 01 00 00 00  B4 00 00 00 00 00 00 00   SFCI····´·······
00000020   00 60 32 02 80 6F 00 01  00 00 00 00 00 00 00 00   ·`2·o··········
00000030   00 00 00 00                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 320
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1262
   at System.Threading.Thread.StartCallback()
ryujinx crashes when i load a game. anyone know anything about this log?

### Reproduction steps

just load the game animal crossing - the data transfer tools

### Log file

[Ryujinx_1.1.0-ldn3.1.3_2024-05-16_18-00-01.log](https://github.com/Ryujinx/Ryujinx/files/15333259/Ryujinx_1.1.0-ldn3.1.3_2024-05-16_18-00-01.log)

### OS

win10

### Ryujinx version

ava-ryujinx-1.1.0-ldn3.1.3-win_x64.zip

**Comment by piplup55** [comment]
The game you are trying to launch needs a service that we don't have, you can try ignore missing services, but I don't think that will work, you can add/move saves by right clicking the game and choose open device save, in future use the [discord](https://discord.gg/ryujinx) for support
