### ISSUE TITLE
A crash error with settings and Fullscreening

### ISSUE THREAD

**Issue by E-Tristan-E** [Ryujinx/Ryujinx#6864]
### Description of the issue

So with this bug, it happens in all of the games that I have attempted it with, the game with slow down, and crash after exiting the settings menu. Its a situational bug, but its annoyed me too many times not to bring up.

### Reproduction steps

The steps in order
1. Exit all Fullscreen modes. 
2. Enter the settings menu
3. Go to any other tab (like input), 
4. Press apply, then okay
5. Enter Fullscreen, (either through the Ryujinx menu, or through the windows tab.
6. The mouse Cursor should start buffering with a blue loading circle next to it.
7. The game will crash.
8. Then the coding will crash.

https://github.com/Ryujinx/Ryujinx/assets/97412338/45203ae0-b7a9-419b-ae1d-b1062b84b177

### Log file

[Ryujinx_1.1.1320_2024-05-23_21-03-35.log](https://github.com/Ryujinx/Ryujinx/files/15425796/Ryujinx_1.1.1320_2024-05-23_21-03-35.log)

### OS

Windows 11

### Ryujinx version

Latest as of 5/23/2024

### Game version

3.0.1

### CPU

AMD Ryzen 5 5500

### GPU

 NVIDIA NVIDIA GeForce RTX 3060 Ti (Vulkan v1.3.278, Driver v555.85.0.0)

### RAM

32 GB

### List of applied mods

Dynamic 20-120 FPS mod from gamebanana.

**Comment by MetrosexualGarbodor** [comment]
I just realized the original error that was posted in the Discord is not in this log.
[Ryujinx_1.1.1319_2024-05-22_22-20-29.log](https://github.com/user-attachments/files/15571333/Ryujinx_1.1.1319_2024-05-22_22-20-29.log)


``` 
00:03:03.638 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorInitializationFailed".
   at Ryujinx.Graphics.Vulkan.ResultExtensions.ThrowOnError(Result result) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\VulkanException.cs:line 20
   at Ryujinx.Graphics.Vulkan.Window.CreateSwapchain() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\Window.cs:line 163
   at Ryujinx.Graphics.Vulkan.Window.RecreateSwapchain() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\Window.cs:line 84
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\Window.cs:line 332
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 987
   at System.Threading.Thread.StartCallback()
```
I've been running into this fullscreening crash since around the time post-processing was added, but I've never seen an error in the logs or console whenever it happened, on an RTX 3070.

**Comment by xJusteen47** [comment]
i have this identical thing too
