### ISSUE TITLE
Wolfenstein II: The New Colossus

### ISSUE THREAD

**Issue by zephyren25** [Ryujinx/Ryujinx#687]
Crashes after Bethesda logo / warning screen

![image](https://user-images.githubusercontent.com/25546261/57180931-7db17b80-6e85-11e9-8225-1758a34efe8b.png)

Error code 0xEA01 `Time out. Also when you give 0 handles to svcWaitSynchronizationN.` 
(from [SwitchBrew](https://switchbrew.org/wiki/Error_codes#Error_codes))

```
0:01:51.411 | 0038 ServiceAm SetTerminateResult: Result = 0x0000ea01 (2001-0117).
00:01:58.484 | 0022 Cpu PrintGuestStackTrace: Guest stack trace:
Process: MERCURY, PID: 81
   sdk:0x000444a4 nn::diag::detail::VAbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, std::__va_list)
   sdk:0x0004455c nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, char const*, ...)
   sdk:0x00096a1c nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x0008d420 nn::os::WaitEvent(nn::os::EventType*)
   main:0x013d36f4 Sys_SignalWait(nn::os::Event*&, int)
   main:0x013423e0 idSysThread::ThreadProc(idSysThread*)
   sdk:0x00091b44 Sub000000000eb85b44
   sdk:0x00095b20 Sub000000000eb89b20
   sdk:0xfffffffff150bffc Subfffffffffffffffc


00:01:58.683 | 0022 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcSystem.cs:line 187
   at Break64(SvcHandler , CpuThreadState )
   at Sub000000000eba55d4(CpuThreadState , MemoryManager )
   at ChocolArm64.Translation.Translator.ExecuteSubroutine(CpuThreadState state, Int64 position) in C:\projects\ryujinx\ChocolArm64\Translation\Translator.cs:line 59
   at ChocolArm64.Translation.Translator.ExecuteSubroutine(CpuThread thread, Int64 position) in C:\projects\ryujinx\ChocolArm64\Translation\Translator.cs:line 51
   at ChocolArm64.CpuThread.<>c__DisplayClass14_0.<.ctor>b__0() in C:\projects\ryujinx\ChocolArm64\CpuThread.cs:line 35
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by AcK77** [comment]
Please could you open an issue here https://github.com/Ryujinx/Ryujinx-Games-List/issues/new and follow the template, thanks.
