### ISSUE TITLE
[Bug] ldn3 Ryujinx crash

### ISSUE THREAD

**Issue by DraftProducts** [Ryujinx/Ryujinx#6938]
### Description of the issue

The Ryujinx crash when starting Super Mario Bross. Wonder due to a issue with `IUserInterface` and `ngc:u`

### Reproduction steps

Try to start Super Mario Bross. Wonder with ldn3 from https://www.patreon.com/posts/introducing-ldn3-74910544

### Log file
```
00:00:06.040 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:06.041 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV11
00:00:06.055 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:06.056 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:06.062 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:06.098 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:06.120 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed.
00:00:06.121 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed.
00:00:06.522 |S| HLE.OsThread.21 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:06.522 |S| HLE.OsThread.21 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:06.892 |S| HLE.OsThread.21 ServiceAm LockExit: Stubbed.

00:00:07.073 |E| HLE.OsThread.4 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: ngc:u
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetService(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 112
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetServiceTipc(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 53
   at InvokeStub_IUserInterface.GetServiceTipc(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Ryujinx.HLE.HOS.Services.IpcService.CallTipcMethod(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\IpcService.cs:line 176
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 320
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1262
   at System.Threading.Thread.StartCallback()
```

### OS

Windows 11

### Ryujinx version

1.1.0-ldn3.1.3

### Game version

1.0.0

### CPU

Ryzen 7 7700X

### GPU

Radeon 6950 XT

### RAM

32GB

### Additional context?

![image](https://github.com/Ryujinx/Ryujinx/assets/29425008/8a3060be-e30f-4407-a617-0accc2b03e59)
![image](https://github.com/Ryujinx/Ryujinx/assets/29425008/a85af301-5688-4313-bde6-0c734294cb86)
![image](https://github.com/Ryujinx/Ryujinx/assets/29425008/2ae5d8f3-ceae-4fca-92d2-63ab99dedf89)

**Comment by MutantAura** [comment]
SMB: Wonder does not have LDN functionality. Use master.
