### ISSUE TITLE
ryujinx not working 

### ISSUE THREAD

**Issue by GuptaChinmay234** [Ryujinx/Ryujinx#694]
the error is Unhandled Exception: System.IO.FileNotFoundException: System archive with titleid 0100000000000823 was not found on Storage NandSystem. Found in None.
   at Ryujinx.HLE.HOS.Services.FspSrv.IFileSystemProxy.OpenDataStorageByDataId(ServiceCtx context) in C:\Users\gchin\OneDrive\Desktop\nintendo switch\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\FspSrv\IFileSystemProxy.cs:line 150
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\Users\gchin\OneDrive\Desktop\nintendo switch\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 110
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\Users\gchin\OneDrive\Desktop\nintendo switch\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 37
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\Users\gchin\OneDrive\Desktop\nintendo switch\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 140
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
pls help

**Comment by emmauss** [comment]
Please only use the issue tracker to report fully detailed issues.  You have not given any details on what you are running or anything. Use the support channel on the discord for any issues first. Thanks.
