### ISSUE TITLE
[Bug] Smash Ulitmate (13.0.1) Crash on Boot

### ISSUE THREAD

**Issue by SoulPunisher1** [Ryujinx/Ryujinx#6943]
### Description of the issue

The game can be ran base with no mods enabled, but when trying to put even just a simple skin mod, the game cannot even boot past the first black screen (not showing the loading icon). I get a ryujinx error in the log code:

> 00:00:22.033 |E| HLE.GuestThread.46 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000de3d000 (opcode 0x00000000) is undefined!
at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1096
   at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\State\ExecutionContext.cs:line 161
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
   at System.Threading.Thread.StartCallback()

### Reproduction steps

1. Install Smash Ultimate version 13.0.1.
2. Set up mod folder (using the steps shown in this guide: https://gamebanana.com/tuts/14311).
3. Ryujinx crashes.

### Log file

[Ryujinx_1.1.1330_2024-06-15_20-42-38.log](https://github.com/user-attachments/files/15856094/Ryujinx_1.1.1330_2024-06-15_20-42-38.log)

### OS

Windows 11

### Ryujinx version

1.1.1330

### Game version

13.0.1

### CPU

13th Gen Intel(R) Core(TM) i9-13900KF

### GPU

NVIDIA GeForce RTX 4090

### RAM

64 GB

### List of applied mods

Just a Captain Falcon Skin mod titled "Retro Falcon." It's placed in sdcard/ultimate/mods.

### Additional context?

The sdcard/atmosphere/contents/01006A800016E000/romfs/skyline/plugins folder has the following mod plugins setup:

- libarcropolis.nro
- libnro_hook.nro
- libone_slot_eff.nro
- libsmashline_plugin.nro

**Comment by SoulPunisher1** [comment]
Nevermind, turns out I had an incorrrect version of acropolis installed for the smash version I'm using.
