### ISSUE TITLE
[Bug] Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory"

### ISSUE THREAD

**Issue by Macrored** [Ryujinx/Ryujinx#6975]
### Description of the issue

After running DAVE THE DIVER using Ryujinx for a period of time, a crash occurred while switching map scenes in the game.

### Reproduction steps

After running DAVE THE DIVER using Ryujinx for a period of time, a crash occurred while switching map scenes in the game.

### Log file

```txt
00:40:10.433 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:40:10.876 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\WorkSpace\Code\cs\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 223
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map, Boolean isBuffer) in D:\WorkSpace\Code\cs\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 55
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, Device device, TextureCreateInfo info, Auto`1 foreignAllocation) in D:\WorkSpace\Code\cs\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 120
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\WorkSpace\Code\cs\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\WorkSpace\Code\cs\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\WorkSpace\Code\cs\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\WorkSpace\Code\cs\Ryujinx\src\Ryujinx\AppHost.cs:line 990

```

[Ryujinx_1.0.0-dirty+0afa8f2c14f046b46ac5ba14c96f3a5ce523ba16_2024-06-23_19-37-09.log.log](https://github.com/user-attachments/files/15949215/Ryujinx_1.0.0-dirty%2B0afa8f2c14f046b46ac5ba14c96f3a5ce523ba16_2024-06-23_19-37-09.log.log)

### OS

Windows 10

### Ryujinx version

1.1.1336

### Game version

1.0.2.651

### CPU

i5-9400F

### GPU

NVIDIA GeForce GTX 1050 Ti

### RAM

16GB

**Comment by ekuland** [comment]
We do not support dirty builds so the most you will get is this:
You ran out of vram. You're on a 4gb card and trying to render at 2x. Set that back to native.
