### ISSUE TITLE
[Bug] Ryujinx doesn't start

### ISSUE THREAD

**Issue by carlotraversa** [Ryujinx/Ryujinx#6989]
### Description of the issue

Ryujinx doesn't start. The Ryujinx console indefinitely loops an error message.

### Reproduction steps

Just run Ryujinx. The Ryujinx console indefinitely loops the error message:

|E| DwmRenderTimerLoop UI : [Error] [Visual] Exception when rendering: 'System.Runtime.InteropServices.COMException (0x80004002): QueryInterface failed
   at MicroCom.Runtime.MicroComProxyBase.QueryInterface[T]()
   at MicroCom.Runtime.MicroComRuntime.QueryInterface[T](IUnknown unknown)
   at Avalonia.Win32.WinRT.Composition.WinUiCompositionUtils.ClipVisual(ICompositor, Nullable`1, IVisual[] )
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindow..ctor(IEglWindowGlPlatformSurfaceInfo, WinUiCompositionShared, Nullable`1)
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindowSurface.CreateRenderTarget(IPlatformGraphicsContext, IntPtr)
   at Avalonia.Win32.OpenGl.Angle.AngleD3DTextureFeature.CreateRenderTarget(IGlContext, Object)
   at Avalonia.Skia.GlSkiaGpu.SurfaceWrapper.CreateGlRenderTarget(IGlContext)
   at Avalonia.Skia.GlRenderTarget..ctor(GRContext, IGlContext, IGlPlatformSurface)
   at Avalonia.Skia.GlSkiaGpu.TryCreateRenderTarget(IEnumerable`1)
   at Avalonia.Skia.SkiaContext.CreateRenderTarget(IEnumerable`1)
   at Avalonia.Rendering.PlatformRenderInterfaceContextManager.CreateRenderTarget(IEnumerable`1)
   at Avalonia.Rendering.Composition.Server.ServerCompositor.CreateRenderTarget(IEnumerable`1)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()' (ServerCompositor #1032856)

### Log file

[Ryujinx_1.1.1340_2024-06-28_17-31-05.log](https://github.com/user-attachments/files/16032857/Ryujinx_1.1.1340_2024-06-28_17-31-05.log)

### OS

Windows 10

### Ryujinx version

1.1.1340

### Game version

N/A

### CPU

Intel Core i7-7700HQ 2.8 GHz

### GPU

NVIDIA GeForce GTX 1050

### RAM

16GB

### List of applied mods

None

**Comment by emptysuns** [comment]
[Ryujinx_1.1.1401_2024-09-30_13-22-53.log](https://github.com/user-attachments/files/17184430/Ryujinx_1.1.1401_2024-09-30_13-22-53.log)

Yeah, I can't start it either.

```
00:00:02.817 |E| DwmRenderTimerLoop UI : [Error] [Visual] Exception when rendering: 'System.Runtime.InteropServices.COMException (0x80004002): QueryInterface failed
   at MicroCom.Runtime.MicroComProxyBase.QueryInterface[T]()
   at MicroCom.Runtime.MicroComRuntime.QueryInterface[T](IUnknown unknown)
   at Avalonia.Win32.WinRT.Composition.WinUiCompositionUtils.ClipVisual(ICompositor, Nullable`1, IVisual[] )
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindow..ctor(IEglWindowGlPlatformSurfaceInfo, WinUiCompositionShared, Nullable`1)
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindowSurface.CreateRenderTarget(IPlatformGraphicsContext, IntPtr)
   at Avalonia.Win32.OpenGl.Angle.AngleD3DTextureFeature.CreateRenderTarget(IGlContext, Object)
   at Avalonia.Skia.GlSkiaGpu.SurfaceWrapper.CreateGlRenderTarget(IGlContext)
   at Avalonia.Skia.GlRenderTarget..ctor(GRContext, IGlContext, IGlPlatformSurface)
   at Avalonia.Skia.GlSkiaGpu.TryCreateRenderTarget(IEnumerable`1)
   at Avalonia.Skia.SkiaContext.CreateRenderTarget(IEnumerable`1)
   at Avalonia.Rendering.PlatformRenderInterfaceContextManager.CreateRenderTarget(IEnumerable`1)
   at Avalonia.Rendering.Composition.Server.ServerCompositor.CreateRenderTarget(IEnumerable`1)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()' (ServerCompositor #3358863)
00:00:02.830 |E| DwmRenderTimerLoop UI : [Error] [Visual] Exception when rendering: 'System.Runtime.InteropServices.COMException (0x88980800): CreateDesktopWindowTarget failed
   at Avalonia.Win32.WinRT.Impl.__MicroComICompositorDesktopInteropProxy.CreateDesktopWindowTarget(IntPtr, Int32)
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindow..ctor(IEglWindowGlPlatformSurfaceInfo, WinUiCompositionShared, Nullable`1)
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindowSurface.CreateRenderTarget(IPlatformGraphicsContext, IntPtr)
   at Avalonia.Win32.OpenGl.Angle.AngleD3DTextureFeature.CreateRenderTarget(IGlContext, Object)
   at Avalonia.Skia.GlSkiaGpu.SurfaceWrapper.CreateGlRenderTarget(IGlContext)
   at Avalonia.Skia.GlRenderTarget..ctor(GRContext, IGlContext, IGlPlatformSurface)
   at Avalonia.Skia.GlSkiaGpu.TryCreateRenderTarget(IEnumerable`1)
   at Avalonia.Skia.SkiaContext.CreateRenderTarget(IEnumerable`1)
   at Avalonia.Rendering.PlatformRenderInterfaceContextManager.CreateRenderTarget(IEnumerable`1)
   at Avalonia.Rendering.Composition.Server.ServerCompositor.CreateRenderTarget(IEnumerable`1)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()' (ServerCompositor #3358863)
```
