### ISSUE TITLE
[Bug] Update Manager can fail to list updates when an added update contains letters

### ISSUE THREAD

**Issue by RupeeClock** [Ryujinx/Ryujinx#7021]
### Description of the issue

I encountered a title update management bug when trying to apply a v1.1.8 update to Sonic Superstars.
The initial impression was that Ryujinx did not recognise the update, but removing a previously loaded update v1.0.5A would allow the newer updates to be listed.
From previous use cases, the expectation was that I'd be able to load all updates against the title and it should list all of them.

Judging by the log file, it appears that the version string ending in "5A" is not being handled correctly, possibly due to containing a letter as compared to the other updates which lack them.
This handling error has manifested in three different ways:

* Adding multiple updates at once can result in no updates being listed, if the v1.0.5A update is among them
* Adding v1.1.5 and/or v.1.1.8 updates will not display if v1.0.5A has been previously added, and will only display once v1.0.5A is removed
* Adding v1.0.5A whilst v1.1.5 and/or v1.1.8 updates have been previously added, will not display the v1.0.5A update and will cause Ryujinx to unexpectedly quit upon removing either v1.1.5 or v1.1.8

### User data
* `Sonic Superstars [01008F701C074000][v0].xci` file dumped from game card using homebrew'd Switch + [nxdumptool](https://github.com/DarkMatterCore/nxdumptool/releases)
   * xci file does not include any update NSP
* `Sonic Superstars [01008F701C074800][v131072][UPD].nsp` - contains v1.0.5A
   * Will have been dumped using nxdumptool [v1.1.15](https://github.com/DarkMatterCore/nxdumptool/releases/tag/v1.1.15) from Feb 2022 
* `Sonic Superstars 1.1.5 [01008F701C074800][v262144][UPD].nsp`
* `Sonic Superstars 1.1.8 [01008F701C074800][v327680][UPD].nsp`
    * v1.1.5 and v1.1.8 updates will have been dumped using [nxdumptool-rewrite (latest commit build)](https://github.com/DarkMatterCore/nxdumptool/releases/tag/rewrite-prerelease)
* Ryujinx build v1.1.1345

### Steps to reproduce
* Launch Ryujinx and locate the game title from the games list
* Right-click and select "Manage Title Updates" to open the title's Update Manager modal
* Click "Add" and use file dialogue to add all three update NSP files
   * Ryujinx's Update Manager will not list any updates, and gives no response message
* Click Add and use file dialogue to add the v1.0.5a update NSP file
    * Ryujinx's Update Manager will list "Version 1.0.5A"
* Whilst Version 1.0.5A is listed, add the v1.1.5 and/or v1.1.8 NSP files
    * Ryujinx's Update Manager gives no response message and continues to only display "Version 1.0.5A"
* Click the Cross button next to "Version 1.0.5A" to remove the update
    * Ryujinx's Update Manger will now display the Version 1.1.5 and Version 1.1.8 updates that were added
* Whilst Versions 1.1.5 and 1.1.8 are listed, re-add the v1.0.5A NSP
    * Ryujinx's Update Manager gives no response message and continues to only display Versions 1.1.5 and 1.1.8
* Click the Cross button next to "Version 1.1.5" or "Version 1.1.8" to remove the update
    * Ryujinx will unexpectedly quit with an `System.InvalidOperationException` error written to log file.

### Video demo
https://github.com/user-attachments/assets/1a2650a2-a41a-4121-938b-2b3d8904aa8b

### Log file
[Ryujinx_1.1.1345_2024-07-12_16-35-38.log](https://github.com/user-attachments/files/16196477/Ryujinx_1.1.1345_2024-07-12_16-35-38.log)

### Log excerpt
```
00:00:29.735 |E| Application : Unhandled exception caught: System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.FormatException: The input string '5A' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1)
   at System.Number.ThrowOverflowOrFormatException[TChar,TInteger](ParsingStatus, ReadOnlySpan`1)
   at System.Number.ParseBinaryInteger[TChar,TInteger](ReadOnlySpan`1, NumberStyles, NumberFormatInfo)
   at System.Int32.Parse(ReadOnlySpan`1 s, NumberStyles style, IFormatProvider provider)
   at System.Version.TryParseComponent(ReadOnlySpan`1, String, Boolean, Int32& )
   at System.Version.ParseVersion(ReadOnlySpan`1, Boolean)
   at System.Version.Parse(String)
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel.<>c.<SortUpdates>b__24_0(TitleUpdateModel first, TitleUpdateModel second) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 141
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(Span`1, Comparison`1, Int32, Int32)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1, Int32, Comparison`1)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1, Comparison`1)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1, Comparison`1)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1, Comparison`1)
   at System.Collections.Generic.List`1.Sort(Comparison`1)
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel.SortUpdates() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 129
   at Ryujinx.Ava.UI.ViewModels.TitleUpdateViewModel.RemoveUpdate(TitleUpdateModel update) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\TitleUpdateViewModel.cs:line 204
   at Ryujinx.Ava.UI.Windows.TitleUpdateWindow.RemoveUpdate(Object sender, RoutedEventArgs e) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\TitleUpdateWindow.axaml.cs:line 93
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object, RoutedEventArgs)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice, UInt64, IInputRoot, Point, PointerPointProperties, KeyModifiers, IInputElement )
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr, UInt32, IntPtr, IntPtr)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 52
```

### OS

Windows 10 v22H2

### Ryujinx version

1.1.1345

### Game version

n/a

### CPU

Intel Core i7-12700K

### GPU

NVIDIA RTX 3070

### RAM

32GB DDR5 (2x16GB)

### Additional context?

Not an emulation issue; front-end update management issue.

**Comment by piplup55** [comment]
this is purely a gui bug/crash if you edit the dlc.json manually the game can still load but this isn't ideal (this can also be used to fix the crashing issue)
![image](https://github.com/user-attachments/assets/f84b51bc-6b96-4b9c-ad61-0d31a7639c1b)
![image](https://github.com/user-attachments/assets/49887edc-9996-4236-995c-733309b199bb)
![image](https://github.com/user-attachments/assets/022d07d8-676a-4aa4-b68b-09c2019db0e0)
this bug is also ava specific GTK was never affected by this issue
![image](https://github.com/user-attachments/assets/959b46d8-c8f6-4628-8cae-8645d3f99518)

**Comment by RupeeClock** [comment]
I've further identified that if all three updates in my use case have been set in the `updates.json` file's `paths` array for this title ID, that opening the title's update manager in Ryujinx will cause an immediate crash.
Thanks @piplup55 for the pointer about the `dlc.json` and `updates.json` files.

**Comment by IsaacMarovitz** [comment]
@RupeeClock When the build is up, please check if #7043 resolves this issue.

**Comment by RupeeClock** [comment]
>When the build is up, please check if #7043 resolves this issue.
@IsaacMarovitz build Ryujinx Version: 1.1.0+dd4b358 for Windows doesn't appear to fix the issue and instead introduces a new issue.
Managing a title's updates where the user has previously added any update NSP files will cause a crash when re-opening.
Updates bundled inside of an XCI file are not affected.

[Ryujinx_1.1.0+dd4b358_2024-07-17_20-00-14.log](https://github.com/user-attachments/files/16273589/Ryujinx_1.1.0%2Bdd4b358_2024-07-17_20-00-14.log)

Excerpt:
```
C:\Users\[redacted]\AppData\Roaming\Ryujinx\games\010084500c7dc000\updates.json
00:00:47.265 |E| Application : Unhandled exception caught: System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.FormatException: The input string 'System' was not in a correct format.
```

Will produce a video recording shortly.

**Comment by RupeeClock** [comment]
@IsaacMarovitz video recording of build Ryujinx Version: 1.1.0+dd4b358, it demonstrates that it will only list one update at a time.
Can reproduce with any title where you have more than one update file, not just Sonic Superstars.


https://github.com/user-attachments/assets/b97e0df1-5117-4ecf-bd67-cf1099f8a8c3
