### ISSUE TITLE
[Bug] crashing on open after 1.1.1350 update due to MissingKeyException despite prod.keys being present

### ISSUE THREAD

**Issue by slickochet** [Ryujinx/Ryujinx#7039]
### Description of the issue

Since updating to new build today 1.1.1350 Ryujinx crashes on scanning games.  Nothing else has changed.  Log file complains about keys file which is still in place and has not moved or changed.

### Reproduction steps

Start Ryujinx

### Log file

00:00:13.320 |E| Application HandleFirmwareInstallation: LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_11
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index, Int64 offset, UInt64 upperCounter)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel, Boolean leaveCompressed)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(NcaSectionType type, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.ContentManager.<VerifyFirmwarePackage>g__VerifyAndGetVersionZip|43_1(ZipArchive archive, <>c__DisplayClass43_0&) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\FileSystem\ContentManager.cs:line 708
   at Ryujinx.HLE.FileSystem.ContentManager.VerifyFirmwarePackage(String firmwarePackage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\FileSystem\ContentManager.cs:line 616
   at Ryujinx.Ava.UI.ViewModels.MainWindowViewModel.HandleFirmwareInstallation(String filename) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\ViewModels\MainWindowViewModel.cs:line 1011
00:01:18.184 |E| GUI.ApplicationLibraryThread Application : Unhandled exception caught: LibHac.Common.Keys.MissingKeyException: Unable to decrypt NCA section.
Key Type: Common
Key Name: key_area_key_application_11
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetDecryptedKey(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index, Int64 offset, UInt64 upperCounter)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel, Boolean leaveCompressed)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.Loaders.Processes.Extensions.NcaExtensions.GetCnmt(Nca cnmtNca, IntegrityCheckLevel checkLevel, ContentMetaType metaType) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Loaders\Processes\Extensions\NcaExtensions.cs:line 239
   at Ryujinx.HLE.Loaders.Processes.Extensions.PartitionFileSystemExtensions.GetContentData(IFileSystem partitionFileSystem, ContentMetaType contentType, VirtualFileSystem fileSystem, IntegrityCheckLevel checkLevel) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Loaders\Processes\Extensions\PartitionFileSystemExtensions.cs:line 35
   at Ryujinx.UI.App.Common.ApplicationLibrary.GetApplicationsFromPfs(IFileSystem pfs, String filePath) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 178
   at Ryujinx.UI.App.Common.ApplicationLibrary.GetApplicationFromNsp(PartitionFileSystem pfs, String filePath) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 151
   at Ryujinx.UI.App.Common.ApplicationLibrary.TryGetApplicationsFromFile(String applicationPath, List`1& applications) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 305
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 555
   at Ryujinx.Ava.UI.Windows.MainWindow.<ReloadGameList>b__77_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\MainWindow.axaml.cs:line 625
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1350

### CPU

Ryzen 7800X3D

### GPU

AMD 7900XTX

### RAM

16GB

### List of applied mods

None.

**Comment by ekuland** [comment]
You need to redump your keys with updated tools. They're out of date.
