### ISSUE TITLE
ryujinx not starting

### ISSUE THREAD

**Issue by lestinkythingy** [Ryujinx/Ryujinx#7061]
### Description of the issue

everytime i try running ryujinx, the console opens, and for a bit there is a see-through window of the actual application, but then in the console i get a error message (look in log file) and the console and the application close.
i have tried uninstalling and re installing ryujinx multiple times, but i keep geting the same message in the console, does anyone know how i can fix this?

### Reproduction steps

i am unsure of how to recreate this

### Log file

00:00:03.851 |E| GUI.ApplicationLibraryThread Application : Unhandled exception caught: LibHac.Common.HorizonResultException: ResultFsPartitionSignatureVerificationFailed (2002-4644)
   at LibHac.Common.ThrowHelper.ThrowResult(Result result)
   at LibHac.Result.ThrowIfFailure()
   at Ryujinx.UI.App.Common.ApplicationLibrary.TryGetApplicationsFromFile(String applicationPath, List`1& applications) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 304
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 556
   at Ryujinx.Ava.UI.Windows.MainWindow.<ReloadGameList>b__77_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\MainWindow.axaml.cs:line 625
   at System.Threading.Thread.StartCallback()

### OS

11

### Ryujinx version

newest version

**Comment by ptexia** [comment]
00:00:00.003 |N| Application ReloadConfig: Loading configuration from: C:\Users\[redacted]\AppData\Roaming\Ryujinx\Config.json
00:00:00.223 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.263 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.270 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.270 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.271 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.272 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.272 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.273 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x73BF
00:00:00.274 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.274 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.274 |I| Configuration LogValueChange: ScalingFilterLevel set to: 100
00:00:00.276 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.282 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.282 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.282 |I| Configuration LogValueChange: EnableTextureRecompression set to: True
00:00:00.282 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.282 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.282 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.282 |I| Configuration LogValueChange: EnableInternetAccess set to: True
00:00:00.282 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.282 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.283 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.283 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.284 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMapped
00:00:00.284 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.284 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.284 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.287 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.291 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1352
00:00:00.296 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.296 |N| Application Print: CPU: AMD Ryzen 9 5900X 12-Core Processor ; 24 logical
00:00:00.297 |N| Application Print: RAM: Total 31.9 GiB ; Available 4.1 GiB
00:00:00.299 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.300 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:03.724 |E| Application BeginParse: Response status code does not indicate success: 403 (rate limit exceeded).
00:00:03.725 |E| Application CreateErrorDialog: An error has occurred when trying to get release information from GitHub Release. This can be caused if a new release is being compiled by GitHub Actions. Try again in a few minutes.
00:00:07.488 |E| GUI.ApplicationLibraryThread Application : Unhandled exception caught: LibHac.Common.HorizonResultException: ResultFsPartitionSignatureVerificationFailed (2002-4644)
   at LibHac.Common.ThrowHelper.ThrowResult(Result result)
   at Ryujinx.UI.App.Common.ApplicationLibrary.TryGetApplicationsFromFile(String applicationPath, List`1& applications) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 304
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 556
   at Ryujinx.Ava.UI.Windows.MainWindow.<ReloadGameList>b__77_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\MainWindow.axaml.cs:line 625
   at System.Threading.Thread.StartCallback()
Unhandled exception. LibHac.Common.HorizonResultException: ResultFsPartitionSignatureVerificationFailed (2002-4644)
   at LibHac.Common.ThrowHelper.ThrowResult(Result result)
   at Ryujinx.UI.App.Common.ApplicationLibrary.TryGetApplicationsFromFile(String applicationPath, List`1& applications) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 304
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.UI.Common\App\ApplicationLibrary.cs:line 556
   at Ryujinx.Ava.UI.Windows.MainWindow.<ReloadGameList>b__77_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Windows\MainWindow.axaml.cs:line 625
   at System.Threading.Thread.StartCallback()

same issue as you yes?
