### ISSUE TITLE
[Bug] Mario Kart 8 Deluxe crashing only on first startup

### ISSUE THREAD

**Issue by mcost45** [Ryujinx/Ryujinx#7096]
### Description of the issue

I am consistently experiencing Mario Kart 8 Deluxe crashing Ryujinx, only when it's opened for the first time.

After the initial crash, I can relaunch and freely run it without any errors. It seems like the issue only 'resets' after my PC is restarted.

### Reproduction steps

1. Restart PC
2. Run Mario Kart 8 Deluxe
3. Ryujinx crashes

### Log file

Crash on initial start: [Ryujinx_1.1.1359_2024-07-23_09-16-41.log](https://github.com/user-attachments/files/16345097/Ryujinx_1.1.1359_2024-07-23_09-16-41.log)

Successful start after launching Ryujinx again: 
[Ryujinx_1.1.1359_2024-07-23_09-21-52.log](https://github.com/user-attachments/files/16345121/Ryujinx_1.1.1359_2024-07-23_09-21-52.log)

### OS

Windows 11

### Ryujinx version

1.1.1359

### Game version

3.0.1

### CPU

i5-14600K

### GPU

NVIDIA 4070 Ti Super

### RAM

64GB

### Additional context?

`Use alternative memory layout` is enabled...

**Comment by stonerl** [comment]
I do have similar crashes on first startup on macOS. But occasionally, it also crashes when I let the game idle for a long time on the title screen. Here is the debug output:

```
00:11:59.901 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 2): Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)
00:11:59.901 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 2): Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)
00:11:59.901 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 2): Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)
00:11:59.901 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 2): Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)
00:11:59.901 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 2): Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)
00:11:59.905 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 2): Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.909 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.910 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.910 |E| .NET TP Worker [mvk-error] VK_ERROR_DEVICE_LOST: MTLCommandBuffer "vkQueueSubmit CommandBuffer on Queue 0-0" execution failed (code 4): Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
00:11:59.923 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in /Users/[redacted]/Developer/Ryujinx/src/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 279
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in /Users/[redacted]/Developer/Ryujinx/src/Ryujinx.Graphics.Vulkan/PipelineFull.cs:line 261
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id, Boolean strict) in /Users/[redacted]/Developer/Ryujinx/src/Ryujinx.Graphics.Vulkan/SyncManager.cs:line 50
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /Users/[redacted]/Developer/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in /Users/[redacted]/Developer/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in /Users/[redacted]/Developer/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in /Users/[redacted]/Developer/Ryujinx/src/Ryujinx/AppHost.cs:line 1000
   at System.Threading.Thread.StartCallback()
Unhandled exception. Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in /Users/toni/Developer/Ryujinx/src/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 279
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in /Users/toni/Developer/Ryujinx/src/Ryujinx.Graphics.Vulkan/PipelineFull.cs:line 261
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id, Boolean strict) in /Users/toni/Developer/Ryujinx/src/Ryujinx.Graphics.Vulkan/SyncManager.cs:line 50
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in /Users/toni/Developer/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in /Users/toni/Developer/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in /Users/toni/Developer/Ryujinx/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in /Users/toni/Developer/Ryujinx/src/Ryujinx/AppHost.cs:line 1000
   at System.Threading.Thread.StartCallback()
```

**Comment by RiedleroD** [comment]
for me it freezes every second time, always at the moment where the opening fanfare is done and the "press LB+RB" thingy shows up. Since it doesn't seem to un-freeze and crash for me, I have to SIGKILL it, which is kind of annoying…

**Comment by P3rf3ctXZer0** [comment]
Make sure you get in cup before going fullscreen this seems to fix it.

**Comment by P3rf3ctXZer0** [comment]
This crashes after each grand prix for me. It seems to mainly crash in menus.

**Comment by Peppercorn27** [comment]
> for me it freezes every second time, always at the moment where the opening fanfare is done and the "press LB+RB" thingy shows up. Since it doesn't seem to un-freeze for me, I have to SIGKILL it, which is kind of annoying…

Exact same issue for me. Opening and closing Ryu + MK8, crashes on title screen every second time. Same thing happens on my Steam Deck.

**Comment by NikoFromOneshot** [comment]
Okay, it sucked but I was able to catch an image of Ryujinx's console right on the crash.

boom

![image](https://github.com/user-attachments/assets/31ed79f2-3593-4a0e-8f2c-55e9c2dc71b9)
(ignore the Nvidia overlay)

So, it's writing or reading protected memory for some reason, not sure if this is what the other people are experiencing but I sure as hell am experiencing it.
