### ISSUE TITLE
LDN version cant load games in folder

### ISSUE THREAD

**Issue by TheRealNOIG** [Ryujinx/Ryujinx#7125]
### Description of the issue

LDN Version 3.1.3 on Ryujinx 1.1.0 cant load games from folder
Works fine on main branch 1.1..1361 non LDN version

Running firmware version 18.1.0 but also tried on a 15.0.1 version

Error
``````
The file encountered was not of a valid type. File: 'E:\ISO\Switch_Game.xci' Error: LibHac.Common.HorizonResultException: ResultFsPartitionSignatureVerificationFailed (2002-4644): Invalid Partition FS type "?L??"
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.PartitionFileSystemHeader..ctor(BinaryReader reader)
   at LibHac.FsSystem.PartitionFileSystem..ctor(IStorage storage)
   at Ryujinx.HLE.HOS.ApplicationLoader.GetGameUpdateData(VirtualFileSystem fileSystem, String titleId, Int32 programIndex, String& updatePath) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 205
   at Ryujinx.Ui.App.Common.ApplicationLibrary.IsUpdateApplied(String titleId, IFileSystem& updatedControlFs) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 801
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 252
```
   ```

### Reproduction steps

Load Games folder on LDN version

### Log file

00:00:00.002 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.025 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.027 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.028 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.028 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.028 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.029 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.029 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x744C
00:00:00.029 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.030 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.030 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.030 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.034 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.034 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.034 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.034 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.034 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.034 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.034 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.034 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.035 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.035 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.035 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.035 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.035 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.035 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.036 |I| Configuration LogValueChange: MultiplayerMode set to: LdnRyu
00:00:00.036 |I| Configuration LogValueChange: DisableP2p set to: False
00:00:00.039 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.0-ldn3.1.3
00:00:00.041 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.041 |N| Application Print: CPU: 13th Gen Intel(R) Core(TM) i7-13700KF ; 24 logical
00:00:00.042 |N| Application Print: RAM: Total 65379 MiB ; Available 45774 MiB
00:00:00.043 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.043 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:13.488 |W| Application LoadApplications: The file encountered was not of a valid type. File: 'E:\ISO\Switch_Game.xci' Error: LibHac.Common.HorizonResultException: ResultFsPartitionSignatureVerificationFailed (2002-4644): Invalid Partition FS type "?L??"
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.PartitionFileSystemHeader..ctor(BinaryReader reader)
   at LibHac.FsSystem.PartitionFileSystem..ctor(IStorage storage)
   at Ryujinx.HLE.HOS.ApplicationLoader.GetGameUpdateData(VirtualFileSystem fileSystem, String titleId, Int32 programIndex, String& updatePath) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 205
   at Ryujinx.Ui.App.Common.ApplicationLibrary.IsUpdateApplied(String titleId, IFileSystem& updatedControlFs) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 801
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 252


### OS

Windows 10

### Ryujinx version

1.1.0

### Game version

_No response_

### CPU

i7 8600KF

### GPU

AMD 7800XT

### RAM

32GB

### List of applied mods

_No response_

### Additional context?

_No response_

**Comment by piplup55** [comment]
whatever you are trying to load is a broken game file, redump the affected game(s) from your switch
