### ISSUE TITLE
[Bug] game cannot launch directly from command line but it is ok on double click on GUI

### ISSUE THREAD

**Issue by asanoic** [Ryujinx/Ryujinx#7130]
### Description of the issue

open Rynjinx and double click game, game load successfully. but if when I launch game by using
./Rynjinx [game_rom_path], Ryujinx crashes

```
00:00:00.047 |N| GUI.ApplicationLibraryThread Application : Unhandled exception caught: System.IO.IOException: The process cannot access the file '/home/[redacted]/.var/app/org.ryujinx.Ryujinx/config/Ryujinx/games/0100300012f2a000/gui/metadata.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Int64& , UnixFileMode& )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, UnixFileMode, Int64& , UnixFileMode& , Boolean, Boolean& , Func`4 )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 , Func`4 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.UnixFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream, String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions)
   at System.IO.File.Create(String, Int32, FileOptions)
   at Ryujinx.Common.Utilities.JsonHelper.SerializeToFile[T](String filePath, T value, JsonTypeInfo`1 typeInfo) in /run/build/Ryujinx/src/Ryujinx.Common/Utilities/JsonHelper.cs:line 46
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadAndSaveMetaData(String titleId, Action`1 modifyFunction) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 631
   at Ryujinx.UI.App.Common.ApplicationLibrary.TryGetApplicationsFromFile(String applicationPath, List`1& applications) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 425
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 548
   at Ryujinx.Ava.UI.Windows.MainWindow.<ReloadGameList>b__77_0() in /run/build/Ryujinx/src/Ryujinx/UI/Windows/MainWindow.axaml.cs:line 625
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.IO.IOException: The process cannot access the file '/home/deck/.var/app/org.ryujinx.Ryujinx/config/Ryujinx/games/0100300012f2a000/gui/metadata.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Int64& , UnixFileMode& )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, UnixFileMode, Int64& , UnixFileMode& , Boolean, Boolean& , Func`4 )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 , Func`4 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.UnixFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream, String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions)
   at System.IO.File.Create(String, Int32, FileOptions)
   at Ryujinx.Common.Utilities.JsonHelper.SerializeToFile[T](String filePath, T value, JsonTypeInfo`1 typeInfo) in /run/build/Ryujinx/src/Ryujinx.Common/Utilities/JsonHelper.cs:line 46
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadAndSaveMetaData(String titleId, Action`1 modifyFunction) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 631
   at Ryujinx.UI.App.Common.ApplicationLibrary.TryGetApplicationsFromFile(String applicationPath, List`1& applications) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 425
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 548
   at Ryujinx.Ava.UI.Windows.MainWindow.<ReloadGameList>b__77_0() in /run/build/Ryujinx/src/Ryujinx/UI/Windows/MainWindow.axaml.cs:line 625
   at System.Threading.Thread.StartCallback()
/app/bin/ryujinx-wrapper: line 7:    13 Aborted                 (core dumped) Ryujinx.sh "$@"
```

### Reproduction steps

launch game from command line, some work, some not. but double click on GUI, all loads well.

### Log file

```
00:00:00.047 |N| GUI.ApplicationLibraryThread Application : Unhandled exception caught: System.IO.IOException: The process cannot access the file '/home/[redacted]/.var/app/org.ryujinx.Ryujinx/config/Ryujinx/games/0100300012f2a000/gui/metadata.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Int64& , UnixFileMode& )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, UnixFileMode, Int64& , UnixFileMode& , Boolean, Boolean& , Func`4 )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 , Func`4 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.UnixFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream, String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions)
   at System.IO.File.Create(String, Int32, FileOptions)
   at Ryujinx.Common.Utilities.JsonHelper.SerializeToFile[T](String filePath, T value, JsonTypeInfo`1 typeInfo) in /run/build/Ryujinx/src/Ryujinx.Common/Utilities/JsonHelper.cs:line 46
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadAndSaveMetaData(String titleId, Action`1 modifyFunction) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 631
   at Ryujinx.UI.App.Common.ApplicationLibrary.TryGetApplicationsFromFile(String applicationPath, List`1& applications) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 425
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 548
   at Ryujinx.Ava.UI.Windows.MainWindow.<ReloadGameList>b__77_0() in /run/build/Ryujinx/src/Ryujinx/UI/Windows/MainWindow.axaml.cs:line 625
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.IO.IOException: The process cannot access the file '/home/deck/.var/app/org.ryujinx.Ryujinx/config/Ryujinx/games/0100300012f2a000/gui/metadata.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Int64& , UnixFileMode& )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, UnixFileMode, Int64& , UnixFileMode& , Boolean, Boolean& , Func`4 )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 , Func`4 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.UnixFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream, String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions)
   at System.IO.File.Create(String, Int32, FileOptions)
   at Ryujinx.Common.Utilities.JsonHelper.SerializeToFile[T](String filePath, T value, JsonTypeInfo`1 typeInfo) in /run/build/Ryujinx/src/Ryujinx.Common/Utilities/JsonHelper.cs:line 46
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadAndSaveMetaData(String titleId, Action`1 modifyFunction) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 631
   at Ryujinx.UI.App.Common.ApplicationLibrary.TryGetApplicationsFromFile(String applicationPath, List`1& applications) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 425
   at Ryujinx.UI.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage) in /run/build/Ryujinx/src/Ryujinx.UI.Common/App/ApplicationLibrary.cs:line 548
   at Ryujinx.Ava.UI.Windows.MainWindow.<ReloadGameList>b__77_0() in /run/build/Ryujinx/src/Ryujinx/UI/Windows/MainWindow.axaml.cs:line 625
   at System.Threading.Thread.StartCallback()
/app/bin/ryujinx-wrapper: line 7:    13 Aborted                 (core dumped) Ryujinx.sh "$@"
```

### OS

Steam Deck OS

### Ryujinx version

1.1.1361

**Comment by nlflint** [comment]
Duplicate: https://github.com/Ryujinx/Ryujinx/pull/7116
