### ISSUE TITLE
[Bug] Pokemon Legends Arceus v1.1.1 Not Working

### ISSUE THREAD

**Issue by i0x404** [Ryujinx/Ryujinx#7161]
### Description of the issue

Hello,
I've been using ryujinx emulator to playa pokemon legends arceus and the v1.0.0 works but when I install the last update it crashes.

### Reproduction steps

Instal v1.1.1 on pokemon legends arceus

### Log file

00:00:00.684 |N| Application LoadGuestApplication: Using Firmware Version: 18.0.1
00:00:03.379 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce 920M (Vulkan v1.2.175, Driver v474.64.0.0)
00:00:12.230 |E| HLE.OsThread.2 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.FsSrv.Impl.StorageInterfaceAdapter.Read(Int64 offset, OutBuffer destination, Int64 size)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1255
   at System.Threading.Thread.StartCallback()

### OS

Windows 10

### Ryujinx version

1.1.1371

### Game version

1.1.1

### CPU

i5-5200u

### GPU

Nvidia 920m

### RAM

8

### List of applied mods

none

**Comment by piplup55** [comment]
your update file is corrupted, redump it from your switch, while your at it you can update those drivers
