### ISSUE TITLE
[Bug] Sporadic crashes in Xenoblade Chronicles: Definitive Edition

### ISSUE THREAD

**Issue by fighuass** [Ryujinx/Ryujinx#7173]
### Description of the issue

At random moments where I'm simply walking around ingame, the game suddenly freezes (the current image displayed hangs and the sound is gone), then after a few seconds the entire emulator crashes.

### Reproduction steps

Simply play the game as you normally would, at random moments it will eventually happen.

### Log file

[Ryujinx_1.1.1372_2024-08-06_19-22-40.log](https://github.com/user-attachments/files/16521820/Ryujinx_1.1.1372_2024-08-06_19-22-40.log)

### OS

Windows 11

### Ryujinx version

1.1.1372

### Game version

1.1.2

### CPU

Ryzen 5 3600

### GPU

RX 5700 XT

### RAM

16GB

### Additional context?

Also encountered the problem before on 1.1.1371.

All of my settings are default, except for that I use 2x resolution scale.

**Comment by fighuass** [comment]
Update: figured I'd try the OpenGL backend as the previous log indicated a Vulkan API issue, though I just had the same issue again during a cutscene.

[Ryujinx_1.1.1372_2024-08-07_16-18-21.log](https://github.com/user-attachments/files/16530521/Ryujinx_1.1.1372_2024-08-07_16-18-21.log)

**Comment by Alejandro9509** [comment]
also happen with Zelda Links Awakening.. :c

**Comment by Midergo** [comment]
same issue, same game same version.


Specs:

i9 11900KF
Ram 32GB
RX 6800


Windows 10 Updated.
Ryujinx Updated.

**Comment by riperiperi** [comment]
I imagine any issue here will be due to the AMD GPU driver. There's no information in the log and it looks like it takes like an hour to happen, so running with graphics debug logs will probably be painful and still might not show anything.

**Comment by Midergo** [comment]
The crash error at the end of the logo:

01:03:38.714 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 279
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\Window.cs:line 457
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 995
   at System.Threading.Thread.StartCallback()



[Ryujinx_1.1.1372_2024-08-29_12-15-07.log](https://github.com/user-attachments/files/16803010/Ryujinx_1.1.1372_2024-08-29_12-15-07.log)


the game usually crash when using "fast travel", that seems to be a trigger.

Drivers Updated to the Last Version "24.10.37.04".
