### ISSUE TITLE
[Bug] Legends Arceus crashing

### ISSUE THREAD

**Issue by hiddenprisom** [Ryujinx/Ryujinx#7187]
### Description of the issue

Game is crashing and I'm not sure why.
This might be dumb, I am new to this.

### Reproduction steps

- Download the .XCI from krnl.vip
- Go into ryujinx and select the part 1 file
- Game crashes

### Log file

0:00:00.254 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.261 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.261 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.262 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.262 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.263 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.264 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2882
00:00:00.264 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
00:00:00.265 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.265 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.266 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.272 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.272 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.272 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.272 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.272 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.272 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.272 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.272 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.272 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.273 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.273 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.274 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.274 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.274 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.274 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.277 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.280 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1373
00:00:00.284 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.284 |N| Application Print: CPU: AMD Ryzen 5 5600 6-Core Processor ; 12 logical
00:00:00.286 |N| Application Print: RAM: Total 47.9 GiB ; Available 37.4 GiB
00:00:00.288 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.288 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.040 |I| Gpu : Backend Threading (Auto): True
00:00:00.282 |N| Application LoadGuestApplication: Using Firmware Version: 18.0.0
00:00:00.282 |I| Application LoadGuestApplication: Loading as XCI.
00:00:00.295 |I| ModLoader QueryContentsDir: Searching mods for Application 01001F5010DFA000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.295 |I| ModLoader QueryContentsDir: Searching mods for Application 01001F5010DFA000 in "C:\Users\[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.297 |I| Loader Load: Loading rtld...
00:00:00.302 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.302 |I| Loader Load: Loading main...
00:00:00.608 |I| Loader PrintRoSectionInfo: main:
    Module: C:\jenkins\workspace\hayabusa\rom\localrombuild\program\output\NX64\Release\main.nss
    SDK Libraries: SDK MW+NINTENDO+nlib_LZ4-20_0714
                   SDK MW+Nintendo+NintendoSDK_libcurl-11_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_libz-11_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Font-11_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-11_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-11_4_0-Release
                   SDK MW+Nintendo+NintendoWare_G3d-11_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NPLN-0_28_0-Release
                   SDK MW+Nintendo+gRPC-0_0_0+NPLN
                   SDK MW+Nintendo+OpenSSL-0_0_0+NPLN
                   SDK MW+Nintendo+PiaCommon-6_16_2
                   SDK MW+Nintendo+Pia-6_16_2
                   SDK MW+Nintendo+PiaLocal-6_16_2
                   SDK MW+Nintendo+PiaLan-6_16_2
                   SDK MW+Nintendo+PiaSession-6_16_2
                   SDK MW+Nintendo+PiaTransport-6_16_2
                   SDK MW+Nintendo+PiaNpln-6_16_2
                   SDK MW+Nintendo+NintendoSDK_gfx-11_4_0-Release
                   SDK MW+Microsoft+Havok_AI-2020_2
00:00:00.608 |I| Loader Load: Loading subsdk0...
00:00:00.628 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-11_4_0-Release
00:00:00.628 |I| Loader Load: Loading subsdk1...
00:00:00.662 |I| Loader PrintRoSectionInfo: subsdk1:
    Module: glslc
00:00:00.662 |I| Loader Load: Loading sdk...
00:00:00.705 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 11.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-11_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-11_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-11_4_0-Release
00:00:00.811 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.820 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.821 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:00.845 |I| Loader LoadNsos: Loading image 2 at 0x000000000c810000...
00:00:00.848 |I| Loader LoadNsos: Loading image 3 at 0x000000000ceb6000...
00:00:00.851 |I| Loader LoadNsos: Loading image 4 at 0x000000000d87e000...
00:00:00.857 |I| ModLoader LoadCheats: Build ids found for application 01001F5010DFA000:
    6F8B1226CC8CD958021D6BFD226EBF23F892AB9B000000000000000000000000
    7FCAD279539DE183B25C11834FD4A030591CFE25000000000000000000000000
    535249A546887CAC875A099E9C8EF367077CF58B000000000000000000000000
    4DD097B435891C5E0E15A65DBE47124F4D7FD1C1000000000000000000000000
    B39ADD63421BE525D352E576DAB438D3812EFDF0000000000000000000000000
00:00:00.860 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.907 |I| Loader Start: Application Loaded: Pokémon Legends: Arceus v1.0.0 [01001f5010dfa000] [64-bit]
00:00:00.938 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:00.948 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.248 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 4060 (Vulkan v1.3.277, Driver v552.44.0.0)
00:00:01.255 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:01.260 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:01.784 |S| HLE.OsThread.47 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:01.876 |S| HLE.OsThread.47 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:01.882 |S| HLE.OsThread.47 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:01.887 |S| HLE.OsThread.47 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:01.960 |S| HLE.OsThread.47 ServicePctl Initialize: Stubbed. 
00:00:03.730 |W| HLE.GuestThread.46 KernelSvc : MapPhysicalMemory() = LimitReached
00:00:04.040 |S| HLE.OsThread.3 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:04.048 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:04.049 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld}
00:00:04.054 |S| HLE.OsThread.47 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:04.259 |S| HLE.OsThread.4 ServiceNv FinishInitialize: Stubbed. 
00:00:04.329 |I| HLE.OsThread.47 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:04.331 |I| HLE.OsThread.47 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:04.425 |S| HLE.OsThread.4 ServiceNv InitializeEx: Stubbed. 
00:00:04.475 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:04.498 |W| HLE.GuestThread.46 KernelSvc : MapPhysicalMemory() = OutOfMemory
00:00:04.500 |W| HLE.GuestThread.46 KernelSvc : MapPhysicalMemory() = OutOfMemory
00:00:04.564 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    ProgramName: main
    Thread: MainThread
    Message: Pure virtual function called!

00:00:04.575 |I| HLE.OsThread.47 ServiceAm SetTerminateResult: Result = 0x000002a2 (ResultErrApplicationAborted (2162-0001)).
00:00:04.693 |I| HLE.GuestThread.46 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Pokémon Legends: Arceus, PID: 127
   0x000000000d9c3038	sdk:0x145038	
   0x000000000d9c3164	sdk:0x145164	
   0x000000000d9c4044	sdk:0x146044	
   0x000000000dde4094	sdk:0x566094	
   0x000000000dd9f3dc	sdk:0x5213dc	
   0x000000000dd8e3f8	sdk:0x5103f8	
   0x000000000dd8deb4	sdk:0x50feb4	
   0x000000000dcf4668	sdk:0x476668	
   0x000000000af5f38c	main:0x2a5b38c	
   0x000000000af5b968	main:0x2a57968	
   0x000000000af87454	main:0x2a83454	
   0x000000000af6a954	main:0x2a66954	
   0x000000000af69750	main:0x2a65750	
   0x000000000ae9dda0	main:0x2999da0	
   0x000000000ac44a40	main:0x2740a40	
   0x000000000ac437a0	main:0x273f7a0	
   0x000000000ac484f4	main:0x27444f4	
   0x000000000ac411e8	main:0x273d1e8	nnMain:0x0088
   0x000000000db2e4c4	sdk:0x2b04c4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000085000d4	rtld:0x00d4	

00:00:04.694 |I| HLE.GuestThread.46 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x00000049f0b08208 (SP:-0x01a8)
	X[02]:	0x0000000000000004
	X[03]:	0x000000000000000c
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000100000000
	X[09]:	0x000000000d87e000 (sdk:0x0000)	=> 
	X[10]:	0x0000000000c696c8
	X[11]:	0x0000000000800000
	X[12]:	0x0000000000000000
	X[13]:	0x000000000000000e
	X[14]:	0x0000000000000002
	X[15]:	0x0000000000000000
	X[16]:	0x000000000d9c4870 (sdk:0x146870)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x000000000e4e76c8
	X[18]:	0x0000000000000000
	X[19]:	0x00000049f0b08208 (SP:-0x01a8)
	X[20]:	0x0000000000000000
	X[21]:	0x000000000e29cd5c
	X[22]:	0x000000000e29cd5c
	X[23]:	0x0000000000000000
	X[24]:	0x000000000e29cd5c
	X[25]:	0x00000049f0b081e8 (SP:-0x0188)
	X[26]:	0x000000000e29cd5c
	X[27]:	0x000000000d9c3164 (sdk:0x145164)	=> 
	X[28]:	0x0000001dbfc72420
	FP:	0x00000049f0b08060 (SP)
	LR:	0x000000000d9c4888 (sdk:0x146888)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x00000049f0b08060 (SP)
	PC:	0x000000000dc1db54 (sdk:0x39fb54)	=> 

00:00:04.694 |W| HLE.GuestThread.49 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:04.694 |W| HLE.GuestThread.48 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:04.694 |W| HLE.GuestThread.54 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:04.695 |W| HLE.GuestThread.51 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:04.695 |W| HLE.GuestThread.50 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:04.695 |W| HLE.GuestThread.55 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:04.695 |W| HLE.GuestThread.52 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:04.695 |W| HLE.GuestThread.53 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:04.695 |W| HLE.GuestThread.56 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:00:04.734 |E| HLE.GuestThread.46 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1899
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\obj\Release\net8.0\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\obj\Release\net8.0\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3461
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
   at Ryujinx.Cpu.Jit.JitExecutionContext.SupervisorCallHandler(ExecutionContext context, UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 99
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\State\ExecutionContext.cs:line 156
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263

### OS

Windows 11

### Ryujinx version

1.1.1373

### Game version

1.1.1

### CPU

Ryzen 5 5600

### GPU

Nvidia RTX 4060 8GB

### RAM

64GB

### List of applied mods

No mods

### Additional context?

The website I downloaded the game from is shady, so it might be the game file.

**Comment by hiddenprisom** [comment]
To anyone else with this issue, It was something to do with memory. To fix this, go Options -> Settings -> System -> Disable "Use alternative memory layout"
