### ISSUE TITLE
[Bug]plants vs zombies battle for neighborville won't boot up

### ISSUE THREAD

**Issue by Wokwokwok3000** [Ryujinx/Ryujinx#7193]
### Description of the issue

So we all know that plants vs zombies bfn don't work well at a switch so I wanted to play it in my pc for better performance and visuals ( with my owned keys, game etc.) but when I open the game it crashes just after the loading screen so I just want a solution so I hope someone has a solution or will make a solution thanks on advance

### Reproduction steps

I just boot the games it opens the load screen then it crashes immediately 

### Log file

It's default

### OS

Windows11

### Ryujinx version

Latest

### Game version

1.0

### CPU

I7

### GPU

Rtx 2050

### RAM

32

### List of applied mods

None

### Additional context?

None

**Comment by lostromb** [comment]
Please provide a log file, as it is we have no clue what could possibly be causing the crash

**Comment by Wokwokwok3000** [comment]
Thx I discovered that's ryujinx can't boot PVZ bfn it's not settings fault or ssmthin because I have other games and they work fine and tbh idk what is log files:/

**Comment by Wokwokwok3000** [comment]
> Please provide a log file, as it is we have no clue what could possibly be causing the crash

Thx I discovered that's ryujinx can't boot PVZ bfn it's not settings fault or ssmthin because I have other games and they work fine and tbh idk what is log files:/

**Comment by Wokwokwok3000** [comment]
> Please provide a log file, as it is we have no clue what could possibly be causing the crash

But if u need logs to make it playable I'll appreciate ur work but idk how to show logs

**Comment by piplup55** [comment]
File > Open Logs Folder
![image](https://github.com/user-attachments/assets/719fadcd-d630-4084-9d0c-039c53897bbb)

**Comment by Wokwokwok3000** [comment]
> File > Open Logs Folder
> ![image](https://github.com/user-attachments/assets/719fadcd-d630-4084-9d0c-039c53897bbb)
> 

Thx for helping but I still don't understand how to put logs srry for my inconvenience btw

**Comment by Wokwokwok3000** [comment]
> File > Open Logs Folder
> ![image](https://github.com/user-attachments/assets/719fadcd-d630-4084-9d0c-039c53897bbb)
> 

And btw should I open the game at least once to work because I deleted the room but I can still replace it because I have a copy of  and there are documents should I copy all of them on the log place or a specific one.
Like I said thx for help

**Comment by lostromb** [comment]
Anyway, I assume this is the missing log
```
00:00:29.543 |I| HLE.GuestThread.51 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Plants vs. Zombies: Battle for NeighborvilleT, PID: 127
   0x000000000988e154   main:0x138a154  fb::Audio::update(float, float):0x00d4
   0x0000000009ed2ee0   main:0x19ceee0  fb::LevelSound::update(float, float, bool):0x0120
   0x0000000009ed255c   main:0x19ce55c  fb::LevelSound::updateJob(unsigned long, unsigned long, unsigned long, unsigned long):0x006c
   0x000000000a87c920   main:0x2378920  EA::Jobs::Detail::JobContextImpl::DispatchJob(EA::Jobs::Detail::JobInstance*):0x0230
   0x000000000a8784a8   main:0x23744a8
   0x000000000a877e88   main:0x2373e88
   0x000000000a877974   main:0x2373974  EA::Jobs::Internal::WorkerThread<EA::Jobs::NullLogger>::Run(bool (*)(void*), void*, int, bool, unsigned long):0x0204
   0x000000000a8734c4   main:0x236f4c4  EA::Jobs::Internal::RunImpl(bool (*)(void*), void*, int, bool, unsigned long):0x0174
   0x000000000a872338   main:0x236e338  EA::Jobs::Internal::JobThreadEntry(void*):0x0028
   0x000000000a500848   main:0x1ffc848  EA::Debug::ExceptionHandler::RunTrapped(long (*)(void*), void*):0x0038
   0x0000000008943048   main:0x43f048
   0x00000000143cf6c0   sdk:0x55b6c0
   0x00000000141b2698   sdk:0x33e698
   0x00000000141b6e64   sdk:0x342e64
   0x0000000000000000


00:00:29.543 |I| HLE.GuestThread.51 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
        X[00]:  0x0000002094cf3000
        X[01]:  0x0000000000000001
        X[02]:  0x0000000000000000
        X[03]:  0x0000000000000000
        X[04]:  0x0000000000000000
        X[05]:  0x0000000000000000
        X[06]:  0x0000000000000000
        X[07]:  0x0000000000000000
        X[08]:  0x0000000014c04a00
        X[09]:  0x0000000000000005
        X[10]:  0x0000000000000067
        X[11]:  0x0000000000000005
        X[12]:  0x00000000000000c0
        X[13]:  0x0000000000000000
        X[14]:  0x000000000000001f
        X[15]:  0x0000000012c4c5f0
        X[16]:  0x0000000014ad4090
        X[17]:  0x00000000141afe10 (sdk:0x33be10)       => nn::os::GetCurrentThread()
        X[18]:  0x0000000013a09da0
        X[19]:  0x0000001101a0ee30
        X[20]:  0x0000000000000000
        X[21]:  0x0000000013625000
        X[22]:  0x00000000137da000
        X[23]:  0x00000010f55fb080
        X[24]:  0x0000001101a0ee70
        X[25]:  0x0000002094c120d0
        X[26]:  0x0000000000000000
        X[27]:  0x0000000000000000
        X[28]:  0x0000000000000000
        FP:     0x000000108b44cb00 (SP:-0x0060)
        LR:     0x00000000098821f8 (main:0x137e1f8)     => fb::MixerManager::update(float):0x0138
        SP:     0x000000108b44caa0 (SP)
        PC:     0x00000000141afe10 (sdk:0x33be10)       => nn::os::GetCurrentThread()


00:00:29.543 |E| HLE.GuestThread.51 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:29.590 |E| HLE.GuestThread.51 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in C:\Code\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 349
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in C:\Code\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at Ryujinx.Cpu.MemoryEhMeilleure.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in C:\Code\Ryujinx\src\Ryujinx.Cpu\MemoryEhMeilleure.cs:line 65
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\Code\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in C:\Code\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in C:\Code\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\Code\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in C:\Code\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 349
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in C:\Code\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at Ryujinx.Cpu.MemoryEhMeilleure.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in C:\Code\Ryujinx\src\Ryujinx.Cpu\MemoryEhMeilleure.cs:line 65
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\Code\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in C:\Code\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in C:\Code\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\Code\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
```

Since it seems audio-related, I switched from SDL to Dummy audio backend and curiously got a different crash:
```
00:00:37.359 |E| AudioRendererManager.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Common.Memory.Array4`1.get_Item(Int32 index) in C:\Code\Ryujinx\src\Ryujinx.Common\Memory\StructArrayHelpers.cs:line 45
   at Ryujinx.Audio.Renderer.Server.Voice.VoiceState.FlushWaveBuffers(UInt32 waveBufferCount, Memory`1[] voiceUpdateStates, UInt32 channelCount) in C:\Code\Ryujinx\src\Ryujinx.Audio\Renderer\Server\Voice\VoiceState.cs:line 565
   at Ryujinx.Audio.Renderer.Server.Voice.VoiceState.UpdateParametersForCommandGeneration(Memory`1[] voiceUpdateStates) in C:\Code\Ryujinx\src\Ryujinx.Audio\Renderer\Server\Voice\VoiceState.cs:line 589
   at Ryujinx.Audio.Renderer.Server.CommandGenerator.GenerateVoices() in C:\Code\Ryujinx\src\Ryujinx.Audio\Renderer\Server\CommandGenerator.cs:line 491
   at Ryujinx.Audio.Renderer.Server.AudioRenderSystem.GenerateCommandList(CommandList& commandList) in C:\Code\Ryujinx\src\Ryujinx.Audio\Renderer\Server\AudioRenderSystem.cs:line 626
   at Ryujinx.Audio.Renderer.Server.AudioRenderSystem.SendCommands() in C:\Code\Ryujinx\src\Ryujinx.Audio\Renderer\Server\AudioRenderSystem.cs:line 675
   at Ryujinx.Audio.Renderer.Server.AudioRendererManager.SendCommands() in C:\Code\Ryujinx\src\Ryujinx.Audio\Renderer\Server\AudioRendererManager.cs:line 242
```

Trying to access `waveBufferIndex` == 26051504
![image](https://github.com/user-attachments/assets/37a2a81f-6e8d-4dcd-8b1d-ac851e335093)

Tried to breakpoint and see where this value was coming from and ended up reaching the title screen instead v0v
![image](https://github.com/user-attachments/assets/93f2ccbb-f466-4eca-9fd2-a8a89127e62d)

**Comment by Wokwokwok3000** [comment]
Does that means it's unplayabe? 
Thx for the help anyway

**Comment by chocoboxx** [comment]
Can someone fix the Plants vs Zombies game please?

**Comment by chocoboxx** [comment]
Can someone fix the Plants vs Zombies game please?
<img width="960" alt="Sin título" src="https://github.com/user-attachments/assets/89b266c0-a9e9-4f51-aed1-8f3a01f8b0b2">

**Comment by chocoboxx** [comment]
Can someone fix the Plants vs Zombies game please?
<img width="960" alt="Sin título" src="https://github.com/user-attachments/assets/7dc22a12-03dc-4e70-b658-7ccb47dfbeb1">

**Comment by Wokwokwok3000** [comment]
> Can someone fix the Plants vs Zombies game please?
> <img width="960" alt="Sin título" src="https://github.com/user-attachments/assets/7dc22a12-03dc-4e70-b658-7ccb47dfbeb1">
> 

That's what I'm saying
