### ISSUE TITLE
Skyward Sword freezes and error appears in logs[Bug]

### ISSUE THREAD

**Issue by Cubicsphinx801** [Ryujinx/Ryujinx#7222]
### Description of the issue

Skyward Sword freezes and error appears in logs
'00:36:43.889 |E| Logger.MessageThread Application : Unhandled exception caught: System.IO.IOException: The device is not ready. [location] 
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean, Boolean)
   at Ryujinx.Common.Logging.Targets.AsyncLogTargetWrapper.<.ctor>b__7_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Common\Logging\Targets\AsyncLogTargetWrapper.cs:line 48
   at System.Threading.Thread.StartCallback()'

### Reproduction steps

Play until it happens

### Log file

[Ryujinx Console 1.1.1376 3rd time.txt](https://github.com/user-attachments/files/16664796/Ryujinx.Console.1.1.1376.3rd.time.txt)
[Ryujinx Console 1.1.1376 2nd time.txt](https://github.com/user-attachments/files/16664799/Ryujinx.Console.1.1.1376.2nd.time.txt)

### OS

Windows 11 

### Ryujinx version

1.1.1376

### Game version

1.0 (I haven't installed any updates 

### CPU

i5-9500

### GPU

AMD Radeon RX 6400

### RAM

32GB

### List of applied mods

None 

### Additional context?

This is the third time: one when goose is talking before the race, entering the bazaar and getting a heart piece in the woods

**Comment by Cubicsphinx801** [comment]
Apologies if I missed anything when skimming thought FAQ and Troubleshooting.

**Comment by Cubicsphinx801** [comment]
Oh this has nothing to do with it but during a cutscene shortly after breaching below the clouds it went strange and the background was off colour and had started looking like the Minecraft missing texture 
'![image](https://github.com/user-attachments/assets/75021ee6-ff4f-46f7-b940-c9babea7238d)
 debug block picture for reference' but when it finished the game went back to normal so i don't know what went on. Sadly i have no proof.
