### ISSUE TITLE
[Bug] Ryujinx is crashing on every game start (iMac 2017)

### ISSUE THREAD

**Issue by mqtt-fan** [Ryujinx/Ryujinx#7296]
### Description of the issue

Starting any game (e.g. Mario Kart or Mario Odyssey) leads to an crash in Ryujinx.

### Reproduction steps

Load any game 

### Log file

[Ryujinx_1.1.1385_2024-09-06_18-20-12.log](https://github.com/user-attachments/files/16918742/Ryujinx_1.1.1385_2024-09-06_18-20-12.log)

### OS

Mac OS 13.6.9 

### Ryujinx version

1.1.1385

### CPU

i5-7360U 

### GPU

AMD Radeon Pro 555

### RAM

8GB

### List of applied mods

none

**Comment by MR-VL** [comment]
Your ram might be overflowing and leading to the game crashing, I notice on games I average 12+ Gb of ram while running. If this is the case you will need to upgrade your ram (if possible) otherwise it may not be possible to game on that machine

**Comment by 6plus4equals52** [comment]
I'm using an iMac 2019
I've tested all versions from 2 months ago to the latest
version 1.1.1375 works perfect
version 1.1.1376 and above always crashes

could you try 1.1.1375, it may work for you 
https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.1375

**Comment by hakushiii** [comment]
Intel macs are not officially supported due to bad gpu drivers. It is much better to boot using windows or linux.

**Comment by 6plus4equals52** [comment]
installing .net 8.0.303 https://dotnet.microsoft.com/en-us/download/dotnet/8.0

and changing global.json to `{ "sdk": { "version": "8.0.303", "rollForward": "disable" } }`

fixes the crash

**Comment by LoganK1234567890** [comment]
> installing .net 8.0.7 -> 8.0.303 https://dotnet.microsoft.com/en-us/download/dotnet/8.0
> 
> and changing global.json to `{ "sdk": { "version": "8.0.303", "rollForward": "disable" } }`
> 
> fixes the crash

How do I change global.json to that?

**Comment by 6plus4equals52** [comment]
global.json should be in the "Ryujinx-master" folder
open it up with a text editor
replace everything with `{ "sdk": { "version": "8.0.303", "rollForward": "disable" } }`

**Comment by LoganK1234567890** [comment]
> global.json should be in the "Ryujinx-master" folder open it up with a text editor replace everything with `{ "sdk": { "version": "8.0.303", "rollForward": "disable" } }`

I don't have that folder or global.json

**Comment by 6plus4equals52** [comment]
Make sure to install .net 8.0.7 -> 8.0.303 -> macOS -> x64 from https://dotnet.microsoft.com/en-us/download/dotnet/8.0
Open Terminal and run

```
git clone https://github.com/Ryujinx/Ryujinx
cd Ryujinx
echo '{ "sdk": { "version": "8.0.303", "rollForward": "disable" } }' > global.json
distribution/macos/create_macos_build_ava.sh "/" "publish_temp" "publish" "distribution/macos/entitlements.xml" "1.1.0" "0000000" "Release" ""
cp -R "publish/Ryujinx.app" "/Applications/"
```
Wait a few minutes to compile
Then Ryujinx should be in your Applications folder

If this doesn't work, you may also need to install xcode https://apps.apple.com/us/app/xcode/id497799835?mt=12
and try again

**Comment by mikesk8** [comment]
Does anybody know if this is going to be fixed in the app? or from now we need to compile by ourselves? Thanks ;)

**Comment by 6plus4equals52** [comment]
I couldn't figure out the bug, debugging the app just crashed all the time, I think it has something to do with JIT though

**Comment by 6plus4equals52** [comment]
I Found a fix without compiling
Go to settings -> CPU -> Memory Manager Mode, and set to Software

**Comment by LoganK1234567890** [comment]
it loads a little further but still crashes

**Comment by 6plus4equals52** [comment]
You can just use an older version here
https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1375/ryujinx-1.1.1375-macos_universal.app.tar.gz
Until the crash is fixed

**Comment by LoganK1234567890** [comment]
that doesnt fix it. it still crashes when using an old build

**Comment by 6plus4equals52** [comment]
Which game are you playing?

**Comment by LoganK1234567890** [comment]
it crashes on mario kart and switch sports. some other games that I have tried that it does not crash on are kirby star allies, cup head, captain toad, and Mario 3d world

**Comment by 6plus4equals52** [comment]
This bug is specific to Intel Macs crashing on every single game no matter what
I'll look into what's happening with your games though

**Comment by LoganK1234567890** [comment]
mb didnt realize it was specifically for intel macs. and I appreciate it

**Comment by HOODEEZ** [comment]
Im using a radeon 6650 xt and 5600x with 32gb ram no other programs taking up ram i installed the keys and firmware tryingto play CXI file game and it had the cover art it loads for a few seconds on both vulkan and opengl then it closes ryujinx theres no straight answer for this anywhere and a ton of people seem to be having the same issue with no answer

**Comment by HOODEEZ** [comment]
00:00:18.214 |E| HLE.GuestThread.46 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000008.
00:00:18.251 |E| HLE.GuestThread.46 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\MemoryBlock.cs:line 440
   at Ryujinx.Cpu.Jit.MemoryManager.Read(UInt64 va, Span`1 data) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 168
   at Ryujinx.Memory.VirtualMemoryManagerBase.Read[T](UInt64 va) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\VirtualMemoryManagerBase.cs:line 150
   at Ryujinx.Cpu.Jit.MemoryManager.ReadGuest[T](UInt64 va) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 150
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
   at System.Threading.Thread.StartCallback()

**Comment by HOODEEZ** [comment]
okay so the answer is to right clock the game and rebuild ppt
