### ISSUE TITLE
[Bug] Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".

### ISSUE THREAD

**Issue by onir** [Ryujinx/Ryujinx#7303]
### Description of the issue

When playing The Legend of Zelda: Tears of the Kingdom I'm getting the error Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost" randomly, or at least I still don't know how to reproduce it, but to be able to play when this error starts to appear I need to restart or turn off the computer a few times and also sometimes I play a little with the graphics in OpenGL (which leaves the image with several defects) and then try again to use Vulkan and hope that the game doesn't give the error again.

### Reproduction steps

The problem happens intermittently, I haven't been able to make it happen when I want it to. But I have the impression that it happens more often after I run a game other than Ryujinx, and also when the computer's memory is very close to 100%.

### Log file

[Ryujinx_1.1.1385_2024-09-09_23-19-09.log](https://github.com/user-attachments/files/16939017/Ryujinx_1.1.1385_2024-09-09_23-19-09.log)

### OS

Windows 11 22H2

### Ryujinx version

1.1.1385

### Game version

1.2.1

### CPU

i5-1135G7

### GPU

Intel(R) Iris(R) Xe Graphics

### RAM

16GB

### List of applied mods

1. TOTK Optimizer
2. Traducao-Triforce
3. Xbox UI Mod v9 - Normal - White

**Comment by Midergo** [comment]
same issue playing xenoblade chronicles definitive edition, it usually happens when i use fast travel although is not always.

Specs:

i9 11900KF
Ram 32GB
RX 6800

Windows 10 Updated.
Drivers Updated.
Ryujinx 1.1.1372

[Ryujinx_1.1.1372_2024-08-29_12-15-07.log](https://github.com/user-attachments/files/16973044/Ryujinx_1.1.1372_2024-08-29_12-15-07.log)

**Comment by RupeeClock** [comment]
Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost" is something that I frequently encounter when trying to emulate [New Super Lucky's Tale](https://github.com/Ryujinx/Ryujinx-Games-List/issues/493), as a title I periodically check to see if Ryujinx updates have addressed its stability issues.
The game is prone to juddery stuttering performance despite being able to achieve full speed with low FIFO thresholds on my machine.

**OS**: Windows 10 22H2
**CPU**: Intel Core i7-12700k @ 3.60Ghz
**GPU**: NVIDIA RTX 3070 8GB / Driver Version 561.09
**RAM**: 32GB DDR5 (2x16)
**Ryujinx Version**: 1.1.1394

Log file: 
[Ryujinx_1.1.1394_2024-09-19_01-57-24.log](https://github.com/user-attachments/files/17052165/Ryujinx_1.1.1394_2024-09-19_01-57-24.log)

Log excerpt:
```
00:05:16.371 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 279
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 258
   at Ryujinx.Graphics.GAL.Multithreading.Commands.SetRenderTargetsCommand.Run(SetRenderTargetsCommand& command, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\Commands\SetRenderTargetsCommand.cs:line 21
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 995
```
