### ISSUE TITLE
[Bug]Crash in ToTK

### ISSUE THREAD

**Issue by fizzingpop** [Ryujinx/Ryujinx#7319]
### Description of the issue

Ryujinx cannot load ToTK without crashing, sometimes when using mods.

### Reproduction steps

Launch ToTK with mods and everything, including the mod, will work perfectly. However, the second time you launch ToTK, Ryujinx crashes while loading the game.

### Log file

00:00:00.002 |N| Application ReloadConfig: Loading configuration from: C:\Users\[redacted]\AppData\Roaming\Ryujinx\Config.json
00:00:00.188 |I| Configuration LogValueChange: EnableFileLog set to: False
00:00:00.189 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.195 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.196 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.196 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.197 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.198 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.198 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x249D
00:00:00.199 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.200 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.200 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.209 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1393
00:00:00.214 |N| Application Print: Operating System: Microsoft Windows 10.0.26100 (X64)
00:00:00.214 |N| Application Print: CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz ; 16 logical
00:00:00.216 |N| Application Print: RAM: Total 63.7 GiB ; Available 55.7 GiB
00:00:00.217 |N| Application PrintSystemInfo: Logs Enabled: <None>
00:00:00.217 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.336 |N| Application LoadGuestApplication: Using Firmware Version: 16.1.0
00:00:21.915 |N| Application : Unhandled exception caught: System.InvalidOperationException: Unable to create child window for native control host. Application manifest with supported OS list might be required.
   at Avalonia.Win32.Win32NativeControlHost.DumbWindow..ctor(Boolean , Nullable`1 )
   at Avalonia.Win32.Win32NativeControlHost.CreateNewAttachment(Func`2)
   at Avalonia.Controls.NativeControlHost.UpdateHost()
   at Avalonia.Controls.NativeControlHost.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs)
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs)
   at Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs)
   at Avalonia.Visual.SetVisualParent(Visual)
   at Avalonia.Visual.SetVisualParent(IList, Visual )
   at Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T, Int32)
   at Avalonia.Collections.AvaloniaList`1.Add(T)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild()
   at Avalonia.Controls.Presenters.ContentPresenter.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable, Size, Thickness, Thickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteQueuedLayoutPass()
   at Avalonia.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at Avalonia.Media.MediaContext.RenderCore()
   at Avalonia.Media.MediaContext.Render()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32DispatcherImpl.DispatchWorkItem()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 53
Unhandled exception. System.InvalidOperationException: Unable to create child window for native control host. Application manifest with supported OS list might be required.
   at Avalonia.Win32.Win32NativeControlHost.DumbWindow..ctor(Boolean , Nullable`1 )
   at Avalonia.Win32.Win32NativeControlHost.CreateNewAttachment(Func`2)
   at Avalonia.Controls.NativeControlHost.UpdateHost()
   at Avalonia.Controls.NativeControlHost.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs)
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs)
   at Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs)
   at Avalonia.Visual.SetVisualParent(Visual)
   at Avalonia.Visual.SetVisualParent(IList, Visual )
   at Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T, Int32)
   at Avalonia.Collections.AvaloniaList`1.Add(T)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild()
   at Avalonia.Controls.Presenters.ContentPresenter.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable, Size, Thickness, Thickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteQueuedLayoutPass()
   at Avalonia.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at Avalonia.Media.MediaContext.RenderCore()
   at Avalonia.Media.MediaContext.Render()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32DispatcherImpl.DispatchWorkItem()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 53

### OS

Windows 11

### Ryujinx version

1.1.1393

### CPU

11800H

### GPU

RTX 3070 Mobile

### RAM

64GB

### List of applied mods

TOTK Optimizer (mod) for ToTK version 1.1.1 applied

**Comment by ekuland** [comment]
Spam click on the game window while loading using the mod.
