### ISSUE TITLE
[Bug]Tears of the Kingdom Crashing with "ErrorDeviceLost"

### ISSUE THREAD

**Issue by 2digitman** [Ryujinx/Ryujinx#7344]
### Description of the issue

I am having inconsistent playtimes while trying to play this game. Sometimes I can play for over an hour without a crash and other times just 5 minutes. It's always the same error and I have already looked through the other bug reports related to this issue. My graphics drivers are on the latest ones.

### Reproduction steps

Playing through the game normally.

### Log file

00:09:32.236 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan1 waitSemaphores, ReadOnlySpan1 waitDstStageMask, ReadOnlySpan1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 279
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 270
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 258
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreateGraphicsPipelineIfNeeded() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1601
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 401
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 995
   at System.Threading.Thread.StartCallback()

### OS

Windows 10

### Ryujinx version

1.1.1398

### Game version

1.2.1

### CPU

Ryzen 9 5950X

### GPU

RTX 4070 Ti Super

### RAM

32GB DDR4

### List of applied mods

TOTK Optimizer on medium preset
Resolution 1080p
Shadow Resolution 512x
60 FPS + Menu
50 FOV

### Additional context?

I'll continue to test stuff to report if I get it fixed before a reply.

**Comment by LaZar00** [comment]
Exactly the same here.

Log file:
`00:00:00.336 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.346 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.346 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.347 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.348 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.349 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.350 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1ED0
00:00:00.351 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.352 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.352 |I| Configuration LogValueChange: ScalingFilterLevel set to: 81
00:00:00.367 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1401
00:00:00.374 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.374 |N| Application Print: CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz ; 12 logical
00:00:00.377 |N| Application Print: RAM: Total 31.9 GiB ; Available 22.7 GiB
00:00:00.380 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.380 |N| Application PrintSystemInfo: Launch Mode: Custom Path G:\Descargas\RYUJINX\Data
00:00:00.553 |N| Application LoadGuestApplication: Using Firmware Version: 18.1.0
00:00:05.499 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.499 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.499 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.499 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.499 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.499 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.500 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.500 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.500 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.500 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.502 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.503 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.503 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.503 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.503 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.503 |E| TamperMachine Compile: Invalid instruction width 0 in Atmosphere cheat
00:00:05.503 |E| TamperMachine Compile: There was a problem while compiling the Atmosphere cheat
00:00:05.836 |W| HLE.TamperMachine TamperMachine AdvanceTamperingsQueue: Tampering program <♯ 2. Inf. Health Cheat> modifies code memory so it may not work properly
00:00:05.837 |W| HLE.TamperMachine TamperMachine AdvanceTamperingsQueue: Tampering program <♯ 3. Inf. Stamina Cheat> modifies code memory so it may not work properly
00:00:05.837 |W| HLE.TamperMachine TamperMachine AdvanceTamperingsQueue: Tampering program <♯ 8. Ignore Fall Damage & Reaction Cheat> modifies code memory so it may not work properly
00:00:05.837 |W| HLE.TamperMachine TamperMachine AdvanceTamperingsQueue: Tampering program <♯35. Inf. Equipment Durability (Fire will still break it.) Cheat> modifies code memory so it may not work properly
00:00:05.837 |W| HLE.TamperMachine TamperMachine AdvanceTamperingsQueue: Tampering program <♯36. Inf. Arrow(s) Cheat> modifies code memory so it may not work properly
00:00:05.837 |W| HLE.TamperMachine TamperMachine AdvanceTamperingsQueue: Tampering program <♯42c Item Pickup Multiplier (8x) Cheat> modifies code memory so it may not work properly
00:00:06.199 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 2080 (Vulkan v1.3.280, Driver v561.9.0.0)
00:00:06.199 |N| GUI.RenderThread Gpu PrintGpuInformation: GPU Memory: 8203 MiB
00:02:20.773 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:04:09.276 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:04:10.921 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:04:11.993 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:04:12.695 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:12:33.376 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:18:00.401 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:23:50.826 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:37:11.738 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:40:08.071 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:40:26.084 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:42:30.084 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:42:31.041 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:44:10.766 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:44:11.675 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:51:37.997 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:51:45.594 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 279
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 270
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 258
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreateGraphicsPipelineIfNeeded() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1601
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 401
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 995
   at System.Threading.Thread.StartCallback()`

OS
Windows 11 Home 23H2 22631.4169

CPU
Intel 9750H

RAM
32Gb

VGA
RTX 2080 Notebook (GT75 Titan) 8Gb

Ryujinx version
1.1.1398-1.1.1401

No mods, but some cheats.
The CTD is from time to time. Sometimes I can play 15 minutes, sometimes 3 hours. When doing some teleports in game or loading a savegame happens more often (or it seems). I use also ALT+TAB to change to windows very often.

**Comment by tung78666** [comment]
i am assuming the cheat is what cause the problem try not using any cheat

**Comment by LaZar00** [comment]
I don't think that is a correct assumption, not after testing the game for 3 hours with cheats. It should have crashed before all that time.
