### ISSUE TITLE
[Bug] Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory"

### ISSUE THREAD

**Issue by Akaryatrh** [Ryujinx/Ryujinx#7376]
### Description of the issue

Just updated to Ryujinxto `1.1.1401` and now when i run a saved game of Luigi's Mansion 3, i'm running into a Vulkan out of memory issue:

(issue probably happens even with a new game)

### Reproduction steps

- Start Ryujinx
- open Luigi's Mansion 3 and run a saved game (or a new game i guess)
- when game is loaded, Ryujinx is crashing

### Log file

```shell
00:00:50.847 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 223
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map, Boolean isBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 55
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, Device device, TextureCreateInfo info, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 133
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.
RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 995
   at System.Threading.Thread.StartCallback()
```

[Ryujinx_1.1.1401_2024-09-29_18-56-43.log](https://github.com/user-attachments/files/17180134/Ryujinx_1.1.1401_2024-09-29_18-56-43.log)

### OS

Win 11 23H2 22631.4169 (not sure why logs says Win 10 BTW)

### Ryujinx version

1.1.1401

### Game version

1.4.0

### CPU

i7-13700K

### GPU

RTX 3800

### RAM

32GB

### List of applied mods

None

**Comment by gdkchan** [comment]
This is a regression caused by #7307 (FYI @MaxLastBreath).
At the native resolution the game should still run, but it does use 4GB of VRAM here, which would be too much for cards with 4GB or less.

**Comment by piplup55** [comment]
i saw a similar thing on my igpu, it has 512mb allocated by default but instead it eats alot of my ram, i never saw a crash or higher vram/ram usage
![image](https://github.com/user-attachments/assets/6b3e401a-65a6-4629-9e35-3b72a2d06e91)

**Comment by Akaryatrh** [comment]
> This is a regression caused by #7307 (FYI @MaxLastBreath). At the native resolution the game should still run, but it does use 4GB of VRAM here, which would be too much for cards with 4GB or less.

@gdkchan RTX 3080 has 10GB of VRAM, so I'm not sure to understand your comment?

**Comment by gdkchan** [comment]
It uses 4GB of VRAM at native resolution. At 2x resolution which is what you're using, it uses more than 12GB. (This is after the PR I have mentioned was merged, before it used a lot less).

**Comment by MR-UNI** [comment]
i was running into this error earlier in which eventually the games would just straight up crash

**Comment by Akaryatrh** [comment]
> At 2x resolution which is what you're using, it uses more than 12GB.

Ah ok, indeed 12GB won't fit 😁

**Comment by Akaryatrh** [comment]
Apparently issue is fixed in `1.1.1402`
