### ISSUE TITLE
[Bug] Shader Cache Issue in Tales of Vesperia Definitive Edition [01002C0008E52000] v1.0.2

### ISSUE THREAD

**Issue by Snipy44** [Ryujinx/Ryujinx#7378]
### Description of the issue

Hi,

I’m experiencing an issue with Tales of Vesperia Definitive Edition [01002C0008E52000] v1.0.2 on Ryujinx. Every time I try to launch the game, I need to manually delete the shader cache files for the game to start again. This happens both with Vulkan and OpenGL backends.

Without deleting the shader cache, the game fails to launch. Is there a known solution to this issue or is there anything I can do to fix it? I’ve tried various settings, but the problem persists.

Thank you for your help!

### Reproduction steps

Launch Ryujinx and ensure shader cache is enabled.
Start the game Tales of Vesperia Definitive Edition [01002C0008E52000] v1.0.2.
Close the game.
Attempt to relaunch the game without clearing the shader cache.
The game will fail to launch.
Delete the shader cache for the game.
Relaunch the game, and it will start normally.

### Log file

I dont have a logs file sorry

### OS

Windows 11

### Ryujinx version

1.1.1401

### Game version

1.0.2

### CPU

Amd Ryzen 9 5950x

### GPU

Nvidia RTX 4090

### RAM

32 Go 4600mhz

### List of applied mods

No mods

**Comment by Snipy44** [comment]
I found my logs : 
With the crash :

00:00:00.232 |I| Configuration LogValueChange: ResScale set to: -1
00:00:00.238 |I| Configuration LogValueChange: ResScaleCustom set to: 5
00:00:00.238 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.239 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.239 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.240 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.240 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2684
00:00:00.241 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.242 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.242 |I| Configuration LogValueChange: ScalingFilterLevel set to: 0
00:00:00.244 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.249 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.249 |I| Configuration LogValueChange: EnableShaderCache set to: False
00:00:00.249 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.249 |I| Configuration LogValueChange: EnableMacroHLE set to: False
00:00:00.249 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.249 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.249 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.249 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: False
00:00:00.249 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.250 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.250 |I| Configuration LogValueChange: AudioVolume set to: 0.8
00:00:00.251 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.251 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.251 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.251 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.254 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.261 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1401
00:00:00.265 |N| Application Print: Operating System: Microsoft Windows 10.0.26100 (X64)
00:00:00.265 |N| Application Print: CPU: AMD Ryzen 9 5950X 16-Core Processor ; 32 logical
00:00:00.266 |N| Application Print: RAM: Total 31.9 GiB ; Available 22.7 GiB
00:00:00.268 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.268 |N| Application PrintSystemInfo: Launch Mode: Custom Path H:\Switch\Data
00:00:01.529 |W| Application CheckScreenBounds: Failed to find valid start-up coordinates. Defaulting to primary monitor center.
00:00:32.507 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.032 |I| Gpu : Backend Threading (Auto): True
00:00:00.511 |N| Application LoadGuestApplication: Using Firmware Version: 18.1.0
00:00:00.511 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.530 |I| Application AddAocItem: Found AddOnContent with TitleId 01002C0008E53002
00:00:00.531 |I| Application AddAocItem: Found AddOnContent with TitleId 01002C0008E53001
00:00:00.545 |I| ModLoader QueryContentsDir: Searching mods for Application 01002C0008E52000 in "H:\Switch\Data\mods\contents"
00:00:00.546 |I| ModLoader QueryContentsDir: Searching mods for DLC 01002C0008E53001 in "H:\Switch\Data\mods\contents"
00:00:00.546 |I| ModLoader QueryContentsDir: Searching mods for DLC 01002C0008E53002 in "H:\Switch\Data\mods\contents"
00:00:00.548 |I| ModLoader QueryPatchDirs: Found NSO patch 'Anisotropic Filtering Fix - Set AF to 16 in Yuzu advanced graphics settings'
00:00:00.548 |I| ModLoader QueryPatchDirs: Found NSO patch 'Camera JPEG Quality Increase'
00:00:00.548 |I| ModLoader QueryPatchDirs: Found NSO patch 'Disable Internal FSR downscaling'
00:00:00.548 |I| ModLoader QueryPatchDirs: Found NSO patch 'Disable Internal FXAA v2 (1.1.2)'
00:00:00.548 |I| ModLoader QueryPatchDirs: Found NSO patch 'Disable LOD Quality Reduction'
00:00:00.548 |I| ModLoader QueryPatchDirs: Found NSO patch 'Disable Targeting DOF'
00:00:00.548 |I| ModLoader QueryPatchDirs: Found NSO patch 'Island Fix'
00:00:00.548 |I| ModLoader QueryPatchDirs: Found NSO patch 'LOD Improvement'
00:00:00.548 |I| ModLoader QueryPatchDirs: Found NSO patch 'Remove Lens Flare'
00:00:00.548 |I| ModLoader QueryContentsDir: Searching mods for Application 01002C0008E52000 in "H:\Switch\Data\sdcard\atmosphere\contents"
00:00:00.549 |I| ModLoader QueryContentsDir: Searching mods for DLC 01002C0008E53001 in "H:\Switch\Data\sdcard\atmosphere\contents"
00:00:00.549 |I| ModLoader QueryContentsDir: Searching mods for DLC 01002C0008E53002 in "H:\Switch\Data\sdcard\atmosphere\contents"
00:00:00.552 |I| Loader Load: Loading rtld...
00:00:00.557 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.557 |I| Loader Load: Loading main...
00:00:00.616 |I| Loader PrintRoSectionInfo: main:
    Module: K:\J_noAV\VEC_BUILD_IDK340_CON\OriginalSources\XB360_EU\TO_8\Programs\VC\build\NX64\ReleaseRom_Patch\TO_8_360_NX\TO_8_360_NX.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-5_4_0-Release
                   SDK MW+Nintendo+NEX-4_4_0-
                   SDK MW+Nintendo+NEX_R2-4_4_0
                   SDK MW+Nintendo+NintendoSDK_libz-5_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-5_4_0-Release
00:00:00.616 |I| Loader Load: Loading sdk...
00:00:00.643 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 5.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-5_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-5_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-5_4_0-Release
00:00:00.729 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.933 |I| Ptc Load: Loaded Translation Cache (size: 20379067 bytes, translated functions: 21336).
00:00:00.942 |I| Ptc Load: Loaded Profiling Info (size: 67043 bytes, profiled functions: 20520).
00:00:00.948 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.950 |I| Loader LoadNsos: Loading image 1 at 0x0000000008504000...
00:00:00.968 |I| Loader LoadNsos: Loading image 2 at 0x000000000bac9000...
00:00:00.973 |I| ModLoader LoadCheats: Build ids found for application 01002C0008E52000:
    6574C7E3A1069FF7C8F9A2523CD3566BF6336A93000000000000000000000000
    F244B656B1CAFE524A99994655970C3E00000000000000000000000000000000
    26FFB122262CA25E4C016C0AF2F92A29483C64A2000000000000000000000000
00:00:00.976 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.149 |I| Loader Start: Application Loaded: Tales of Vesperia: Definitive Edition v1.0.2 [01002c0008e52000] [64-bit]
00:00:01.192 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.202 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:02.839 |N| GUI.RenderThread Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 4090 (Vulkan v1.3.280, Driver v561.9.0.0)
00:00:02.839 |N| GUI.RenderThread Gpu PrintGpuInformation: GPU Memory: 24142 MiB
00:00:02.845 |I| GPU.MainThread Gpu LoadShaders: Loading 75 shaders from the cache...
00:00:02.976 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:03.309 |I| HLE.GuestThread.46 Ptc LoadTranslations: 20411 translated functions loaded
00:00:03.316 |I| HLE.GuestThread.46 Ptc MakeAndSaveTranslations: 0 of 109 functions translated | Thread count: 31
00:00:03.436 |I| HLE.GuestThread.46 Ptc MakeAndSaveTranslations: 109 of 109 functions translated | Thread count: 31 in 0,1191447 s
00:00:03.492 |S| HLE.OsThread.47 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:03.495 |S| HLE.OsThread.47 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:03.495 |S| HLE.OsThread.47 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:03.496 |S| HLE.OsThread.47 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:03.500 |S| HLE.OsThread.47 ServicePctl Initialize: Stubbed. 
00:00:03.506 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 3s
    ProgramName: TO_8_360_NX
    Thread: MainThread
    Filename: K:/J_noAV/VEC_BUILD_IDK340_CON/OriginalSources/XB360_EU/TO_8/Programs/Common/Main.cpp
    Line: 1534
    Function: nninitStartup
    Message: step1: A nninitStartup() function is invoked.

00:00:03.922 |I| Ptc Save: Saved Translation Cache (size: 20421081 bytes, translated functions: 21445).
00:00:05.227 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 5s
    ProgramName: TO_8_360_NX
    Thread: MainThread
    Message: --------------------------------------------------------------------------

00:00:05.227 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 5s
    ProgramName: TO_8_360_NX
    Thread: MainThread
    Message: Game memory range: 0x208c800000 - 0x20d4800000

00:00:05.227 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 5s
    ProgramName: TO_8_360_NX
    Thread: MainThread
    Message: Game small memory range: 0x20d4800000 - 0x20dc800000

00:00:05.228 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 5s
    ProgramName: TO_8_360_NX
    Thread: MainThread
    Message: --------------------------------------------------------------------------

00:00:05.228 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 5s
    ProgramName: TO_8_360_NX
    Thread: MainThread
    Message: Gfx memory range: 0x20dc800000 - 0x213c800000

00:00:05.228 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 5s
    ProgramName: TO_8_360_NX
    Thread: MainThread
    Message: --------------------------------------------------------------------------

00:00:05.250 |S| HLE.OsThread.47 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:05.250 |S| HLE.OsThread.47 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:05.250 |S| HLE.OsThread.47 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:05.251 |S| HLE.OsThread.47 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: False ; unknownFlag3: True}
00:00:05.251 |S| HLE.OsThread.47 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:05.259 |G| HLE.OsThread.18 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 5s
    ProgramName: TO_8_360_NX
    Thread: QC::File::RequestManager
    Filename: K:/J_noAV/VEC_BUILD_IDK340_CON/OriginalSources/XB360_EU/TL_LIB/tl/kernel/src/win/file/qcFileDriverNX.cpp
    Line: 88
    Function: Mount
    Message: Mouting rom

00:00:05.276 |S| HLE.OsThread.3 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 1}
00:00:05.276 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld}
00:00:05.280 |S| HLE.OsThread.3 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8,Handheld
00:00:05.293 |S| HLE.OsThread.4 ServiceNv FinishInitialize: Stubbed. 
00:00:05.300 |S| HLE.OsThread.4 ServiceNv InitializeEx: Stubbed. 
00:00:05.310 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.338 |I| HLE.OsThread.47 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:05.378 |S| HLE.OsThread.4 ServiceNv SetNvMapFd: Stubbed. 
00:00:05.379 |S| HLE.OsThread.4 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:05.379 |S| HLE.OsThread.4 ServiceNv AllocObjCtx: Stubbed. 
00:00:05.379 |S| HLE.OsThread.4 ServiceNv SetTimeout: Stubbed. 
00:00:05.380 |S| HLE.OsThread.4 ServiceNv SetErrorNotifier: Stubbed. 
00:00:05.380 |S| HLE.OsThread.4 ServiceNv SetUserData: Stubbed. 
00:00:05.380 |S| HLE.OsThread.4 ServiceNv SetPriority: Stubbed. 
00:00:05.381 |S| HLE.OsThread.4 ServiceNv ZcullBind: Stubbed. 
00:00:05.387 |E| HLE.OsThread.7 SurfaceFlinger OnTransact: Error returned by transaction Disconnect: BadValue
00:00:05.398 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:05.398 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.398 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv ZbcSetTable: Stubbed. 
00:00:05.399 |S| HLE.OsThread.4 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:05.474 |I| HLE.OsThread.11 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:05.505 |I| HLE.OsThread.11 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:00:05.620 |I| HLE.OsThread.11 AudioRenderer AcquireSessionId: Registered new output (1)
00:00:05.621 |I| HLE.OsThread.11 AudioRenderer ReleaseSessionId: Unregistered output (1)
00:00:05.621 |I| HLE.OsThread.11 AudioRenderer AcquireSessionId: Registered new output (1)
00:00:05.634 |I| HLE.OsThread.11 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 512
00:00:08.195 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000001000
   at Ryujinx.Memory.VirtualMemoryManagerBase.AssertValidAddressAndSize(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\VirtualMemoryManagerBase.cs:line 266
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.IsRangeMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 325
   at Ryujinx.Memory.Tracking.MemoryTracking.BeginTrackingBitmap(UInt64 address, UInt64 size, ConcurrentBitmap bitmap, Int32 bit, Int32 id, RegionFlags flags) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 258
   at Ryujinx.Memory.Tracking.MultiRegionHandle..ctor(MemoryTracking tracking, UInt64 address, UInt64 size, IEnumerable`1 handles, UInt64 granularity, Int32 id, RegionFlags flags) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MultiRegionHandle.cs:line 110
   at Ryujinx.Memory.Tracking.MemoryTracking.BeginGranularTracking(UInt64 address, UInt64 size, IEnumerable`1 handles, UInt64 granularity, Int32 id, RegionFlags flags) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 203
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.BeginGranularTracking(UInt64 address, UInt64 size, IEnumerable`1 handles, UInt64 granularity, Int32 id, RegionFlags flags) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 432
   at Ryujinx.Graphics.Gpu.Memory.PhysicalMemory.BeginGranularTracking(UInt64 address, UInt64 size, ResourceKind kind, RegionFlags flags, IEnumerable`1 handles, UInt64 granularity) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\PhysicalMemory.cs:line 423
   at Ryujinx.Graphics.Gpu.Image.Pool`2..ctor(GpuContext context, PhysicalMemory physicalMemory, UInt64 address, Int32 maximumId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\Pool.cs:line 72
   at Ryujinx.Graphics.Gpu.Image.TexturePool..ctor(GpuContext context, GpuChannel channel, UInt64 address, Int32 maximumId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 165
   at Ryujinx.Graphics.Gpu.Image.TexturePoolCache.CreatePool(GpuContext context, GpuChannel channel, UInt64 address, Int32 maximumId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\TexturePoolCache.cs:line 27
   at Ryujinx.Graphics.Gpu.Image.PoolCache`1.FindOrCreate(GpuChannel channel, UInt64 address, Int32 maximumId, TextureBindingsArrayCache bindingsArrayCache) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\PoolCache.cs:line 102
   at Ryujinx.Graphics.Gpu.Image.TextureManager.GetTexturePool(UInt64 poolGpuVa, Int32 maximumId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 389
   at Ryujinx.Graphics.Gpu.Shader.ShaderSpecializationState.Matches(GpuChannel channel, GpuChannelPoolState& poolState, Boolean checkTextures, Boolean isCompute) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Shader\ShaderSpecializationState.cs:line 748
   at Ryujinx.Graphics.Gpu.Shader.ShaderSpecializationState.MatchesGraphics(GpuChannel channel, GpuChannelPoolState& poolState, GpuChannelGraphicsState& graphicsState, Boolean vertexAsCompute, Boolean usesDrawParameters, Boolean checkTextures) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Shader\ShaderSpecializationState.cs:line 625
   at Ryujinx.Graphics.Gpu.Shader.ShaderSpecializationList.TryFindForGraphics(GpuChannel channel, GpuChannelPoolState& poolState, GpuChannelGraphicsState& graphicsState, CachedShaderProgram& program) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Shader\ShaderSpecializationList.cs:line 41
   at Ryujinx.Graphics.Gpu.Shader.ShaderCacheHashTable.TryFind(GpuChannel channel, GpuChannelPoolState& poolState, GpuChannelGraphicsState& graphicsState, ShaderAddresses addresses, CachedShaderProgram& program, CachedGraphicsGuestCode& guestCode) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Shader\ShaderCacheHashTable.cs:line 239
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(ThreedClassState& state, ProgramPipelineState& pipeline, GpuChannel channel, Int32 samplerPoolMaximumId, GpuChannelPoolState& poolState, GpuChannelGraphicsState& graphicsState, ShaderAddresses addresses) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 315
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1436
   at Ryujinx.Graphics.Gpu.Engine.Threed.ThreedClass.UpdateState() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Threed\ThreedClass.cs:line 139
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount, Int32 drawFirstVertex, Int32 drawVertexCount) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 156
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 108
   at Ryujinx.Graphics.Gpu.Engine.Threed.ThreedClass.DrawEnd(Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Threed\ThreedClass.cs:line 610
   at Ryujinx.Graphics.Device.DeviceState`1.WriteWithRedundancyCheck(Int32 offset, Int32 data, Boolean& changed) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Device\DeviceState.cs:line 132
   at Macro(MacroJitContext, IDeviceState, Int32)
   at Ryujinx.Graphics.Gpu.Engine.MME.MacroJit.Execute(ReadOnlySpan`1 code, IDeviceState state, Int32 arg0) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\MME\MacroJit.cs:line 36
   at Ryujinx.Graphics.Gpu.Engine.MME.Macro.Execute(ReadOnlySpan`1 code, IDeviceState state) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\MME\Macro.cs:line 89
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.CallMme(Int32 index, IDeviceState state) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 248
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 270
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 229
   at Ryujinx.HLE.Switch.ProcessFrame() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Switch.cs:line 105
   at Ryujinx.Ava.AppHost.<RenderLoop>b__115_1() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 1011
   at System.Threading.Thread.StartCallback()
