### ISSUE TITLE
Fatal error. System.AccessViolationException

### ISSUE THREAD

**Issue by bukyapavankumar** [Ryujinx/Ryujinx#821]
0:15.507 | 0019 ServiceNv Create: Created map 26 with size 0x00100000!
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Tsubajashi** [comment]
Attention: That User seems to try to use the leaked Version of pokemon SwSh. He also tried over at yuzu to get help.

**Comment by emmauss** [comment]
Closing this because no info on the game  or context were given.

**Comment by bukyapavankumar** [comment]
this isnt pokemon sword

**Comment by emmauss** [comment]
Please use the discord server if you want any support first, before creating issues.

**Comment by gdkchan** [comment]
Next time please at least include the name of the game or homebrew you're trying to run.
