### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by bukyapavankumar** [Ryujinx/Ryujinx#825]
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.b__0()
at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.ThreadHelper.ThreadStart()

in pokemon sword  and shield

**Comment by AcK77** [comment]
Please don't open issues for nothing. You should provide us a full log on our Discord server.
Moreover your issue isn't explicit enought, we don't get any context, your specs, OS, etc...

Feel free to ask for help in our support channel on our Discord server.
Thanks.

**Comment by Treviusfox** [comment]
[Ryujinx_2020-04-08_02-09-37.log](https://github.com/Ryujinx/Ryujinx/files/4446358/Ryujinx_2020-04-08_02-09-37.log)
I have this issue:
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
